### ISSUE TITLE
Has a 40 items limit?

### ISSUE THREAD

**Issue by Garito** [ViennaRSS/vienna-rss#1000]
Hi!
I'm subcribed to python channel and it always show 40 items top
Is there a limit? how can I disable it?

Thanks!

**Comment by DavidMunch** [comment]
No limit AFAIK. I have feeds that pull in more than 100 entries at a time. Likely a limitation on their end.

**Comment by Garito** [comment]
Sorry, i've checked and they clearly specify the limit
I've been subscribed to that list that long I've forgotten
