### ISSUE TITLE
No longer moving to next article after deletion

### ISSUE THREAD

**Issue by macsrwe** [ViennaRSS/vienna-rss#1004]
Vienna updated for me yesterday.  Today, when I delete an article with the delete key, the article line disappears properly, the cursor moves to the next article line, and... then, nothing.  Prior to this update Vienna would always put up the next article in the text window and mark it as read.  Now, the only way to open the next article is to click on a completely different article and then click back.

MacBook Pro, Sierra 10.12.6.

**Comment by lapcat** [comment]
This should be fixed in https://github.com/ViennaRSS/vienna-rss/pull/1002

**Comment by barijaona** [comment]
@macsrwe Can you verify it is solved in 3.1.14 ?

**Comment by macsrwe** [comment]
The bad behavior no longer occurs.
