### ISSUE TITLE
Author doesn't display well with ArXiv

### ISSUE THREAD

**Issue by gillesbonnet** [ViennaRSS/vienna-rss#1007]
I have subscribed to the RSS feed [https://arxiv.org/rss/cs](https://arxiv.org/rss/cs).
The author names do not display correctly. For example it display 
`<a href="http://arxiv.org/find/cs/1/au:+Moosavi_V/0/1/0/all/0/1">Vahid Moosavi</a>`
instead of simply 
_Vahid Moosavi_.
I tested that with Vienna 3.1.14 on an iMac with OS X El Capitan 10.11.6.
![screenshot 2017-09-13 09 34 59](https://user-images.githubusercontent.com/14077290/30365307-9abb8964-9867-11e7-8008-dbe25e7f153d.png)

**Comment by barijaona** [comment]
The problem is on their side. In the XML file, one can find : 
````XML
<dc:creator> &lt;a href=&quot;http://arxiv.org/find/cs/1/au:+Luo_T/0/1/0/all/0/1&quot;&gt;Tie Luo&lt;/a&gt;, &lt;a href=&quot;http://arxiv.org/find/cs/1/au:+Zeynalvand_L/0/1/0/all/0/1&quot;&gt;Leonit Zeynalvand&lt;/a&gt;</dc:creator>
````

**Comment by gillesbonnet** [comment]
Thanks for your answer. I contacted ArXiv administrators. They suggested me to try adding the version command to the feed url, so
[http://arxiv.org/rss/cs?version=0.91](http://arxiv.org/rss/cs?version=0.91)
or:
[http://arxiv.org/rss/cs?version=2.0](http://arxiv.org/rss/cs?version=2.0).
Doing this with Vienna 3.1.14 results in both cases not showing anything in the author field. 
![screenshot 2017-09-15 08 52 08](https://user-images.githubusercontent.com/14077290/30469991-3f7066e6-99f3-11e7-85d1-c6e4ee5b2727.png)
I tried with an other reader (feedly.com). [https://arxiv.org/rss/cs](https://arxiv.org/rss/cs) doesn't work for the authors, but both [http://arxiv.org/rss/cs?version=0.91](http://arxiv.org/rss/cs?version=0.91) and [http://arxiv.org/rss/cs?version=2.0](http://arxiv.org/rss/cs?version=2.0) work perfectly fine.
