### ISSUE TITLE
Selection jumps to next article if same unread article appears in different feeds

### ISSUE THREAD

**Issue by joostvanwollingen** [ViennaRSS/vienna-rss#1012]
Bug description:
If 2 feeds contain the same article, upon selecting the one with the earliest publication time the selection will jump to the post with the latest publication time (but only if the early article is marked as unread). Other actions (besides selection) that will also trigger this behaviour is 'mark read', 'mark unread', 'mark flagged', both through the right-click menu or Article menu. When doing actions the older article doesn't need to be unread.

Versions: 
- Vienna 3.1.14 :2d636f62:
- macOS Sierra 10.12.5 (16F73)

Reproduction path:

1. Update settings: 
    Mark current article read: After a short delay
1. Add these two feeds to a folder:
    http://feeds.feedburner.com/mottestingfeeds
    http://secretsofconsulting.blogspot.com/feeds/posts/default
2. Article "What should be my next step to becoming a better programmer?" appears twice, as contained in both feeds
3. Select the article published on 14-9-2017 23:25 (GMT+1)
4. Selection will jump to the article published on 14-9-2017 23:27 (GMT+1)

Also see this GIF of the behaviour: http://www.giphy.com/gifs/l378z0mh1bs666viU

Expected behaviour:
1. Selection stays with the originally selected article

**Comment by lapcat** [comment]
It's worth noting that mottestingfeeds is a bad feed: http://www.feedvalidator.org/check?url=http://feeds.feedburner.com/mottestingfeeds

What's messing up Vienna is that the 2 articles have the same guid. By the Atom standard, these are supposed to be globally unique. So, no 2 feeds on the internet should ever have items with the same guid. Again, this is the fault of mottestingfeeds for simply republishing the guid from another feed.

Maybe we can do something to make Vienna handle it better, but this is really bad form from mottestingfeeds.

**Comment by Baffjr** [comment]
I have the exact same thing happening in my folder which contains about 140 feeds from spoilertv.com, so not just mottestingfeeds that uses bad form.

It is too bad this won't get fixed.  It is getting increasingly annoying to deal with. Vienna "handled it better" until just a few weeks ago.

A couple example feeds that have some of the same articles.
http://www.spoilertv.com/feeds/posts/default/-/The%20Orville
http://www.spoilertv.com/feeds/posts/default/-/The%20Last%20Ship

**Comment by barijaona** [comment]
Can you check if version 3.1.16 improves on this issue ?

**Comment by joostvanwollingen** [comment]
No change for me in version 3.1.16 with the two feeds mentioned in the initial issue.

**Comment by Baffjr** [comment]
No change for me either. Thank you very much for looking into it.
