### ISSUE TITLE
Scroll position is unchanged when switching between feeds

### ISSUE THREAD

**Issue by JanX2** [ViennaRSS/vienna-rss#1013]
Some of my feeds have a lot of entries while others have few. So it happens quite often, that I switch from a feed where I have scrolled down several pages to another where there are only few unread items. 

Ever since a few versions ago, Vienna keeps the scroll position when switching between feeds. This is rarely what I need. I can currently think of no scenarios where this is advantageous. It might make more sense to remember the scroll position for each feed or not at all. 

Any opinions?

**Comment by JanX2** [comment]
#1009 seems to be related.

**Comment by barijaona** [comment]
Fixed in version 3.1.15

**Comment by JanX2** [comment]
At first blush this is working fine now. :)

A warm thank you goes out to all of you dev!
