### ISSUE TITLE
Vienna improved start/exit time of the App

### ISSUE THREAD

**Issue by giannigdev** [ViennaRSS/vienna-rss#1022]
I have updated the app to 3.1.16 release and I noticed starting and closing the App is much faster and reactive. I was wondering with a bit of curiosity what did you guys changed in the codebase? was a database syncing problem or something else? As always thank you for the updates and for your time.

**Comment by RobFog** [comment]
You might be able to figure out the changes that improved performance by inspecting the [commits made on the `stable`](https://github.com/ViennaRSS/vienna-rss/commits/stable) branch between 3.1.16 and the time when the version you previously used was released. :-)
