### ISSUE TITLE
Per-feed retrieval timing overrides

### ISSUE THREAD

**Issue by midnightmagic** [ViennaRSS/vienna-rss#1023]
Some sources don't like having their .rss feeds hammered even just a couple of times per day. It would be cool if we could set local overrides for .rss retrieval—especially if the same mechanism can be used to temporarily disable .rss feed retrieval for just singular feeds until later re-enabled.

Similarly, for high-volume feeds which turn over more rapidly than the default retrieval interval, it would be cool to increase retrieval times for them.

Thanks for the awesome software. Seriously.

**Comment by barijaona** [comment]
Temporary disabling a feed is already supported ("subscribed" checkbox in the Info window)

**Comment by midnightmagic** [comment]
Sure; but the problem is that some RSS feeds are literally updated by the minute and only have, say, a 20-item content—this means that hammering it is the only way to make it useful. Some comic feeds don't update mote than once a week—this means that hammering it every 5 minutes might make the comic artist (or his sysadmin) angry.
