### ISSUE TITLE
Vienna is using 32GB memory

### ISSUE THREAD

**Issue by thewidgetsmith** [ViennaRSS/vienna-rss#1037]
I am using Vienna version 3.1.16 on Mac OSX 10.12.6 with 6 subscriptions. Vienna has been running for nearly 1 week now and it is currently using 32GB  of memory. I have attached a screenshot for reference.

![screen shot 2017-11-06 at 09 49 07](https://user-images.githubusercontent.com/3577220/32453615-ef988972-c2d9-11e7-8bc7-ae41f28b8936.png)

**Comment by barijaona** [comment]
I have spent some time investigating this.
The most probable cause is that Vienna has no limit set for undoing mark read/unread actions. So `ArticleReference` objects can be kept for long times…

https://developer.apple.com/documentation/foundation/nsundomanager/1409753-levelsofundo

**Comment by josh64x2** [comment]
@barijaona what do you think a sensible limit would be?

**Comment by barijaona** [comment]
Apparently, the default value in Excel is 16. And the default value in Photoshop is 20.

**Comment by Eitot** [comment]
How about Apple Mail?

**Comment by barijaona** [comment]
Haven't found it for Apple Mail, but after searching on the internet, I am convinced 20 will be largely enough.

**Comment by Eitot** [comment]
I was only able to restore the last 30 emails, but marking as read/unread went beyond 100.

**Comment by bluszcz** [comment]
Macbook pro, Vienna constantly consumes ~ 30% CPU, 9GB V and ~350 RES memory:

<img width="1138" alt="screen shot 2018-02-14 at 11 29 36" src="https://user-images.githubusercontent.com/221943/36199648-78c5cd9c-117a-11e8-8109-b07b671e7c7d.png">

**Comment by MacDisein** [comment]
My Vienna consumes 670 MB of RAM with 9 feeds.
I think this is too much - because only one message is visible at a time. And I also regularly delete old messages.
