### ISSUE TITLE
Open an enclosure in its default app

### ISSUE THREAD

**Issue by PacoH** [ViennaRSS/vienna-rss#1038]
If I click the link to an mp3 podcast, it opens in my browser. I want it to open in my default media player, VLC Media Player. The only way to do that is to first download the file and then go and find it and manually open it, or copy the link and manually add it to VLCMP. Is there any way to automatically open the link in my player?

**Comment by barijaona** [comment]
Another description of the issue here : https://forums.cocoaforge.com/viewtopic.php?t=27044&p=140254#p140254

**Comment by barijaona** [comment]
Button in enclosure pane has been changed in version 3.5.7
