### ISSUE TITLE
Right-to-left support

### ISSUE THREAD

**Issue by Hameds** [ViennaRSS/vienna-rss#1039]
It seems that vienna doesn't support [rtl](https://en.wikipedia.org/wiki/Right-to-left) content.

**Comment by josh64x2** [comment]
Hi,

Have you got an example RSS feed I can look at?

Thanks!

**Comment by Hameds** [comment]
sure. take a look at  [this one](http://pullrequest.ir/feed) which is in [Persian](https://en.wikipedia.org/wiki/Persian_language) the content should be `rtl` and `text align` should be `right`

**Comment by Eitot** [comment]
Vienna indeed does not support it. This is something that has to be specifically implemented in the UI as well as the themes. The only workaround is to enable the full HTML view on those feeds.

**Comment by phiw13** [comment]
I meant to post this months ago,… better late than never.

@Hameds,

I have a theme (viennastyle) that has support for RTL languages. It is a bit rough on the edges, as I have only very few hooks to play with, but it is (says a friend who is fluent in Persian) quite usable.

Sample article(s): https://dev.l-c-n.com/Vienna/

Download: https://emps.l-c-n.com/file_download/34/Grey_square.viennastyle.zip

@Eitot

There a few things that can (easily…) make themes RTL compatible. 

* the `dir=auto` attribute; in the theme linked above, I happen it to a block that wraps the actual article content. For the “default” theme shipping with Vienna, you could append it to the `<body>`. That will make Webkit automatically flip the direction of the text based on the text strings/block.

* for elements that have a list marker (`ul` and `ol`), set `text-align: start` to make sure the list marker is at the beginning of the block (right for RTL)

* for the same elements; you need to set the padding on the “correct” side (value used here is the default Webkit value):

```
ol, ul {
  - webkit-padding-start: 40px;
  /* future proof per spec */
  padding-inline-start: 40px;
}
```

* In general, think symmetrically, e.g. if one adds `padding-left` to an element, use the same value for `padding-right` (for example, the header `articleTitleStyle` in the default theme)

**Comment by Hameds** [comment]
Thanks @phiw13 I will try that

**Comment by barijaona** [comment]
I see that @phiw13 's style specifies `direction: ltr` for `pre`elements.
Is there a specific reason for this ?
