### ISSUE TITLE
Wrong text vertical alignment for titles with emojis

### ISSUE THREAD

**Issue by gradha** [ViennaRSS/vienna-rss#1044]
After seeing some odd title rendering problems, I realised they seem to be related to emojis, and found a single case to report. The following screenshot shows how I see a title using Vienna 3.1.16 :891d05ea: under OSX 10.13.1 (17B1003):

![captura de pantalla 2017-12-05 a las 16 59 50](https://user-images.githubusercontent.com/101927/33617068-107f9704-d9df-11e7-9a06-33fdf674721c.png)

The RSS feed can be found at http://gonlamperouge.tumblr.com/rss and might contain NSFW content from time to time. Here is a manually extracted RSS XML for the item in case it helps reproducing the problem:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
  <channel>
    <description/>
    <title>Untitled</title>
    <generator>Tumblr (3.0; @gonlamperouge)</generator>
    <link>http://gonlamperouge.tumblr.com/</link>
    <item>
      <title>fyloona:
171205 / loonatheworld: 💕⠀⠀⠀⠀Say ‘give it to me~’,...</title>
      <description>…</description>
      <link>http://gonlamperouge.tumblr.com/post/168195703870</link>
      <guid>http://gonlamperouge.tumblr.com/post/168195703870</guid>
      <pubDate>Mon, 04 Dec 2017 22:03:06 +0100</pubDate>
    </item>
  </channel>
</rss>
```
It seems that the rendering of the title is using the top/left alignment instead of font baseline, so whenever emojis appear the text bounding box is bigger and normal characters are displaced visually within the title area. Using the font baseline would help read the text but still cut off the emojis, so maybe the only real solution would be to have variable height titles cells depending on each title's rendering size.

The previous screenshot is when the feed is selected individually and no more items are visible. Here is another screenshot as seen when more unread items are visible:

![captura de pantalla 2017-12-05 a las 17 14 14](https://user-images.githubusercontent.com/101927/33617416-e50f4c76-d9df-11e7-9a18-da784851ded3.png)

**Comment by barijaona** [comment]
I'll close it because it is identical to #447
