### ISSUE TITLE
Will it support website on LAN?

### ISSUE THREAD

**Issue by 4ft35t** [ViennaRSS/vienna-rss#1045]
It's doesn't support website on LAN, will it support?

**Comment by gradha** [comment]
Can you elaborate? As long as you use a valid URL everything should work.

**Comment by 4ft35t** [comment]
When add a JIRA activity feed, nothing happend.  Then I import it from opml file , but it jump to http://www.feedvalidator.org to check the source, and said
> Server returned [Errno -5] No address associated with hostname

**Comment by gradha** [comment]
Maybe the problem is Vienna not using your proxy settings if you have one, so it is unable to connect to the URLs? I tried the steps you mentioned and got a feed with 16 news items in what looks like Chinese.

**Comment by josh64x2** [comment]
There is an existing issue about being unable to add authenticated JIRA feeds https://github.com/ViennaRSS/vienna-rss/issues/522 . 

Vienna does support fetching feeds from any reachable HTTP server though so it does work on the LAN.

**Comment by barijaona** [comment]
Vienna uses system's network settings, so if you can open it in Safari, you should be able to access it through Vienna.
