### ISSUE TITLE
Exporting list of articles

### ISSUE THREAD

**Issue by andredevleeschouwer** [ViennaRSS/vienna-rss#1047]
Can it be made possible to export the list of all articles in a map, or a list of all articles marked, including all the article properties (subject, folder, date, author, URL, summary, ...) ?  This would be a very helpful feature.  Format like csv or html is fine.

**Comment by barijaona** [comment]
You'd probably better directly query the SQLite database (file messages.db, table messages) to have something fitting your exact needs.
