### ISSUE TITLE
Exporting articles to pdf

### ISSUE THREAD

**Issue by andredevleeschouwer** [ViennaRSS/vienna-rss#1048]
Can it be made possible in future releases to export articles marked (or all articles in a folder) into pdf files, and giving them a useful name, ie the subject name.  Intention is to extract articles, including the pictures, in a readable format, cfr. Reader mode in Safari.

**Comment by barijaona** [comment]
I don't know if you want individual PDF files for each article or just a single file, but in fact, there is a hack for the latter…
- Use Horizontal or Vertical layout
- In the article list section, select relevant articles (or just select one article and 'Select All' in Edit menu)
- Use 'File → Print…' menu and use the PDF menu to save the resulting file.

**Comment by andredevleeschouwer** [comment]
Thank you for the reply.  That feature was already known by me.  It supplies me with 1 document with the summary text of all articles.  My demand is to get the articles in full + attachments (pictures), by preference in separate files, and with a useful name.  That would be a very nice extension.

**Comment by barijaona** [comment]
Would need to implement #476 first.

**Comment by andredevleeschouwer** [comment]
I would already be very grateful, if the current Print would have an option to start every article on a new page.  Can this be implemented soon ?

**Comment by andredevleeschouwer** [comment]
I understand now your earlier comment about #476.  Therefore, I keep mij request open, but will open a new request on every article starting on new page.  Hopefully this can be done fast.
