### ISSUE TITLE
How can I run a plugin over a multiple article selection?

### ISSUE THREAD

**Issue by gradha** [ViennaRSS/vienna-rss#1049]
Hi, I did register recently at the cocoaforge forums to ask this, but wasn't getting the confirmation email. Today I checked and there seem to be problems with cocoaforge, the main domain points at some goddady iframe (hopefully I didn't break anything during registration).

Anyway, I took the safari add to bookmarks plugin and rewrote it to simply dump the contents of the article to the clipboard. The built in _copy_ command does most of this but doesn't include the URL of the article. For youtube feeds and others this is the most important and sometimes only useful element I need to have on the clipboard (whole other machinery in the background monitoring the clipboard for urls). Here's the modified script:

```
tell application "Vienna"
	
	set article_URL to documentTabURL
	if (article_URL is not "") then
		try
			-- tell application "Safari" to add reading list item article_URL
			set the clipboard to article_URL
		end try
	else -- we probably are on Vienna's primary tab
		
		set the_article to current article
		try
			set article_URL to the link of the_article
			set article_title to the title of the_article
			set mixed to (article_URL & "
" & article_title & "
" & body of the_article)
			set the clipboard to mixed as text
		end try
	end if
end tell
```

This works as expected for single items. However, when I select multiple items I would like the script to be able to grab the contents of all of them. I presume there is some collection element in applescript that can be iterated over, but as it's foreign to me I don't know where to start. Can somebody show an example of iterating over articles similar to the above code?

**Comment by barijaona** [comment]
Sorry, we have no solution for the moment. We have a feature request #440 already opened.
