### ISSUE TITLE
Tabs issue with Vienna 3.2.0b1 

### ISSUE THREAD

**Issue by rei-vilo** [ViennaRSS/vienna-rss#1054]
When launched, Vienna 3.2.0b1 displays a special area with one single tab. Adding a second tab and removing it collapses the special area.

Wouldn't be better to allow a dedicated setting for tabs?

- either having no special area
- or keeping the special area, even when there is one single tab.

See the [video](https://vimeo.com/247617979).

**Comment by Eitot** [comment]
This is already on the list. The tab bar needs to be replaced, as it is based upon an unmaintained third-party framework.

**Comment by barijaona** [comment]
In the meantime, shouldn't we at least revisit commit 24dd91d ?

**Comment by josh64x2** [comment]
Fixed in #1058
