### ISSUE TITLE
Tab bar should be always visible

### ISSUE THREAD

**Issue by MacDisein** [ViennaRSS/vienna-rss#1060]
It is really annoying that the tab bar appears/disappears if you open/close an article.
The tab bar should be always visible to avoid reorganization of the layout. Each time you open an article the tab bar appears and the other controls are moved down - and the opposite way if you close the last article tab.

**Comment by josh64x2** [comment]
This behaviour was changed in #1058 because of issue #1054 
@barijaona perhaps we need a preference for `[tabBarControl setHideForSingleTab:YES];` ?

**Comment by pukku** [comment]
I think it should be an option, because I never use tabs (I don't use the built-in browser), and it would be annoying to have a tab bar there when I never use it.

**Comment by MacDisein** [comment]
Yes, I agree

**Comment by josh64x2** [comment]
Would it make sense to have it based on this setting:
<img width="235" alt="screen shot 2018-01-10 at 08 31 50" src="https://user-images.githubusercontent.com/799345/34750196-c25a00b4-f5e0-11e7-8d8a-465f4d9538e3.png">

If it is checked, then we hide the tab bar. If it is unchecked (e.g. you are using internal browser) then we always show the tab bar.

**Comment by pukku** [comment]
That would work for me...

Thanks!

**Comment by barijaona** [comment]
I tend to disagree.
The current behavior is similar to the default one in Safari, and in my opinion, it's for good reasons. Saving screen space should be high priority for a content based app like Vienna. So tab bar should appear only if : 
- user has explicitly required it (via a **dedicated** setting or through the "Open new tab" comment)
- or it is required by the context (multiple tabs used)

I understand from @MacDisein 's comment that he is mostly annoyed by the animation which was recently added to the tool bar (commit 24dd91d). I suggest we reverse it, and wait a decision on replacement of PSMTabBarControl to make more significant UI changes.

**Comment by MacDisein** [comment]
Got you, then please revert the annoying animation

**Comment by MacDisein** [comment]
If I compare the behavior of the tab bar in version 3.2.0 Beta 2 with the 3.2.0 release - than it behave different - and this is really annoying because the whole article list is shaking around when the tab bar become visible or disappear.

**Comment by josh64x2** [comment]
That's true, it is quite annoying

**Comment by TAKeanice** [comment]
This will be solved when I replace the tab bar.

**Comment by MacDisein** [comment]
Solved, great implementation
