### ISSUE TITLE
Improve tab saving / reloading

### ISSUE THREAD

**Issue by TAKeanice** [ViennaRSS/vienna-rss#1061]
I tend to have many tabs open with news that I want to read later, as I usually do in Safari or Firefox when investigating a topic.

I also usually close the application when I am done reading or have to go somewhere else.

The first part of the issue happens when opening Vienna again: Every open tab is being reloaded immediately, instead of when I select it. That needs an awfully long time and also internet volume.

The second issue affects me less often, but is worse: Sometimes, when the list was very long, after re-opening Vienna, all URLs to be loaded are gone. Every tab is still re-opened, but displays "No title" ("Ohne Titel" in German), does not load anything and has no url in the url field.

I suspect that the latter issue is a combination of the tabs still loading but me already closing Vienna again. This suspicion is supported by my observation, that Vienna starts loading the most recently opened tab first, and sometimes a small number of most recently opened tabs still has a title and a url when re-opening Vienna another time later, but the older ones do not. It does not happen every time when closing Vienna while the content of the tabs is still loading, though.

Sorry that I cannot pin the issue more closely. I love Vienna for being a still active RSS project, which for me is the favorite way to read my bundled news! Keep up the fantastic work! I might at some point help contributing a little...

**Comment by barijaona** [comment]
You are probably right regarding the second issue : it is related to the fact that while Vienna is still restoring the saved tabs, quitting the application also requires it to save existing tabs.

Thanks for the suggestion to reload a tab only when the user selects it. We will probably try it after treatment of issue #762

**Comment by Eitot** [comment]
CPU and memory management in relation to WebView is not that easy to do, especially not in a multi-tab interface. Loading a tab upon selection would be an efficient solution, but it will of course add delays. An alternative solution would be to fetch the web content in the background and then pass the data to the web view once it’s shown (then it ‘only’ needs to be drawn).

Sadly, we cannot use Apple’s solution of having multiple XPC services.

**Comment by TAKeanice** [comment]
I think users are ok with delays when tabs are loaded on selection after they closed the application. Of course tab content would stay once loaded, for example if a user opened the tab from the feed or it was loaded due to some heuristic (e.g. the tab right to the selected one could be preloaded, and if it does not exist the left one, because it will be opened once the user closes the current tab). From my experience with Safari and Firefox, tab loading is done in such a way (minus the mentioned heuristic, so even more primitive).

**Comment by TAKeanice** [comment]
This is solved in the current release candidate
