### ISSUE TITLE
Missing delete button in toolbar

### ISSUE THREAD

**Issue by rawtaz** [ViennaRSS/vienna-rss#1069]
The toolbar is missing a delete button that can be clicked to delete the currently marked or focused article.

**Comment by Eitot** [comment]
Should be easy enough to add!

**Comment by Eitot** [comment]
@Aoiike: Would you be willing to help out with an icon?

**Comment by Aoiike** [comment]
I'm on it

**Comment by Aoiike** [comment]
![videlete](https://user-images.githubusercontent.com/26124815/36185385-ab11db32-1130-11e8-867a-10778222284d.png)
![videlete 2x](https://user-images.githubusercontent.com/26124815/36185388-acf2af4e-1130-11e8-807d-87ecb6ec8f08.png)

**Comment by rawtaz** [comment]
Bumping this as there's still no Delete button in the toolbar (in version 3.5.7) :)

**Comment by TAKeanice** [comment]
We are lacking a 3x or PDF version of the icon, @Aoiike or @Eitot I will leave it like that, the missing resolution can later be added to the DeleteTemplate image in the asset catalogue.

**Comment by Aoiike** [comment]
I must have forgotten to upload the PDF version at some point, added a second version without the arrow so you can choose whichever you see best fit.

[ViDelete.pdf](https://github.com/ViennaRSS/vienna-rss/files/5366034/ViDelete.pdf)
[ViDelete-alt.pdf](https://github.com/ViennaRSS/vienna-rss/files/5366035/ViDelete-alt.pdf)
