### ISSUE TITLE
Vienna unmarks the articles from Github feeds because Github sends slightly different message body each time.

### ISSUE THREAD

**Issue by stanislaw** [ViennaRSS/vienna-rss#1089]
First of all, as a happy user of Vienna I want to say thank you very much for making and maintaining this great RSS app!

I am seeing that the articles from the Github subscriptions like https://github.com/stanislaw.atom are always unmarked from "read" to "unread" even if I have marked them as read before.

I am looking at the payload of `article` and `updatedArticle` and compare their `body` fields in the
`-(BOOL)updateArticle:(Article *)existingArticle ofFolder:(NSInteger)folderID withArticle:(Article *)article` method and I am seeing that Github sends slightly different payload each time it is asked for the articles.

The following two pieces of payload from Github only have `data-hydro-hmac=` parameter different but this still makes Vienna to unmark the articles from being read (see also [Diffchecker for these two chunks](https://www.diffchecker.com/hrUvnoqS)).

Does anybody have a good idea how we could relax the rule that considers if the articles identical or not? Write an adapter specific to Github and do a bit more of parsing to exclude irrelevant modifications?

Thanks.

---

```
... 
          <a href="https://github.com/stanislaw" class="link-gray-dark text-bold wb-break-all" data-ga-click="News feed, event click, Event click type:PullRequestEvent target:actor" data-hydro-click="{&quot;event_type&quot;:&quot;news_feed.event.click&quot;,&quot;payload&quot;:{&quot;action_target&quot;:&quot;actor&quot;,&quot;org_id&quot;:null,&quot;event&quot;:{&quot;repo_id&quot;:121409745,&quot;actor_id&quot;:452547,&quot;public&quot;:true,&quot;type&quot;:&quot;PullRequestEvent&quot;,&quot;target_id&quot;:null,&quot;id&quot;:7244510505,&quot;additional_details_shown&quot;:false},&quot;originating_request_id&quot;:&quot;E9CA:245A5:1E25295:31CEA8A:5A871A3B&quot;}}" data-hydro-hmac="3777a287c1f2cb0570bddf395d8ac9cc7b5e508d69761dc647df27d77e4b9488" rel="noreferrer">stanislaw</a> opened a pull request in <a href="https://github.com/ligurio/practical-fm" class="link-gray-dark text-bold wb-break-all" data-ga-click="News feed, event click, Event click type:PullRequestEvent target:repo" 
...
```

```
...
          <a href="https://github.com/stanislaw" class="link-gray-dark text-bold wb-break-all" data-ga-click="News feed, event click, Event click type:PullRequestEvent target:actor" data-hydro-click="{&quot;event_type&quot;:&quot;news_feed.event.click&quot;,&quot;payload&quot;:{&quot;action_target&quot;:&quot;actor&quot;,&quot;org_id&quot;:null,&quot;event&quot;:{&quot;repo_id&quot;:121409745,&quot;actor_id&quot;:452547,&quot;public&quot;:true,&quot;type&quot;:&quot;PullRequestEvent&quot;,&quot;target_id&quot;:null,&quot;id&quot;:7244510505,&quot;additional_details_shown&quot;:false},&quot;originating_request_id&quot;:&quot;E9E5:245A5:1E26D4F:31CEE9C:5A871A3F&quot;}}" data-hydro-hmac="febc3bc7273009d74f61a2e570b84888ba52b24f0b23e1d34baa1a9253180907" rel="noreferrer">stanislaw</a> opened a pull request in <a href="https://github.com/ligurio/practical-fm" class="link-gray-dark text-bold wb-break-all" data-ga-click="News feed, event click, Event click type:PullRequestEvent target:repo" 
...
```

**Comment by josh64x2** [comment]
I will subscribe to your feed and take a look at how Vienna behaves whilst I contemplate how to handle it :)

**Comment by TAKeanice** [comment]
I have subscribed to my own feed and also the Vienna main branch feed, and I cannot reproduce the issue.
