### ISSUE TITLE
Notification sounds

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1093]
I have seen some user feedback about this. It appears that it is not as intuitive to turn the sound off in System Preferences → Notifications as I expected. Should we turn the sounds off again?

Alternatively, we could add a user preference to Vienna, perhaps even with custom audio.

**Comment by barijaona** [comment]
I didn't even notice when sound was added for the first time…

**Comment by Eitot** [comment]
I added it when I replaced Growl: #874.

**Comment by stanislaw** [comment]
Now that I know about System Preferences / Notifications I am happy to turn this sound off (only sound, all other notifications are on).

As an alternative, instead of having a custom sound this could be a FAQ question somewhere in the app. The FAQ should be easily discoverable though 😄

**Comment by DavidMunch** [comment]
Ah, that's the way to do it. iOS-ification strikes macOS again. 

I think the System Preferences centric approach is fine, I just never considered looking there after having been using Mac OS for 30 years. Also, I think a short description and perhaps a button that links to the location in System Preferences would be sufficient.

And yeah, I also turned off sound but kept the visual notification on. Maybe the audio notification shouldn't be on by default - Is that possible, or is it set by the system? RSS feeds are convenient and shouldn't be "in your face", and audio is that IMHO.

**Comment by Eitot** [comment]
> Maybe the audio notification shouldn’t be on by default - Is that possible, or is it set by the system? RSS feeds are convenient and shouldn’t be "in your face", and audio is that IMHO.

Sadly, this is not possible. A notification object either has a sound or it hasn’t. The API gives no control to set the user default in Notification Center. 

iOS 10 had comprehensive additions to user notifications which so far have not been replicated on macOS.

> Also, I think a short description in Vienna’s preferences and perhaps a button that links to the location in System Preferences would be sufficient.

An excellent suggestion! Will work on this.

**Comment by Eitot** [comment]
It appears that Apple has added the UNUserNotifications framework to macOS Mojave. It might now be possible to request permission to send audible notifications when first requesting access: [`requestAuthorization(options:completionHandler:)`](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649527-requestauthorization).
