### ISSUE TITLE
Can not subscribe any feed

### ISSUE THREAD

**Issue by ishell** [ViennaRSS/vienna-rss#1095]
macOS: 10.13.3
Vienna version: 3.2.1 :8e8c75b3:(6748)  download from github
When I subscribe feed like `https://xkcd.com/rss.xml` ,there is no response on vienna.
I google for that, only find it seems like that my system language is Chinese, but I cannot confirm .
<img width="421" alt="2018-03-05 6 20 05" src="https://user-images.githubusercontent.com/1236303/36969968-ea9ab12c-20a1-11e8-9e09-8084b7aeb9c9.png">

**Comment by barijaona** [comment]
I could not reproduce the problem, even after switching my system to Traditional Chinese (Hong Kong). Could it be a temporary network problem ?

**Comment by ishell** [comment]
<img width="780" alt="2018-03-06 12 07 00 pm" src="https://user-images.githubusercontent.com/1236303/37013789-003bbb26-2137-11e8-89fd-a03ae10cda58.png">
After change system language to English , vienna can subscribe.
But if I change the language to  `简体中文 (Chinese Simplified)` , and reopen vienna, still can not subscribe.

**Comment by marc-medley** [comment]
macOS: 10.13.3
vienna: 3.2.1 :8e8c75b3:(6748)

**Had two issues:**

1. launched after boot to find that ALL subscriptions had dissapeared.
2. tried to add new subscript, found that _can not subscribe to any feed_. (topic of this issue).

**Fix:**

Quit Vienna.

_"Removed"_ by renaming /Library/Preferences/uk.co.opencommunity.vienna2.plist, ./Library/Cookies/uk.co.opencommunity.vienna2.binarycookies, and /Library/Caches/uk.co.opencommunity.vienna2.

``` sh
mv ./Library/Preferences/uk.co.opencommunity.vienna2.plist ./Library/Preferences/uk.co.opencommunity.vienna2.plist.backup
mv ./Library/Cookies/uk.co.opencommunity.vienna2.binarycookies ./Library/Cookies/uk.co.opencommunity.vienna2.binarycookies.backup
mv ./Library/Caches/uk.co.opencommunity.vienna2 ./Library/Caches/uk.co.opencommunity.vienna2_backup
```

I did _not_ make any changes to `./Library/Application Support/ViennaBackup`

On relaunch, all the existing feeds were back in Vienna.

**Possible Cause:** 

Normally I quit all apps before shutting down.  However, the last shutdown was done without first quitting the applications.  (i.e. the various applications were left to respond to the system shutdown signal.) So, possibly Vienna does not behave well (e.g. cache corruption) if shutdown occurs while Vienna is still running.

**Comment by ishell** [comment]
Thx @marc-medley , but still not solve my problem.

It seems caused by vienna's i18n code, because when I change my system langugage to English, vienna can subscribe.

Is there anyone else can reproduce this issue?Only on my mac have this problem?

**Comment by ishell** [comment]
New version is still have this bug🤷‍♂️

**Comment by Eitot** [comment]
I will have a look.

**Comment by Eitot** [comment]
I can confirm that it won’t work with Simplified Chinese. My guess is that it relates to the RSSSources.plist file and its usage in NewSubscription.m.
