### ISSUE TITLE
Autoupdate mechanism broken between 3.2.1 and 3.3.0 Beta 1

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1096]
I uploaded a 3.3.0 Beta 1 yesterday.
Then I ran 3.2.1 after making sure that "Check for newer versions of Vienna on startup" and "Search for latest Beta versions" checkboxes in General Preferences are both checked.

Vienna 3.2.1 does not find the new beta and claims that it's up to date.
No update detection problem when trying to update from 3.2.0 or a 3.2 beta…

I guess that the cause is that 3.2.1 sits on the `stable` branch, while the new beta sits on the `master` branch, but I don't see how I can confirm this without disturbing normal users.
@dak180 , do you have any suggestion ?

**Comment by TAKeanice** [comment]
At least I can confirm the issue. It does not find the new beta.

**Comment by barijaona** [comment]
The hint used for Sparkle auto updates relies on `autorevision`'s `VCS_NUM`, which is [described](https://github.com/Autorevision/autorevision/blob/master/autorevision.asciidoc) as a count of revisions between the current one and the initial one.

`VCS_NUM` is computed as :
```
git rev-list --count `git rev-parse HEAD`
```

Apparently, confusion is caused by the fact that the `master` and `stable` branches diverged for such a long time.
So, a solution would be rebasing current `master` on current `stable`.
