### ISSUE TITLE
Move focus to external browser

### ISSUE THREAD

**Issue by viktorgoc** [ViennaRSS/vienna-rss#1098]
Hi, I prefer to use my external browser (FF) to read articles. It would be great if focus could switch to the browser when I click on the title field in Vienna. As it is now, the page opens in the browser but I have to manually switch to the workspace where the browser is.

Thanks for a great app,
/Viktor

**Comment by pukku** [comment]
Do you have the "open new links in the background" option selected in the preferences? If you uncheck that, it should work the way you want.

**Comment by viktorgoc** [comment]
Yes that was it. Sorry for causing some noise in the channel.
