### ISSUE TITLE
Build broken in Xcode 9.3 / macOS 10.13.4

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1108]
After a clean, build fails on SwiftLint:

src/FilterView.swift:24:40: error: Superfluous Disable Command Violation: SwiftLint rule 'private_outlet' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)

src/MainWindowController.swift:26:40: error: Superfluous Disable Command Violation: SwiftLint rule 'private_outlet' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)

**Comment by Eitot** [comment]
Curious, I don’t get that error.

**Comment by barijaona** [comment]
I didn't get it first, but it appeared once I performed a Product->Clean.

**Comment by josh64x2** [comment]
Fixed in #1113
