### ISSUE TITLE
Clicking feed URL in Safari opens it in Vienna, but can't subscribe

### ISSUE THREAD

**Issue by johnridesabike** [ViennaRSS/vienna-rss#1111]
When I click a feed URL in Safari, it opens in Vienna, and Vienna will display the pop-up window with the subscribe button. However, clicking subscribe will won't do anything.

As far as I can tell, this is because `feed:` gets automatically added at the beginning of the URL. For example, if you click this: [https://blog.dmptool.org/feed](https://blog.dmptool.org/feed) and open it in Vienna, it gets changed to this: `feed:https://blog.dmptool.org/feed`

Clicking the "subscribe" button in Vienna seems to have two different possible outcomes. If you subscribe with an open reader server, then simply nothing happens, and the feed is not added. If you subscribe without an open reader server, then the URL gets added as "(Untitled Feed)," and does not retrieve any items.

In both situations, there is no error message.

For now, users can avoid this error by manually removing the `feed:` portion of the URL.

**Comment by ahyattdev** [comment]
I am experiencing the same issue. Version 3.3.0 :7f06bb62: (6805)

**Comment by TAKeanice** [comment]
@Eitot probably it is possible to check first which url version is correct, right? It’s just with `feed:`, with `http:` and probably also `https:`...

**Comment by jbpjackson** [comment]
To add to this, I've also noticed that some URLS will replace the `http` with `feed` entirely (instead of just adding it to the beginning). For example, [http://feeds.feedburner.com/against-the-grain](http://feeds.feedburner.com/against-the-grain) will become `feed://feeds.feedburner.com/against-the-grain` when it's opened in Vienna.
