### ISSUE TITLE
Videos keep playing after closing tab

### ISSUE THREAD

**Issue by TAKeanice** [ViennaRSS/vienna-rss#1119]
Apparently videos are not stopped, when a tab is closed. This can be either because the webview is not released, or because the plugin is not told to stop. I encountered the problem on this page:

https://www.ndr.de/nachrichten/niedersachsen/hannover_weser-leinegebiet/Unbekannte-entfernen-Hakenkreuz-von-Glocke,naziglocke100.html
(please forgive that it is with nazi stuff, it was in the German news that I subscribed about a removal of the symbol from a bell.)

When starting the video, then closing the tab, the video keeps running. Probably related to #1112

**Comment by barijaona** [comment]
Do you mean that you encountered this problem with the branch of #1112 and with the Flash plugin installed ?

**Comment by TAKeanice** [comment]
No, the branch has the issues that I mentioned in the review. It is the current Vienna master branch version. I am not sure whether it is a flash or html5 video.

**Comment by TAKeanice** [comment]
Seems to be some custom player according to the website, but I have no idea on what technology it is based. When I do the same as above in Safari, the video stops when closing the tab.

**Comment by Eitot** [comment]
I remember that Apple used to have a separate process for decoding the video, until they added support for hardware decoding. It might be that the legacy WebView still uses this, possibly on older hardware.

**Comment by barijaona** [comment]
I was not able to reproduce the problem, so I can not really help here.

**Comment by TAKeanice** [comment]
For additional information, I use flash player "NPAPI-Plug-In-Version 29.0.0.140", Mac OS 10.13.4, and as I said the current main-branch version of Vienna.

**Comment by TAKeanice** [comment]
Possibly solved with #1121, let´s see

**Comment by TAKeanice** [comment]
See comment in #1121

**Comment by TAKeanice** [comment]
solved by #1125
