### ISSUE TITLE
Can not save the password of syncing in Preferences.

### ISSUE THREAD

**Issue by neargle** [ViennaRSS/vienna-rss#1131]
![image](https://user-images.githubusercontent.com/7868679/39037243-77429b10-44b2-11e8-84dc-b15e1e1445e1.png)
How to save the password? It will always be null, no matter what I do.

The post data in http body is always:
```
Email=xxxxxxx%40gmail.com&Passwd=
```

Which file is config file of this, can i just edit it?

**Comment by Eitot** [comment]
Which system language are you using?

**Comment by neargle** [comment]
Thx for reply.
Chinese (Simplified).

**Comment by barijaona** [comment]
I hope pull request #1245 will also fix this.
