### ISSUE TITLE
Notifications for individual new articles

### ISSUE THREAD

**Issue by khilangudka** [ViennaRSS/vienna-rss#1132]
Hi,

Apologies if this has already been discussed but I was unable to find an answer to it.

Is it possible to have notifications per new article pulled in? I've just discovered Vienna and I'm using it to keep track of GitHub activity by subscribing to our organisation's RSS feed. It would be really handy to be able to see individual articles (which in this case might be commits or comments on issues).

Currently the only behaviour I see is a notification saying that 1 new article has been retrieved.

Otherwise I think this is an awesome RSS reader.

Thanks!
Khilan

**Comment by DavidMunch** [comment]
At the moment no.
