### ISSUE TITLE
Crash: uncaught exception 'NSRangeException'

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1136]
```
Application Specific Information:
*** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFString substringWithRange:]: Range {72, 4} out of bounds; string length 75'
abort() called
terminating with uncaught exception of type NSException
```
Crash log attached below

Version 3.3.0 :7f06bb62: (6805) - macOS 10.13.4

feed causing the crash (new bugs filed on the Webkit Bugzilla site in the past 24hours):
https://bugs.webkit.org/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&chfield=%5BBug%20creation%5D&chfieldfrom=1d&chfieldto=Now&product=WebKit&query_format=advanced&title=Bug%20List&ctype=rss

Possibly some illegal character in the `<title />` improperly encoded. Note: the feed will change quickly (and “recover”).

[Vienna-crash.txt.zip](https://github.com/ViennaRSS/vienna-rss/files/1966028/Vienna-crash.txt.zip)

**Comment by phiw13** [comment]
I have the nagging suspicion that the offending `<title `> _may_ have been

`Use pointer instead of std::optional<std::reference_wrapper<>>`

**Comment by barijaona** [comment]
Do you have the XML file ? You can visualize it with "Get Info" then "Open Cached File…"
It should be in ~/Library/Application Support/Sources

**Comment by phiw13** [comment]
Sure, attached below are the xml files for 2 feeds. 
`folder 256.xml` is for the feed listed above
`folder 255.xml` is for a similar feed , but where the keyword is `fixed` instead of `new`, this feed started crashing somewhere between 10 and 12am Japanese Time today ( I was absent at that moment).
 
the possibly offending bug was quick fixed - [bug185186](https://bugs.webkit.org/show_bug.cgi?id=185186) Found it via the track listing

Note that the offending is not listed (was not recorded in the xml code). Vienna crashed before that could happen I think.

second feed url:
```
https://bugs.webkit.org/buglist.cgi?bug_status=RESOLVED&chfield=%5BBug%20creation%5D&chfieldfrom=1d&chfieldto=Now&product=WebKit&query_format=advanced&resolution=FIXED&title=Bug%20List&ctype=rss
```

[webkit-feeds-xml.zip](https://github.com/ViennaRSS/vienna-rss/files/1969612/webkit-feeds-xml.zip)

**Comment by barijaona** [comment]
Seems OK with 3.5.3
