### ISSUE TITLE
[Proposal] Folders column with duration since last article.

### ISSUE THREAD

**Issue by karlcow** [ViennaRSS/vienna-rss#1141]
On the left side, there is the folders column with the list of feeds.
It would be useful to have a timestamp (probably in days and years) of the latest article of the feed.

1d Foobar Cooking
2y Uncle Bob Feed
…

This doesn't relate to the last update date (aka feed HTTP request), but really the last time an article has been added in the feed.

Why is it important: 
That could help decide  if one wants to keep the feed in the folder list or remove it or move it to a oldies list with a refresh every once in a while.

**Comment by Eitot** [comment]
I agree that it is useful to have this information, but the suggested implementation is not something I would support. I think it would be much better to have this information shown in the activity viewer. It might also be useful if Vienna could notify the user if a feed has not been updated in a while.  I will add a new issue and close this one.
