### ISSUE TITLE
[3.4.0b1] Notification banner lacks article count

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1146]
The notification banner currently says:

'New unread articles retrieved'

In previous versions it used to say XX new articles retrieved - where XX is a number

**Comment by Eitot** [comment]
Also related: http://www.cocoaforge.com/viewtopic.php?f=18&t=27076

**Comment by Eitot** [comment]
This is puzzling. In the example above, “Credentials Prompt” is a localised string in [FeedCredentials.m#L67](https://github.com/ViennaRSS/vienna-rss/blob/master/Vienna/Sources/Alerts/FeedCredentials.m#L67). The localised string is present in Localized.strings and translated. I do not understand why it shows the key instead.

**Comment by Eitot** [comment]
@barijaona: The Localized.strings files in the compiled app are jibberish. Could be related to the encoding issue we encountered?

**Comment by Eitot** [comment]
@barijaona: In 3.4.2 the Base.lproj/Localizable.strings file is still corrupted.
