### ISSUE TITLE
Video does not stop when playing in last tab and tab gets closed

### ISSUE THREAD

**Issue by TAKeanice** [ViennaRSS/vienna-rss#1157]
If I play a video in the very last tab of Vienna, and close that tab with CMD+W or the little X at the tab, the video does not stop (audio keeps playing). However, when opening a new tab afterwards, the video stops.
It seems like, while plugins are stopped for tabs that get closed, they are not get stopped for the last open tab.

Another, maybe related bug, is that the title of the last tab in the tab bar overflow list is not shown. Instead, it keeps displaying the hostname of the website URL.

**Comment by ahyattdev** [comment]
I have looked into this issue and found the following:

[`dealloc`](https://github.com/ViennaRSS/vienna-rss/blob/dbee044cd0b4951a1e874318f185cf766441b0d8/Vienna/Sources/Main%20window/BrowserPane.m#L735) is called on `BrowserPane` when every tab but the last open tab is closed. It is not called on the last open tab until a new tab is created after the last tab has been closed. This is why video continues playing after the last open tab is closed and doesn't stop until a new tab is opened.

`dealloc` calls `handleStopLoading`, which includes stopping video on the page.

**Comment by TAKeanice** [comment]
Thank you very much, @ahyattdev ! I appreciate every hint that I can get, that saves me debugging time. Probably that missing deallocation was a mistake on my side with the integration of MMTabBar into Vienna. I opened the issue to document it and to be able to come back and fix it later. Later is now, since I have holidays now and thus time to help on Vienna again! I hope to be able to fix it in the next few days.

**Comment by ahyattdev** [comment]
@TAKeanice awesome! I lack the familiarity with the project to fix it so I left what I had noticed from debugging.

**Comment by TAKeanice** [comment]
https://github.com/ViennaRSS/MMTabBarView/pull/5 should resolve it.
