### ISSUE TITLE
Subscriptions don´t get refreshed

### ISSUE THREAD

**Issue by iortizdemen** [ViennaRSS/vienna-rss#1158]
Hi,

Thanks for reading. Many of my subscriptions do not get refreshed and when I get the info an validate the link it tells me it is valid. Moreover, if I open the link it works perfectly. Any help will be much appreciated. 

Kind regards

Iñigo

![screen shot 2018-06-23 at 15 36 58](https://user-images.githubusercontent.com/18899606/41810226-6c6a88ee-76fb-11e8-8c83-1916fb685ddb.png)

**Comment by mpbraendle** [comment]
The same here: Please check the following feeds:
https://www.uzh.ch/id/cl/dl/dn/feed.rss
https://www.uzh.ch/blog/zi/feed

**Comment by barijaona** [comment]
Look at the details in the Activity window after a refresh attempt
