### ISSUE TITLE
Vienna 3.4.0 crash at startup on 10.9.5

### ISSUE THREAD

**Issue by xif-fr** [ViennaRSS/vienna-rss#1162]
After update from 3.3.0 to 3.4.0, Vienna RSS crashes at startup.

Here is what it shows just before crashing :
![screenshot](https://user-images.githubusercontent.com/34941891/42724360-e2ade2b4-8770-11e8-81fa-2b27f2c4d6d9.png)

Here is the crash report :
[vienna-crash.txt](https://github.com/ViennaRSS/vienna-rss/files/2194927/vienna-crash.txt)

**Comment by canro91** [comment]
Same issue here. After installing it (`brew cask install vienna`), it crashes a few seconds later. Also, running OSX 10.9.5. Is it a know issue with these version?

**Comment by barijaona** [comment]
@josh64x2 Do you still have a 10.9 environment available ?

**Comment by barijaona** [comment]
@Eitot I don't know if this is related, but I notice a significant size difference between the MMTabBarView binary file in the 3.4.0 build (633296 bytes) and the MMTabBarView binary file located in my Carthage/Build/Mac folder (606844 bytes, same as in my Carthage cache).

Any idea ?

**Comment by barijaona** [comment]
@Eitot : I found the reason of the size difference. The output of the `make clean ; make release` commands will incorporate development build of the frameworks, while `carthage update` produces deployment versions.

**Comment by TorgoKong** [comment]
Just a note, I'm seeing this same crash (same stack crawl from the looks of it, same behavior), on 10.10.5 after updating to 3.4.0.

**Comment by barijaona** [comment]
Just to be sure, because I am not on my usual machine, so I cannot access to the 10.9 VM : can any of you verify this build is OK for you ?


[Vienna3.4.1.zip](https://github.com/ViennaRSS/vienna-rss/files/2223848/Vienna3.4.1.zip)

**Comment by xif-fr** [comment]
Yes, this build is ok for me on 10.9.5

**Comment by xif-fr** [comment]
Oh and by the way, this new version fixes an annoying bug I had since few versions : the webkit viewer was resizing automatically on certain web pages, sometimes very small (800px maybe).

**Comment by TorgoKong** [comment]
That webkit view resize fix is a welcome fix for me, too, as I had one feed that consistently triggered it.

Thanks @barijaona for the timely fixes!

**Comment by barijaona** [comment]
I am not sure what caused and what fixed the viewer auto resize, so let's credit all @ViennaRSS/contributors for the gradual improvements you are noticing !
