### ISSUE TITLE
Feature request: dark theme

### ISSUE THREAD

**Issue by ylluminarious** [ViennaRSS/vienna-rss#1164]
I recently tried out Vienna as an alternative to [Reeder,](http://reederapp.com/mac/) which is often recommended as the "best" RSS app for macOS. According to some things that I've read, Vienna seems more stable and mature. Indeed, it doesn't take much to be less buggy than Reeder. It's not uncommon that Reeder has inexplicable, spontaneous crashes. It also spawns a ridiculous amount of WebKit processes when fetching feeds. If you don't periodically restart Reeder, these processes go unchecked and can hang the whole system! On top of that, Reeder's developer is unresponsive and updates are infrequent.

Unfortunately, Reeder *does* have one feature that sets it apart: it has a very nice dark theme (two, actually). As I tried out Vienna, I was hoping to find that it has a dark theme as well. But, it seems that there is no such luck right now. I found [a post on the forum](https://forums.cocoaforge.com/viewtopic.php?f=18&t=27032) which echoes this same feature request, but it's completely stale with no replies. I am hopeful that we can get some action going here, especially with macOS Mojave approaching. I haven't tried Mojave yet, so I don't know whether the builtin dark mode will cover Vienna or not.

**Comment by josh64x2** [comment]
Hi @ylluminarious,

We are working on making sure Vienna is ready to work with Mojave's dark mode when Mojave is released. I have tried it out and we don't have very many changes to make thankfully :)

**Comment by ylluminarious** [comment]
@josh64x2 That's good to hear! Should I leave this issue open in the meantime?

**Comment by Eitot** [comment]
In case we do not make it in time and still want to link against the 10.14 SDK, there appears to be a user-defaults key to enable/disable the dark mode: `NSRequiresAquaSystemAppearance`.

**Comment by ylluminarious** [comment]
@josh64x2 @Eitot Just curious: are there any plans for a dark theme which is not dependent on Mojave? I.e., which would work on older versions such as High Sierra, Sierra, etc.?

**Comment by Eitot** [comment]
No plans. I suppose it can be done, given that [relevant APIs](https://developer.apple.com/documentation/appkit/nsappearancecustomization) are available. However, as Mojave offers this basically for free, I do not see much of a reason to work on this. PRs are always considered, of course. :)

**Comment by ahyattdev** [comment]
Agreed, I don't think it is worth the effort given that Mojave can do this.

**Comment by DavidMunch** [comment]
Mojave is here, and Dark Mode support for Vienna would be wonderful!

**Comment by josh64x2** [comment]
I know :( I need to finish the view-based table cells so we can enable it...

**Comment by barijaona** [comment]
Essentially closed with 3.5.0
