### ISSUE TITLE
Tumblr rss feeds don't work due to cookie consent

### ISSUE THREAD

**Issue by gradha** [ViennaRSS/vienna-rss#1166]
After wondering why I haven't been getting updates for months from tumblr feeds I checked on the subscriptions I had and saw that tumblr is serving some cookie accepting policy file and thus viennarss never gets any actual rss. Here is an example url: https://hematocritico.tumblr.com/rss, and here is the cached file as opened by xcode https://gist.github.com/gradha/d04e3611d505974c482d3406766c8721.

If I open the URL with chrome, I get the following screenshot along the redirected url: 
https://www.tumblr.com/privacy/consent?redirect=https%3A%2F%2Fhematocritico.tumblr.com%2Frss.

![captura de pantalla 2018-07-31 a las 23 27 25](https://user-images.githubusercontent.com/101927/43488253-5c1b357e-9519-11e8-8072-35cc1bd8243c.png)

The validator button points at https://www.feedvalidator.org/check?url=https://hematocritico.tumblr.com/rss which is able to get the rss, so it seems that tumblr is doing some user agent detection. Any ideas how to make this work in viennarss?

**Comment by teunzwart** [comment]
I'm seeing the same thing.  Other RSS readers had this issue too. The workaround used by Tiny Tiny RSS can be found at [https://github.com/GregThib/ttrss-tumblr-gdpr](https://github.com/GregThib/ttrss-tumblr-gdpr). 

The user agent also has an impact on the results, as per [https://discourse.tt-rss.org/t/change-on-tumblr-rss-feeds-not-working/1158](https://discourse.tt-rss.org/t/change-on-tumblr-rss-feeds-not-working/1158). Using curl with the default one yields the GDPR page, while using "googlebot" leads to the actual feed. 

Trying to consent on GDPR using the internal browser (Javascript has to be enabled) doesn't work (Vienna doesn't seem to use the same cookies for the feeds and the browser as per #522).

**Comment by Eitot** [comment]
I suppose it would be better to add some form of cookie management to Vienna. Vienna is currently using an older version of WebKit APIs which do not give that much control. I know that at least the newer APIs make this a lot easier.

I am, however, not willing to add site-specific workarounds for what is clearly an issue on Tumblr’s end.

**Comment by gradha** [comment]
I agree. I ended writing myself a small python proxy script (https://gist.github.com/gradha/83385ac91ad279c978d7647e4db5f56f) and modified my viennarss feeds to use it on some cheap host I had.
