### ISSUE TITLE
Smart folder can't be configured

### ISSUE THREAD

**Issue by Ruko2010** [ViennaRSS/vienna-rss#1167]
I think an image shows more than 1000 words. when I try to configure a smart folder, when I add a secound criteria, the first one gets invisible. But it is still present, because the filter I configured first is working! See what I mean. I select 8 Filters, only 4 are visible but all 8 are used for the folder. Even after a save and edit of the folder only 4 of them are visible:
![kapture 2018-08-03 at 15 26 48](https://user-images.githubusercontent.com/2239440/43645281-adf588b2-9731-11e8-9120-559441fb86e3.gif)

**Comment by barijaona** [comment]
Fixed in version 3.5.4

**Comment by Ruko2010** [comment]
Thanks for the Fix!
