### ISSUE TITLE
Trim whitespace before loading URL

### ISSUE THREAD

**Issue by rawtaz** [ViennaRSS/vienna-rss#1169]
If you copied a URL from some source where you happened to get the ending linebreak as well, Vienna fails to load the URL.

E.g. the URL "https://isc.sans.edu/forums/diary/Administrators+Password+Bad+Practice/23465/
" which has an ending linebreak will make Vienna say that it cannot find the requested hostname. If you remove the ending linebreak it works fine, however.

I suggest that code be added to trim any beginning and ending whitespace from URLs before they are used to load a site (when input in the address bar, that is).

**Comment by barijaona** [comment]
Fixed in version 3.5.4
