### ISSUE TITLE
feeds from Safari prepend feed:

### ISSUE THREAD

**Issue by RussWoodroofe** [ViennaRSS/vienna-rss#1170]
I often add feeds to Vienna by looking for the feed site in Safari.  Safari then asks to open Vienna.  So far so good.

The URL that Vienna gets, however, has "feed:" prepended to it.  (I.e., has the form "feed:https://site.com/feed".  Vienna doesn't recognize the feed scheme, and is unable to load the site.  It doesn't give a useful error message.  Since I don't add feeds that often, it usually takes me several minutes to figure out what is wrong.

I suggest that either Vienna should strip the "feed:" provided by Safari when present, or else (perhaps better) recognize and deal with "feed:" at the beginning of a feed URL.

**Comment by Eitot** [comment]
Already resolved with #1165.

**Comment by RussWoodroofe** [comment]
Apologies.  I did look for similar issues, but I guess I didn't go back far enough.  Thanks for all your hard work on the app!
