### ISSUE TITLE
I got error when trying to install the app

### ISSUE THREAD

**Issue by Asher1000** [ViennaRSS/vienna-rss#1180]
1. I download the project
2. open terminal, type cd and drag the folder that include the xcode project file
3. type catrhage update, this fetched the frameworks,build scheme and others
4. open the project, try to compile and run and got 3 errors :

![screen shot 2018-10-03 at 2 36 21 pm](https://user-images.githubusercontent.com/34809095/46408138-cd766b80-c719-11e8-95af-f0a7122d881d.png)

the first error :
built-in>:1:10: fatal error: 'XXXXXXXXXXX/Developer/Xcode/DerivedData/Vienna-bkrtsqwrmnwflheheqyugjvbcrdh/Build/Intermediates.noindex/autorevision.h' file not found
#include "/XXXXXXXXXX/Developer/Xcode/DerivedData/Vienna-bkrtsqwrmnwflheheqyugjvbcrdh/Build/Intermediates.noindex/autorevision.h"

**Comment by dak180** [comment]
Did you download the project or did you use git to clone it?

If you only downloaded the project then this is entirely expected, if you cloned the project then I would need to see the output of the `type -ap git` command.

> 1. I download the project

**Comment by Asher1000** [comment]
The green button say "Clone Or Download", I thought it's doing the same thing in 2 ways :)
Now I used git clone (and continue with the next steps) and it works perfect. Thanks !

btw.
so...what the difference between the 2 ways ? 
what git clone do that downloading the zip don't ?

**Comment by dak180** [comment]
Cloning the repo gets you the full repository and autorevision uses metadata there in to function; downloading, on the other hand only grabs the current version of files in the repo not the repo its self.
