### ISSUE TITLE
Some feeds fail

### ISSUE THREAD

**Issue by Henrietta1989** [ViennaRSS/vienna-rss#1181]
These feeds fail in Vienna but work in online RSS-reader:

feed:https://macscripter.net/extern.php?action=new&type=rss&fid=2
feed:https://macscripter.net/extern.php?action=feed&type=atom
feed:https://macscripter.net/extern.php?action=feed&fid=2&type=atom

**Comment by mpbraendle** [comment]
The same here: Please check the following feeds:
https://www.uzh.ch/id/cl/dl/dn/feed.rss
https://www.uzh.ch/blog/zi/feed

**Comment by mpbraendle** [comment]
My case is resolved. Our webadmin installed a Bot black list. This list denies requests that have the word CFNetwork in the User Agent string.

**Comment by barijaona** [comment]
The macscripter.net feeds run OK here.
