### ISSUE TITLE
Dark mode tab titles are hard to read

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#1184]
From 3.5.0 RC1, dark mode tab titles are hard to read.

![image](https://user-images.githubusercontent.com/799345/46715654-97923380-cc93-11e8-8189-3f49f24af18a.png)

**Comment by zachary822** [comment]
To add to this. The horizontal layout titles are impossible to read.

<img width="1204" alt="screen shot 2018-10-12 at 14 58 19" src="https://user-images.githubusercontent.com/4814373/46888734-59ca1200-ce2f-11e8-8bd3-581993d732de.png">

**Comment by josh64x2** [comment]
> 
<sub>[View in Slack](https://vienna-rss.slack.com/archives/C6B2GLJPL/p1539530406000100)</sub>

I'll need to test this in a 10.9 VM if someone hasn't already tested it?

**Comment by barijaona** [comment]
Closed by 3.5.1
