### ISSUE TITLE
Viewer intempestive resizes

### ISSUE THREAD

**Issue by xif-fr** [ViennaRSS/vienna-rss#1185]
The webkit view intempestive resize I mentioned at issue #1162 reappeared in Vienna 3.5.0 RC1 on OSX 10.9.5, but it is less an issue now because it is only intempestive, not systematic as before the 3.4.0.

To give more details, it happens only on some feeds, and only when I open the folder for the _first time_, and load a entry of the folder. I have to restart Vienna to reproduce the bug on a given feed, but it is deterministic. The amount of resizing depends on the feed (I guess it depends on some CSS properties of the website) and is only horizontal, not vertical.

PS : The modernization of the network access was great, all my sources now load properly

**Comment by barijaona** [comment]
Could you provide me an example of a feed which causes the issue ?

**Comment by xif-fr** [comment]
First, I'd want to point out that, since I opened the issue, the behavior changed with almost all update, and now it is less deterministic than before, but the resize is 'reversible' : when I delete the last article of the feed, the viewer revert back to the initial size. Well, sometimes. Quite strange.

I forgot to add that this happens often when the option "Load full HTML article" is activated. Note that JavaScript is disabled in the settings.

Here are some pages/feeds which triggers the resize :

- HTML : https://www.developpez.com/actu/248286/Internet-est-en-proie-a-une-vague-d-attaques-inedites-du-systeme-de-noms-de-domaine-a-annonce-l-ICANN/
- HTML : https://motherboard.vice.com/en_us/article/59xw45/shutdown (the width of the view becomes 640px, which correlates with the numerous `max-width:640px;` in the CSS of the page, here is a screenshot : [screenshot](https://www.xif.fr/uploads/vienna-view.png) )
- Feed : http://www2.cnrs.fr/rss.php?id=all
- Feed : https://www.bitchute.com/feeds/rss/channel/chemplayer/
- Feed : https://srv01.silvercraft.fr/utilities/rss/?action=display&bridge=Twitter&u=EKMeteo&norep=on&nopic=on&format=Atom (only when there is an image)

And here are some which doesn't :

- HTML : http://theconversation.com/south-sudan-peace-deal-offers-promising-end-to-conflict-but-challenges-remain-112167
- HTML : https://www.schneier.com/blog/archives/2019/02/friday_squid_bl_664.html
- HTML : https://phys.org/news/2019-02-reset-uriosity.html
- Feed : All YouTube video feeds

**Comment by Eitot** [comment]
I suspect that this is an auto-layout issue. It could be the result of the overlaying status bar or the attachments view at the bottom:

<img width="906" alt="screenshot 2019-02-24 at 23 27 22" src="https://user-images.githubusercontent.com/15073177/53306300-bf251980-388b-11e9-8bcd-8181bcfdbef9.png">

**Comment by xif-fr** [comment]
For feeds, It may well be. All the feeds which trigger the resize I pointed out have this bar.

For HTML pages, there is no such bar.

**Comment by xif-fr** [comment]
Seem to be fixed with version 3.5.5.
