### ISSUE TITLE
Visual bug in article list 

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#1195]
Version 3.5.0 :c42d4483: (6970)
OS X 10.13.4

I'm seeing this when initially loading a feed:

![image](https://user-images.githubusercontent.com/914142/47106513-c28d0200-d214-11e8-91bf-8e1e11776ae3.png)

That's not so bad, as it usually goes away when the articles load, but occasionally it gets stuck there and I have to browse to another feed and then come back for it to go away.

**Comment by barijaona** [comment]
It's a refresh indicator. You probably have many articles stored for this feed, and the initial load from database requires some time.

After this initial load, it gets much faster as the articles are cached in memory.

**Comment by tonycpsu** [comment]
Yeah, except under certain conditions it gets stuck there:

![image](https://user-images.githubusercontent.com/914142/49258288-e68e5680-f402-11e8-8e1f-47ecceae4859.png)

Seems to happen only with my non-cloud subscriptions (I use Inoreader for most of my feeds, but subscribe to a few directly.)

**Comment by barijaona** [comment]
Fixed in version 3.5.4
