### ISSUE TITLE
FreshRSS Support

### ISSUE THREAD

**Issue by bisherbas** [ViennaRSS/vienna-rss#1197]
Is it possible for Vienna to support Fresh RSS? I chose Other from the Sync settings but it didn't work for me.

https://freshrss.org/

**Comment by Alkarex** [comment]
FreshRSS supports clients through two APIs:
* Google Reader API (best set of features, most widely used, kind of de facto standard)
* Fever API

I can see the Vienna-RSS supports the [Open Reader API](http://rss-sync.github.io/Open-Reader-API/rssconsensus/) . As far as I can see, this API has never been written / completed (or I cannot find it - links welcome), and it is the first client I stumble upon that seems to support it.
I am happy to collaborate from FreshRSS side to make the compatibility happen.

Related: https://github.com/FreshRSS/FreshRSS/issues/2091

**Comment by bisherbas** [comment]
@Alkarex Thank you for responding and linking to the FreshRSS issue I submitted. I am quite new at self-hosted RSS world so unfortunaltely I cannot offer any contribution at this time. I am really hoping that someone from FreshRSS will respond. As far as I can tell both are great applications to solve the problem of news aggregation. It would be great to see if these two apps can work together.

**Comment by barijaona** [comment]
There is no important differences between Google Reader API and Open Reader API. 

I would appreciate temporary access to a FreshRSS account to debug this.

**Comment by barijaona** [comment]
@Alkarex 
Bonjour 😃
barijaona chez gmail point com

**Comment by barijaona** [comment]
Thanks to the collaboration with @Alkarex, a new compatible version of FreshRSS should be available soon.

Meanwhile, I found some improvements / clarifications in Vienna's OpenReader code which have been submitted as #1200.
I just want to make clear here that these changes are not directly FreshRSS related.

**Comment by bisherbas** [comment]
Thank you both! Awesome work.

**Comment by bisherbas** [comment]
@Alkarex Can you tell me how to install the appropiate commit onto my server without screwing everything up? I'm not very good at advanced `git` commands. I don't want to install a separate instance of FreshRSS just for testing. If I can simple `pull` the correct commit temporarirly and revert to back after testing is completed that would be great!

**Comment by Alkarex** [comment]
@bisherbas Have you installed FreshRSS using git?

If yes, please see https://github.com/FreshRSS/FreshRSS#example-of-full-installation-on-linux-debianubuntu

```sh
cd /usr/share/FreshRSS/ # Or the path you use
sudo git checkout -b dev origin/dev
```

Should do it. If not, please report any error message you might get.

If you have not installed it by git, you can just deploy https://github.com/FreshRSS/FreshRSS/archive/dev.zip on top of your installation (after having done a back-up).

**Comment by bisherbas** [comment]
@Alkarex Yes I did install FreshRSS using git. After checking out the dev branch via the command you have provided and verifying that everything works properly, can I return to the latest stable release with `sudo git pull`? Or is there another command I should run?
