### ISSUE TITLE
Open Reader Authentication Failed

### ISSUE THREAD

**Issue by y0y0z** [ViennaRSS/vienna-rss#1203]
i am using vienna version 3.5.0 :c42d4483: (6970).

i never had issues synchronizing with the oldreader.
i've verified my credentials are correct by login into oldreader service in the web browser but when i use the same credentials within vienna, i get the following error:

> **Open Reader Authentication Failed**
> Make sure the username and password needed to access the Open Reader server are correctly set in Vienna's preferences.
> Also check your network access.

i did exactly as https://github.com/ViennaRSS/vienna-rss/issues/376 suggest, but it did not work for me.
https://github.com/ViennaRSS/vienna-rss/issues/1201 suggest to use an older version.

am i missing something or is it a bug?

**Comment by barijaona** [comment]
Works correctly here.
I use e-mail address as user ID.

**Comment by y0y0z** [comment]
@barijaona:
i also use my email in the login information, yet it does not work.
i even tried to remove it by deleting vienna, and:
-  `~/Library/Preferences/uk.co.opencommunity.vienna2.plist` 
- `~/Library/Caches/uk.co.opencommunity.vienna2`

to start from scratch, but once i reinstalled vienna all the subscription where still there...
any clue how do i completely remove it to start fresh?

**Comment by barijaona** [comment]
Sorry, I missed your message.
You should also remove ~/Library/Application Support/Vienna

**Comment by hobrien** [comment]
I had the same issue authenticating with the Old Reader after updating. I rolled back to 3.4.0 and it's working perfectly again.

**Comment by barijaona** [comment]
Similar to #1201 

Could you try zapping Vienna's cookies ?
- Open ~/Library/Cookies in Finder
- Trash the `uk.co.opencommunity.vienna2.binarycookies` file
- Reboot

(You must do it through Finder, because macOS Mojave will prevent you from doing it through command line)

**Comment by barijaona** [comment]
I tried to reproduce your problem but was unable to do so.
I suggest you try this with the latest 3.5.4 : 
- verify first in Keychain Access.app that the 'Vienna sync' item is present; check if the account name and password are OK
- disable 'Check new articles on startup' in General preferences
- relaunch Vienna
- select menu item 'File -> Update Subscriptions From Open Reader'
- open Console.app : filter items with 'vienna', select them, copy and paste in a text file, zip it and let me have a look (post the zipped file here or send me at barijaona at gmail )

**Comment by hobrien** [comment]
I tried the cookies thing and it made no difference. Everything looks fine in my keychain. I've reproduced the behaviour on a second computer. Synching works with v3.4.2 but not with v3.5.4. The output from my console is [here](https://github.com/ViennaRSS/vienna-rss/files/2849224/hob_console.txt.zip). Thanks for your help with this

**Comment by barijaona** [comment]
Thanks @hobrien . But this output appears too truncated to me.
 
I'd be interested by a log part that would probably begin with something like : 
````
default	...	Vienna	[C1 Hostname#... tcp, url: https://theoldreader.com/accounts/ClientLogin?accountType=GOOGLE&service=reader, tls] start
default	...	Vienna	[C1 Hostname#... tcp, url: https://theoldreader.com/accounts/ClientLogin?accountType=GOOGLE&service=reader, tls] start
````
and would finish with something like
````
default	...	Vienna	[C2 Hostname#... tcp, url: https://theoldreader.com/reader/api/0/subscription/list?client=ViennaRSS&output=json, tls] cancel
default	...	Vienna	[C2 Hostname#... tcp, url: https:/theoldreader.com/reader/api/0/subscription/list?client=ViennaRSS&output=json, tls] cancel
````

**Comment by hobrien** [comment]
Yeah, weird. If I search for `Vienna`, I get output like the attached file. If I search for `Reader` I get this:

```
default	10:53:09.237467 +0000	Vienna	[C1 Hostname#49ee7b6b:443 tcp, url: https://theoldreader.com/accounts/ClientLogin?accountType=GOOGLE&service=reader, tls] start
default	10:53:09.865050 +0000	Vienna	clientAuthOperation statusCode 403 for URL https://theoldreader.com/accounts/ClientLogin?accountType=GOOGLE&service=reader
default	10:53:09.868453 +0000	Vienna	[C2 Hostname#49ee7b6b:443 tcp, url: https://theoldreader.com/reader/api/0/subscription/list?client=ViennaRSS&output=json, tls] start
default	10:53:40.375333 +0000	Vienna	[C1 Hostname#49ee7b6b:443 tcp, url: https://theoldreader.com/accounts/ClientLogin?accountType=GOOGLE&service=reader, tls] cancel
default	10:53:40.375646 +0000	Vienna	[C1 Hostname#49ee7b6b:443 tcp, url: https://theoldreader.com/accounts/ClientLogin?accountType=GOOGLE&service=reader, tls] cancelled
	[C1.1 <private> 192.168.1.32:50119<->IPv4#7362531b:443]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 31.137s, DNS @0.000s took 0.026s, TCP @0.028s took 0.110s, TLS took 0.357s
	bytes in/out: 5727/823, packets in/out: 6/4, rtt: 0.109s, retransmitted packets: 0, out-of-order packets: 0
default	10:54:10.492714 +0000	Vienna	[C2 Hostname#49ee7b6b:443 tcp, url: https://theoldreader.com/reader/api/0/subscription/list?client=ViennaRSS&output=json, tls] cancel
default	10:54:10.492871 +0000	Vienna	[C2 Hostname#49ee7b6b:443 tcp, url: https://theoldreader.com/reader/api/0/subscription/list?client=ViennaRSS&output=json, tls] cancelled
	[C2.1 <private> 192.168.1.32:50120<->IPv4#7362531b:443]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 60.623s, DNS @0.000s took 0.003s, TCP @0.005s took 0.111s, TLS took 0.387s
	bytes in/out: 5777/734, packets in/out: 8/3, rtt: 0.112s, retransmitted packets: 0, out-of-order packets: 0
```

**Comment by barijaona** [comment]
I am a bit confused… Your last post refers to a Vienna session, isn't it ?

**Comment by barijaona** [comment]
Another thought : do you have any special (Non ASCII) characters in your username or password ?

**Comment by hobrien** [comment]
When I launch Vienna and select "Update Subscriptions From Open Reader", then search for Vienna in the console, there are no messages about Old Reader, but if I search for Reader, I see the messages above. For some reason, they aren't showing up when I search for Vienna. 

Yeah, my pw includes `&`, `^`, and `!`

**Comment by hobrien** [comment]
That does seem to be the issue. I reset my password without those characters and it's working now

**Comment by barijaona** [comment]
Thanks for the info, I will work on this !
I will also try to improve password handling : currently, writing into/retrieving from keychain is behaving strangely.

**Comment by hobrien** [comment]
No problem. Thanks for making a great product

**Comment by y0y0z** [comment]
> When I launch Vienna and select "Update Subscriptions From Open Reader", then search for Vienna in the console, there are no messages about Old Reader, but if I search for Reader, I see the messages above. For some reason, they aren't showing up when I search for Vienna.
> 
> Yeah, my pw includes `&`, `^`, and `!`

confimed, this is indeed the issue.

**Comment by komisega** [comment]
Having this issue with Version 3.5.5. Have tried zapping cookies, changing password etc. Any tips?

**Comment by josh64x2** [comment]
@komisega if you're using Inoreader then it's probably related to #1252

**Comment by komisega** [comment]
> @komisega if you're using Inoreader then it's probably related to #1252

Ah, I see - I am using Inoreader so you must be right. Thanks
