### ISSUE TITLE
Buffer plugin sends Vienna in the background

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1206]
When the user uses the Buffer plugin, a Javascript attempts to close the Buffer tabview after user input has been validated.
This sends Vienna in the background: one has to reselect it in the Dock to continue working.

The problem appeared after version 3.3.0.
Any idea @TAKeanice ?

**Comment by barijaona** [comment]
Seems to be caused by #1130, especially the removal of definition of `webViewClose:`

**Comment by TAKeanice** [comment]
I did not watch for the plugins when refactoring. I will investigate it.

**Comment by TAKeanice** [comment]
Thanks for investigation. In order to remove the back reference from the browserpane to the browser, I had to remove the method, because it called the browser to close the tab. It needs to be added to the browser extension for WebUIDelegate now.
