### ISSUE TITLE
[BUG] constantly wants to update 3.5.2 to 3.5.2

### ISSUE THREAD

**Issue by JayBrown** [ViennaRSS/vienna-rss#1209]
I've updated Vienna to version 3.5.2 :624fb17e: (7000), and even though this seems to be the current release, it keeps bugging me that a new version is available, namely 3.5.2 :59e52e98: … if I install that update, it "works", but I always get the already installed version 3.5.2 :624fb17e:

This seems to be like a faulty appcast number, maybe. (?)

![snap](https://i.imgur.com/uwgAMlA.jpg)

**Comment by ylluminarious** [comment]
Yup, same problem.

**Comment by barijaona** [comment]
Not sure about the cause. I just remembered I amended some commits, and I may have forgotten to run `make clean` before `make release`.

Worked around by manually adjusting the appcast.
