### ISSUE TITLE
Vienna as default browser

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1210]
Vienna tends to be listed among dedicated browsers in System Preferences, giving users the option to choose it as the default browser. Is this desirable? I find it a bit confusing, to be honest.

I think it has to do with the URL type association for the http/https scheme in the Info.plist. I am not sure what this does. Removing it does not seem to have any (side) effect. Any thoughts?

<img width="443" alt="screenshot 2018-12-25 at 11 26 17" src="https://user-images.githubusercontent.com/15073177/50420595-e766ac80-0837-11e9-881c-43f7c8ad6522.png">

**Comment by barijaona** [comment]
Caused by #371

**Comment by Eitot** [comment]
I never noticed! I did a bit of digging and perhaps found an acceptable compromise:

According to the [Info.plist reference](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-101685-TPXREF107), `LSHandlerRank` gives a bit more control over the presentation. Setting the value to `None` retains the drag and drop, but removes it from the browser list. I haven’t found any other drawbacks so far.
