### ISSUE TITLE
Singular forms of some texts are not translated

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1219]
When I worked on #1218, using French localization, I noticed that "1 unread article" is not translated into French and remains in English, while the plural form is correct, giving for instance "10 articles non lus".

Both singular and plural forms are correctly translated in Crowdin, but it seems that the Localizable.dictstrings are not reimported into Vienna's Resources.

**Comment by Eitot** [comment]
Sadly, these have to be imported manually. Xcode and Crowdin are not cooperating as much as I had hoped. Xcode 10 even changed the export format again, so we have to change the import routine. :/

**Comment by barijaona** [comment]
OK, I will import the stringsdict-s manually.
