### ISSUE TITLE
feedvalidator.org down, discontinued?

### ISSUE THREAD

**Issue by slater** [ViennaRSS/vienna-rss#1233]
Vienna helpfully provides a direct link to feedvalidator.org to ... validate feeds. It seems like that site has been discontinued, and I get no response from the folks in charge of it.

Steps to reproduce bug:
1) Right-clicking on a feed in Vienna, then select "Get info".
2) In the opened window, click on the 'Validate' button.
3) Rejoice and delight at the harsh glow of an _Error 500 Internal Server Error_ message.

Maybe replace that button's action to go to https://validator.w3.org/feed/ ?

**Comment by Eitot** [comment]
Done by #1232
