### ISSUE TITLE
The "Move articles to Trash:" function is not working

### ISSUE THREAD

**Issue by denLaure** [ViennaRSS/vienna-rss#1248]
MacOS Mojave 10.14.3
Vienna 3.5.4 :8b11d92d: (7074)

I have "Move articles to Trash:" set to "after a month". However, I still have articles dated since November 2017 (i.e. more than one year old). Maybe I don't understand how it works or I have to set up some additional function?

**Comment by barijaona** [comment]
Are these articles marked read ? Are they starred ?

Only read and un-starred articles are automatically deleted.

**Comment by denLaure** [comment]
Yes, all of them a marked as read and un-starred

**Comment by marcpearson** [comment]
Same thing for me and all articles are read and un-starred

**Comment by rcgoncalves** [comment]
I'm experiencing the same issue.

To get old articles removed, I have to change that setting (e.g. from "After a Month" to "After 2 Weeks") and restart Vienna.

**Comment by Eitot** [comment]
I believe this issue was fixed by 48b23ff. This commit was deployed with Vienna version 3.6.0.
