### ISSUE TITLE
Headlines Visual Layout  Problem Version 3.5.4

### ISSUE THREAD

**Issue by neilt** [ViennaRSS/vienna-rss#1253]
Only seen on most recent version, Version 3.5.4 :8b11d92d: (7074). Only seen on one feed; [https://www.dailyfx.com/feeds/all](https://www.dailyfx.com/feeds/all)

<img width="560" alt="Screen Shot 2019-03-13 at 10 43 13 AM" src="https://user-images.githubusercontent.com/1809796/54292914-05ad9000-457d-11e9-850c-381290cc9588.png">

**Comment by neilt** [comment]
More info. The layout is 'Vertical', the style is 'Default'. and no filter.

**Comment by neilt** [comment]
This seems to happen to other feeds when turning showing the Author column.

**Comment by barijaona** [comment]
Could not reproduce the problem.

@josh64x2 could you reproduce the problem, before adding the “bug” label to the issue? (cf. [issue classificationcriteria](https://github.com/ViennaRSS/vienna-rss/wiki/Vienna-Development-Cycle#1-labelling-of-issues))

@neilt : Which items are checked in your "View -> Columns" submenu ? Which macOS version do you use ?

**Comment by neilt** [comment]
Just updated to Vienna Version 3.5.5 :817110fe: (7130).

The problem with the original feed does not seem to be present, but another feed has the problem.

Columns are; Read, Subject, Date, Author

Feed: [feed://feeds.feedburner.com/breitbart](feed://feeds.feedburner.com/breitbart)

<img width="542" alt="Screen Shot 2019-12-27 at 6 00 02 AM" src="https://user-images.githubusercontent.com/1809796/71516474-d4355500-286e-11ea-9026-35ac5fa1ef53.png">

**Comment by neilt** [comment]
Originally when I filed the bug report I am sure I validated the feed.  But this time it does not validate.  Here are the errors.

`
This feed does not validate.
line 31, column 24: Invalid email address: James P. Pinkerton (46 occurrences) [help]
		James P. Pinkerton	]]></author>
                        ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
line 25, column 217: Unregistered link relationship: standout (46 occurrences) [help]
... jerry-nadler-and-aoc/" rel="standout" />
                                             ^
line 30, column 2: An item should not include both author and dc:creator (46 occurrences) [help]
		<author><![CDATA[
  ^
line 817, column 197: media:title should not contain HTML unless declared in the type attribute: &#039; (2 occurrences) [help]
... twork&amp;#039;s Libra digital coin plan</media:title>
                                             ^
line 904, column 2: item contains more than one enclosure [help]
		<enclosure url="https://media.breitbart.com/media/2019/12/trumphomealone1. ...
  ^
`

The feed is attached.

[breitbart.zip](https://github.com/ViennaRSS/vienna-rss/files/4005263/breitbart.zip)

**Comment by Eitot** [comment]
Thanks for adding the feed, it helps.

I see two problems here: (1) the author name is shown twice and (2) the line break.

As for (1) I think the problem originates in this code [here](https://github.com/ViennaRSS/vienna-rss/blob/3c1c2a41f5b85e69de52637724a000dad59cc1b3/Vienna/Sources/Parsing/RichXMLParser.m#L394-L412). This part is executed twice per item if it has both `dc:creator` and `author` elements.

One way to fix this is to remove the inclusion of the `author` element, as the RSS2 specification sets out that this is supposed to be the email address of the author. It seems that the specification does not have an equivalent element for Atom’s `author` element. `dc:creator` is non-standard, but supported. Another way is to check if the author could be parsed as an email address and, if not, assume that the element refers to a name instead, then compare that value to `dc:creator` to avoid showing the exact name twice. @ViennaRSS/maintainers Any thoughts?

Problem (2) can be resolved by removing extraneous whitespace. The feed above declares the content of `author` and `dc:author` as character data (CDATA) and includes line spaces.

**Comment by Eitot** [comment]
What is weird about this is that I cannot reproduce the issue myself, even with the same feed. For me the text is just cut off (macOS 10.15.2).

<img width="400" alt="Screenshot 2019-12-27 at 20 03 19" src="https://user-images.githubusercontent.com/15073177/71529213-ef8e7780-28e3-11ea-9e95-8e3e1b69947b.png">

**Comment by neilt** [comment]
Did you try turning off the Attachment and Flagged columns. The only columns I have on are Read,  Subject, Date, and Author.  Also, the layout is Vertical and the style is Default.

**Comment by Eitot** [comment]
I have encountered the issue now as well, but I am not sure what changed since my test a few hours ago. I did not turn off the mentioned columns. The issue is clearly caused by the line-breaks in the author string though. Maybe there is some caching issue at play too.

**Comment by neilt** [comment]
This is with v3.5.5.  Add another data point. This, at first glance, looks like a different issue as the author strings don't exist. Creator cdata has no extra characters.

<img width="482" alt="Screen Shot 2020-01-08 at 6 09 43 AM" src="https://user-images.githubusercontent.com/1809796/71977343-29158b80-31de-11ea-8154-a135f89f5579.png">

[TheWirecutterFeed.zip](https://github.com/ViennaRSS/vienna-rss/files/4035200/TheWirecutterFeed.zip)

**Comment by Eitot** [comment]
I am not sure what is causing that. The source strings look fine this time. The issue seems to occur only when the author column is shown. I cannot reproduce it at all with the master branch.

**Comment by neilt** [comment]
Ok, I'll wait for the next release, unless there is someplace that nightly builds are located?

**Comment by neilt** [comment]
I am not seeing this problem in recent releases.  Thanks for working on this.
