### ISSUE TITLE
Wiley Onlinelibrary RSS feeds do not load

### ISSUE THREAD

**Issue by xiamaz** [ViennaRSS/vienna-rss#1254]
Wiley Onlinelibrary RSS feeds (RSS 1.0) do not seem to work with the reader.

They are correctly parsed by feedly.

An example link would be eg `https://onlinelibrary.wiley.com/feed/15524930/most-recent`

**Comment by josh64x2** [comment]
it looks like this is because the feed isn't valid: https://validator.w3.org/feed/check.cgi?url=https://onlinelibrary.wiley.com/feed/15524930/most-recent
