### ISSUE TITLE
Default Unsplash feed is not working

### ISSUE THREAD

**Issue by petecooper** [ViennaRSS/vienna-rss#1260]
https://github.com/ViennaRSS/vienna-rss/blob/f5712aa4c312e7a77d86189640b8c0a673f549e5/Vienna/Resources/DemoFeeds.plist#L35

Feed is not found in Vienna, Feed Validator does not recognise the URL.

![Screen Shot 2019-04-24 at 11 17 21](https://user-images.githubusercontent.com/226578/56652352-16284e80-6683-11e9-9bbd-b66de51ad498.png)
![Screen Shot 2019-04-24 at 11 19 23](https://user-images.githubusercontent.com/226578/56652353-16284e80-6683-11e9-85f1-9cd90d2b82fe.png)

**Comment by Eitot** [comment]
The feed appears to be gone. I suppose it should be removed from the list.
