### ISSUE TITLE
mark as read not working

### ISSUE THREAD

**Issue by y0y0z** [ViennaRSS/vienna-rss#1265]
i am using version 3.5.4 :8b11d92d: (7074) and articles are never marked as read. regardless whether i explicitly choose to "mark as read" or even after a short delay (while reading the article).

if it is importent, i am using theoldreader synchronization feature.

**Comment by y0y0z** [comment]
anyone?

**Comment by josh64x2** [comment]
Sorry for the delay, I'll try and look into this this weekend!

**Comment by y0y0z** [comment]
@josh64x2: were you able to reproduce the issue?

**Comment by josh64x2** [comment]
No sorry :( I am going to try again this weekend. Are you able to attach any logs that may help?

**Comment by y0y0z** [comment]
@josh64x2: which logs and how to produce them?

**Comment by y0y0z** [comment]
@josh64x2: launching vienna from the command line and checking logs printed on screen, i found nothing special which worth sharing.

the bug which doesn't mark article as read make the use of vienna useless :(
and it is a shame, as i really love vienna and i think it is one of the single application for mac which has an integration with theoldreader.com

please let me know which logs do you need in order to pinpoint the issue.

**Comment by josh64x2** [comment]
@y0y0z sorry that I'm really slow with replies. 

It seems confusing to get logs out of the new versions of Console app. What version of macOS are you using?

To help me narrow down this issue, what happens if you close Vienna, use the web interface of The Old Reader to mark an article as read, and then open Vienna again? Does the article still show as unread in Vienna but read in the web interface?

Thank you for your patience

**Comment by y0y0z** [comment]
@josh64x2: no need to apologies, i truely appreciate your work and dedication. especially since the project is an open source project. 

i just don't want to ditch vienna in favor for [other rss readers][1] - i want to support this project even if it is only by promoting vienna.

theoldreader web app and other rss readers with theoldreader integration are working smoothly.
although vienna shows the right amount of unread articles, all the articales are marked as unread and vienna shows all of the articles as unread -- feels like there is inconsistency in sync'ing with theoldreader.

i just updated my machine to catalina, but vienna still suffers from the same behavior
```shell
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A583
```

[1]: https://github.com/brentsimmons/NetNewsWire/issues/778

**Comment by josh64x2** [comment]
Are you able to send me a copy of your Vienna database file? I'm wondering if there is some sort of corruption which is preventing Vienna from updating the database to mark it as read.

I'm assuming you can find your way around the Terminal, so the file is `~/Library/Application Support/Vienna/messages.db`

Let me know if you need more detailed instructions to get the database file.

Thanks!

**Comment by y0y0z** [comment]
@josh64x2: due to security, i am not a fan of sharing my personal files. please share how would you check whether the (sqlite) database is corrupted, or how would you suggest to recreate the database file (shall i just delete the file and it will be recreated)

**Comment by y0y0z** [comment]
@josh64x2: could you please share any update on the issue?
