### ISSUE TITLE
Article won't display

### ISSUE THREAD

**Issue by GeorgeBogosian** [ViennaRSS/vienna-rss#1266]
Version 3.5.4 :8b11d92d: (7074)

How to reproduce:

1. Have a subscription/subject selected and an article displaying.
2. Choose a different subscription without selecting any articles.
3. Return to previous subscription and select the originally selected article.
4. Article will not display.

**Comment by josh64x2** [comment]
Hey @GeorgeBogosian which layout are you using?

**Comment by GeorgeBogosian** [comment]
Hi,

I'm using the vertical layout.
