### ISSUE TITLE
log into pocket button not working

### ISSUE THREAD

**Issue by piccolbo** [ViennaRSS/vienna-rss#1267]
When I try to save an article to pocket I am taken to a login screen (in Vienna, not the browser). So far so good. I enter my credentials, just checked to work in the browser. The log in button doesn't do anything. It looks de-activated, as if I didn't type password or login. The pointer doesn't change from an arrow to a hand when I am hovering over the button. I tried to log out and back in in the browser (firefox) and sure enough it all works.

**Comment by barijaona** [comment]
Do you have Javascript enabled in Vienna's internal browser ? (Advanced preferences)

**Comment by piccolbo** [comment]
That was it. Thanks
