### ISSUE TITLE
Memory leak on macOS 10.15 catalina

### ISSUE THREAD

**Issue by junkblocker** [ViennaRSS/vienna-rss#1269]
On macOS 10.15 catalina, Vienna starts consuming all the memory until the system runs out of it and throws up a 'Force Quit Applications' dialog.

**Comment by josh64x2** [comment]
@junkblocker I haven't had any memory leaks on macOS 10.15 and I've been running it since the very first developer beta.

Just to confirm, are you using the latest version of Vienna (3.5.4)?

How many feeds are you subscribed to? Do you use the internal browser to view articles? Do you synchronise with any sync servers such as The Old Reader or Inoreader etc?

**Comment by junkblocker** [comment]
Yes. About 50. Yes. No.

Well, after the upgrade to catalina it goes into beachball mode right on launch and I can't even do anything with it. I can see the memory increasing at a few MB a second in Activity Monitor until it exhausts all the swap space. Close to full disk, the dialog happens which shows the memory being consumed too (80G or so about the space I have left on my disk).

**Comment by josh64x2** [comment]
OK I'm wondering if there is some sort of file corruption happening here. How comfortable are you with the command line?

**Comment by junkblocker** [comment]
I'm fine with command line. Tell me.

**Comment by Mezriss** [comment]
Same issue here. Vienna manages to open, render one of the feeds, then becomes unresponsive and starts to rapidly consume memory.
3.5.4 :8b11d92d: 
100-200 subscriptions (26k unread). 
I use internal browser. 
No sync to any servers

If this is unsolvable at the moment, is there at least a way to export my subscription list without launching Vienna?

**Comment by junkblocker** [comment]
> If this is unsolvable at the moment, is there at least a way to export my subscription list without launching Vienna?

**Comment by junkblocker** [comment]
I see the data is all there in `l ~/Library/Application\ Support/Vienna/Sources` but would need to write something to parse and extract the data.

**Comment by Eitot** [comment]
There is no mechanism to export the data from outside of the main app. The data is stored in a SQLite database. It should be fairly straightforward to extract the URLs from it, but obviously an export into a usable format (e.g. OPML) is more complicated.

**Comment by Mezriss** [comment]
Luckily I was able to catch about 30 seconds of responsiveness after launch and that was enough to export my subscription list.

Here is an excerpt from crash dump
[vienna_hang.txt](https://github.com/ViennaRSS/vienna-rss/files/3725703/vienna_hang.txt)

**Comment by Eitot** [comment]
I have little experience with these crash reports, but I do notice a lot of references to WebKit. It might be something caused by WebKit in some way. Legacy WebKit is unsupported as of 10.15, so there is no certainty that it works as expected anymore on that platform.

There was work underway to support the modern WebKit API… (@TAKeanice)

**Comment by junkblocker** [comment]
> Luckily I was able to catch about 30 seconds of responsiveness after launch and that was enough to export my subscription list.

That gave me the idea to use https://github.com/AppPolice/AppPolice to slow it down on my system and export, which worked!

**Comment by josh64x2** [comment]
Just wondering if you have Vienna set to automatically refresh your feeds or not?

**Comment by junkblocker** [comment]
I have.

**Comment by josh64x2** [comment]
@junkblocker can you please try turning off the refresh and see if it still chews up all of your RAM? Or at least try to cancel the refresh. Then we can try and narrow down where this leak is happening.

Thanks :)

**Comment by junkblocker** [comment]
No luck. I disabled automatic refresh on load. Relaunched. It goes unresponsive still and memory continues to leak.

**Comment by TAKeanice** [comment]
Yes, the effort to replace the old WebView is still underway - work was interrupted by me writing my master thesis. Another caveat about the new WebKit framework is that it does not offer all the functionality we used to have - on macOs, where it seems to be a incredibly dumbed-down version compared to the iOS one.
I will restart my efforts in November, but if anyone wants to check out my work so far (and maybe rebase it to the newest version), it is tracked here: Browser <https://github.com/ViennaRSS/vienna-rss/projects/10> and in this branch webkit_browser <https://github.com/TAKeanice/vienna-rss/tree/webkit_browser>

**Comment by josh64x2** [comment]
It would be extremely helpful if someone who was experiencing this issue felt comfortable enough to share their database file. 🤞

**Comment by convex-problems** [comment]
Same issue here (late 2012 Mac Mini) since update to Catalina. The refresh process basically seems to work, because after every kill and restart of Vienna process the number of unread items shown in the top of the window has grown. My database is relatively small (only 11 feeds, about 12 MB of data in messages.db, uncompressed) and contains no secrets, so I attached it ;-)
[messages.db.zip](https://github.com/ViennaRSS/vienna-rss/files/3742922/messages.db.zip)

**Comment by josh64x2** [comment]
@convex-problems thank you! Unfortunately I still can't replicate this issue :( Could you please take a screenshot of Vienna and how it looks as the memory usage starts climbing? 

For example this is Vienna using only 86MB of RAM (and your database file)
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/799345/67085132-ffa22080-f1e9-11e9-8a1a-698a54878a20.png">

**Comment by convex-problems** [comment]
No problem. You will notice that memory usage at the moment of the screenshot is more than 3 GB and Vienna says "Aktualisierung durchgeführt" which means "Refresh completed". 
![screenshot_20191018](https://user-images.githubusercontent.com/56716620/67089250-7a961780-f1a7-11e9-926a-29ccfdcef385.png)

**Comment by josh64x2** [comment]
@convex-problems interesting. Does the memory leak still happen if you only have a feed selected and not a smart folder?

I won't have a chance to test this myself until tomorrow morning.

**Comment by convex-problems** [comment]
Sorry, no chance to change the selection from a smart folder to a feed. Vienna is in beachball mode, and the GUI is not responding. I add parts of the crash report, maybe it helps ...
[20191018_CrashReport_part.txt](https://github.com/ViennaRSS/vienna-rss/files/3743707/20191018_CrashReport_part.txt)

**Comment by josh64x2** [comment]
OK I can reproduce by using the smart folders with the unified layout. I think the smart folders only affects it due to the amount of articles it tries to display.

**Comment by josh64x2** [comment]
To confirm this issue can you please run:

```
defaults write uk.co.opencommunity.vienna2 Layout -int 1
```

in the Terminal and then launch Vienna?

**Comment by junkblocker** [comment]
> To confirm this issue can you please run:
> 
> ```
> defaults write uk.co.opencommunity.vienna2 Layout -int 1
> ```
> 
> in the Terminal and then launch Vienna?

Yep, that seems to make it stop leaking.

**Comment by josh64x2** [comment]
Thanks, OK it's an issue with the Unified layout on 10.15. I'll look into it :)

**Comment by convex-problems** [comment]
> defaults write uk.co.opencommunity.vienna2 Layout -int 1

I can also confirm that Vienna is operational after doing that. When trying to change back to the unified layout Vienna immediately goes into beachball mode and starts leaking again. But I think I can handle that for a while ;-)

**Comment by josh64x2** [comment]
OK I think I've found the real issue:

https://github.com/ViennaRSS/vienna-rss/blob/2b555770756b4e56786d0078ef4982a9635cfe3f/Vienna/Sources/Main%20window/UnifiedDisplayView.m#L305-L329

So I (or someone else if they are quicker 😄 ) can get this fixed permanently soon.

**Comment by nsherron90** [comment]
Not at all relevant but, I just wanted to say this was a refreshing issue thread to read.  I see so many issues go stale (for many reasons) from lack of feedback/followup by the maintainers and/or the issuer. Well done @josh64x2  and @junkblocker  👍

**Comment by junkblocker** [comment]
Hello, Any updates on this? Vienna has been frankly unusable on Catalina. Even without Unified layout, everything is slow and every click causes beachballs. Worse with images and media. Video play has completely broken audio and the play otherwise is very jittery.

**Comment by convex-problems** [comment]
From my point of view this issue is fixed with 3.5.5!

**Comment by junkblocker** [comment]
Hurray! This is indeed fixed. Beautiful gift first thing in the morning!
