### ISSUE TITLE
The forum is down

### ISSUE THREAD

**Issue by maxnordlund** [ViennaRSS/vienna-rss#1279]
I'm not sure if you have noticed, or if this is the right place, but I figured I should say something. The gist is that cocoaforge seems to have gone by by, and is now parked by godaddy.

I read #506, but unfortunately http://forums.cocoaforge.com/viewtopic.php?f=18&t=26795 is not in the wayback machine and I can't read what was said there.

**Comment by josh64x2** [comment]
Thanks @maxnordlund - I had not checked the forums in a couple of weeks or so. I'll check in with the hosting provider but unfortunately some old developers owned the domain so I doubt we will get it back. We might have to set it up under forums.vienna-rss.com

**Comment by josh64x2** [comment]
@maxnordlund this should be resolved now - the auto renew for the domain wasn't working.
Thanks!

**Comment by maxnordlund** [comment]
👍
