### ISSUE TITLE
Sparkle edDSA signature

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1282]
[Sparkle 1.21](https://github.com/sparkle-project/Sparkle/releases/tag/1.21.0) and newer has a different signature scheme than before (ed25519 instead of DSA). For this, Sparkle has created helper tools based on a portable [ed25519 library](https://github.com/orlp/ed25519) to create and sign the releases. The previous scheme is deprecated, but both schemes can be used simultaneously.

Further reference: https://sparkle-project.org/documentation/

I have found that the OpenSSL implementation is a bit flaky. I haven’t been able to generate an identical signature using the existing private key. There are many GitHub issues on the Sparkle repo about this. It has been suggested that the OpenSSL libraries in macOS are to blame.

**Comment by Eitot** [comment]
Carthage sadly fails to build the correct Sparkle scheme that contains the helper scripts for the signature scheme. We may have to find an alternative.

**Comment by barijaona** [comment]
Did you try the 2.x branch ?

**Comment by Eitot** [comment]
Resolved by #1485
