### ISSUE TITLE
crashes on updating feeds in compact view since Catalina 

### ISSUE THREAD

**Issue by sozifa** [ViennaRSS/vienna-rss#1283]
Since Catalina Vienna hangs with "spinning wheel of death" when switching view to compact with preview - works well in the other two options though - only solution I found so far is a complete reinstall of Vienna ... happens in every layout option  - worked great on Mojave so it must be related to Catalina ...

**Comment by Eitot** [comment]
Can you check with Vienna 3.5.5?

**Comment by sozifa** [comment]
3.5.5 fixed the problem - many thanks!
