### ISSUE TITLE
Next unread command shouldn't mark current read when it was manually marked unread

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#1290]
Often times I will want to mark the current article unread and move to the next using the "next unread" command.  However, this command marks the current article read before moving to the next unread.  This occurs regardless of what I have set for the "Mark current article read" setting.

Workaround is to use arrow keys or mouse to move to the next unread instead of the next unread command.  A proper fix would not update the current article's read state if it has been changed manually by the user while that article is selected.

Version 3.5.5 :817110fe: (7130)

**Comment by barijaona** [comment]
why don't you just flag the article ? ('m' shortcut to flag/unflag)
Very convenient with the "Unread or flagged" filter and the "Flagged articles" smart folder.

**Comment by tonycpsu** [comment]
Flag is for permanently marking my favorite posts.  Leave unread is for simply leaving it in a state where I'll see it again the next time I read that feed.

**Comment by TAKeanice** [comment]
Is this implemented?
