### ISSUE TITLE
cannot hide vienna window

### ISSUE THREAD

**Issue by captnblood** [ViennaRSS/vienna-rss#1297]
i got latest stable vienna release ( Version 3.5.5 :817110fe: (7130) ).
and the option to hide the window is not available.
if i right click on dock's vienna icon, from the contextual menu i see 'hide' option is grayed out.
from vienna window's menu itself, there's not even a grayed option to hide it.
all i get is 'minimize' which is not the same.

is there something i must do to enable vienna to hide instead of minimize ?
or is this a known issue already ?

**Comment by Eitot** [comment]
It works for me. Which OS version are you using?

**Comment by captnblood** [comment]
i have version: 10.15.4 (19E266)
for some reason, the option "hide" that was grayed out in doc's context menu is now available.
shortcut "command + h" is also working again whereas it wasn't before.
so i don't know what happened but it's working as it should now.
so i'll close my issue, and put this on human error from my part. 
i'll keep an eye on this and if it happen again i'll try to gather more info. 
sorry for the disturbance.
