### ISSUE TITLE
Feature requests: pin tabs, filter for invalid feeds

### ISSUE THREAD

**Issue by bsdooby** [ViennaRSS/vienna-rss#1300]
Love Vienna. Great app (although a little resource hungry with my many feeds on my old MacBook Pro 17'', 2011 model). Would be great to have the options:

> to pin tabs, or that the order of tabs is saved/stored
> to have a smart folder which lists invalid or no longer valid feeds (exclamation mark)

**Comment by TAKeanice** [comment]
If you break this up, we can more easily work on the individual topics.

**Comment by bsdooby** [comment]
Will do, thanks for letting me know!

Cheers from Switzerland
Peter

**Comment by TAKeanice** [comment]
Actually, the tabs should be saved in order. Have you experienced trouble with that? Make it into a separate issue anyway, I will look at the pinning part as soon as I have finished the browser rework (see #1312). Cheers back from Germany!

**Comment by barijaona** [comment]
Closing this as it was split into #1337 and #1338
