### ISSUE TITLE
Unread counter is hard to see if background is blue

### ISSUE THREAD

**Issue by kimbara** [ViennaRSS/vienna-rss#1304]
The unread mark indicates white number in light blue oval icon, so if the background of the Vienna window is blue, the white number is really hard to read because the feed list is transparent and would have soft blue background as the result (See attached screenshot).  Please make the color of the oval icon to dark gray like Mail.app. 

<img width="265" alt="スクリーンショット 2020-05-27 13 52 49" src="https://user-images.githubusercontent.com/6996761/82979250-8c834700-a021-11ea-82ce-9954a7905fb6.png">

**Comment by Eitot** [comment]
Per the discussion at #1372, this appears to be a bug.

**Comment by barijaona** [comment]
Fixed in 3.6.1+

**Comment by kimbara** [comment]
Thanks!  The unread indicator in Gray color is much better for me.
