### ISSUE TITLE
Main window stopped responding

### ISSUE THREAD

**Issue by shish** [ViennaRSS/vienna-rss#1305]
My cat walked on my keyboard, somehow this triggered a change in layout where the feed name and item title were on top of each other instead of side-by-side. I wanted to go back to my regular view so, my first attempt was to restart Vienna, but now it seems soft-locked :(

The process runs, no windows open, but I can get to the menu. Window -> Main Window shows me the main window, but it's empty - I thought maybe "all my settings got nuked somehow" but adding a new folder / feed doesn't help either. It looks like the basic structure of the window is fine but it's disconnected from the database somehow?

<img width="897" alt="Screenshot 2020-06-05 at 10 18 25" src="https://user-images.githubusercontent.com/40659/83859484-e5d03200-a715-11ea-8010-2f661bc0d904.png">

I've tried moving ~/Library/Application Support/Vienna to Vienna.bak and restarting, but that doesn't seem to have helped. Are there settings stored somewhere else too?

**Comment by josh64x2** [comment]
Hi @shish I should be able to help, but first I'm going to need to see a photo of the cat that did this.

Thanks!

**Comment by shish** [comment]
Here she is, returning to the scene of the crime~ Unfortunately while randomly mashing keyboard shortcuts *appears* to have caused the problem, further random keyboard mashing didn't fix it :(

![ciri](https://user-images.githubusercontent.com/40659/83955461-19f93f00-a84b-11ea-8439-52374904bc3b.jpg)

**Comment by josh64x2** [comment]
Ahh, I see the problem. The cat didn't have enough scratches under her collar, and was trying to get attention.

I'm not entirely sure what the problem for Vienna is though. I'm assuming that your messages.db file (the main database) is not the issue, because you did try moving the `~/Library/Application Support/Vienna` folder already. 

If you want to nuke all of the settings for Vienna including the layout/window settings you could try running `defaults delete -app Vienna` in Terminal, and then starting Vienna. Please let me know how you go!

**Comment by shish** [comment]
`defaults delete -app Vienna` said `Can't determine domain name for application Vienna; defaults unchanged` - but I fiddled around using that command as a starting point, and `defaults delete uk.co.opencommunity.vienna2` worked :)

Before doing a reset I exported the broken settings, in case there's something in here that helps to figure out which edge case I hit - https://gist.github.com/shish/ae4046ae0805618353ad33e480a54d25

**Comment by josh64x2** [comment]
Oh that's annoying - I had originally prepared the `defaults delete uk.co.opencommunity.vienna2` but when I was reading the man page for `defaults` I saw the `-app Vienna` version and tried it out and it worked too. 

Thanks for sharing the settings! I'll take a proper look this week.

**Comment by shish** [comment]
Also just noticed: while the UI and the database appeared to be disconnected, I tried using the "new folder" button to see if any new content would be visible. It didn't help, but now that things are working again, I see that the folder is there. So the database is connected, just something in those settings made everything (tree of feeds, list of items, preview pane) invisible at once.
