### ISSUE TITLE
article not marked as read (version 2)

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1325]
This [old bug](https://github.com/ViennaRSS/vienna-rss/issues/678) is possibly coming back (Version 3.6.0 Beta 2 :2f2f6e4e: (7229) and 3.6.0 beta1 before that).

After several days running fine, all of sudden _some_ articles refuse to be marked read. Click on them, they are marked read but the article count (title bar, dock) does  not change. Change views (e.g from a smart folder to an individual feed in the feed list) and the article is marked un-read again.

Quit Vienna, reopen Vienna and all is well – the article can now be marked read.

macBook Air 2018, macOS 10.15 latest.

**Comment by barijaona** [comment]
Try "Reindex Database"

**Comment by phiw13** [comment]
So today I noticed the issue again, will try the "Reindex Database" (again)

Doesn’t Vienna do that when quitting ? Quiting and restarting Vienna always seem to fix the issue.

**Comment by barijaona** [comment]
I am afraid that your database is afraid.

Reindexing database helps fixing minor issues, but having the same problems reappear is a sign of more serious issues.

**Comment by phiw13** [comment]
> I am afraid that your database is corrupted.

Hmm would it be ? The issue above is actually the only (database related) problem I see, atm.

**Comment by phiw13** [comment]
But I will close this as I am apparently the only one seeing the issue.
