### ISSUE TITLE
Youtube subscription issue

### ISSUE THREAD

**Issue by akasaka99** [ViennaRSS/vienna-rss#1347]
Hi-
Did you get an answer on cocoaforge so i will ask it here if i may.
It seems that some youtube channels can be added as feeds and sometimes no. I get the feed "untiteled feed" with nothing in the feed and sometime for other channels it works.
However, that same channel when its imported through an xml file works fine?
Why this seemingly random behavior?
Thanks !

**Comment by barijaona** [comment]
If you go to the Activity window and select the feed, you will get more details on the nature of the error.

Are you sure the feed address is correct ?
- If the URL of channel's page looks like https://www.youtube.com/channel/CHANNEL_ID , then the RSS feed is at https://www.youtube.com/feeds/videos.xml?channel_id=CHANNEL_ID
- If the URL of channel's page looks like https://www.youtube.com/user/USER_HANDLE , then the RSS feed is at https://www.youtube.com/feeds/videos.xml?user=USER_HANDLE

**Comment by akasaka99** [comment]
Yes it worked. 
Thank you very much !!!
