### ISSUE TITLE
Travis is now paid

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1374]
I only just now learned that Travis switched to a [paid-only plan](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), even for FOSS projects. It seems that this transition has already occurred for Vienna:
<img width="676" alt="Screenshot 2020-11-26 at 00 19 30" src="https://user-images.githubusercontent.com/15073177/100291262-94468880-2f7d-11eb-9940-61880d0c20c3.png">

If that is indeed correct and if the cost per build minute (50 credits) is also true, then the project will run out of credits shortly.

**Comment by josh64x2** [comment]
I suggest we remove Travis for now and utilise only the GitHub CI. We can mark it as required to pass.

Unless @barijaona, do you want to apply for a renewable credit allocation for FOSS?

**Comment by barijaona** [comment]
OK, let's try the GitHub CI way. But as a first step, I would not set it as required to pass.

**Comment by josh64x2** [comment]
@barijaona We have been using GitHub CI for a while - if we remove Travis CI we should require GitHub CI to pass before allowing any merges.

This will prevent any build issues and broken unit tests...

**Comment by barijaona** [comment]
The problem is that we added tools without providing adequate documentation about use and implications… The situation is intimidating for newcomers in Vienna development.

The situation is even worst with SwiftLint…

**Comment by Eitot** [comment]
It looks as though Travis has not even responded to credit requests, if their support forums are an indication. Having someone request this regularly is undesirable for the project anyway. I have no second thoughts about GH Actions, given that GitHub is Vienna’s hub. If GitHub goes a similar route, then there will be options, no doubt.
