### ISSUE TITLE
Problems opening new tabs in current master branch

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1382]
After pull request #1375, new tabs are not visible.

**Comment by Eitot** [comment]
I didn't notice any problems. How can I reproduce?

**Comment by josh64x2** [comment]
i can't reproduce either - have you cleaned your build folder and reset your spm package caches?

**Comment by barijaona** [comment]
The problem seems to be intermittent. Like the "Cycle inside Vienna", it's difficult to identify a clear cause to the phenomenon.

**Comment by barijaona** [comment]
I am closing this as I can not reproduce exactly the same problem.
Probably related to difficulties with dependencies migrated to Swift Packet Manager.
