### ISSUE TITLE
Visual clue of presence of tab overflow menu is hidden

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1383]
When you have many tabs opened, a contextual menu listing additional tabs is available near the right end of the tab bar.

 Before transition to SPM (#1375), there was a visual clue of the existence of this overflow menu.  
<img width="265" title="A clue of the presence of additional tabs is displayed" src="https://user-images.githubusercontent.com/442030/100651040-e4df2c80-3355-11eb-968b-d26977d7b6ce.png">

Currently, the visual clue is missing. The menu is still present and usable, though, but you have to guess that it exists somewhere in the tab…

<img width="288" title="The double arrows sign is missing ! " src="https://user-images.githubusercontent.com/442030/100651146-135d0780-3356-11eb-8896-1300c29c12d6.png">

**Comment by barijaona** [comment]
MMTabBarView Demo does not have a similar problem.

**Comment by Eitot** [comment]
Maybe a problem with the asset catalog then. Is just this image missing?

Have you built the demo app against the same master branch of MMTabBarView?

**Comment by Eitot** [comment]
It does appear to be gone when I use the SPM version in the demo app. Building the framework normally works as usual.

**Comment by Eitot** [comment]
The problem appears to be that the SPM version shows no images at all. Functionality is otherwise unaffected.

**Comment by Eitot** [comment]
Please check ViennaRSS/MMTabBarView#33.

**Comment by Eitot** [comment]
Resolved by #1384
