### ISSUE TITLE
Vienna 3.6.1 doesn't open any window and shows no content

### ISSUE THREAD

**Issue by gradha** [ViennaRSS/vienna-rss#1389]
Today I opened Vienna 3.6.1, which I updated yesterday (or the day before) and was met with silence. The icon opened in the dock bar, but nothing was being shown. Using the options in the menu bar on top I was able to open windows one by one from the Window menu, but even when opened manually the only indicator of content I saw was the title bar indicating 514 items were unread.

![bad vienna](https://user-images.githubusercontent.com/101927/101278775-13c62a00-37be-11eb-93e8-29f5e514e20e.jpg)

I opened the gihub release page, downloaded 3.6.0 and was able to open the program normally and showing the content:

![3 6 0](https://user-images.githubusercontent.com/101927/101278801-2b9dae00-37be-11eb-9b7e-af7ae8a20d45.jpg)

In case it helps, [here is a log of the console filtering for the word vienna opening the bad 3.6.1 version](https://github.com/ViennaRSS/vienna-rss/files/5648672/badlog.txt), and [here is the same kind of log using version 3.6.0](https://github.com/ViennaRSS/vienna-rss/files/5648673/goodlog.txt).

**Comment by Eitot** [comment]
Which macOS version are you running?

The only two lines I see are these:
```
Unknown class NSSearchToolbarItem in Interface Builder file at path /Users/gradha/Applications/Vienna 3.6.1 bad.app/Contents/Resources/Base.lproj/MainWindowController.nib.
<NSBackgroundActivityScheduler: 0x600003248990>: Invalid value for interval (0.000000). The value must be >= 1.
```

**Comment by gradha** [comment]
Mojave 10.14.6 (18G6042).

**Comment by Eitot** [comment]
I have done a quick test. I can confirm the problem and it appears to be caused by the background activity scheduler, when the automatic refresh is set to “manual”.

**Comment by Eitot** [comment]
I can also confirm that the other line mentioned above (Unknown class NSSearchToolbarItem in Interface Builder file) appears to have no functional impact as far as I can tell. The search toolbar items works on El Capitan as it is supposed to.
