### ISSUE TITLE
Search not working in Vienna > 3.6.0

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1400]
Reported here: https://forums.cocoaforge.com/viewtopic.php?f=18&t=27234

> Search no longer works in Vienna 3.6.2. 
> Cannot search either All Articles or Current web page.
> Not sure if this has broken just with this updated version or the problem existed in previous recent versions. There seemed to be so many.
> It always used to work fine.
>
> macOS 10.15.7
> Mac mini (2018)

> Update: I have gone through testing versions 3.6.2 3.6.1 and the last version in which Search worked for me has been 3.6.0. So had to revert to using that.

---

I have not been able to reproduce this myself.

**Comment by vonstael** [comment]
Same behavior for me. Search is not working any longer 
macOS 10.15.7
Vienna Version 3.6.2 :3452c8e1: (7371)
MacBook Pro (15, 2016)

**Comment by Eitot** [comment]
I have tested this on El Capitan and there it works fine. I wonder if it’s pertinent to Catalina?

**Comment by josh64x2** [comment]
I can confirm 3.6.2 is broken on 10.15.7

**Comment by vonstael** [comment]
I have tested with MacBook Air (M1, 2020), Version 3.6.2 :3452c8e1: (7371), Big Sur 11.1
Search feature is working

**Comment by Eitot** [comment]
I think the problem is with the search field in the toolbar, not the search function itself. I have submitted a fix that should be deployed with the next version of Vienna.

**Comment by barijaona** [comment]
Can anyone using 10.15 confirm not having the problem with version 3.7.0 ?

**Comment by josh64x2** [comment]
@barijaona I confirm it.
