### ISSUE TITLE
Folder search field placeholder text barely readable

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1401]
Reported here: https://forums.cocoaforge.com/viewtopic.php?f=18&t=27235

> The background of the folder search field is too dark.
> ![image](https://user-images.githubusercontent.com/15073177/102776155-89b9bc00-438e-11eb-8b14-71f892c960ea.png)

--- 

I am not entirely sure what causes this. The text colour of the placeholder text is system-defined and looks alright to me in both El Capitan and Big Sur. However, I have seen instances where it does look wrong. It needs some testing.

**Comment by josh64x2** [comment]
Bump for myself
