### ISSUE TITLE
New smart folders not working correctly

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1402]
Reported here: https://forums.cocoaforge.com/viewtopic.php?p=140949#p140949

> Smart folders no longer work. I had to reinstall (last version 3.6.2) and re-import the opml subscriptions because Vienna was constantly crashing with the latest updates (I have imac 10.11.6). The old smart folders work, while the ones I create new don't seem to work at all, in the sense that the filters I set seem to have no effect. What can I do?
---

I have tested this on El Capitan myself. I cannot reproduce this.

**Comment by asmaloney** [comment]
So I've never used "smart folders" before but they don't seem to be working for me.

**Comment by barijaona** [comment]
I note that it works correctly if I use "Author" "does not contain" "Foo Bar"  
instead of "Author" "is not" "Foo Bar"

**Comment by TAKeanice** [comment]
I know it's two years later but may I suggest to the original author of the post to try the newest version and send a crash log? It should be more informative now with the newest generation of smart folders.
