### ISSUE TITLE
Regression in FetchManager in macOS 10.11

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1405]
I believe PR #1396 causes a regression in macOS 10.11 El Capitan (I have not tested any other versions).

The feed refresh (whether all or a specific one) can get stuck at 1 remaining feeds. The cancel toolbar item is not working when that happens. This is not reproducible for me with version 3.6.2. I tested three different versions of `master`, one without #1395, #1396 and #1392. The issue disappears without #1396.

@barijaona Any ideas?

**Comment by barijaona** [comment]
Did you identify the stuck feed ?
Have you tried reverting commit 7e70023f0cad339fa5fb82d0e0fd7f9d267c3d01 ?

**Comment by Eitot** [comment]
No feed seems to have problems refreshing. I used the default feeds of Vienna to test it. I can pick any feed and refresh it selectively and the issue still appears.

I cannot do proper debugging on El Capitan. I might to have to test line by line to see where the issue might be.

**Comment by Eitot** [comment]
I cannot reproduce the problem without 7e70023 anymore, so it appears to be the cause of the problem. I suspect there might be some concurrency bug?

All feeds appear to refresh correctly, but the overall fetch operation just never seems to wrap up properly. I used the default feeds and tested selective refreshes to rule out any feed problems, but the issue occurs almost all the time. Console does not log any errors.

**Comment by barijaona** [comment]
Fixed by #1410 (included in version 3.7.0)
