### ISSUE TITLE
Tabs broken

### ISSUE THREAD

**Issue by noyannus** [ViennaRSS/vienna-rss#1422]
No tabs are shown, but it is possible to cycle through them with `cmd-opt-right` and `cmd-opt-left`

Version 3.7.0 :5698f89d: (7429)
macOS 10.14.6 (18G2022)

**Comment by Eitot** [comment]
When does the problem occur? Can you show a screenshot? Have you checked your Console for any logs (you can filter by: `process:Vienna`).

Have you tried reverting to an older version of Vienna and if so, does the problem occur there also?

**Comment by noyannus** [comment]
tl;dr: Problem gone.


It started a while ago, with the update to 3.7 (iirc, had no time then to file a bug report). Looked like this:
![3 7 0](https://user-images.githubusercontent.com/6339921/103564034-1e0f3d00-4ebe-11eb-8464-a0b10ea3197d.png)

Strange… 
I ran 3.6.2, tabs were displayed. 
Quit it, launched 3.7.0, and it was OK, too. 
~8-/
Did the switch to 3.7 come with a change in a database that returning to 3.6 could fix?

**Comment by Eitot** [comment]
It is difficult to say what might be causing it if the problem is not easily reproducible. The database change ought to have nothing to do with this. I cannot think of any UI changes that effect the tab bar from version 3.6.2 to 3.7.0.

**Comment by noyannus** [comment]
May be something unique to my system. Thank you for your work!
