### ISSUE TITLE
Vienna crashing upon start

### ISSUE THREAD

**Issue by TempSpas** [ViennaRSS/vienna-rss#1427]
**Describe the bug**
This morning I refreshed Vienna and it froze my computer entirely, forcing me to restart. Upon restarting, Vienna now crashes every time I attempt to open it.

**To Reproduce**

**Screenshots**
Add screenshots to help explain your problem, if possible.

**Please complete the following information:**
 - Vienna version 3.7.1
 - OS version: macOS 10.14.6

**Additional information:**
I've attached the console.log output for when I try to open the program and it crashes.

[vienna_crash_log.txt](https://github.com/ViennaRSS/vienna-rss/files/5836563/vienna_crash_log.txt)

**Comment by Eitot** [comment]
It appears that your database is corrupted. Have you got any Time Machine backup or perhaps a backup from the last database upgrade? It is located in `/Users/myuser/Library/Application Support/Vienna/` and is called “messages.db.bak”.

**Comment by TempSpas** [comment]
Thankfully I had one from a few days ago. There's no way to fix the corrupted database? I followed the steps [here](https://www.2doapp.com/kb/article/how-do-i-repair-a-corrupt-database.html), but when I tried putting the new file in the path for Vienna it didn't work either. (I don't have the console output, but the error was something like "Table already exists")

Also, is there any way to prevent this from happening in the future?

**Comment by Eitot** [comment]
I cannot say whether the database is repairable. That would depend on the problem.

I have not experienced that an app, let alone Vienna, brings the entire system down. It might have been coincidental to some other problem, e.g. OS or hardware related. Without further data, it cannot be diagnosed on Vienna’s side.
