### ISSUE TITLE
Bintray is shutting down

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1434]
After 1 May, Bintray is no longer available. This will affect Vienna too, since Sparkle updates rely on it.

Source: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Eitot** [comment]
Homebrew Cask also has to be updated: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vienna.rb.

**Comment by josh64x2** [comment]
@barijaona what do you think of as "slow"? It makes out my home connection at > 6.0 MB/sec

**Comment by TAKeanice** [comment]
I experienced that for larger downloads, GitHub has a high speed at the beginning but creeps forward at a few bytes per second later on.

**Comment by barijaona** [comment]
For me, the local Sourceforge mirror (located in South Africa) is much faster than the US Amazon S3 servers Github uses.
