### ISSUE TITLE
Vienna loads but there's no screen

### ISSUE THREAD

**Issue by jwsapp** [ViennaRSS/vienna-rss#1451]
**Describe the bug**
When I open Vienna there's no window. 
**To Reproduce**
I tried cmd-1 and it's blank. 
**Screenshots**
Add screenshots to help explain your problem, if possible.
![Screen Shot 2021-03-17 at 10 10 54 PM](https://user-images.githubusercontent.com/80874344/111576952-b2bfd200-876e-11eb-8f63-b4b8387f79a7.png)
![Screen Shot 2021-03-17 at 10 19 19 PM](https://user-images.githubusercontent.com/80874344/111577068-de42bc80-876e-11eb-8cb7-6f928270587a.png)

**Please complete the following information:**
 - Vienna version Version 3.7.1 :d356d926: (7437)
 - OS version: MacOS 10.15.7

**Additional information:**
I downloaded a fresh copy of the app, but no change. 

I tried to use your support forum, but it says there was a problem with my account so I messaged the administrator about it but got no response. I tried to open a new account but wasn't able to. 

I have used Vierra for several years and I need it to work again. Please help!

**Comment by Eitot** [comment]
I suppose it is too late to try to resolve this issue, but for the record: there might be some corruption of app data (in the user library) that causes this, if installing a pristine copy of Vienna is not working.
