### ISSUE TITLE
Vertical split screen.

### ISSUE THREAD

**Issue by tbodt** [ViennaRSS/vienna-rss#1460]
**Is your feature request related to a problem? Please describe.**
My screen is wide, the articles and article list are not. This results in inefficient use of screen space as can be seen below:

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/5678977/121041624-c3795600-c767-11eb-8bdd-b6b55930787b.png">

**Describe the solution you would like**
I'd like a checkbox in settings that just makes the split pane vertical.

**Describe alternatives you have considered**
None

**Additional context**

**Comment by TAKeanice** [comment]
Other users have a screenshot in this mode as well: https://camo.githubusercontent.com/31fc0724851b0c56d7b1d6e6d1421e8e6a85f793adc194cf753a049145d0927d/687474703a2f2f696d6167652e70726e747363722e636f6d2f696d6167652f36336238396165616239373234366463626461326465346566363930363631652e706e67

**Comment by tbodt** [comment]
Oh, this is just in the View menu, I was looking for it in the preferences. :)

**Comment by TAKeanice** [comment]
Yes, I also had this confusion once... If I find time I may propose a change that puts this property into settings. Actually, that will be not too difficult to achieve, so if you by any chance have any IT background, and if you'd like to improve this, give it a shot and make a pull request!
