### ISSUE TITLE
Need to reimplement spacebar handling

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1475]
**Describe the bug**
Vienna 3.7.1 handles very nicely the spacebar:  you can go through all of your news just by repeatedly hitting the spacebar.
This is almost completely broken in current master.

**To Reproduce**
- Launch Vienna 3.7.1
- Choose Vertical or Horizontal layout
- Select a feed with long articles like The Conversation: https://theconversation.com/articles.atom?language=en
- See how you can progress into each article, as well as from an article to the following one, just by hitting the spacebar
- Try to  do the same thing with current master and assess how much you feel frustrated 😆 

**Additional information:**
While working on my `bugfixes` branch, I asked myself: why does the `Tab` protocol include `PageDown()` and `PageUp()` methods ?
In fact, these are only needed by AppController's handling of spacebar : https://github.com/ViennaRSS/vienna-rss/blob/7344bed0a75f98f3958ad064179b66a1fea30343/Vienna/Sources/Application/AppController.m#L2222-L2244

@TAKeanice's opinion needed here.

NetNewsWire has very similar needs and implements a `scrollOrGoToNextUnread` action in its MainWindowController: https://github.com/Ranchero-Software/NetNewsWire/blob/56abb94901345118b0662c5abf1b633782c87126/Mac/MainWindow/MainWindowController.swift#L266-L274
Some details are explained at: https://inessential.com/2017/12/20/wkwebview_workarounds

**Comment by barijaona** [comment]
The best solution seems to :
- remove `PageDown()` and `PageUp()` from the `Tab` protocol
- add `scrollOrGoToNextUnread()` to the `ArticleBaseView` protocol

It might be good to have a similar approach for the `back()` and `forward()` methods.

**Comment by TAKeanice** [comment]
I believe you already implement something like that in the bugfixes branch right? First part sounds good, but we need to keep the back and forward methods which are actually in use, because in one tab it is possible to navigate back and forward between web pages.

**Comment by TAKeanice** [comment]
One could also argue that page up and page down should go into the Tab interface because those are possible interactions with a web page. If they don't work yet, it would be better to not offer them for now though.
