### ISSUE TITLE
New WKWebView article view does not scale (Bigger/Smaller Text command)

### ISSUE THREAD

**Issue by sprgchma** [ViennaRSS/vienna-rss#1478]
**Describe the bug**

When you activate "Preview new webbrowser" checkbox the article pane always shows it's content at 100%. It does not respond to View->Bigger Text, View->Smaller Text menu command.

**To Reproduce**
Tick the "Preview new webbrowser" checkbox, restart and select one of View->Bigger/Smaller Text commands.

**Please complete the following information:**
 - Version 3.8.0 Beta 1 :fd960136: (7605)
 - macOS BigSur 11.4
 - Mac mini (M1, 2020)

**Additional information:**

If i don't activate "Preview new webbrowser" the preview scales it's content as expected.

**Comment by TAKeanice** [comment]
Thank you for the report! Indeed, the smaller /bigger feature is not implemented because there is no api in WebKit for doing so.
However, it should be possible to zoom using a pinch gesture on the trackpad or its equivalent for mouse. Could you try and report whether it suits your needs?

**Comment by barijaona** [comment]
Possible solution: https://stackoverflow.com/questions/34130319/how-to-de-and-increase-the-font-size-with-wkwebview

**Comment by sprgchma** [comment]
Unfortunately zooming is not an option:

- mouse does not have such functionality. It has "smart zoom" and it does not work in the article pane (double click does not zoom the article preview)

   ![mouse-smartzoom](https://user-images.githubusercontent.com/904364/131235225-9a3cc531-e00c-44fa-b533-784306cc78cb.png)

- zooming is not equal to bigger/smaller text. It scales whole the page:
 
   in the old article pane the overflown text is moved to next line 

  <img width="1126" alt="bigtext-old" src="https://user-images.githubusercontent.com/904364/131235269-aad1dda7-2292-40ee-8c02-a99f4525d300.png">

   but with zooming it is cropped by window edge

  <img width="1163" alt="bigtext-new" src="https://user-images.githubusercontent.com/904364/131235272-e5945dea-d3a5-4c52-afbd-1f27b478d898.png">

If it is not possible natively in wkwebview than can the text scaling be implemented as part of the styles bundle? As some variable to use in css for example?

**Comment by TAKeanice** [comment]
I get it. @barijaona posted a potential solution, which I will look into. So maybe we will get it working after all.

**Comment by Eitot** [comment]
Has anyone looked for private APIs in the WebKit source code yet?
