### ISSUE TITLE
with new WKWebView Article view: hovering over a link does not show link destination

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1479]
When using the “old browser” *and* have “show status bar” turned on, the action shows the destination of a link in an overlay at the bottom of the article, Safari style. This does not appear to work with WKWebView.

MacOS 11(latest) Vienna 3.8 beta1

**Comment by TAKeanice** [comment]
Indeed, this is something WKWebView doesn't seem to be made for. It was already a hassle to get the context menu to work. Thanks for the feedback though, I will certainly look into it and try to find a way!

Just one question, because I imagine that being much easier at the moment, would it suffice to have the link URL when right clicking, potentially displayed in the context menu?

**Comment by TAKeanice** [comment]
Oh and secondly, we welcome any feedback on the new browser, positive or negative!

**Comment by barijaona** [comment]
I've been trying to get WKScriptMessageHandler and OverlayStatusBar to work together for a few days now... No progress yet, but I remain hopeful.

**Comment by TAKeanice** [comment]
Where's the issue? Maybe I can help somehow...

**Comment by phiw13** [comment]
> this is something WKWebView doesn't seem to be made for. 

I was afraid so. Sad though. NetNewsWire uses WKWebView, I think? They do have this working, with the same display as Safari.

> Just one question, because I imagine that being much easier at the moment, would it suffice to have the link URL when right clicking, potentially displayed in the context menu?

That would be a potential solution, sure (that would be a bit surprising to users maybe, but there is a precedent – the long press on links in iOS).

**Comment by TAKeanice** [comment]
Well there is always the option to handle this via JS, and I guess NetNewsWire is doing it this way. Don't despair, one of the options will be implemented.

**Comment by barijaona** [comment]
Fixed by #1486
