### ISSUE TITLE
Javascript not disabled in internal browser (WKWebView)

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1484]
**To Reproduce**

Vienna Preferences > Advanced: **Uncheck** “Enable Javascript in internal browser”.

Read an article in a feed that  contains YT video or Bandcamp embeds.

* Expected result: the YT vid is displayed as a black box with an error message; the Bandcamp embed is not displayed at all.
* Actual result: the YT vid can be played/viewed; the Bandcamp embed is displayed, songs can be played, etc

macOS 11.latest, Vienna 3.8b1 + WKWebView
Sample feed: https://www.freejazzblog.org/feeds/posts/default – Regularly (often) includes Bandcamp embeds, and some times YT or Vimeo embeds (e.g 28 and 29/08 articles).

*notes*:
With the “old browser”, the problem does not happen, afaict.
The same applies in the actual web browser view, not only  article view.

**Comment by barijaona** [comment]
Yes, it's a current limitation as we are in early phase of development. 

Be warned however: I'm not sure we will be able to implement a convincing "no-JavaScript" mode. 

In fact, WKWebView forces us to emulate many functionalities through JavaScript.

**Comment by TAKeanice** [comment]
Does the "JavaScript enabled" configuration for WKWebView disable our injected JS as well? Currently in the constructor of CustomWKWebView we have that configuration hardcoded as "true"

**Comment by phiw13** [comment]
If JS enabled is required for the application-injected JS to work, then of course it does not make much sense to have that pref anymore.

(reason for filing: mainly tracking prevention; some feeds manage to insert some tracking cr*p, and I am not sure Vienna could opt-in to Safari’s ITP, which does  a more than reasonable job)

**Comment by Eitot** [comment]
[The documentation](https://developer.apple.com/documentation/webkit/wkpreferences/1536203-javascriptenabled) indicates that there is a distinction between JavaScript code that originates in the website and “user scripts” injected through WKUserContentController. Also note that this API is deprecated since macOS 10.15, the [replacement API] (https://developer.apple.com/documentation/webkit/wkwebpagepreferences/3552422-allowscontentjavascript) has clearer language: 
>If you change the value to false, the web view doesn’t execute JavaScript code referenced by the web content. That includes JavaScript code found in inline <script> elements, javascript: URLs, and all other referenced JavaScript content.

**Comment by barijaona** [comment]
> [The documentation](https://developer.apple.com/documentation/webkit/wkpreferences/1536203-javascriptenabled) indicates that there is a distinction between JavaScript code that originates in the website and “user scripts” injected through WKUserContentController.

I may miss something obvious here, but for me, setting `javaScriptEnabled` to `false` breaks all functions based on user scripts…

**Comment by Eitot** [comment]
You are right. The context-menu event listener does not seem to be working anymore.

However, when setting this:
```swift
// preferences
let prefs = configuration.preferences
if #available(macOS 11, *) {
    configuration.defaultWebpagePreferences.allowsContentJavaScript = false
} else {
    prefs.javaScriptEnabled = false
}
```
then it seems to work differently. I only tested this on Big Sur.

Can you check this too? What else doesn’t work specifically anymore?

**Comment by barijaona** [comment]
Your proposition works perfectly for macOS 11. But the alternative for earlier OSes (`prefs.javaScriptEnabled = false`) breaks all functionalities based on Javascript injunction:
- context menu commands ("_Open in background_" and "_Open in [alternate browser]_")
- determination of  cells heights for Unified layout
- RSS button in browser tabs
- display of links in overlay status bar

Tested on BigSur and El Capitan (10.11)

**Comment by Eitot** [comment]
Strangely, you can still send the message handler itself:
```js
window.webkit.messageHandlers.mouseDidEnter.postMessage(message);
```

e.g. this dummy code still works:
```swift
static let linkHoverScriptSource = """
  var message = {};
  window.webkit.messageHandlers.\(mouseDidEnterName).postMessage(message);
"""
```
But this does not:
```swift
static let linkHoverScriptSource = """
  window.onmouseover = function() {
    var message = {};
    window.webkit.messageHandlers.\(mouseDidEnterName).postMessage(message);
  }
"""
```

It doesn’t look as though event listeners or functions are working at all. I wonder if there is a workaround for this. I am having a hard time finding any decent documentation on this aspect at all.

**Comment by Eitot** [comment]
I may have found something in the WebKit source code:
`WKWebViewConfiguration._allowsJavaScriptMarkup` (requires macOS 10.12+ though)

This seems to disable JavaScript that originates in the website, but keeps the injected JavaScript working. It works similar to `allowsContentJavaScript` above. At least on macOS Big Sur, I found that YouTube does not work anymore with either setting. In both cases, the `javaScriptEnabled` has to be set to `true` (the default value).

Test commit: https://github.com/Eitot/Vienna/tree/javascript

**Comment by barijaona** [comment]
I will test tonight. It might be compatible with Safari 11.1 / Webkit 605.1.33 (latest available for OS X 10.11)

**Comment by barijaona** [comment]
Have a look at my branch `Javascript+Plugins` https://github.com/barijaona/vienna-rss/tree/Javascript%2BPlugins

I am tempted to require macOS 10.12 as a minimum for version 3.8.0, for two main reasons:
- new browser seems to hang easily with OS X 10.11
- no easy workaround to the current Javascript issue with OS X 10.11

I am going to install a 10.12 virtual machine before taking a decision

**Comment by Eitot** [comment]
The [keypath-based observers](https://github.com/barijaona/vienna-rss/commit/489284ea506632b0cfc7bbc8bd0c7e1d283904fc#diff-be10486530e818fb183f8a0804291000b3b7670be277a0bc106814d3c17a9a9bR62-R87) do not work here, at least not for changes at runtime (just the “initial” trigger), becayse the Preferences properties are not themselves KVO-compliant. You’d either have to add KVO signals to the accessors or use the ObjC-style observer methods by referencing the corresponding NSUserDefaults key directly.

I am not against raising the minimum OS requirement, but would it not be enough to just not offer the new browser to 10.11 users and raise the requirement when the old browser is removed? That’s still 2 minor versions of support, with other fixes included.

**Comment by barijaona** [comment]
> The [keypath-based observers](https://github.com/barijaona/vienna-rss/commit/489284ea506632b0cfc7bbc8bd0c7e1d283904fc#diff-be10486530e818fb183f8a0804291000b3b7670be277a0bc106814d3c17a9a9bR62-R87) do not work here, at least not for changes at runtime (just the `.initial` trigger), because the Preferences properties are not themselves KVO-compliant.

I see them working. The code is being called whenever I change the settings in Preferences. This is probably due to the bindings set by Interface Builder.

**Comment by barijaona** [comment]
> I am not against raising the minimum OS requirement, but would it not be enough to just not offer the new browser to 10.11 users and raise the requirement when the old browser is removed? That’s still 2 minor versions of support, with other fixes included.

I find it easier (and more optimal) to maintain a `stable` branch. I currently have a 3.7.2 version almost ready, but my intention is to publish it simultaneously with 3.8.0 Beta 2.

**Comment by barijaona** [comment]
Fixed by #1498

**Comment by barijaona** [comment]
The solution in #1498 is not perfect with systems prior to macOS 11 (as seen on my macOS Sierra 10.12 virtual machine).

I see the [code modifying the setting](https://github.com/ViennaRSS/vienna-rss/pull/1498/files#diff-be10486530e818fb183f8a0804291000b3b7670be277a0bc106814d3c17a9a9bR62-R71) being executed, but one does not see immediately the effects of the change. In fact, you will generally have to restart the application to ensure that the new setting is taken into account.

The explanation is that WKWebViews are heavily reused and recycled by the system. We are making changes to  the WKWebViewConfiguration, but as [stated by the documentation](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration): _The web view incorporates your configuration settings only at creation time; you cannot change those settings dynamically later_. So views created before the change of setting are still used and retain the previous setting.

The macOS 11 or later code, which modifies the defaultWebpagePreferences, is not affected by this problem.

**Comment by Eitot** [comment]
Since JavaScript is an “advanced” feature in Vienna, I think adding a label to tell the user that these settings only take effect after a restart ought to be enough.
