### ISSUE TITLE
Development builds are unable to access the "Vienna sync" keychain element

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1492]
I noticed that OpenReader syncing does not work anymore when I launch Vienna through Xcode.
Debugging revealed that the app fails to access the server's password through the Keychain: [the call to SecKeychainFindGenericPassword](https://github.com/ViennaRSS/vienna-rss/blob/2d2cd9b32fb2e0962163f2d6dc0685b202f82ba0/Vienna/Sources/Shared/KeyChain.m#L187-L196) returns a -25293 error code ([errKCAuthFailed](https://opensource.apple.com/source/CarbonHeaders/CarbonHeaders-18.1/MacErrors.h.auto.html))

The root cause is that there is a problem with the ad-hoc code signature that is applied by Xcode. If I check the built app with `codesign -vvvv`, I get "`invalid Info.plist (plist or signature have been modified)`", so macOS allows the app to run, but limits its security credentials.

I can punctually work around the problem by applying `codesign -f -s -` to the app, but I was unable to automate that: I tried adding a script for forcing the signature, but Xcode will perform frameworks copying and application signing after the script's execution.

The problem is clearly caused by the switch to Sparkle 2 (#1485)

No problem with Deployment builds, thanks to  the procedures described in `Release Instructions.md`

**Comment by Eitot** [comment]
Have you tried adding that routine to a post-build action under Vienna’s scheme?

**Comment by barijaona** [comment]
I prefer my issue-1492 branch

**Comment by barijaona** [comment]
Closed by #1494
