### ISSUE TITLE
GitHub Actions file

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1495]
The tests fail since #1485.

I am unable to track down the problem. I believe it is caused by an NSAlert that shows up after about 4 seconds, but I cannot ascertain which alert it is, nor can I reproduce it locally.

I disabled the automatic updates for Sparkle both by setting a launch argument in the Vienna scheme and by reversing the commit that enabled it (18a35660bec2a2c7c350b69fed92f8cc3e219867), but it makes no difference.

**Comment by barijaona** [comment]
Seeing where all tests are interrupted, I strongly suspect `testRenamingFile()` in DirectoryMonitorTests.swift

**Comment by josh64x2** [comment]
Relevant log:
```
Test Case '-[Vienna_Tests.DirectoryMonitorTests testEditingFile]' started.
726
2021-09-20 04:30:05.105909+0000 Vienna[5410:48212] Failed to find immediate ancestor for symbol at 0x4 - 0xa
727
2021-09-20 04:30:05.106030+0000 Vienna[5410:48212] Failed to find immediate ancestor for symbol at 0x4 - 0xa
728
2021-09-20 04:30:05.106068+0000 Vienna[5410:48212] Failed to find immediate ancestor for symbol at 0x4 - 0xa
```

**Comment by Eitot** [comment]
Nothing changed about the DirectoryMonitor tests that would explain this. I think this is a symptom of another problem; a coincidence that appears due to the delayed callbacks of the test methods (each test method waits for 2 seconds to check whether the DirectoryMonitor observed the changes to the directory).

This is why I think there is a GUI interrupt that happens about 4 seconds after launch, which is just around the time before `-testRenamingFile` returns.

**Comment by Eitot** [comment]
Thanks to @josh64x2 I was able to narrow down the problem to Sparkle's version checker. It seems that fails to validate Vienna's CFBundleVersion and then shows an NSAlert about 4 seconds after launch.

Changing the field to a fixed value resolved the problem. I suspect that something goes wrong with Autorevision at some point.
