### ISSUE TITLE
VIenna and Jira RSS feeds

### ISSUE THREAD

**Issue by michbsd** [ViennaRSS/vienna-rss#1520]
Hi, 

First off, thank you for all the work you put into this great RSS reader. Very much appreciated. 

I am running Vienna 3.7.2 on MacOS 11.6.

For "typical" RSS feeds Vienna is working brilliantly (by typical I mean each RSS entry is a brand new article , a good example of this : https://www.cloudflarestatus.com/history.atom) 

However, I also use Vienna to track movement on tickets in a JIra system.  I have a filter in Jira that looks like this:

```
Project = myProject AND status not in (Closed) AND updatedDate < now() AND updatedDate > -1d ORDER BY updated DESC
```
 
I can access the result of the above Jira filter in an RSS feed - the feed contains all tickets that have a "updatedDate" within the last 24 hours. 

For some reason, Vienna only displays some of these articles.
I just made a test right now, and my filter returns 16 Jira tickets - however, Vienna is only displaying 4 unread items (and they look to be new tickets vs an updated existing ticket). 

Could it be that Vienna for some reason will not take existing, but newly updated RSS items into account - as it might consider those as already "fetched' or something? 

Let me know if you require further explination. 

Many thanks,
Michael

**Comment by JykkeDaMan** [comment]
Anybody able to confirm this scenario?
- Fresh empty DB for Vienna.
- Get updated Jira tickets, all OK.
- Delete article from the main view (right click option menu) and from the Trash. I assume this will leave the rss_guid table entry into the message.db, which now prevents the updates to be detected???
- Update a Jira ticket
- Refresh the Vienna subscription feed.
- The updated Jira ticket is NOT seen any more, even if it is received and found from the cache file.

**Comment by barijaona** [comment]
Check if the article is still present in the Trash folder. Then, use "Restore Article" (contextual menu or Article menu)
