### ISSUE TITLE
Copying articles in the article list not working

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1527]
See the discussion at #1526 

Copying one or more articles in the article list throws an exception. The cause is ArticleListView’s `‑copyTableSelection:toPasteboard:` method which expects an NSIndexPath, but is handed an NSArray by MessageListView’s `‑copy:` method.

It might be worthwhile to refactor the code with the NSPasteboardWriting protocol. The Folder and Article classes could both adopt this protocol and reuse the code in `‑copyTableSelection:toPasteboard:`. NSTableView and NSOutlineView both use deprecated methods (`‑tableView:writeRowsWithIndexes:toPasteboard:` and `‑outlineView:writeItems:toPasteboard:`) that ought to be replaced with `‑tableView:pasteboardWriterForRow:` and `‑outlineView:pasteboardWriterForItem:`.

**Comment by barijaona** [comment]
As Xcode does not emit warnings, I prefer limiting myself to minimalist fixes …

**Comment by Eitot** [comment]
It does not with the current deployment target, but starting with 10.15 it does. You never know what happens on newer systems… (there were issues with this before, e.g. ). Regardless, an easy fix is fine for now.
