### ISSUE TITLE
Mark all articles read in a folder containing smart folders

### ISSUE THREAD

**Issue by eric-nieuwland** [ViennaRSS/vienna-rss#1532]
**Is your feature request related to a problem? Please describe.**
On folders with only feeds I can "Marks the current folder read then skips to the next folder with unread articles." (shortcut s).
On a folder with two smart folders in it this doesn't work.

**Describe the solution you would like**
When using "Marks the current folder read then skips to the next folder with unread articles." (shortcut s) on a folder with (only) smart folders all articles should be mark "read".

**Describe alternatives you have considered**
Manually access each smart folder and used "Marks the current folder read then skips to the next folder with unread articles." (shortcut s). This is a pain.

**Additional context**
N/A

**Comment by hphde** [comment]
I consider this a bug. I am using V3.7.3 under Monterey 12.4 on a M1 chip and did not have this behaviour under an Intel based chip on the same OS before.
Though I have just a regular folder inside a smart folder.

**Comment by barijaona** [comment]
I haven't tested yet, but I am surprised that it would work on Intel and not on M1.

Can you attempt creating another folder with the same characteristics and try again ?

**Comment by eric-nieuwland** [comment]
Created everythin afresh - same result.
Intel iMac w/ MacOS 12.5.

**Comment by LeeNFr** [comment]
> This issue hasn't been updated in a while so we're going to mark it as `stale`. `stale` issues will automatically be closed after 60 days of inactivity. If this issue is still affecting you, please update us on how it affects you, and we'll keep it open. We are sorry that we haven't been able to prioritize it yet. Thank you for your contributions.

**Comment by LeeNFr** [comment]
- - [ ] [__]()

**Comment by hphde** [comment]
Still the bug exists in 3.8.8

**Comment by eric-nieuwland** [comment]
Yup, still exists.
Also on M2 MacBook Air w/ MacOS 13.5.2.

**Comment by TAKeanice** [comment]
I had not seen this issue yet, thanks for notifying us about it. I no one of the other maintainers is faster I will look into the problem.

**Comment by barijaona** [comment]
Should be solved by #1710

**Comment by TAKeanice** [comment]
https://github.com/ViennaRSS/vienna-rss/releases/tag/v%2F3.9.1 should contain the fix that @barijaona mentioned. Therefore I will close this issue for now. @darth-hp and @eric-nieuwland can you confirm this is solved? If not, please leave a comment so we can reopen the ticket.

**Comment by eric-nieuwland** [comment]
Seems to work. Thanks.
