### ISSUE TITLE
Persistent OpenReader error message

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#1539]
From [cocoaforge](https://forums.cocoaforge.com/viewtopic.php?p=140985#p140985):

> On starting up Vienna this morning, I received the error message "OpenReader Authentication Failed". Eventually I figured out that I needed to supply new billing information to my OpenReader provider on their website. But meanwhile the error message kept popping up repeatedly and instantaneously, with no interval between appearances, covering anything else I tried to do, including opening Preferences, and preventing me from accessing the Vienna menubar to quit the app. So I had to force-quit.

Sounds pretty annoying so I'll put it on the list of OpenReader stuff to investigate.

**Comment by barijaona** [comment]
Closed by #1620 (commit 3a5352af43d0a38d526deff21283f1d2395719f3)
