### ISSUE TITLE
Empty article list for feeds

### ISSUE THREAD

**Issue by JustinCEO** [ViennaRSS/vienna-rss#1541]
**Describe the bug**
I'm having behavior that appears to be very similar to this previous bug
https://github.com/ViennaRSS/vienna-rss/issues/599
When I first load up Vienna, everything is fine, but after a bit (amount of time required is indeterminate), if I switch from Feed A to Feed B and then back to Feed A, the article list in Feed A will be empty. Then if I switch away from Feed A again and go back again, I'll see the articles in Feed A again.

**To Reproduce**
Run Vienna. Leave it open for a while. Select a feed and then switch to a different feed, then back to the first feed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6414980/147613013-c21258fd-06b1-4108-a4df-c72ac1027c1b.png)

**Please complete the following information:**
 - Vienna version 3.7.2
 - OS version: macOS 12.1

**Comment by ptrdtznr** [comment]
What I have figured out is, this happens when the application looses its focus. So if Vienna moves to the background and I put Vienna back up in front, I do have the same behavior... So it does not depend on time, its event based
