### ISSUE TITLE
Open News Summary in a Tab

### ISSUE THREAD

**Issue by sbondorf** [ViennaRSS/vienna-rss#1555]
News items come with a summary. There are already multiple options where to show the summary: in the article info "column" in the headlines list, in a "unified" way in the headlines list or in a separate part of the window according to some selected layout (either horizontal or vertical).

What is missing is the option to open the summary in a new tab. 
At the moment, tabs can only be used to open the original article webpage ("Open Article Page").

Can you allow opening the news summary in a separate tab? 
It can (and should) simply look like the horizontal or vertical layout's summary section of the window.

**Comment by barijaona** [comment]
Would you explain the advantage this would bring to your workflow ?

**Comment by sbondorf** [comment]
Sure, here is a description of my specific workflow. There might be others, too.

## Keeping TODO Lists in GitLab Issue Descriptions

The description is part of summary in the RSS feed. 
And despite this bug in GitLab (https://gitlab.com/gitlab-org/gitlab/-/issues/345797), Vienna receives/shows proper checkbox lists. See here:
<img width="1140" alt="Screen Shot 2022-05-04 at 08 19 39" src="https://user-images.githubusercontent.com/5295332/166631695-bd716d10-4377-4006-8b57-d75a06df1f88.png">
(source: https://gitlab.com/sbondorf/rsstestsvienna3/-/issues/1)

Un-/Checking a checkbox will refresh the article summary accordingly.
