### ISSUE TITLE
NSToolbar text-only mode is broken

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1577]
The text-only mode of the toolbar is broken and does not work correctly in macOS 12. When the user has chosen text-only mode for the toolbar then the toolbar items that do not have a menu are not validated. Whether they are enabled or disabled (i.e. greyed out or not) seems to be unpredictable.

I have confirmed that it still works in macOS 10.13 (my earliest test environment). It seems that neither NSToolbarItem’s `validate` method is sent for these items nor the corresponding `validateMenuItem` method is used (neither is `validateToolbarItem`). Based on the comments I wrote at the time, `validate` is supposed to be sent for text-only toolbar items too:

```swift
// The default implementation of this method does nothing. Overriding this
// will allow any responder object to validate the toolbar item. This method
// is also invoked in text-only mode.
override func validate() {
```

From [Apple’s old documentation](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Toolbars/Tasks/ValidatingTBItems.html#//apple_ref/doc/uid/20000753-BAJGFHDD):

> Validation for view items is not automatic because a view item can be of unknown complexity. To implement validation for a view item, you must subclass NSToolbarItem and override validate (because NSToolbarItem’s implementation of validate does nothing for view items). In your override method, do the validation specific to the behavior of the view item and then enable or disable whatever you want in the contents of the view accordingly. If the view is an NSControl you can call setEnabled:, which will in turn call setEnabled: on the control.
> 
> In the absence of a custom menu form representation, NSToolbar by default disables a view item’s overflow menu item.
>
> If a toolbar item has a custom menu form representation with no submenu, then the toolbar will validate the overflow menu item and the toolbar item’s text in Text Only Mode differently than it would with the default menu form representation: If the menu form representation menu item’s target implements validateMenuItem: (part of NSMenuValidation), the toolbar calls that method to validate both the overflow menu item and the toolbar item’s text in Text Only Mode.

**Comment by barijaona** [comment]
Related or not ? : when the toolbar is in text-only mode, after you hit the "Refresh" button, the toolbar switches to text+icon mode…

**Comment by barijaona** [comment]
It appears that the switch is provoked by this change of image : https://github.com/ViennaRSS/vienna-rss/blob/0b3bba857f49454d792497618191d4154445ee30/Vienna/Sources/Application/AppController.m#L1964

**Comment by barijaona** [comment]
For some reasons, this quick and dirty hack works : replace `item.image = …` with `((NSButton *)item.view).image = …`
