### ISSUE TITLE
Dropping Sierra support

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#1589]
Xcode 14 (as of beta 2) [does not build targets for macOS Sierra](https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes).

Depending on when Vienna 3.8 is released, the next minor version ought to have High Sierra as a minimum. Hardware-wise, no Macs should be affected by this, since [High Sierra supports all Macs that had support for Sierra](https://arstechnica.com/gadgets/2017/09/macos-10-13-high-sierra-the-ars-technica-review/#h1).

**Comment by josh64x2** [comment]
Just to follow on to this:

Since Ventura drops support for a lot of capable Intel macs, I think we should keep whatever Xcode 14.x version is still supported in Monterey as our development environment for at least a year.
