### ISSUE TITLE
Folder list width is not maintained when quitting and starting Vienna 3.8.0

### ISSUE THREAD

**Issue by neilt** [ViennaRSS/vienna-rss#1595]
**Describe the bug**
When staring Vienna 3.8.0 the folder list column width always goes to the default.

**To Reproduce**
1. Start Vienna
2. Adjust folder list column width, say double the size.
3. Stop Vienna
4. Start Vienna, see that column width is back to default. 

I deleted the Vienna preferences, tried again, and the problem persisted.

**Screenshots**

**Please complete the following information:**
 - Vienna Version 3.8.0 :47f3bd9f: (7816)
 - OS version: 12.4 (21F79)

**Additional information:**
The last version before 3.8.0 was ok.

**Comment by barijaona** [comment]
Closed in 3.8.1
