### ISSUE TITLE
Back button doesn’t work

### ISSUE THREAD

**Issue by b0gdanw** [ViennaRSS/vienna-rss#1600]
**Describe the bug**
The back button is not active in the Toolbar, re-adding it did not solve the problem.
Back/Forward in the View menu don’t work.
Problem doesn’t seem related to “Preview new browser”, it’s the same behaviour with it disabled or enabled.

**Screenshots**
![back](https://user-images.githubusercontent.com/26733455/185384340-9ad021f8-6e0e-4b45-a260-9b914c395b0b.jpg)

**Please complete the following information:**
 - Vienna version 3.8.1 :d62d4a53: (7830)
 - OS version: macOS 11.6.8 (20G730)

**Additional information:**
The problem was not present in Vienna 3.7.4, it started in Vienna 3.8.1

**Comment by barijaona** [comment]
Fixed in 3.8.2
