### ISSUE TITLE
Global search not search by subject

### ISSUE THREAD

**Issue by landy2005** [ViennaRSS/vienna-rss#1601]
When I try search articles in Global search field, nothing found (by subject).
Also with simple numeric field.

**To Reproduce**
Seems as Global search by article subject broken in 3.8.x
When i put text string from articles body - search work.
But when I use any string from subject - nothing found

**Screenshots**
Add screenshots to help explain your problem, if possible.

**Please complete the following information:**
 - Vienna version 3.8.1 :d62d4a53: (7830)
 - OS version: 12.5.1 (21G83) Apple Silicon M1

That was work in old versions (before 3.8).

**Comment by landy2005** [comment]
> I cannot reproduce this. Can you provide an example feed and search term?


https://user-images.githubusercontent.com/217520/185752068-31a2d8fb-e96f-43c2-8d8a-d52e64a66fc1.mp4

**Comment by landy2005** [comment]
In screencast feed with saved auth.
I did already Reindex.

**Comment by landy2005** [comment]
What I can do to draw attention to the problem?
Issue still actual, but I not know what I can do for you can reproduce.

**Comment by landy2005** [comment]
I just added any random feed: https://www.liga.net/tech/all/rss.xml
And trying to find any article from this feed (i.e. iPhone 14) and still not found anything.

**Comment by barijaona** [comment]
> I just added any random feed: https://www.liga.net/tech/all/rss.xml
> And trying to find any article from this feed (i.e. iPhone 14) and still not found anything.

I could not reproduce the problem either.
I suspect your database is somewhat corrupted.

**Comment by landy2005** [comment]
> > I just added any random feed: https://www.liga.net/tech/all/rss.xml
> > And trying to find any article from this feed (i.e. iPhone 14) and still not found anything.
> 
> I could not reproduce the problem either. I suspect your database is somewhat corrupted.

ok, and how I can restore/recreate database?
As I said before - I was do Reindex Database - it's not help.

**Comment by barijaona** [comment]
Hi,
This can be done in Terminal, using the `sqlite3` command.
I'll do a personal test before suggesting some commands.
