### ISSUE TITLE
Regression in keyboard navigation

### ISSUE THREAD

**Issue by therealprof** [ViennaRSS/vienna-rss#1609]
**Describe the bug**

Previously when I selected a feed, the first article was properly selected so when I hit enter it would automatically open in the browser. Now it "lightly" selects and previews the first article but when I hit enter it goes to the feed homepage instead unless remember to hit right arrow before. Also the focus stays on feed when skipping articles with the space bar. Since I tend to gang open articles to view in external browser, it is super annoying to figure out that instead of having 5 articles open and marked as read, I get 5 times the homepage (and still the articles are marked as read)...

**To Reproduce**

Open Vienna, select a feed, hit the space bar, hit enter, enjoy the RSS feed homepage instead of the selected article.

**Please complete the following information:**
 - Vienna 3.8.1 and 3.8.2
 - macOS 10.15.7

**Additional information:**

This problem wasn't there before upgrading to 3.8.

**Comment by barijaona** [comment]
Thanks for the report. Will be fixed in 3.8.3

**Comment by barijaona** [comment]
Closed in 3.8.3
