### ISSUE TITLE
"Open Link in new Tab" broken in new browser preview

### ISSUE THREAD

**Issue by therealprof** [ViennaRSS/vienna-rss#1612]
**Describe the bug**

When "Preview new browser" is enabled in settings, the "Open Link in New Tab" context menu item doesn't work anymore. It works fine if the "Preview new browser" feature is not selected.

**To Reproduce**

1. Make sure the "Preview new browser" is enabled and Vienna restarted.
2. Select an Article, got to the preview, activate the context menu on the heading and select "Open Link in new Tab"
3. Observe no new tab being opened

**Screenshots**

<img width="1340" alt="Screenshot 2022-09-06 at 13 36 11" src="https://user-images.githubusercontent.com/3321888/188626727-ac36c27f-af92-4d34-ab24-744f4a2e2381.png">

**Please complete the following information:**
 - Vienna version: 3.8.2
 - OS version: macOS 10.15.7

**Comment by barijaona** [comment]
Closed in 3.8.3
