### ISSUE TITLE
Misleading Syncing Preferences window

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1615]
**Describe the bug**
Users having a FreshRSS account report they are unable to connect to it using Vienna.
They get messages "A server with the specified hostname could not be found". https://github.com/FreshRSS/FreshRSS/issues/3417

When I tried to reproduce the problem with a test account, I noticed in my debug info something similar to (<i>redacted</i>):
````
Task <A7944B2B-497A-4087-9A08-C634E50C7800>.<1> finished with error [-1003] Error Domain=NSURLErrorDomain Code=-1003 "A server with the specified hostname could not be found" 
....
NSErrorFailingURLStringKey=https://https://freshrss.example.com/api/greader.php/accounts/ClientLogin?accountType=GOOGLE&service=reader
````
(note the __double__ sequence `https://https://` in the URL)

 It occurred to me that Vienna's syncing preferences dialog is misleading. The window suggests to input a complete URL, while the user should only provide a hostname and a path.
In the above example, I immediately got correct access once I replaced `https://freshrss.example.com/api/greader.php`with `freshrss.example.com/api/greader.php` in my settings.

**Screenshots**
In previous versions of Vienna, the preference window was more explicit about what was expected.
Here is a 3.5.3 screenshot : an `https://` string does show on the window, as an advice to the user to avoid inputting any scheme.
<img width="513" alt="Vienna 3 5 3" src="https://user-images.githubusercontent.com/442030/191233241-03200700-6fd1-4393-bd80-7529ecf91fe5.png" title="Vienna 3.5.3">

This changed once we switched to a storyboard based window (commit 5dfb7a1)
The current display is completely misleading:
<img width="628" alt="master" src="https://user-images.githubusercontent.com/442030/191235734-8c2628f0-5b38-484e-8767-794cc64e543b.png" title="Current Vienna (branch master)">

**Additional information:**
Change occurred with Version 3.6.

**Comment by barijaona** [comment]
@Eitot , do you see a more elegant (and localizable) solution than just replacing the `URL:` label with `URL: https://` ?

**Comment by Alkarex** [comment]
In any case, what about accepting both inputs with and without scheme? You can always add an explicit scheme such as `https://` if is not provided by the user. That is what Web browsers have been doing for years
