### ISSUE TITLE
Sidebar width not retained after quit in macOS Ventura

### ISSUE THREAD

**Issue by jazzace** [ViennaRSS/vienna-rss#1622]
**Describe the bug**
If you resize the left sidebar, then quit, the sidebar will return to its default width on relaunch.

**To Reproduce**
Change the width of the left sidebar. Quit Vienna. Open Vienna.

Expected Behaviour: Width of the left sidebar will be the same as when the app was quit.

Actual Behaviour: Width of the left sidebar returns to the (apparent) default width of the length of the longest feed name plus space for the unread article counter.

**Please complete the following information:**
 - Vienna version 3.8.3
 - macOS Ventura 13.0 RC 2 (22A380)

**Additional information:**
This could appear in earlier OSes, but has not been tested. This also may be related to a behaviour that I noticed after a recent Vienna update where Vienna would not remember which of my two displays it was last loaded on; it always loads on the primary display and I have to relocate it.

**Comment by barijaona** [comment]
Some similarity with issue #1595 : problem seen in Vertical layout and also in Unified layout.

In Horizontal layout, it is quite difficult to resize the folder list sidebar.

**Comment by jazzace** [comment]
Fixed by #1625, released in 3.8.4.
