### ISSUE TITLE
Unread Articles list not showing on launch

### ISSUE THREAD

**Issue by jazzace** [ViennaRSS/vienna-rss#1623]
**Describe the bug**
The list of Unread Articles will not show up when Vienna is launched if the Unread Articles folder was selected in the sidebar when Vienna in the previous session.

**To Reproduce**
1. In the left sidebar, select Unread Articles.
2. Ensure that there are unread articles in your feed.
3. Quit Vienna.
4. Open Vienna

**Expected Behaviour**
List of Unread Articles is shown in the Headlines column.

**Actual Behaviour**
List of Unread Articles is blank. If you select another item in the sidebar and then return to Unread Articles, the list will appear.

**Screenshots**
![Unread list not showing](https://user-images.githubusercontent.com/4193278/197809443-752814f4-da98-4d44-8d71-4579f4591ef8.png)

**Please complete the following information:**
 - Vienna version 3.8.3
 - OS version: macOS 13.0

[Issue updated to reflect the fact that you don't have to have read all the articles for the problem to occur.]

**Comment by josh64x2** [comment]
I was unable to reproduce on macOS 12.6.1, hopefully one of the other devs can try on macOS 13.

**Comment by jazzace** [comment]
I just tested on macOS 13.0.1 Beta 1 and the problem does not occur. So perhaps this was something on Apple's end.

**Comment by josh64x2** [comment]
I did install Ventura 13.0 and couldn't reproduce there either sorry 😞 . 
If you experience this issue again please re-open the issue and I'll try digging a bit deeper.

**Comment by jazzace** [comment]
Happened when I launched this morning.
<img width="1334" alt="Screenshot 2022-10-27 at 8 31 05 AM" src="https://user-images.githubusercontent.com/4193278/198316071-ae886ae3-a6fd-4245-a82f-eae566e683b3.png">

If there are logs or other details that would help, let me know. In the meantime, I will see if I can come up with steps that are more reproducible.

**Comment by jazzace** [comment]
My best bet (which is, admittedly, hard to reproduce) is that the original circumstance I found (prior to editing my initial post) is the primary problem and other, seemingly random occurrences are related to the underlying bug that causes the issue. Those repro steps were:
1. Read (or Mark as Read) all the articles in your feeds.
2. In the left sidebar, select Unread Articles.
3. Quit Vienna.
4. Wait until you know one of your feeds has a new article.
5. Open Vienna

That is, if there were no unread items in the list when you quit Vienna, the Unread Articles list does not update when the feeds are refreshed upon launch. Moving to any other item and returning to Unread Articles shows the list correctly.

**Comment by barijaona** [comment]
I have seen something similar while I was working on pull request #1625 and put breakpoints in initialization code.

**Comment by jazzace** [comment]
Yes.
