### ISSUE TITLE
BrowserTab is leaking memory

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#1667]
**Describe the bug**
When new browser is used, closed tabs continue to be present.
I found out that while testing #1666 : after closing some tabs, a bunch of 'about:blank' items remain visible in Safari's Developer menu.

**To Reproduce**
In Xcode, place a breakpoint into `BrowserTab`'s [deinit routine](https://github.com/ViennaRSS/vienna-rss/blob/fce963ef7613e5c7473bf3e5fcdb0ff4a6745d79/Vienna/Sources/Main%20window/BrowserTab.swift#L141).
Then, build and run Vienna, and open and close many tabs:
- You will notice that `deinit` never gets called.
- If you have enabled Safari's Developer menu, you can verify that the tabs that you have opened and closed remain into Developer menu with 'about:blank' as title.

**Please complete the following information:**
 - Vienna version : current master (but also present in stable branch
 - OS version: macOS 13.3.1

**Additional information:**
No similar problem with old browser.

**Comment by TAKeanice** [comment]
I had a similar issue but solved it at some point during development. It was due to a closure capturing self with KVO. See 38106a780f14d1eec10c3add3a17067b9b8e9f91 for reference

**Comment by barijaona** [comment]
Fixed in Vienna 3.8.6
