### ISSUE TITLE
Make Vienna more flexible in searching articles within certain feeds

### ISSUE THREAD

**Issue by tijmenvangulik** [ViennaRSS/vienna-rss#1676]
**Describe the bug**
I add the following rss feed which seems to be a valid rss feed but vienna can not find any articles

**To Reproduce**
Add the following feed:
https://www.deingenieur.nl/nieuws/rss/all

In the log you see:

Connecting to https://www.deingenieur.nl/nieuws/rss/all
124 KB received
And message: No articles in feed
When you open the feed in a browser you see that er many news items in de feed

**Screenshots**
Add screenshots to help explain your problem, if possible.

**Please complete the following information:**
 - Vienna version n 3.8.7 :15608906: (8038)
 - macOS 13.2.1

**Comment by tijmenvangulik** [comment]
Thank you for the quick reply.  I will take it up with the rss provider. Sorry to bother you with this wrong error report.

Tijmen

**Comment by barijaona** [comment]
I am all in favor of more flexibility.

But there are various popular specifications of RSS which are in fact unrelated, so we'll have to be careful not to break feeds conforming to a specific specification.

**Comment by barijaona** [comment]
Examples:
- in the example listed for [RSS 0.9](https://www.rssboard.org/rss-0-9-0),`<item>`s are outside `<channel>`
- in the example listed for [RSS 1.0](https://web.resource.org/rss/1.0/spec), `<item>`s are listed inside `<channel>` __and__ detailed outside `<channel>`

Good to know: work on RSS 1.0 and RSS 2.0 were done separately. The later is not the successor of the former.
