### ISSUE TITLE
messages.db file could not be located 

### ISSUE THREAD

**Issue by JohannesFeng** [ViennaRSS/vienna-rss#1683]
I had followed the instruction from the Vienna official site https://www.vienna-rss.com/faq.html#:~:text=By%20default%2C%20your%20Vienna%20database,another%20folder%20if%20you%20wish where it states: 

How do I move my Vienna database to another folder?
By default, your Vienna database is the messages.db file which is located at ~/Library/Application Support/Vienna. You can move this to another folder if you wish. The following steps show how:

I could not find the Vienna folder in the mentioned path, nor I could find the messages.db file using the search function in Mac OS. However, my Vienna contains a lot of subscriptions and they are still updating. I guess the database file must be very large and it cannot be missed. 

So what I could do in this situation to locate the database file? Thank you so much!

**Comment by barijaona** [comment]
If you do not find it at the location indicated [above](#issuecomment-1535007729), try the following command in Terminal:

`defaults read uk.co.opencommunity.vienna2`

It should reveal the current location if it has been changed.
