### ISSUE TITLE
Printing fails with new browser enabled

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#1694]
Vienna 3.8.7
MacOS 13.4

1.  With one or more articles selected, press ⌘P (print from the file menu)
2. The print dialog opens, the preview pane shows a blank preview of two (2) pages that  will be printed (either to PDF or on paper).
3. From the PDF dropdown widget at the bottom, select “Preview…” to verify the output. Preview opens showing a file with  2 blank pages.

Expected  -  print the article

With Old browser, it works correctly with the one minor issue in that the article being viewed scales down slightly when the print dialog is open – as if “print preview” in the Webkit developer tools is selected (elements tab).

**Comment by barijaona** [comment]
This is addressed for versions 3.9

Pull request #1635 has already been merged into master.

**Comment by barijaona** [comment]
A public beta of 3.9 is expected to be available this month.

**Comment by phiw13** [comment]
> This is addressed for versions 3.9

Oh. Thank you. I somehow did not see that when scanning  recentish commits.

Looking forward to a beta for 3.9!
