### ISSUE TITLE
Feature request: disable plugins

### ISSUE THREAD

**Issue by belkadan** [ViennaRSS/vienna-rss#170]
In Safari I always have [ClickToPlugin](http://hoyois.github.com/safariextensions/clicktoplugin/) enabled, and only load Flash when I really have to. However, some of my newsfeeds put Flash embeds in their content, and since I browse in Unified layout, Vienna ends up loading _all_ of them. This ended up pegging one of my cores at 100% today. I would love it if Vienna had an option to disable plugins, or make them load-on-demand like ClickToPlugin does.

**Comment by poweruser82** [comment]
It would be nice if there was an option in the preferences to disable the whole plugin architecture like it is possible in Safari (just a simple single toggle is enough, I don't feel the need of granular options Safari 7 has)
