### ISSUE TITLE
Extensions for external browser

### ISSUE THREAD

**Issue by aint** [ViennaRSS/vienna-rss#171]
Is there some way to install Safari (Chrome) extensions in Vienna external browser?

**Comment by Eitot** [comment]
Given that this is an old issue and considering that Safari extensions are deemed a legacy feature by Apple (replaced by [Safari App Extensions](https://developer.apple.com/documentation/safariservices/safari_app_extensions)) and that Chrome extensions only work in Chrome, I think that this proposal is unworkable.

That said, it is possible to [inject JavaScript and even content-blocking rules](https://developer.apple.com/documentation/webkit/wkusercontentcontroller). This could be achieved by a Vienna plugin, but none of the currently supported ones is capable of this. I am closing this issue and add a suggestion to the browser project.
