### ISSUE TITLE
Can't reorder feeds

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#1718]
**Describe the bug**
I'm unable to reorder my folders and feeds in the feed list.   It worked before in the same version with no changes I'm aware of to my configuration.

**To Reproduce**
I'm not sure what steps led to it.  I just know I can't reorder feeds within folders, or reorder the folders.

**Please complete the following information:**
 - Vienna version 3.9.0 beta 1
 - OS version: MacOS 14.1.1

**Additional information:**

I'm using OpenReader with Inoreader.

**Comment by tonycpsu** [comment]
Fixed by nuking Vienna directory and cache, but would like to know what could have caused this and how I can non-destructively fix it.

**Comment by barijaona** [comment]
You probable had changed the selection in the menu 'View'->'Order by'
If you select 'Order By Name', you cannot reorder manually.

I reckon this is not very user friendly. If you inadvertently select 'By Name', you loose any fine tuned arrangement you previously have.

**Comment by tonycpsu** [comment]
Oh!  That's probably it.  Thank you for pointing me in the right direction on this.
