### ISSUE TITLE
Problem with recent update

### ISSUE THREAD

**Issue by andredevleeschouwer** [ViennaRSS/vienna-rss#1726]
Today I have Vienna 3.8.8.  Vienna asks for an update to 3.9.0, warning that Mac OS 10.13 of later is necessary.  On my computer is 10.13.6.  However, after downloading, unpacking and trying to install I get the message that installing is not possible, because there an error occurred.  I did this already 4 times, always with the same result.  See 2 printscreens.
Regards, André De Vleeschouwer.

**Comment by TAKeanice** [comment]
Sorry to hear you are having trouble. Seems that the screenshots are missing in your post, though. Can you add them and maybe look for any log file from the installation process?

**Comment by andredevleeschouwer** [comment]
Sorry for the inconvenience.  Here the two screenshots.

Kind regards.
André De Vleeschouwer.



ir. André De Vleeschouwer - AKMOS
Voorzitter Koninklijke Heemkring Hoghescote vzw
Secretaris-Bestuurder EKBRA vzw
Lid van IE-net Ingenieursvereniging
BTW BE 0821.893.668
Tel: +3236057989  GSM: +32473442675
***@***.***
https://www.akmos.be
https://www.heemkring-hoghescote.be


Op 23 jan. 2024, om 09:47 heeft Tassilo Karge ***@***.***> het volgende geschreven:


Sorry to hear you are having trouble. Seems that the screenshots are missing in your post, though. Can you add them and maybe look for any log file from the installation process?

**Comment by gpb01** [comment]
Same here, also if I download the .tgz file, extraction return "file incomplete or corrupted" ... :(

Guglielmo

**Comment by barijaona** [comment]
Obviously, pictures attached as e-mail attachments are not displayed by GitHub. 

@andredevleeschouwer, please visit the issue webpage <https://github.com/ViennaRSS/vienna-rss/issues/1726> to post your screenshots.

**Comment by andredevleeschouwer** [comment]
OK, my complaint was that I tried 4 times to update to Vienna version 3.9.0, my current version is 3.8.8.

The pictures were the popups.  One said that it is about version 3.9.0, the other said that after downloaden and unpacking, "Bijwerken" or update did not work properly due to an error during this process.

I just tried it again, with exactly the same result.

My OS is 10.13.6, hence obviously OK for the new Vienna version.

Kind regards.


ir. André De Vleeschouwer - AKMOS
Voorzitter Koninklijke Heemkring Hoghescote vzw
Secretaris-Bestuurder EKBRA vzw
Lid van IE-net Ingenieursvereniging
BTW BE 0821.893.668
Tel: +3236057989  GSM: +32473442675
***@***.***
https://www.akmos.be
https://www.heemkring-hoghescote.be


Op 23 jan. 2024, om 17:25 heeft Barijaona Ramaholimihaso ***@***.***> het volgende geschreven:


Obviously, pictures attached as e-mail attachments are not displayed by GitHub.

@andredevleeschouwer <https://github.com/andredevleeschouwer>, please visit the issue webpage #1726 <https://github.com/ViennaRSS/vienna-rss/issues/1726> to post your screenshots.

**Comment by andredevleeschouwer** [comment]
OK, thank you.  I took the newest version from the Vienna website, and tried to install.  The message is similar:

Vienna3.9.0.tar kan niet tot 'Programma's' worden uitgepakt.  (Fout 1 - Bewerking niet toegestaan.)

Translated: Vienna3.9.0.tar cannot being unpacked to 'Programma's'.  (Error 1 - Operation not allowed.

I had the same message when I started the upgrade to the Desktop.

What is the problem ?  Am I wrong in any way ?

Regards.
André De Vleeschouwer.


ir. André De Vleeschouwer - AKMOS
Voorzitter Koninklijke Heemkring Hoghescote vzw
Secretaris-Bestuurder EKBRA vzw
Lid van IE-net Ingenieursvereniging
BTW BE 0821.893.668
Tel: +3236057989  GSM: +32473442675
***@***.***
https://www.akmos.be
https://www.heemkring-hoghescote.be


Op 25 jan. 2024, om 23:36 heeft Eitot ***@***.***> het volgende geschreven:


This seems to be an issue with the Sparkle updater. Without the exact wording of the error, this cannot be investigated further.

As a workaround, you can also just download the latest version of Vienna from GitHub and install it.

**Comment by gpb01** [comment]
I have had the same problem ... I don't know exactly what's wrong with this .tgz file, but under MacOS 10.14.6 (Mojave), both the system program and an application called "Archiver" report the same problem. I was able to solve it by using a third program called "BetterZip", which was able to extract the application from the .tgz without any errors.

Don't ask me why or what the differences are ... I don't know, but it was **the only way** I could update the program.

Suggestion, wouldn't it be possible to use a more standard .zip or .dmg?

Guglielmo

**Comment by andredevleeschouwer** [comment]
Dear Guglielmo,

Your advice worked with BetterZip.   But nevertheless it is strange that the normal built-in unzipper from Mac doesn't.  Can it still be reported as a bug ?  Everything should work properly.

Kind regards.
André De Vleeschouwer.


ir. André De Vleeschouwer - AKMOS
Voorzitter Koninklijke Heemkring Hoghescote vzw
Secretaris-Bestuurder EKBRA vzw
Lid van IE-net Ingenieursvereniging
BTW BE 0821.893.668
Tel: +3236057989  GSM: +32473442675
***@***.***
https://www.akmos.be
https://www.heemkring-hoghescote.be


Op 26 jan. 2024, om 15:25 heeft Guglielmo Braguglia ***@***.***> het volgende geschreven:


I have had the same problem ... I don't know exactly what's wrong with this .tgz file, but under MacOS 10.14.6 (Mojave), both the system program and an application called "Archiver" report the same problem. I was able to solve it by using a third program called "BetterZip", which was able to extract the application from the .tgz without any errors.

Don't ask me why or what the differences are ... I don't know, but it was the only way I could update the program.

Suggestion, wouldn't it be possible to use a more standard .zip or .dmg?

Guglielmo

**Comment by gpb01** [comment]
Tried on macOS 10.14.6 with the following command:

tar --extract --gzip --verbose --file /Users/gpb01/Desktop/Vienna3.9.0.tgz 2> /Users/gpb01/Desktop/extract.log

... attached is the error log:

[extract.log](https://github.com/ViennaRSS/vienna-rss/files/14151625/extract.log)

Guglielmo

**Comment by gpb01** [comment]
> Can you check whether the [3.9.0 beta version](https://github.com/ViennaRSS/vienna-rss/releases/tag/v%2F3.9.0_beta1) extracts without errors using the system Archive Utility?

Better but still 6 errors:

...
x Vienna.app/Contents/Frameworks/libswiftFoundation.dylib
x Vienna.app/Contents/Frameworks/Sparkle.framework/._Resources
tar: Ignoring malformed pax extended attribute
x Vienna.app/Contents/Frameworks/Sparkle.framework/Resources
x Vienna.app/Contents/Frameworks/Sparkle.framework/Versions/
x Vienna.app/Contents/Frameworks/Sparkle.framework/._Autoupdate
tar: Ignoring malformed pax extended attribute
x Vienna.app/Contents/Frameworks/Sparkle.framework/Autoupdate
x Vienna.app/Contents/Frameworks/Sparkle.framework/._Updater.app
tar: Ignoring malformed pax extended attribute
x Vienna.app/Contents/Frameworks/Sparkle.framework/Updater.app
x Vienna.app/Contents/Frameworks/Sparkle.framework/._XPCServices
tar: Ignoring malformed pax extended attribute
x Vienna.app/Contents/Frameworks/Sparkle.framework/XPCServices
x Vienna.app/Contents/Frameworks/Sparkle.framework/._Sparkle
tar: Ignoring malformed pax extended attribute
x Vienna.app/Contents/Frameworks/Sparkle.framework/Sparkle
x Vienna.app/Contents/Frameworks/Sparkle.framework/Versions/._Current
tar: Ignoring malformed pax extended attribute
x Vienna.app/Contents/Frameworks/Sparkle.framework/Versions/Current
x Vienna.app/Contents/Frameworks/Sparkle.framework/Versions/B/
...

Hope this help :)

Guglielmo

**Comment by scrutinizer11** [comment]
I concur. Upon downloading the update package and hitting "Install" the error "error occurred while trying to extract the archive". macOS 10.14
