### ISSUE TITLE
issue with Delete Article keyboard shortcut in Vienna 3.9.0

### ISSUE THREAD

**Issue by cseppan** [ViennaRSS/vienna-rss#1735]
**Describe the bug**
When focus is on the article content panel, pressing the Delete key doesn't delete the article. Instead, the contents of the article panel are replaced with whatever was previously displayed, and no changes are made to the article list. If the menu option Delete Article is chosen, the article is deleted as expected. If focus is in the article list panel, either pressing the Delete key or selecting the menu option Delete Article works as expected. I'm seeing this issue regardless of whether the feed uses Load Full HTML Articles or not.

**To Reproduce**
With an article selected, click on the article contents so that the article panel has focus. Press the Delete key.

**Please complete the following information:**
 - Vienna version: 3.9.0 :7ad9df044: (8175)
 - OS version: macOS Sonoma 14.2.1 (23C71)

**Additional information:**
Vienna 3.8.8 does not have this issue.

**Comment by barijaona** [comment]
Closed by 3.9.1
