### ISSUE TITLE
Drag-to-rearrange Not Working

### ISSUE THREAD

**Issue by scrutinizer11** [ViennaRSS/vienna-rss#1779]
**Describe the bug**

Dragging items in the source list to rearrange the order of the display is rendered non-functional.

**To Reproduce**
Drag any folder or feed in the sidebar in a usual macOS way.

**Please complete the following information:**
 - Vienna version: 3.9.1
 - OS version: macOS 10.14

**Additional information:**
In which version of Vienna does the problem not occur, if applicable? 

3.5.x–3.8.x

**Comment by scrutinizer11** [comment]
I meant items won't allow me to drag up or down to rearrange them in the sidebar. I hover over an item and try to move it by dragging it, but nothing happens. This used to be a feature, which is no more.

**Comment by barijaona** [comment]
What is currently displayed for "View -> Sort By" ?

**Comment by scrutinizer11** [comment]
Date->Descending.

**Comment by scrutinizer11** [comment]
Order By––>Manual

It's been like that for ever since I started using Vienna.

**Comment by barijaona** [comment]
Do you have Group folders 📁 ?
Creating one and attempting to move one / some feed(s) into it might unlock the problem.

**Comment by barijaona** [comment]
I am closing this ; you are welcome to open a new issue if a similar problem occurs with Vienna 3.9.2 or later.
