### ISSUE TITLE
Folder sort order destruction problem has gone from worse to unacceptable

### ISSUE THREAD

**Issue by PacoH** [ViennaRSS/vienna-rss#1785]
Vienna Version 3.9.0
macOS Ventura 13.6.5

Today I found all my folders sorted in alphabetical order again, despite the fact that I set 'Order By' to 'Manual' the last time I opened Vienna. I again reset it back to 'Manual' and moved one folder up to the top position. Much to my horror, every single article, the accumulation of years and years of relying on this app, was marked 'read'. This has to be a user's worst nightmare. I see that, supposedly, v/3.9.1 adds "Prevent Vienna from unexpectedly switching to alphabetical sorting of folders and feeds". This does me no good if I can't restore the Read status of every article first. How exactly do I do that?

I see no setting that can automatically 'Export Subscriptions'. This is a needed functionality to recover from the current disaster.

Recent articles are usually bolded. Here you can see that they are unbolded:

![SCR-20240803-iida](https://github.com/user-attachments/assets/acd2e1c6-e8c0-43d9-89c1-097e0596e668)

**Comment by barijaona** [comment]
Really sorry for this.
I am actively working on this issue, but I am pretty sure that the fact that articles have been marked read has no direct relation to the loss of your folder sort.

My only guess is that you might have inadvertently used the "Mark All Subscriptions as Read" command.

**Comment by barijaona** [comment]
Please try version 3.9.2
