### ISSUE TITLE
Newest release still intercepts characters typed into input boxes as Vienna commands

### ISSUE THREAD

**Issue by macsrwe** [ViennaRSS/vienna-rss#1793]
Reference bug #1722, comment https://github.com/ViennaRSS/vienna-rss/issues/1722#issuecomment-1903652297

Vienna still intercepts characters being typed into input boxes (e.g., blog comments) as Vienna commands, with destructive results. For example, typing a comment containing a comma immediately abandons the current article and opens an unrelated one. 

This portion of bug #1722 remains unfixed.

 - Vienna version Version 3.9.2 :df48d9ec: (8268)
 - OS version: Sonoma 14.6.1 (23G93)

**Comment by barijaona** [comment]
The main tab ('Articles' tab) is not intended to be a fully functional web browser ; its main goals are to navigate between feed's articles and allow quick reading of articles.
Therefore, the "Use Web Page for Articles" option is only a convenience ; you shouldn't expect webpages appearing into it to behave as a normal webpage as priority is given to Vienna's navigation shortcuts over user interaction.
If you want to interact with the webpage, double-click on the article to open it in a new tab (or in your main web browser, according to what is set in your preferences).

**Comment by macsrwe** [comment]
I'm sorry to hear that. Up until version 3.8.8, Vienna did all this "properly," so I was hoping someone would be capable of returning it to its classic behavior. If that is no longer an option, I will simply continue using 3.8.8 for my purposes. Thanks for responding.

**Comment by barijaona** [comment]
Can you provide a link to a feed where this behavior difference is visible ?

**Comment by macsrwe** [comment]
https://waronguns.com/feed/

**Comment by barijaona** [comment]
The challenge: modifying this without reopening issue #1735

**Comment by macsrwe** [comment]
Thank you for your hard work. The newest version does everything I do right once more!
