### ISSUE TITLE
Migrate vienna subscriptions from a machine that no longer exists?

### ISSUE THREAD

**Issue by ipflowss** [ViennaRSS/vienna-rss#1796]
Migrate a vienna subscriptions list from a backup of a macbook pro that no longer exists to another MBP?

**Comment by barijaona** [comment]
What you need is located in the Vienna folder inside your Library's Application Support folder :

`\Users\USER_NAME\Library\Application\ Support\Vienna`
or
`~/Library/Application\ Support/Vienna`

Restore either the entire `Vienna` folder or just the `messages.db` file inside it.
