### ISSUE TITLE
Add Unit Testing

### ISSUE THREAD

**Issue by Echelon9** [ViennaRSS/vienna-rss#227]
_A reminder to myself to review adding a unit testing framework to ViennaRSS, to benefit developers_

See further:
http://stackoverflow.com/questions/33207/what-is-the-best-way-to-unit-test-objective-c-code
http://nshipster.com/unit-testing/
https://github.com/afnetworking/afnetworking#unit-tests

**Comment by tothgy** [comment]
Hi guys,

I’ve been a Vienna user for a while and wondered it’d be great to add something to the project.

Adding unit tests to get a better understanding first.

I converted the Test target to _logic test_, to speed up the test runs and get a better view of code coverage. Also moved the performance tests to different target.

**Comment by tothgy** [comment]
#651

Share your thoughts please

**Comment by josh64x2** [comment]
Also linked to #693
