### ISSUE TITLE
Individual sorting for folders

### ISSUE THREAD

**Issue by acrylian** [ViennaRSS/vienna-rss#231]
I use folders a lot to group feeds. I think it might be useful to be able to set an individual sort order for each folder that sticks to it instead always being globally for all. 

For example on some folders with fewer feeds the date order is more useful but on some others with more feeds by feed is better suited to get an overview what is new per each feed.

Great would of course be if you could set order by feed source and within it by date.

**Comment by sLoPPydrive** [comment]
I second this feature request. Currently I can define sorting only globally. I have feeds that I read in chronological order while for others the timestamp isn't relevant and I'd like to read them sorted alphabetically.

I would highly appreciate individual sorting by folder or even feed.
