### ISSUE TITLE
HTTPS feeds does not displaed with self-signed certificate.

### ISSUE THREAD

**Issue by stupalov** [ViennaRSS/vienna-rss#246]
Vienna (Version 3.0.0 Beta 20 :0fb193d:)
does not display feeds with self-signed certificate.
I have some inter-corporate feeds with https:// and private self-signed certificate,
Vieena does not display them.
See screenshot: 
![cqyb](https://f.cloud.github.com/assets/217520/2119446/7c42edcc-916a-11e3-9c47-d210a8380d49.png)

If run Vieena from console, displayed this errors:

```
mks-mac:MacOS mike$ ./Vienna
2014-02-09 13:03:53.829 Vienna[6407:b70b] CFNetwork SSLHandshake failed (-9807)
2014-02-09 13:03:53.905 Vienna[6407:b70b] CFNetwork SSLHandshake failed (-9807)
```

**Comment by landy2005** [comment]
Ohh, yes.. after one year I install vienna on new device.. and again forgot why all my feeds (intra company) not displayed.
Only by this ticket I remembered :)

And nothing changed since that time.
> « Window -> Activity Window »

```
Connecting to https://mycompany/feed.php?************************
Error retrieving RSS feed: A connection failure occurred: SSL problem (Possible causes may include a bad/expired/self-signed certificate, clock set to wrong date)
```
Please add option or popup or any other user interaction, for add exclude for these certificates.

**Comment by dellgreen** [comment]
Same here I would like the option per feed to allows self-signed certs for my internal company feeds rather than doing the work around to install the certificate manually (which is not the end of the world), like one does in a web browser.
