### ISSUE TITLE
Embedded images not displayed

### ISSUE THREAD

**Issue by mankoff** [ViennaRSS/vienna-rss#265]
I'm really not sure if this is a Vienna bug or IPython/RSS bug, but thought I would start here.

I've subscribed to a blog with embedded images. See all images (but bottom few w/ people) in this post: http://ocefpaf.github.io/python4oceanographers/blog/2014/03/31/itaguare/

Image URLs look like, for example:

```
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABI...<etc.>
```

These are not displayed by Vienna. Instead I see the small blue `?` symbol.

**Comment by mankoff** [comment]
This bug has re-appeared. The previous embedded image began with the following text: `data:image/jpeg;base64,`. That same blog (see [link here](https://ocefpaf.github.io/python4oceanographers/blog/2015/12/14/geopandas_folium/)) is now serving images that begin with: `data:text/html;base64,` and I'm getting the following error from Vienna

<img width="778" alt="screen shot 2015-12-15 at 12 00 46" src="https://cloud.githubusercontent.com/assets/145117/11817591/917ef4a2-a323-11e5-80d9-96b254b7dc03.png">

**Comment by barijaona** [comment]
Fixed by #628
