### ISSUE TITLE
Menu localization issue for "Hide Toolbar/Show Toolbar" 

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#288]
For some localizations, the menu item text for "Hide Toolbar" does not toggle to "Show Toolbar" when the toolbar is hidden.

The problem can be encountered for instance in German, French and Italian localizations.
It does not appear in English and Spanish localizations.

Currently, I am at loss…

**Comment by Eitot** [comment]
Curious, `validateMenuItem(_:)` in MainWindowController is never called for this selector. Let me try something.

**Comment by Eitot** [comment]
A quick fix is to implement `validateMenuItem(_:)` in a subclass of NSWindow. It seems that the controller never receives this selector. I have yet to figure out how to best use the responder chain, so I will keep this issue open for now.

**Comment by Eitot** [comment]
I think I would indeed prefer to re-introduce an NSWindow subclass and simply override validateMenuItem(_:) there for just this selector. After all, `toggleToolbarShown(_:)` is an NSWindow method, so it makes more sense to keep the selector validation there too. However, I will keep the NSLocalizedString approach.
