### ISSUE TITLE
Add option to filter similar articles

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#313]
Issue raised at http://forums.cocoaforge.com/viewtopic.php?t=26587

**Comment by DavidMunch** [comment]
As a user who have this 'issue', I can probably be of help to test out such a feature if it is ever developed, so feel free to notify me in that case, if I fail to see the feature being introduced. :) 

My usecase: I subscribe to a lot of feeds from scientific journals, but also to websites which aggregate scitentific articles based on pre-specified topics. So I end up with a lot of duplicates, and in many cases situations where the only duplicate string is the titel of the entries.
