### ISSUE TITLE
Add "Mark All Articles as Read" Button in Toolbar

### ISSUE THREAD

**Issue by veda1** [ViennaRSS/vienna-rss#320]
Am I missing something? Would very much like to have a "Mark All Articles as Read" button in toolbar. Thanks

**Comment by chewitt** [comment]
It would be nice to see this added .. I have ingrained muscle memory from other readers that keeps me reaching for a toolbar button that doesn't exist :)

**Comment by benhalverson** [comment]
:+1:

**Comment by wmangano** [comment]
:+1:

**Comment by Eitot** [comment]
I will add one, once I have moved the toolbar to Interface Builder. I am currently working on it, but it takes more time that I anticipated due to coupling issues.
