### ISSUE TITLE
Transition project from ASIHTTPRequest to AFNetworking (or NSURLSession)

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#344]
Suggested path as follows:
- [x] Use cocoapods for current dependencies (ASIHTTPRequest, JSONKit, FMDatabase)
- [ ] Introduce AFNetworking cocoapod
- [ ] Replace ASIHTTPRequest code with AFNetworking code
- [ ] Remove ASIHTTPRequest from project dependencies

**Comment by josh64x2** [comment]
Cocoapods implements as per PR #427

**Comment by josh64x2** [comment]
I have actually started working on the next steps for this.

**Comment by Eitot** [comment]
Are you still planning to use AFNetworking or are you going the native route instead?

**Comment by josh64x2** [comment]
Going to try the native route but we shall see. Actually the most difficult part is the app logic flow which assumes synchronous network calls. 

A lot of refactoring needs to be done to introduce callbacks into things like the new subscription window and the google reader sync.

**Comment by josh64x2** [comment]
So I have had a look at the networking code and the main classes affected are `RefreshManager` and `GoogleReader`.

A lot of the existing networking code is synchronous which can be a bit annoying to convert to asynchronous but thats OK as it needs doing.
It would be nice to use `NSURLSesssion` for everything (combined with `NSOperationQueue` for `RefreshManager`) however AFNetworking is starting to look appealing. It's a real shame that [AFNetworking-ASIHTTPRequest](https://github.com/AFNetworking/AFNetworking-ASIHTTPRequest/commit/fb055a15b57205929a5de480759eec7fb9cca1a4) never got finished.

AFNetworking has an [extension for handling OAuth2](https://github.com/AFNetworking/AFOAuth2Manager) nicely which will be helpful as many sharing services are moving to only support OAuth2 (an existing one that we use is [Inoreader](https://www.inoreader.com/developers/oauth). It would be easier to add new services once we have OAuth2 support in Vienna.

AFNetworking also has JSON and XML helpers.

`GoogleReader` will require the most refactoring - so do we keep it in Objective-C with AFNetworking, or do we rewrite in Swift and use [Alamofire](https://github.com/Alamofire/Alamofire)?

If we use Alamofire, then we would have to rewrite `RefreshManager` in Swift as well to take advantage of Alamofire properly.

I am aware Alamofire and AFNetworking are related, but Alamofire has much nicer documentation and that alone has nearly convinced me that rewriting in Swift and using Alamofire is the best approach.

@barijaona @Eitot thoughts?

**Comment by Eitot** [comment]
Alamofire is 10.10+, sadly. Though it looks that the dependency is on QualityOfService and ProcessInfo.processInfo.operatingSystemVersion, which should be trivial to work around.

I have no experience with either framework and I am unlikely going to contribute any networking code. Any of these three seem to be decent. Whichever framework works best for you, I’d say.

**Comment by josh64x2** [comment]
Ohhh damn I missed the 10.10+ requirement but it looks like that's only for version 4.x and 3.5.1 is fine for 10.9+ https://github.com/Alamofire/Alamofire/tree/3.5.1

I still value your input as you have good development practices :)

**Comment by Eitot** [comment]
3.x is Swift 2 though. Can we bundle both Swift 2 and Swift 3?

**Comment by josh64x2** [comment]
I can't believe I missed that haha. That makes it an easy choice though, AFNetworking it is :)

Where possible I will use straight `NSURLSession` and friends, so if we decide we don't want AFNetworking it will be easier to drop it :)

**Comment by josh64x2** [comment]
Interesting median adoption stats on that issue for Mac OS versions

**Comment by josh64x2** [comment]
Update: I hate cocoapods.

**Comment by Eitot** [comment]
What problem do you have?

**Comment by josh64x2** [comment]
I just hate how the project file always needs changing, I also had to manually add the framework and library directory to the Vienna project file because cocoapods didn't add it automatically.

It's almost easier to fork ASIHTTPRequest and make it a framework for Carthage in the interim.

**Comment by josh64x2** [comment]
Anyway I've nearly finished the first step which is converting RefreshManager to use `NSOperationQueue` instead of `ASINetworkQueue` and completionHandlers + KVO instead of delegates.

**Comment by Eitot** [comment]
If you need a working directory with Carthage: https://github.com/Eitot/vienna-rss/commits/carthage.

**Comment by josh64x2** [comment]
OK thanks, once I kill off ASIHTTP we can use this!

**Comment by Eitot** [comment]
Just needs `carthage bootstrap --platform osx`. I haven’t added the frameworks to the unit tests yet though.

**Comment by barijaona** [comment]
As @josh64x2 wrote, this change also requires refactoring our code to use asynchronous calls instead of synchronous ones.

I did some progress on that during last week-end (still using the old ASIHTTPRequest) and I hope to submit it for review soon.

**Comment by josh64x2** [comment]
@barijaona can you please publish your branch?

**Comment by barijaona** [comment]
I will publish it once I am at home, probably this evening (this night for you)

**Comment by josh64x2** [comment]
Ok thanks, there will obviously be duplication between our two branches so I just want to minimise causing merge conflicts down the road :)

**Comment by josh64x2** [comment]
@barijaona I didn't get anything done tonight so I just commited some things into a wip branch here: https://github.com/josh64x2/vienna-rss/tree/wip-networking-refactor

**Comment by barijaona** [comment]
I am not yet able to comment on your WIP branch, but our respective works will not conflict as I concentrated my own reflexions on GoogleReader.

Can you have a look at my [OpenReaderAsyncAuth branch](https://github.com/barijaona/vienna-rss/tree/OpenReaderAsyncAuth) ?

**Comment by josh64x2** [comment]
Oh yes that's good. Maybe abstract the authentication a little bit so we can handle OAUTH2?
I'd try to refactor `
-(void)authenticateForRequest:(ASIHTTPRequest *)clientRequest` as it is quite long.

Also now might be a good time to rename it to OpenReader? Or are you waiting to convert to async first and then submit a different PR for rename/refactor etc.

**Comment by josh64x2** [comment]
Please let me know when it is ready to test because I have a Vienna config backed up that creates errors in authentication which previously weren't handled. 😄

**Comment by josh64x2** [comment]
update: Currently stuck on `NSOperationQueue`.

From the [AFNetworking Migration Guide](https://github.com/AFNetworking/AFNetworking/wiki/AFNetworking-3.0-Migration-Guide#afnetworking-3x-1):

>Note that NSURLSession is not built upon NSOperation. If you have an app that heavily relies on the NSOperation aspects of AFURLConnectionOperation, there may be additional rework needed for your application to wrap AFHTTPSessionManager with an NSOperation based approach.

As mentioned, it is possible to use `NSURLSession` and its AFNetworking cousins with an `NSOperation` based approach, I'd like to consider some other options.

**Comment by josh64x2** [comment]
Update: currently trying an implementation using `NSURLSession` and `NSOperation` based on the approach I found here: http://williamboles.me/networking-with-nsoperation-as-your-wingman/

**Comment by barijaona** [comment]
@Eitot, could you explain your goal with [ViennaRSS/ASIHTTPRequest](https://github.com/ViennaRSS/ASIHTTPRequest) ?

**Comment by Eitot** [comment]
It is primarily for https://github.com/Eitot/vienna-rss/tree/project-outline. The fork is also an updated version of ASIHTTPRequest, so that it can be built with Xcode 9. I stripped all the non-framework code from it to keep it maintainable.

**Comment by barijaona** [comment]
It would be nicer if you keep it in your own repos, until you need to do a pull request… It's a bit strange seeing new work on ASIHTTPRequest, while the ultimate goal is to get rid of it.

**Comment by Eitot** [comment]
I am planning to submit the PR very soon, after a couple more tests.

This is all without prejudice to a transition.

**Comment by Eitot** [comment]
I am currently looking into creating a bridge to URLSession (without making substantial changes to RefreshManager for now) and dropping ASIHTTPRequest. If I manage to do this, then we might not even need the branch at all.

**Comment by barijaona** [comment]
I have also started some work on this, by replacing all synchronous calls with asynchronous ones. My [issue-344 branch](https://github.com/barijaona/vienna-rss/tree/issue-344) might interest you.
