### ISSUE TITLE
Add support for ownCloud News / Tiny RSS / Newsblur

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#345]
Originally requested [by Northdude from the forums](http://www.cocoaforge.com/viewtopic.php?f=18&t=26635&sid=094ba2f2875a499d915c42a6dd454e0b).

Many people are already using ownCloud, but there are just mobile applications available to sync with the integrated News App. Some of this mobile applications are Open Source, maybe it would not be that hard to modify the existing code so that Vienna could support it. [They are listed here, subitem news](https://github.com/owncloud/core/wiki/Apps).

[ownCloud News API](https://github.com/owncloud/news/wiki/API-1.2)

**Comment by lenucksi** [comment]
:+1: I would also appreciate Newsblur support very much.

**Comment by barijaona** [comment]
An interesting alternative for the apps listed here is [FreshRSS](
https://github.com/FreshRSS/FreshRS)S, which is open source, lightweight, uses the OpenReader consensus and [is being fixed to be fully compatible with Vienna](https://github.com/FreshRSS/FreshRSS/issues/2091).
.

**Comment by rodneyrod** [comment]
It's been brought up that the OpenReader API is incompatible with how Nextcloud authenticates, so unless changes are made to Vienna to support how Nextcloud does their login, or if that was worked into the OpenReader spec, this doesn't look like it will be supported.

Link to discussion:
https://github.com/nextcloud/news/issues/618#issuecomment-574452287
