### ISSUE TITLE
Add option "update to stable versions only"

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#352]
Originally reported [on sourceforge](https://sourceforge.net/p/vienna-rss/feature-requests/50/)

I propose we make 3.0 final check only for stable updates with sparkle (with no option to change in the UI), and then add a UI option to switch between stable/testing on the new development branch (after 3.0 is released)

**Comment by barijaona** [comment]
Fixed with commit bbbb086b626d6d94b9254dbe5b362926e0aa203c
