### ISSUE TITLE
Mark/unmark hotkeys should be simpler

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#365]
[This page](http://www.vienna-rss.org/?page_id=96#Is_there_a_shortcut_key_for_going_to_the_next_article_marking_read_etc_) suggests that the key equivalent for flagging is F, but Vienna 3 seems to use Cmd-Shift-M, with "F" activating the filter bar.  Coming from NetNewsWire, I feel "F" makes much more sense for quick access to flagging.

**Comment by tonycpsu** [comment]
Still want

**Comment by barijaona** [comment]
You can just use 'm or 'M'…
The menu item 'Help'->'Keyboard Shortcuts' is probably the most undervalued asset of Vienna! 😆

**Comment by tonycpsu** [comment]
Not sure that was the case six years when I originally submitted this issue, but thanks for the tip! :)
