### ISSUE TITLE
Use standard shortcut key for full screen support on OS X 10.7+

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#388]

**Comment by barijaona** [comment]
We should probably implement the "Enter full screen" menu command.
http://www.gilsmethod.com/how-to-go-full-screen-in-mac-os-x-lion
https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/FullScreenApp/FullScreenApp.html

**Comment by josh64x2** [comment]
Closed by PR #779
