### ISSUE TITLE
Mac OS X UI bug while scrolling article

### ISSUE THREAD

**Issue by e5faf2** [ViennaRSS/vienna-rss#399]
When Im scrolling long rss article, i have bad effect with filter UI control copying on scroll. 
![Screenshot](https://api.monosnap.com/image/download?id=0uVTHajJEQ9FcFXT7R2iXBsdRQe7US)

**Comment by e5faf2** [comment]
Version 3.0.4 :a86edf4: fixed!

**Comment by e5faf2** [comment]
Im sorry, its still reproducing on Version 3.0.4 :a86edf4:

**Comment by Hopper262** [comment]
I have seen this bug too, and noticed that it only happens when the Status Bar is hidden on startup. Showing and hiding the Status Bar will prevent the bug from recurring until the next launch.

**Comment by Eitot** [comment]
Is this still happening on `master`?
