### ISSUE TITLE
Beachball/freeze when scrolling subscription list during refresh

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#415]
Title pretty much describes the bug.  Using version 3.0.2 :3139437, I have to be careful not to scroll the subscription list during a refresh, or I will often get a beachball and permanent lock-up of the app.  Only solution is to force-quit and restart.  I'm using InoReader sync if that's relevant.

**Comment by josh64x2** [comment]
I'm able to reproduce this so will need to fix it.

**Comment by karlcow** [comment]
I can reproduce this consistently. It freezes every time. I need to kill the app for restarting it.

**Comment by acrylian** [comment]
I do frequently encounter this as well with 3.0.4 :a86edf4. Just selecting a folder with several feeds freezes the app often for some seconds without refreshing or having refreshed at all. Same when refreshing such a folder, too. It gets responsive afterwards again but the delay is a bit, well, inconvenient. Also trying to quit the app keeps several seconds hanging with the beach ball. So I often use force quite therefore… (21" iMac late 2011, 10.9.5)

**Comment by josh64x2** [comment]
is this still an issue for people? i haven't had it for a while and i have a large list of feeds.

**Comment by tonycpsu** [comment]
No, I haven't seen it lately, either.
