### ISSUE TITLE
Correct Syncing Preferences instructional text

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#417]
In the syncing preferences, there is text that instructs the user to enter their email address an password for their syncing account. This can result in authentication errors because some accounts (like FeedHQ) allow the user to create a username to use for authentication instead of their email address.

![syncing-prefs](https://cloud.githubusercontent.com/assets/799345/5689153/2168fd9a-98b4-11e4-8331-8f0c7c2d8bdf.png)

It is also important to make it clear that Vienna does not sync subscriptions up to an Open Reader server. The subscriptions must already exist on the remote server.

**Comment by barijaona** [comment]
This is relatively easy to fix. We just need to modify the hint in the various `KnownSyncServers.plist`files.
