### ISSUE TITLE
Smart Folder Improvement

### ISSUE THREAD

**Issue by Rand72889** [ViennaRSS/vienna-rss#423]
My case: having a group folder for each topic.
Problem: got the idea to use a smart folder for each group but the problem is now that i want a smart folder that is only getting articles of ONE specific group (possible and working fine).
I want that it parses the group for words - Word1 OR Word2 in the article text AND the headline.
To do so (and not searching all folders) i have to select “match all criteria” but than i cannot use it as an OR operator!

Version 3.0.3

Any solution ?
Thanks

**Comment by josh64x2** [comment]
I think this would be easier once we refactor Vienna... which we are hoping to do shortly!

**Comment by Rand72889** [comment]
Ive noticed that behind a smartfolder there is no indicator for unread posts. It should handle a smartfolder as a subscription IMO so that if i use the "mark as read" button it opens it and if i click mark all as read - at also marks the real items as read in the other subscriptions.

**Comment by barijaona** [comment]
@thinmanballad suggested in #714 to add regex conditions and the following user interface : 

![Interface](https://cloud.githubusercontent.com/assets/6265407/20652281/0a4aa782-b4bc-11e6-86f1-1d3e73df9d4e.png)

**Comment by dak180** [comment]
I think there are actually some standard controls to do this as I have seen rule setups like this in a few apps both apple and third party.
