### ISSUE TITLE
Mark updated articles as new --> higlight changes

### ISSUE THREAD

**Issue by Rand72889** [ViennaRSS/vienna-rss#424]
Is it possible that somebody could implement a feature that highlights the changes between the old and new article (in bold OR yellow..) - if "mark updated articles as new" is activated ?

Latest version with setting "Mark updated version as new".

Thank you very much

**Comment by josh64x2** [comment]
Interesting idea ... It ultimately depends on the complexity of the article though. The whole article could end up highlighted!
