### ISSUE TITLE
Easy access to Articles tab

### ISSUE THREAD

**Issue by rawtaz** [ViennaRSS/vienna-rss#430]
When opening an article from within the Articles tab, reading it, and then closing the tab for the article, the previous tab in the list is the one that is focused.

It would be great if the Articles tab (or perhaps put another way, the previously active tab) was refocused when you close a tab.

On a similar note there should be a menu item and corresponding (simple) keyboard shortcut for going directly to the Articles tab, wherever you are in the application.

What do you think?

**Comment by josh64x2** [comment]
Good suggestion! Have added it as a feature request

**Comment by TAKeanice** [comment]
#1116 is merged and will be there in the next version, so you have the cmd+y shortcut to go to the articles tab. The other part (i.e. the preference pane for it) is in progress.

**Comment by TAKeanice** [comment]
@josh64x2 @barijaona This is one example why I think the pref. pane of my PR 
https://github.com/ViennaRSS/vienna-rss/pull/1186  is appropriate. There are many different reading behaviors, this is one of them, and the settings allow for adapting Vienna to it.

**Comment by rawtaz** [comment]
Bumping this, as besides the shortcut to the Articles tab (Cmd+Y) the tab refocusing is not "backtracking" (instead of showing the tab you had open before the one you just closed, Vienna focuses on the tab that is to the left of the one you just closed).

**Comment by rawtaz** [comment]
Closing this, as there's a shortcut (Cmd+Y) to the Articles tab. The other feature suggested (refocusing on the previously focused tab) is tracked in #1070.
