### ISSUE TITLE
InoReader -- read flags lost

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#434]
I just updated to version 3.0.4 :a86edf4, and now all my feeds are showing 1000 unread articles.  if I manually mark them all as read, they just come back as unread on the next refresh.  This is using InoReader sync.

**Comment by tonycpsu** [comment]
Well, this problem seems to have come and gone, so maybe it was on InoReader's end.

**Comment by josh64x2** [comment]
excellent! we will be doing work on the syncing side of things for the next version though for future issues.
