### ISSUE TITLE
Use Cocoa Bindings for preferences

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#441]
https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CocoaBindings/Concepts/NSUserDefaultsController.html

**Comment by Eitot** [comment]
What are the benefits of this controller? The documentation is sparse. Cocoa bindings have the big disadvantage that they cannot be used with non-KVO properties, so we would have to type the string literals by hand  to match the bindings with the defaults keys.

**Comment by josh64x2** [comment]
I forget the actual advantage of using that controller - we can wire `NSUserDefaults` up directly from Interface Builder using the bindings inspector.

I think it is better if we can have Interface Builder do as much for us as possible
