### ISSUE TITLE
Article with fields containing emoji are pushed down in article list views (vertical/horizontal layout)

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#447]
Here is another case where ‘special’ characters cause incorrect layout in article listings. In this case the author field contains an emoji character (⏰)

In both bellow feeds the offending article author (bug reporter on Firefox bugzilla) is David Baron.

https://bugzilla.mozilla.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&chfieldfrom=2d&chfieldto=Now&component=CSS&component=CSS%20Parsing%20and%20Computation&component=CSS%20Styles&query_format=advanced&resolution=---&resolution=FIXED&resolution=DUPLICATE&title=Bug%20List%3A%20css&ctype=atom&list_id=6399433

referred from http://tinyurl.com/njg3k6v

or this one
https://bugzilla.mozilla.org/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&chfieldfrom=2d&chfieldto=Now&component=Layout&component=Layout%3A%20Block%20and%20Inline&component=Layout%3A%20Floats&component=Layout%3A%20Form%20Controls&component=Layout%3A%20HTML%20Frames&component=Layout%3A%20Images&component=Layout%3A%20Misc%20Code&component=Layout%3A%20R%20%26%20A%20Pos&component=Layout%3A%20Tables&component=Layout%3A%20Text&component=Layout%3A%20View%20Rendering&list_id=1540341&query_format=advanced&resolution=---&resolution=FIXED&resolution=DUPLICATE&title=Bug%20List&ctype=atom

referred from http://tinyurl.com/nks6n2g

screenshot:
![emoji](https://cloud.githubusercontent.com/assets/8944809/6838480/5c1c3b04-d39d-11e4-80b5-a4d8da6cdc72.png)

**Comment by RobFog** [comment]
Reports at Cocoaforge:
- July 2017: https://forums.cocoaforge.com/viewtopic.php?f=18&t=26984
- Yesterday: https://forums.cocoaforge.com/viewtopic.php?f=18&t=27055

**Comment by karlcow** [comment]
This is another example

<img width="1372" alt="capture d ecran 2018-05-21 a 11 05 56" src="https://user-images.githubusercontent.com/505230/40287280-1f898d64-5ce7-11e8-861e-e313a7083751.png">

**Comment by karlcow** [comment]
Is this related to the issue?

https://github.com/ViennaRSS/vienna-rss/blob/bd6f2647c29f02b5583888f935f2ed93c7deb04a/External/BJRVerticallyCenteredTextFieldCell/BJRVerticallyCenteredTextFieldCell.m#L29-L52

**Comment by karlcow** [comment]
Maybe something to help with this (IANAOCC = I am not a Objective C coder) 
https://stackoverflow.com/questions/36248156/calculate-uilabel-height-for-text-with-different-languages-and-emojis-in-objecti

**Comment by barijaona** [comment]
As a consequence of studying removal of hard coded colors in order to improve dark mode, I finally found a solution to this long standing and annoying bug…
@josh64x2, I think it's safe enough to be included in 3.5.0 (will have to test it tonight on my 10.9 virtual box though…). Your opinion ?

**Comment by phiw13** [comment]
> As a consequence of studying removal of hard coded colors in order to improve dark mode, I finally found a solution to this long standing and annoying bug…

Works well so far in 3.5.0. Big thanks!
