### ISSUE TITLE
Crash on initial database creation

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#448]
When there is no database present and Vienna attempts to create one, an assertion failure due to recursive calls to FMDatabaseQueue occur.

**Comment by josh64x2** [comment]
@barijaona I had tested this previously when I wrote some unit tests for this commit https://github.com/josh64x2/vienna-rss/commit/fee5c4305389c529c078a7098936f871faeaf090
(I don't think I've committed the unit tests to my branch though). 

I can check it when I get back from holiday though!

**Comment by barijaona** [comment]
Happy holiday !

**Comment by barijaona** [comment]
I cherrypicked @josh64x2 's [commit fee5c43](https://github.com/josh64x2/vienna-rss/commit/fee5c4305389c529c078a7098936f871faeaf090) in my solution.
