### ISSUE TITLE
If adding existing feed, focus it.

### ISSUE THREAD

**Issue by diimdeep** [ViennaRSS/vienna-rss#451]
I'm trying to add feed, but it already added. Get error "You are already subscribed to that feed". It's ok. I would like that feed get focus in tree. Now I have to find it manually.

**Comment by diimdeep** [comment]
Whoa. My previous comment was in situation when adding happens trough panel, but if add by drag and drop link from web page to vienna tree of feeds in arbitrary location, instead of error, already existing feed get focused. Thus not consistent behaviour here.

**Comment by josh64x2** [comment]
ok thanks for the update :smile:
