### ISSUE TITLE
Replace JSONKit

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#457]
Now that we are supporting 10.7 as the minimum we can implement NSJSONSerialization.
JSONKit is abandoned and will not compile with Xcode 7 out of the box which is another reason to move away from it.

- [ ] Write tests for existing code in Xcode 6.4 on OS X 10.10
- [ ] Convert JSONKit calls to NSJSONSerialization and confirm tests are still passed
- [ ] Test compilation in Xcode 7

**Comment by barijaona** [comment]
There is a single jsonDecoder object in current code (in the GoogleReader class), so I am not sure it is worth creating a wrapper class.

**Comment by barijaona** [comment]
The crash caused by commit d01260b is due to a memory management problem. Will fix it.
