### ISSUE TITLE
Feed and article titles compressed

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#458]
After building from master with the changes from PR #453 the titles are compressed as shown below.

![compressed titles](https://cloud.githubusercontent.com/assets/799345/8610635/1f4d52f4-26f8-11e5-9ef2-3416a3ef3603.png)

**Comment by josh64x2** [comment]
@barijaona do you think this is from the table changes you pushed ?

**Comment by barijaona** [comment]
Almost certainly, not. I only modified the UnifiedDisplayView class. The screenshot shows an ArticleListView (in vertical layout mode).

**Comment by barijaona** [comment]
@josh64x2 I can reproduce the problem, but only with Xcode 7

**Comment by barijaona** [comment]
It is not a bug, it is a feature :wink:
NSTextFieldCell attempts to squeeze long texts before inserting ellipsis.
It is ugly with some fonts, less ugly with others (for instance HelveticaNeue) …
