### ISSUE TITLE
OpenReader (Inoreader): All articles disappear

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#466]
I upgraded to 3.0.5 to get the fix to #456, and it worked for a day or so, but suddenly my articles have disappeared.  If I restore `~/Library/Application Support/Vienna` and restart, the same thing happens.  The articles are all there, then it refreshes from Inoreader, and the articles are gone.

**Comment by barijaona** [comment]
The default rate limit set by Inoreader has already been reached. Cf. http://www.inoreader.com/developers/rate-limiting

I have asked for a limit increase from the Inoreader team and I am waiting for their feedback.

**Comment by barijaona** [comment]
The current limit are : 
- 150,000 requests/day for zone 1
- 70,000 requests/day for zone 2

This only temporarily solves the problem. We will have to wait for the upload of 3.0.5 at SourceForge (hopefully before the end of the week) to check that these limits are sufficient.

**Comment by barijaona** [comment]
3.0.6 has largely been adopted now, and Inoreader has increased its limits to safe levels.
