### ISSUE TITLE
Duplicate feed

### ISSUE THREAD

**Issue by miguelarauj1o** [ViennaRSS/vienna-rss#467]
Hey, running Vienna for the first time, some feeds came included. But, each one feed came duplicated. Is it right?

Besides, after I removed each duplicate feed, I can't remove the feed that remains (see image below). 

![screenshot 2015-07-28 12 39 36](https://cloud.githubusercontent.com/assets/7546651/8936090/b7444bbc-3526-11e5-92b7-75bf85bcb2b6.png)

**Comment by barijaona** [comment]
It is clearly an anomaly. Which version and which OS are you running ? Are you able to reproduce it ? (move somewhere else the ~/Library/Application Support/Vienna folder, and restart from a fresh install).

**Comment by josh64x2** [comment]
@barijaona I remember seeing a commit to fix the duplicate feeds in new installations. I can't find a reference to it though!

**Comment by barijaona** [comment]
OK. I could reproduce the problem with 3.0.5. I will backport the commit 641f220 to branch 3.0.x

**Comment by miguelarauj1o** [comment]
@barijaona, Yosemite 10.10.4 and Vienna 3.0.4.

Yes, I can reproduce it.
<img width="366" alt="screenshot 2015-07-29 11 13 00" src="https://cloud.githubusercontent.com/assets/7546651/8959794/37e70e0a-35e3-11e5-9ac2-60b3acd427b0.png">

After delete one duplicate feed.
<img width="622" alt="screenshot 2015-07-29 11 13 18" src="https://cloud.githubusercontent.com/assets/7546651/8959795/37ffad98-35e3-11e5-81e8-847cf9dc077e.png">

Another thing,  _mac os x hints_ feed has an error.

**Comment by barijaona** [comment]
Fixed in 3.0.6
