### ISSUE TITLE
Articles not opening in the background with external browser

### ISSUE THREAD

**Issue by aar0nr** [ViennaRSS/vienna-rss#473]
When I click an article, it opens it in Chrome, but it brings focus to Chrome instead of opening in the background. Any ideas?

OS X: 10.10.4
Vienna: 3.0.6 5eaf312
Chrome: 44.0.2403.125 (64-bit)

I have these settings enabled:

<img width="298" alt="ss" src="https://cloud.githubusercontent.com/assets/173250/8986909/9b9fc26c-369b-11e5-8635-8a941c3242d2.png">

**Comment by barijaona** [comment]
It works as expected with Safari, Firefox. Omniweb ;-) …

For some reason, Chrome and Opera do not respect the [NSWorkspaceLaunchWithoutActivation](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSWorkspace_Class/index.html#//apple_ref/c/tdef/NSWorkspaceLaunchOptions) option. You should report this as a bug to their developers.

**Comment by aar0nr** [comment]
Thanks for the information. The Chromium issue can be found at the following link:

https://code.google.com/p/chromium/issues/detail?id=500038
