### ISSUE TITLE
Migrate from CFXMLTree to NSXMLDocument

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#479]
CFXMLTree is deprecated as of Mac OS X 10.8. 
Our XMLParser class needs to be refactored to use NSXMLDocument.

**Comment by josh64x2** [comment]
Instead of refactoring XMLParser, I've migrated most classes away from using it and replaced it with NSXMLDocment/NSXMLNode. The only remaining class is RichXMLParser.

The works is being done on https://github.com/josh64x2/vienna-rss/tree/xmlchanges
and I will create a PR once RichXMLParser has been done.

**Comment by josh64x2** [comment]
@barijaona if you tell me which feeds you have been using for testing RichXMLParser I will save them as .xml files and use them in the unit tests. Then I can write performance tests so we can do some optimisations :smile: !

**Comment by barijaona** [comment]
You have a very comprehensive collection, here : https://github.com/rss-sync/corpus

I haven’t tested them all :grinning:
