### ISSUE TITLE
Serious problems with NPR content

### ISSUE THREAD

**Issue by PacoH** [ViennaRSS/vienna-rss#481]
ONE. Cannot open NPR Media Player. Always get error:

>Thanks for launching the NPR Media Player!

>The Player requires version 8 or higher of the Adobe Flash Player.

Installed Flash Player **18**! and still get same error.

TWO. Download button does not work. Error:

>The page you requested could not be loaded.
>
>Check the URL (or address) you entered for typing errors such as ww.test.com instead of www.test.com.
>If the error persists and you are unable to load other pages as well, check your network connection.
>If your computer or network is protected by a firewall or proxy, make sure that your account, your machine, and Vienna are allowed to access the resource you specified.
>Error Information:
>
>Frame load interrupted

Have to right-click Download button plus 3 up-arrows to download EACH article and then play them in VLC MP. That's my only option.

THREE. All downloaded MP3s from WBUR have mangled names. e.g. 

>npr_428138824.mp3

downloads as

>npr_428138824.mp3?orgId=1&amp;d=2761&amp;p=510053&amp;story=428138824&amp;t=podcast&amp;e=428138824&amp;ft=pod&amp;f=510053

Have to manually delete the garbage.

Problems with previous versions still persist with 3.0.6.

OS X 10.8.5

**Comment by barijaona** [comment]
To help me investigate, could you :  
- give me the URL of the feed you are subscribed to
- provide a page link which includes a download link

**Comment by barijaona** [comment]
Also make sure that "Enable Plugins in the internal browser" is enabled in the Advanced Preferences

**Comment by PacoH** [comment]
OK, thanks. For some reason, "Enable Plugins in the internal browser" was unchecked, maybe when I updated? Is this the default? Checking it now enables the player to work.

The 'Download' button opens the stream in the app as it always has, but does not download it as expected. I still have to right-click and select 'Download Linked File' to download it. I think this in itself is a bug. I should be able to just click the button and have the file download in one click.

http://www.npr.org/rss/rss.php?id=2
>http://www.npr.org/programs/all-things-considered/

http://www.npr.org/rss/rss.php?id=3
>http://www.npr.org/programs/morning-edition/

WBUR problem still persists.

http://www.npr.org/rss/podcast.php?id=510053
>npr_428138824.mp3?orgId=1&amp;d=2761&amp;p=510053&amp;story=428138824&amp;t=podcast&amp;e=428138824&amp;ft=pod&amp;f=510053

http://www.npr.org/rss/podcast.php?id=510208
>npr_428424843.mp3?orgId=1&amp;d=3199&amp;p=510208&amp;story=428424843&amp;t=podcast&amp;e=428424843&amp;ft=pod&amp;f=510208

http://www.npr.org/rss/podcast.php?id=510051
>npr_428148807.mp3?orgId=1&amp;d=2485&amp;p=510051&amp;story=428148807&amp;t=podcast&amp;e=428148807&amp;ft=pod&amp;f=510051

This is when I click the 'Download' button lower right on the main feed page.

**Comment by barijaona** [comment]
Multiple points here.

1/ By default, plugins are enabled

2/ I guess you are using either the Horizontal, either the Vertical layout, with the option to display articles as web pages enabled. So, you probably have something like this.

![telechargements_et_vienna__85_non_lus_](https://cloud.githubusercontent.com/assets/442030/9026927/060542b6-394a-11e5-9e44-36f8f1e4b763.jpg)

This may vary according your preferences settings, but here are my observations : 
- if I click on the “Download this story” link on the webpage (red circled in the screenshot), a new tab opens in Vienna. It appears as a blank window, but if I call the Downloads window, I can see that the file is being downloaded with the correct name
- if I click the text link at the bottom (circled in yellow in the screenshot), the podcast opens in Safari
- if I click the Download button at the bottom (circled in orange in the screenshot), the download starts inside Vienna, and I effectively have a name problem.

I think the latter needs a fix.

**Comment by PacoH** [comment]
I am using the Horizontal layout but I don't see a setting to display articles as web pages. How did you do this? I get a summary of the article instead of the webpage. 

![Screenshot](http://i.imgur.com/KCPL14I.jpg)

If I hit 'Enter', the webpage opens in a new tab. When I click 'Download this story' on the webpage in the tab, it downloads and names the file correctly, no new tab.

>onpoint_0731_iran-deal-cincinatti-boston-2024-cecil.mp3 

Clicking the link at the bottom left in the horizontal layout opens the stream in my default browser (Firefox).

>http://podcastdownload.npr.org/anon.npr-podcasts/podcast/510053/428138824/npr_428138824.mp3?orgId=1&amp;d=2761&amp;p=510053&amp;story=428138824&amp;t=podcast&amp;e=428138824&amp;ft=pod&amp;f=510053

Clicking the 'Download' button in the horizontal layout downloads the file and names it

>npr_428138824.mp3?orgId=1&amp;d=2761&amp;p=510053&amp;story=428138824&amp;t=podcast&amp;e=428138824&amp;ft=pod&amp;f=510053

So this definitely needs fixing.

But I think the other problem of opening the stream in the tab when 'Download' is clicked on an NPR webpage in a tab also needs to be addressed. It is unintuitive and unexpected/undesired behavior.

>http://www.npr.org/programs/morning-edition/

**Comment by barijaona** [comment]
> I am using the Horizontal layout but I don't see a setting to display articles as web pages. How did you do this?

It is a per feed setting. You can have it be selecting the feed and use the menu item 'Folder -> Use Web Page for Articles'

You can also set it by selecting the feed and choosing 'Get Info…' in the contextual menu.

Will work on this later.

**Comment by PacoH** [comment]
Oh I see. I like this setting much better. Now I can just click the 'Download this article' link and get the properly named article for now. Thank you.
I would like to set this as the default for all feeds. I can use CMD-I to 'Get Info', shift-TAB, space, CMD-W to set each feed but I have hundreds of feeds.

**Comment by barijaona** [comment]
I forgot to mention that alternatively, you can just select the folder and use the menu item "Folder -> Use Web pages for Articles".

**Comment by PacoH** [comment]
I guess I already did that because I see the web page if I select an article. But the problem still persists in 3.0.8. If I click 'Download' I get the  mangled name that I have to edit but the article remains selected and I can navigate the panel with the cursor keys. If I cmd-click 'Download this story' in the web page, I have to hit up-arrow 3 times and hit 'return' to download but it is properly named. Either way is inefficient and I hate using the trackpad/mouse. Expected behavior is click 'Download' once and get correctly named file. I can then navigate the articles with the keyboard and another click will download that article. Simple.
