### ISSUE TITLE
Translation: Galician

### ISSUE THREAD

**Issue by leitinha** [ViennaRSS/vienna-rss#485]
Hello!

I would like help translating Vienna to Galician. Could I try?
I'm an absolute newbie, so I would like to learn and help. I could also help with Spanish.

**Comment by barijaona** [comment]
Thanks for volunteering ! Yes, you can try, it will be very appreciated.

The bad news is that we are currently changing things in our architecture, so it is not the best time to start a new translation.
The good news is that the new architecture will make translations much easier !

You can start anyway, but I suggest you only change one file for the time being, `Localizable.strings` : 
- learn a bit about Git and [read these advices](https://github.com/ViennaRSS/vienna-rss/wiki/Good-manners-with-Git)
- checkout a new branch from master
- in the lproj folder, duplicate one of the existing subfolders to a __gl.lproj__ folder (gl is the code for Galicean). I don’t know if starting from the Spanish version to build the Galicean version is a good idea or not.
- inside the new gl.lproj folder, modify the `Localizable.strings` file.

You will need a text editor supporting the UTF-8 encoding. I use TextWrangler, as it is free.

I will get back to you soon for the other parts of the translation.

**Comment by leitinha** [comment]
Perfect!
Thank you so much!

**Comment by leitinha** [comment]
I'm translating that file right now. Before reading your answer I had already translated other files... 
https://github.com/leitinha/vienna-rss/tree/master/lproj/gl.lproj
(I dit not duplicate folders to know exactly what I've done)

**Comment by josh64x2** [comment]
@leitinha hi! For the Preferences window there are more strings files in the `Interfaces/Preferences`folder if you would like to translate those as well.

Thanks!
