### ISSUE TITLE
Xcode 7?

### ISSUE THREAD

**Issue by marchyman** [ViennaRSS/vienna-rss#496]
Is Xcode7 supported?

Trying "make development" results in this

    ...
    ld: building for OSX, but linking in object file built for (unknown), file '/Users/marc/src/vienna-rss/3rdparty/Sparkle.framework/Sparkle' for architecture x86_64
    cclang: error: linker command failed with exit code 1 (use -v to see invocation)

    ** BUILD FAILED **

**Comment by barijaona** [comment]
See issue #492

**Comment by josh64x2** [comment]
@marchyman it is supported technically but the current build of Xcode 7 has a linker bug which you've discovered. Issue #492 is a workaround for the linker bug, but it is also something we should do anyway.

**Comment by josh64x2** [comment]
@marchyman I've submitted a PR to fix this ( #498 ) so hopefully it will be merged soon.

**Comment by marchyman** [comment]
I saw the commit.  Thanks.
