### ISSUE TITLE
Unable to access basic-auth atom feed

### ISSUE THREAD

**Issue by DVGeoffrey** [ViennaRSS/vienna-rss#503]
Hello,
When trying to access a (JIRA) atom feed, Vienna prompts me for a username and password endlessly (even though I'm entering the right credentials).  I am able to get a rss feed through curl:

```
> curl -k --user USERNAME:PASSWORD "https://jira.example.com/activity?maxResults=20&providers=issues&os_authType=basic&title=undefined"
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:atlassian="http://streams.atlassian.com/syndication/general/1.0"> ...
```

Am I doing something wrong?

**Comment by DVGeoffrey** [comment]
I'm using Vienna "Version 3.0.8 :074a131:"

**Comment by barijaona** [comment]
Can you verify if your credentials are stored in Keychain ?

**Comment by DVGeoffrey** [comment]
I found the JIRA credentials in the apple Keychain.  I deleted the Keychain entries and tried to log into the RSS feed through Vienna again... which added the key back to the Keychain.  Username and password are correct.

**Comment by barijaona** [comment]
Might be related to issue #522. Could you try logging in through Vienna’s internal browser, and check if things improve ?
