### ISSUE TITLE
Decide on replacement for cocoaforge forums

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#506]
Cocoaforge forums seem to be broken and attempts to contact administrators have been unsuccessful.
This issue is for discussing our options.

[Vienna Blog announcement](http://www.vienna-rss.org/?p=441)

Options are limited because we haven't set up a financial structure for Vienna to accept donations etc and therefore can't pay for hosting.
Sourceforge has hosting which we currently use for our blog but that limits us to forums built on php and mysql.
* [PHPBB](https://www.phpbb.com/)
* [Vanilla forums](http://vanillaforums.org/)

We could use a hosted solution that has free hosting for open-source projects:
* [TenderApp](http://tenderapp.com/)

**Comment by deseven** [comment]
I can provide hosting free of charge and without any time limits on my private server in Netherlands or in our datacenter in Russia (i work for russian ISP). I can also install and configure phpbb as i know it pretty well.

Why? Well, because i can :) And also my private server have too much free resources.

However, you still need a domain (something like forum.vienna-rss.org should be ok). And if you want a custom template you'll need to develop it yourself.

**Comment by josh64x2** [comment]
@deseven thanks for the offer!
@barijaona what are your thoughts?

**Comment by barijaona** [comment]
@deseven Thanks for the offer !
@mstroeck You are the owner of the vienna-rss.org domain. Are you OK with this ?

**Comment by deseven** [comment]
Some more details about possible locations:
1. Netherlands - hosted on DigitalOcean and they guarantee 99.99% availability. The ip is 95.85.14.170.
2. Russia - basically the same, maybe a bit lower availability, usually no more than 30 minutes per month ([statistics](https://dl.dropboxusercontent.com/u/943974/Screenshots/b9xjglp1a51i.png)). The ip is from 195.191.220.0/23 network, you can ping/tracert 195.191.221.2 to check the latency.

**Comment by barijaona** [comment]
The Netherlands location is more responsive from here (Madagascar, which is probably representative for Africa).

**Comment by benhalverson** [comment]
@barijaona  Instead of a forum why not use a slack channel?

**Comment by josh64x2** [comment]
@benhalverson We have a slack channel for devs (so just @barijaona and I for now :smile: ) but slack channels aren't really public and we need something public. We also have an IRC channel but hardly anyone uses it.

**Comment by benhalverson** [comment]
@josh64x2 Sure slack was designed to be not public, but there are lots of public slack channels popping up as support. A few examples I am on are bootstrap http://bootstrap-slack.herokuapp.com/ and http://www.angularbuddies.com/ both use this open source project called slackin http://rauchg.com/slackin/ Another common way to handle signups is with typeform. 
Here's a list of popular public slack channels http://www.chitchats.co/

**Comment by josh64x2** [comment]
@benhalverson that's excellent! thanks! I will look at setting it up :) I still think we'd need forums as they are a more passive approach than a slack/irc channel.

**Comment by sjmills** [comment]
So has anything been done? I'd really like to be able to report bugs somehow. Cocoaforge registration has been broken for months.

**Comment by josh64x2** [comment]
@sjmills We haven't done anything yet as we are trying to get 3.1.0 finished. If you have bugs to report please report them here on GitHub. Thanks!

**Comment by 4estGits** [comment]
The CocoaForge problems are a bad joke at this point. The least someone could do is POST A STICKY at the very top of the forums and on each main sub-forum telling everyone of the problem. Also, there have been offers of free hosting and I'm sure there would be others. Take someone up on the offer. Anything is better than the mess existing now.

**Comment by josh64x2** [comment]
@4estGits good point re: sticky, i'll get on to that today.

**Comment by josh64x2** [comment]
forum announcement here: http://forums.cocoaforge.com/viewtopic.php?f=18&t=26795

**Comment by deseven** [comment]
Well, 6 months passed, i'm still ready to help if anyone needs it.

**Comment by josh64x2** [comment]
OK thanks, I'll set a reminder to take a proper look at it again this week. :grin:

**Comment by josh64x2** [comment]
In contact with current maintainer of cocoaforge. stay tuned!

**Comment by 4estGits** [comment]
Great!

F

**Comment by stevewpalmer** [comment]
The code base for Vienna came from an earlier incarnation I wrote for the CIX Conferencing system (http://www.cix.co.uk) which provides moderated online discussions and support. Might be an option although the web based Forums is a little clunky.

**Comment by josh64x2** [comment]
Another option I just had a random thought about is creating a ViennaRSS subreddit. 

Will wait to see how this Cocoaforge maintenance discussion goes.

**Comment by 4estGits** [comment]
Okay. I’m in support of anything that works!

Forrest

**Comment by josh64x2** [comment]
Cocoaforge should now be working. I'm going to close this issue but please feel free to reopen it if you spot any other problems with the forums.

**Comment by 4estGits** [comment]
Josh,

I’ve tried to sign up for the Vienna forum on CocoaForge this morning and gotten no where. I can get through the process, but I never receive a confirmation email. I’ve checked my spam, etc. Also, it seems that at one time I was able to sign up for a CocoaForge account, possibly for CyberDuck, but I can’t remember the password or username. Providing them the email address won’t reset the old password or send me a reset email.

Forrest

**Comment by josh64x2** [comment]
@4estGits if you let me know your email address i can delete your account so you can sign up again. When I signed up a test account the verification email did go into the spam folder unfortunately so once I've deleted your current account make sure you do check the spam folder.
