### ISSUE TITLE
Broken feed in OS X 10.11 (works in OS X 10.10)

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#507]
The feed in question is: http://feeds.feedburner.com/Boagworldcom-ForThoseManagingWebsites
I think this is due to the Parsing changes, though it may also have something to do with the OS X 10.11 SDK.

I'm happy to investigate this weekend.

**Comment by barijaona** [comment]
NSXMLDocument's `-initWithData:options:error` seems unable to handle certain invalid characters.
At the end of a title in this feed, there is an unexpected character (code 8) which causes failure in our parsing.

**Comment by josh64x2** [comment]
Confirmed fixed with PR #510 :smile:

**Comment by barijaona** [comment]
PR #510 is incomplete, because it does not take into account Unicode… It uses unsigned char, while a Unicode character might be represented by two bytes or more.
