### ISSUE TITLE
3.1.0 beta 2, beta 3 weird rendering of panes at startup.

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#513]
My preferences are set to vertical layout.
When launching Vienna, there is a weird painting of the various panes going on. The feeds list (side bar) displays correctly, the article list and the article pane behave oddly. First Vienna displays both panes as if to render the horizontal layout. Both panes are empty at this point. Then after a (brief) moment it switches to vertical layout, and then populates the article list pane. The article pane itself out to be empty as no article is selected at this point.

I *think* I have seen the same happening with Vienna 3.0.6, after which I switched to 3.1.0 beta 2.

It doesn't seem to matter what is selected in the sidebar — individual feed, folder or smart folder (usually a “today” smart folder is the active, selected thing in my case).

I see this on older machines, although even the 2011 iMac (still vintage… sigh) shows the issue

**Comment by barijaona** [comment]
I cannot reproduce the issue here.

**Comment by phiw13** [comment]
You’re right. With 3.1.0 beta4 it is not visible anymore. (at least on OS X 10.11.1)
