### ISSUE TITLE
Authentication failing for RSS feeds from ASF Jira

### ISSUE THREAD

**Issue by neuroticnetworks** [ViennaRSS/vienna-rss#522]
I attempted to add RSS feeds to Vienna from both 

https://issues.apache.org/jira/activity?maxResults=10&streams=key+IS+CASSANDRA&providers=dvcs-streams-provider+thirdparty+issues&os_authType=basic&title=undefined

and 

https://issues.apache.org/jira/activity?maxResults=10&streams=key+IS+SPARK&providers=dvcs-streams-provider+thirdparty+issues&os_authType=basic&title=undefined

when I attempt from my browser while signed out, I am asked to authenticate myself with a username and password. This authentication succeeds in Chrome and Firefox, as you would expect.

Likewise, when I removed &os_authType=basic&title=undefined from the url I handed to Vienna, it worked just fine.

Still, I was asked for authentication in Vienna... but it does not succeed as expected. A part of me suspects this is such an isolated issue that it's not worth reporting, especially since you can simply remove the &os_authType=basic&title=undefined portion of the url and get around it ... but on the other hand I imagine a lot of us do keep an eye on ASF RSS feeds from Jira and the fact that Vienna is attempting basic auth and failing at it seemed like it was at least worth mentioning. 

I don't know of any strictly password protected RSS feeds off the top of my head or else I'd test auth and scope out this issue a bit more, see if it's failing at basic auth in general. If I happen across a good, non-Jira RSS feed to test this with, I will and I'll report back with how it goes.

**Comment by barijaona** [comment]
Try logging in through Vienna’s internal browser.

**Comment by josh64x2** [comment]
OK so internal browser does hold cookies, but they aren't used when trying to view the feeds. I'm also getting consistent crashes when trying to add feeds and credentials which isn't a great sign :frowning:

**Comment by josh64x2** [comment]
@barijaona it looks like there are lots of problems with Authentication.
E.g. I can't find anything that calls `-(void)handleRequireAuthenticationForFolder:(NSNotification *)nc` in `RefreshManager.m`. Is that old code we can safely delete or has the notification been mistakenly deleted?

**Comment by barijaona** [comment]
Strange, it has been so since at least Vienna 2.0…

I only have one authenticated feed in my setup (one which just requires username/password), and it seems to work OK… I remember recently changing credentials on it, and it prompted me as expected…

I still suspect the behavior change is related to cookie management. I noticed that before El Capitan, Vienna's browser used the same cookie jar than Safari, and this was also used by ASIHTTPRequest when useCookiePersistence was set to YES (which is the default).

**Comment by josh64x2** [comment]
OK I actually had my JIRA server configured wrong, so if you have a cookie set in the internal browser it authenticates OK with the feed.
If I clear the cookie and Vienna requests credentials, it just keeps requesting the credentials.

**Comment by fabien-michel** [comment]
Encoutering exactly the same problem with Vienne and Jira.
Using internal browser to authenticate allow Vienna to retrieve Jira's feed items, but restarting Vienna, make it "forgot" the auth and request for password endlessly.

**Comment by josh64x2** [comment]
IIRC, this issue is with the way Vienna is adding new feeds and storing the credentials. JIRA is also partly at fault here because it will not prompt for authentication and will show an empty RSS feed sometimes and then Vienna doesn't request for credentials.
I'll try to revisit this.

**Comment by mnarrell** [comment]
Is there any workaround for this?
