### ISSUE TITLE
make development build fails

### ISSUE THREAD

**Issue by marchyman** [ViennaRSS/vienna-rss#530]
Up to date source -- hash 03078fc917d921bef947a3a4d4d49e7ca3b4983d

The command line `make development` fails with

```
/Users/marc/src/vienna-rss/Vienna Tests/ExportTests.m:39:33: error: no known class method for selector
      'exportToFile:from:withGroups:'
    int countExported = [Export exportToFile:tmpUrl.absoluteString from:folders withGroups:NO];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/marc/src/vienna-rss/Vienna Tests/ExportTests.m:39:9: warning: incompatible pointer to integer conversion initializing 'int'
      with an expression of type 'id' [-Wint-conversion]
    int countExported = [Export exportToFile:tmpUrl.absoluteString from:folders withGroups:NO];
        ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/marc/src/vienna-rss/Vienna Tests/ExportTests.m:48:33: error: no known class method for selector
      'exportToFile:from:withGroups:'
    int countExported = [Export exportToFile:tmpUrl.absoluteString from:folders withGroups:YES];
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/marc/src/vienna-rss/Vienna Tests/ExportTests.m:48:9: warning: incompatible pointer to integer conversion initializing 'int'
      with an expression of type 'id' [-Wint-conversion]
    int countExported = [Export exportToFile:tmpUrl.absoluteString from:folders withGroups:YES];
        ^               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings and 2 errors generated.
```

**Comment by josh64x2** [comment]
@marchyman is that on OS X 10.11?

**Comment by marchyman** [comment]
On Oct 31, 2015, at 3:25 PM, Josh <notifications@github.com> wrote:
> 
> @marchyman is that on OS X 10.11?

Should have included that info, sorry...

OSX 10.11.1, Xcode 7.1


Marc

**Comment by josh64x2** [comment]
Hrm that's what I'm running and I don't have an issue with it. I'll investigate further!

**Comment by marchyman** [comment]
On Oct 31, 2015, at 5:37 PM, Josh <notifications@github.com> wrote:
> 
> Hrm that's what I'm running and I don't have an issue with it. I'll investigate further!

I killed the derived data folder on the off chance it would make a difference in addition to doing a make clean.  No difference.

Marc

**Comment by josh64x2** [comment]
Are you using the default case-insensitive HFS+ ?
(`diskutil info /`)

**Comment by josh64x2** [comment]
Oh never mind, I get the same errors if I run tests manually from xcode!

**Comment by josh64x2** [comment]
all fixed... let me know how you go :smile:

**Comment by marchyman** [comment]
On Oct 31, 2015, at 5:46 PM, Josh <notifications@github.com> wrote:
> 
> Are you using the default case-insensitive HFS+ ?
> (diskutil info /)

Yup.

   Device Identifier:        disk2
   Device Node:              /dev/disk2
   Whole:                    Yes
   Part of Whole:            disk2
   Device / Media Name:      Macintosh HD

   Volume Name:              Macintosh HD

   Mounted:                  Yes
   Mount Point:              /

   File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)
   Journal:                  Journal size 90112 KB at offset 0x205e000
   Owners:                   Enabled

etc

Marc

**Comment by marchyman** [comment]
> On Oct 31, 2015, at 6:05 PM, Josh <notifications@github.com> wrote:
> 
> all fixed... let me know how you go 

** BUILD SUCCEEDED **

and it seems to be running quite fine.  Thanks,

Marc

**Comment by josh64x2** [comment]
excellent! thanks for reporting the issue :smile:
