### ISSUE TITLE
Vienna doesn't maintain image aspect ratio when resizing images

### ISSUE THREAD

**Issue by marchyman** [ViennaRSS/vienna-rss#534]
The title is a guess as to the problem.  When displaying an item that contains an image where the image size is too large to fit in the Vienna window the image is made to fit, but the aspect ratio is not maintained.

 Example: an item contains a 1920x1080 image.   Page is displayed in a window that is much narrower that 1920 pixels using Horizontal layout (although the issue seems to be the same in all layouts).  Image is shrunk on the X axis to fit the window.  Image is not shrunk on the Y axis since the window is more than 1080 pixels high.

OSX 10.11.1, Vienna based upon commit d69cabede2d5d9c97a132fb360737d7314060865 although I'm pretty sure this has been going on for a while.

**Comment by barijaona** [comment]
Which style are you using ?
Also make sure there is no conflict with Vienna’s built-in styles and custom ones (in `~/Library/Application Support/Vienna/Styles`)

**Comment by marchyman** [comment]
On Nov 6, 2015, at 8:05 PM, Barijaona Ramaholimihaso <notifications@github.com> wrote:
> 
> Which style are you using ?

FeedLight Graphite

> Also make sure there is no conflict with Vienna’s built-in styles and custom ones (in ~/Library/Application Support/Vienna/Styles)

That folder only contains Images/, Sources/, and messages.db

Marc

**Comment by barijaona** [comment]
I cannot reproduce the issue,even if I deliberately shrink Vienna's window.
![vienna](https://cloud.githubusercontent.com/assets/442030/11014010/9ac636e4-8535-11e5-8551-190e2908ec11.jpg)

**Comment by marchyman** [comment]
On Nov 6, 2015, at 10:56 PM, Barijaona Ramaholimihaso <notifications@github.com> wrote:
> 
> I cannot reproduce the issue,even if I deliberately shrink Vienna's window.

OK.  I’ll dig further to see if I can find what is going on.

Marc
