### ISSUE TITLE
Preferences did not reflect changes in Fonts picker

### ISSUE THREAD

**Issue by FakeYin** [ViennaRSS/vienna-rss#536]
Version 3.1.0 Beta 5 :6319258:  El Capitan

The Article list font and Folder list font cannot be changed through fonts picker. 
![screen shot 2015-11-16 at 03 43 34](https://cloud.githubusercontent.com/assets/15860714/11170600/42802310-8c14-11e5-9832-c4ebb7c18e70.png)

**Comment by barijaona** [comment]
I cannot reportduce this.

**Comment by FakeYin** [comment]
The font can be changed when redownload the 3.0.9 build from http://www.vienna-rss.org.  

However if I use "check for update" and install Version 3.1.0 Beta 5 :6319258:, the font change is not working.

**Comment by barijaona** [comment]
For me, 3.0.9 and 3.1.0 Beta 5 behave the same way.

What I noticed is that the selection is not effective when the Preferences window is sent in the background (is hidden by the main window)

**Comment by FakeYin** [comment]
I downloaded the build from https://github.com/ViennaRSS/vienna-rss/releases .

3.0.9 worked fine but not in 3.1.0 Beta 5. 

Same behaviours are observed on another computer I have with clean install.

**Comment by aar0nr** [comment]
Same problem here.

I'm running Vienna ```Version 3.1.0 Beta 5 :6319258``` on OS X ```10.11.3```, and the font preferences do not work.

**Comment by josh64x2** [comment]
Yup this is definitely and issue. will look into it. thanks!

**Comment by josh64x2** [comment]
This can be fixed by upgrading MASPreferences to the latest version (1.1.2)
