### ISSUE TITLE
Subscribing to new feed adds feed headlines to currently open feed

### ISSUE THREAD

**Issue by slater** [ViennaRSS/vienna-rss#540]
See image:

http://i.imgur.com/X08387A.png

Was reading Clean Rinse blog's feed: http://blog.mecheye.net/ then added Princess Pricklepants's feed (as one does): http://princesspricklepants.com/

The new items got added to the CR headlines view, but also got their own entry on the left-most panel, as per usual. 

When I click on the PPP feed in the left-most panel, the correct headlines are displayed, and they are no longer in the CR headlines view.

Vienna Version 3.0.9 :22b3ce2:

**Comment by josh64x2** [comment]
@slater is this still an issue with Vienna 3.1.0?

Thanks

**Comment by slater** [comment]
@josh64x2 yes :(

**Comment by barijaona** [comment]
Same here : http://cocoaforge.com/viewtopic.php?f=18&t=26834
