### ISSUE TITLE
Use a proper Version format

### ISSUE THREAD

**Issue by ChrOst** [ViennaRSS/vienna-rss#541]
``<key>CFBundleShortVersionString</key>
<string>3.0.8 :074a131:</string>``

Please remove the colons + spaces from the Version string.

For Reference have a look at:
https://en.wikipedia.org/wiki/Software_versioning
http://semver.org/

**Comment by dak180** [comment]
This is an unfortunate consequence of how the keys in the info.plist are used by standard Apple tools (as an example: crash reports) and the ability to identify a unique revision when using a DVCS (like git) as apposed to something like svn where each revision can be identified by a monotonically increasing number (used by `CFBundleVersion`).

The best answer to these problems is for Apple to add a `CFBundleRevision` key to the info plist without the formatting restrictions of `CFBundleVersion` or to redefine the allowed formatting in `CFBundleVersion`; in any case I encourage you to file a radar on this subject with Apple as they use the number of duplicate reports to assign priorities.
