### ISSUE TITLE
[Feature Request] Change notifications to include subject line instead of generic message

### ISSUE THREAD

**Issue by oshmanm** [ViennaRSS/vienna-rss#544]
Instead of notifications that say "n number of articles retrieved", I think it would be valuable for the notification to read the subject line of the article instead, so one could just read the banner notification without having to necessarily open the app.

**Comment by Eitot** [comment]
This feature would only make sense if there was a way to mute individual feeds or folders. Sending individual notifications for each fetched article would be overkill otherwise.
