### ISSUE TITLE
Must Vienna use the discrete GPU?

### ISSUE THREAD

**Issue by JayBrown** [ViennaRSS/vienna-rss#548]
Older MacBook Pro models, those with two GPUs (discrete & internal, i.e in my case NVIDIA and Intel GPUs), often suffer from panics of the discrete GPU , which results in an immediate reboot in El Capitan. (Hardware repairs sometimes work, sometimes they don't, as in my case.) Some applications try to force-use the discrete card, which I can understand if they're graphics heavy, like Living Earth Desktop etc. I can override their behavior by switching to internal graphics card only (using gfxCardStatus). But when I manually switch to discrete GPU, then these apps (naturally) start using the discrete GPU immediately, but this also means I can't switch back to the internal GPU, because the discrete GPU is now in use. So I have to quit all those applications, then switch to internal GPU, then relaunch the applications. As I said, I can understand that apps with a graphics-heavy GUI try to force the discrete GPU, but why does Vienna do that? I know, I'm using outdated hardware, moreover hardware that isn't functioning properly anymore, but is it really necessary that Vienna tries to force-use the discrete GPU instead of the internal GPU?

**Comment by JayBrown** [comment]
This could be of help: https://developer.apple.com/library/mac/qa/qa1734/_index.html

**Comment by josh64x2** [comment]
@JayBrown we already have that enabled and on my 2011 MBP it stays on Integrated graphics instead of going to discrete. I wonder what is causing it.

**Comment by barijaona** [comment]
Vienna supports automatic graphics switching for a long time now. Cf issue #102.

Alas, it is a well known fact that there is an issue with some older Macbooks (notably, 2009 and before models) and third party developers can do little to circumvent it.
