### ISSUE TITLE
Vienna will modify RSS urls in certain condition

### ISSUE THREAD

**Issue by luzpaz** [ViennaRSS/vienna-rss#549]
Sometimes when I visit a certain cafe their free WIFI boots me off the network and I need to re-login. Sometimes perhaps in mid refresh the redirected URL that the WIFI requires me to register through ends up getting prepended to my Vienna-RSS files. 
Meaning suddenly after I refresh many of the feeds fail. Upon closer inspection this:
```http://10.0.2.1:4106/hotspot/Hotspot/?redirect=``` is appended to the front of every RSS feed 

I need to go in and manually change each one to get them working again. 

Why does this happen ? How do I fix this faster than going one-by-one ?

**Comment by luzpaz** [comment]
Screenshot of Failed RSS feeds 
![screenshot 2015-12-04 18 13 49](https://cloud.githubusercontent.com/assets/4140247/11604489/dba66a5c-9ab2-11e5-89ec-659d3647dafa.png)

**Comment by josh64x2** [comment]
@luzpaz what version of Vienna are you using? We did fix this issue in #380 so it should be fixed for both > 3.0.5 and 3.1.x beta. I'd like to get to the bottom of this!

Thanks!

**Comment by luzpaz** [comment]
Apologies.Version 3.0.9 :22b3ce2:
