### ISSUE TITLE
[Feature Requests (2): local "Read Later" folder; folder item counts

### ISSUE THREAD

**Issue by garynunes** [ViennaRSS/vienna-rss#551]
Been using Vienna a while. Overall an enjoyable experience. Two feature requests:

1) A local folder (not the ability to use an online facility, e.g., Instapaper) to store articles to be read later.
2) Item counts displayed for folders (including smart folders).

Regards,
    Gary Nunes

**Comment by josh64x2** [comment]
Great suggestions! Thanks :smile:

**Comment by garynunes** [comment]
Thanks for your response.

I just noticed that, if you close Group folders, a count is displayed for the folder. That surprised me. Still I think it would be nice if a folder count was visible even when a group folder is open, perhaps differentiated in some way from article counts (e.g., by color) and, as mentioned previously, counts for smart folders would also be appreciated.

Regards,
Gary Nunes

**Comment by barijaona** [comment]
Related to issue #476

**Comment by barijaona** [comment]
I'll close this because there are issues #532 and #476
