### ISSUE TITLE
Certain Vienna behaviors seem to be "hard wired" to Safari

### ISSUE THREAD

**Issue by garynunes** [ViennaRSS/vienna-rss#553]
This is, at least, an observation about Vienna's behavior. I'm not sure it qualifies as a fix or feature request since I don't know whether it can be fixed (it may be out of Vienna's hands) or even if you consider the behavior "broken".

When I select Chrome as the default browser for the system, Vienna for the most part, honors the request. I have however observed two instances where there seems to be a Safari dependency:

1) Whenever Safari's Adobe flash player extension needs to be updated (in order for Safari to continue to be able to play flash videos) Vienna also stops being able to play flash videos until Safari's flash player extension is updated. Seems like Vienna is dependent on Safari's extension even when Safari is not the default browser.

2) If you right-click (control-click) selected text in a Vienna article and choose the "Search with Google" item from the context menu Vienna (or something) starts up Safari rather than Google to do the search.

Regards,
    Gary Nunes

**Comment by josh64x2** [comment]
Hey @garynunes ,

Vienna uses the OS X WebKit framework for viewing web content, and this is also what Safari is based on. This is why the "Safari" (really WebKit) Flash plugin needs to be updated for both Vienna and Safari.
I'm guessing this is also the reason behind "Search with Google" opens Safari and not Chrome for 2).
I can see how this would be frustrating, I will try to see if we can change the behaviour of the context menu but unfortunately this will be low priority as there are bigger bugs we need to look at fixing first.

Cheers
