### ISSUE TITLE
flag current article (internal browser)

### ISSUE THREAD

**Issue by wmangano** [ViennaRSS/vienna-rss#563]
Feature Request:
add "flag" to current article (opened via internal browser)

my current daily workflow:
open all interesting articles in internal browser .... read it ... if i like the article ... "flag" it. problem is that sometimes i cannot relocate the origin feed (~1700 subscriptions)

**Comment by TAKeanice** [comment]
This is an interesting idea, and your workflow is quite similar to mine. It would require that for every open tab, we need a pointer back to the article from which it comes, if it was opened through the article view. There are some unclear things about the implementation though; What behavior would you expect when following a link from the opened article for example?
