### ISSUE TITLE
"Ghost" posts and wrong post count

### ISSUE THREAD

**Issue by Addicted2light** [ViennaRSS/vienna-rss#567]
Hi, 

from a few weeks Vienna is constantly showing the wrong post count in the dock (Mac OS X 10.11.3 El Capitan), pulling "ghost" posts from the following sources (I have the sync with Inoreader active; see screenshots below):

- http://www.kenrockwell.com/rss-daily.php
- http://www.japancamerahunter.com/feed/
- https://www.youtube.com/feeds/videos.xml?channel_id=UCVcxJ9k14bi__-uA1cGkEcA
- http://feeds.feedburner.com/techradar/cameras-and-camcorders-reviews?format=xml

Uploading the entire list of feeds doesn't make a difference, while uploading each single feed make the ghost posts disappear from the post count; but as soon as Vienna updates the entire list of feeds they are back.

The only way to solve the problem is to log in via web to Inoreader and mark all as read. The strange thing, though, is that in Inoreaded the feeds showing unread posts are not from the same feeds that are showing false post counts in Vienna, but actually pretty old posts from other feeds already read and deleted in Vienna, so my guess this is some kind of sync error.

P.s. keep up the good work, this software is borderline perfect! The only feature I think is missing is the ability to copy video links from within Vienna itself (or to download them)

![schermata 2016-02-18 alle 09 58 07](https://cloud.githubusercontent.com/assets/17311611/13138320/bc9b0dfc-d626-11e5-9610-29e7a97e0be2.png)
![schermata 2016-02-18 alle 09 58 20](https://cloud.githubusercontent.com/assets/17311611/13138323/bcc45edc-d626-11e5-8470-ff236e9c484c.png)
![schermata 2016-02-18 alle 09 58 27](https://cloud.githubusercontent.com/assets/17311611/13138321/bcc13af4-d626-11e5-9e4e-ab19c6ff9a44.png)

**Comment by josh64x2** [comment]
@Addicted2light thanks for the clear bug report! I'll try and get a look at it this weekend :smile:

**Comment by Addicted2light** [comment]
Thanks to you for the speedy response! :)

**Comment by Addicted2light** [comment]
Since the original post, I've experienced the same behavior just once (and going to Inoreader and marking the affected article as "read" solved it).

Let's hope this new released version has solved this small nuisance for good :+1:

**Comment by josh64x2** [comment]
I am glad you're not experiencing this issue very often. I am very sorry that I forgot to revisit the issue - I will try and keep an inoreader account connected to my copy of Vienna so if any issues arise then I can help debug them.

**Comment by Addicted2light** [comment]
That is what I would call a fast response!!! :) 

No need to be sorry btw, I just updated the issue report exactly to let you know that is not something that’s happening very often, so you can concentrate on eventual more urgent “stuff”.

Keep up the good, no, scratch that, GREAT work!


Gianluca Bevacqua
www.addicted2light.com
facebook.com/addicted2light
info@addicted2light.com

Il giorno 14 marzo 2016 @ 10:02:59, Josh (notifications@github.com) ha scritto:

I am glad you're not experiencing this issue very often. I am very sorry that I forgot to revisit the issue - I will try and keep an inoreader account connected to my copy of Vienna so if any issues arise then I can help debug them.
