### ISSUE TITLE
Tons of old articles show as unread every day

### ISSUE THREAD

**Issue by sjmills** [ViennaRSS/vienna-rss#568]
In the last few months, every time I launch Vienna every evening, I'm shown tons of really old articles that I know I've already read. They're marked with the green dot, not blue. Their dates go back years. Right now I see them going from 2010 to yesterday - articles I'd just read yesterday. I couldn't say what started it; a beta? Not sure. Each time it happens, I select all the green ones, mark them as read, and move onto the first truly new article and work my way through all new articles before quitting. Here are just a few of the urls of the sites this happens with:

http://grossgrub.tumblr.com/rss
http://sixawesomefacts.com/rss
http://unusualadultpartyitems.tumblr.com/rss
http://blackandwtf.tumblr.com/rss
http://fuckyeahvintage-retro.tumblr.com/rss

Using 3.1.0 Beta 5 :6319258: on 10.11.3.

**Comment by sjmills** [comment]
To qualify what I meant by "tons" of articles, it's over 300 articles every day that appear as unread, even though they were ready long ago, multiple times in the case of most of these that will reappear.

**Comment by barijaona** [comment]
Are you sure that the « Mark updated articles as new » preference is unchecked ?

**Comment by sjmills** [comment]
No, that pref is turned ON. But this only started happening in the recent past, and I don't know why *hundreds* of articles dating back 6 years or more would suddenly have updates *every day*. I'll keep it off for a couple days and see what happens.

**Comment by barijaona** [comment]
Some feeds may include in their posts informations like number of comments, user ratings etc.
While the article itself is unmodified, these informations change and trick Vienna.

**Comment by sjmills** [comment]
Yes, I know. But these things aren't changing. This is just one of the posts that I see often. No comments.

http://grossgrub.tumblr.com/post/967232547/john-got-the-idea-for-his-peas-in-milk-recipe

**Comment by DavidMunch** [comment]
I am seeing a similar issue, which started with 3.0.9 or 3.0.10 I believe.

Vienna shows previously read articles as unread, and reading them turns the article count into negatives. Refreshing feeds resets the count to 0 (Ie. not shown). 
![vienna](https://cloud.githubusercontent.com/assets/3511519/14498111/a6628ae4-0199-11e6-9ca7-dc9bf8265060.jpg)

**Comment by DavidMunch** [comment]
Update: Turns out that a simple Database reindexing fixed my problem. You may want to try that, under the Vienna menu.

**Comment by sjmills** [comment]
That menu item isn't enabled for me. I tried a few things, but it won't enable.

**Comment by barijaona** [comment]
@sjmills can you upload a screenshot of your General preferences setting ?

**Comment by sjmills** [comment]
Sure. I turned "Mark updated articles as new" off again after I couldn't get the reindex menu item to work.

![screen shot 2016-04-18 at 22 09 49](https://cloud.githubusercontent.com/assets/6181413/14626586/64d8e560-05b2-11e6-82a7-0dcc03493342.png)

**Comment by barijaona** [comment]
The “Reindex” menu should be available after the feed refresh process stops.

If it is not available, I suggest you temporarily deactivate “Check for new articles on start up” and relaunch the application.

**Comment by sjmills** [comment]
That might have done it. All those articles that kept reappearing as new have stopped that behavior. We'll see after a day or two.

**Comment by sjmills** [comment]
It took a while, but it's started up again. I guess I'll just leave the "Mark updated articles as new" turned off if it's going to keep acting up.

**Comment by DavidMunch** [comment]
I have to come back and say that I see the problem reappearing again and again. So far it seems the problem can be fixed temporarily by reindexing the database and then restarting Vienna, but after a few days, it will occour again.

I should mention that I use Bazqux for syncing, and then Vienna on 3 different Macs, and Feeddler on two iOS units, in case something goes wrong there specifically. I have a hunch that the problem lies somewhere specific, because some times the unread posts are recent, and sometimes they will be older (Ie. 12-24 hours) with read posts after these unread posts. I should also mention that I don't see issues with Feeddler on iOS.

And now that we are at it, could we get a visual indicator that the Database Reindexing process is running? I have no idea how fast is it, or when it finishes. :)

**Comment by barijaona** [comment]
@DavidMunch what OpenReader server do you use ? I just spotted a similar problem with Bazqux. Old articles were temporarily marked as unread by the server, and Vienna kept this unread status, after the problem was fixed server side.

I will include this with my current work on issue #631

**Comment by DavidMunch** [comment]
Bazqux as posted in the post above. :)

Funny enough, Feeddler just gave me last 500 posts of certain feeds as being unread, from Bazqux, so that is probably also what you describe. Haven't seen that one happening before.

**Comment by barijaona** [comment]
If it happens, try refreshing the feed,, may be force refresh.

**Comment by DavidMunch** [comment]
Force refresh didn't do a difference. This was just after a reindex.

I also just noticed something strange. Stories may be marked as unread, even though they aren't, in a feed, while the stories are shown as read if I look in the folder the feed is in.

**Comment by tonycpsu** [comment]
I'm also seeing this with the Inoreader backend.  Have tried rebuilding the index, etc. but the problem always comes back.  I've noticed no rhyme or reason as to which feeds it happens with.

**Comment by barijaona** [comment]
We have an upcoming version which should improve on this problem.

**Comment by barijaona** [comment]
Fixed in 3.1.4 RC 2 . See http://forums.cocoaforge.com/viewtopic.php?t=26793&p=139435
