### ISSUE TITLE
Articles reappearing in a feed after canceling its removal

### ISSUE THREAD

**Issue by Julien-Elie** [ViennaRSS/vienna-rss#571]
On latest Vienna 3.1.0 beta 5:
- go to a feed that has articles in;
- suppress one or all the articles in that feed;
- try to suppress the feed (with for instance the "Suppr" touch after clicking on the name of the feed);
- respond "cancel" when Vienna asks whether it should really suppress the feed;
- go to another feed and go back to the first feed;
- you will see that the previously suppressed articles have reappeared.

I believe these articles should not show up in the feed.

**Comment by Julien-Elie** [comment]
Note that the issue exists without trying to suppress the feed.  Just:
- select a feed that has articles in;
- suppress one article in that feed;
- select another feed;
- select the previous feed (where an article has been removed).

You will see that the previously suppressed articles has reappeared (as read).  Is it really the expected behaviour?

**Comment by barijaona** [comment]
No, it is an anomaly. Investigating it.

**Comment by barijaona** [comment]
This bug appeared between Beta2 and Beta3. Might be related to change in managing articles cache.

**Comment by Julien-Elie** [comment]
I confirm the issue in solved in 3.1.0.

**Comment by josh64x2** [comment]
Excellent, thanks!
