### ISSUE TITLE
3.1: Crash on first launch

### ISSUE THREAD

**Issue by JanX2** [ViennaRSS/vienna-rss#574]
Had to suppress „Reopen windows“ for it to finally run.

Additionally, and perhaps relatedly, this was and keeps being written to the system log:

    14.03.16 09:43:52,466 WindowServer[342]: _CGXRemoveWindowFromWindowMovementGroup: window 0xd9e is not attached to window 0xdb0

**Comment by josh64x2** [comment]
@JanX2 can you please take a screenshot for me so i can see what layout you're using?

**Comment by JanX2** [comment]
Well, it’s reset now, but I was using the [layout as displayed on the main page](http://www.vienna-rss.org/img/vienna_mainwindow_large.png).

**Comment by josh64x2** [comment]
OK thanks. I'm getting some of those system log messages too but I haven't had any crashes. Google isn't helping with regards to that message but I'll keep vienna closed for a while and see if it still appears in my logs.

**Comment by JanX2** [comment]
I just built from source (after #576) and the message is absent from the logs, but I get this instead:

> 14.03.16 10:18:05,368 WindowServer[342]: Surface testing disallowed updates for 10 sequential attempts...
> 14.03.16 10:18:05,377 WindowServer[342]: Surface test allowed updates after 11 attempts (44 ms)

**Comment by JanX2** [comment]
Looks like the first log entry has [something to do with NSNotificationCenter](https://news.ycombinator.com/item?id=10823897).

**Comment by garynunes** [comment]
Just upgraded from 3.0.9 to 3.1.0 (in application upgrade). Tried to launch. Much bouncing on the dock (about a minute) then icon stops bouncing but no appearance of Vienna on the desktop (icon still in the dock, no longer bouncing). Had to Force Quit. Downloaded directly from the site and tried again. Same behavior (both beta and final). Had to go back to 3.0.9.

Running 10.8.5 (Mountain Lion) if that helps.

Not much in the console logs but here it is:

3/14/16 6:54:10.252 AM Vienna[19058]: path: /Applications/Vienna.app/Contents/Frameworks/Growl.framework
3/14/16 6:54:10.255 AM Vienna[19058]: Using Growl.framework 2.0.1 (2.0.1)
3/14/16 6:57:22.053 AM com.apple.launchd.peruser.501[136]: ([0x0-0x146f46e].uk.co.opencommunity.vienna2[19069]) Exited: Terminated: 15
3/14/16 6:58:15.089 AM com.apple.launchd.peruser.501[136]: ([0x0-0x1473472].uk.co.opencommunity.vienna2[19078]) Exited: Terminated: 15
3/14/16 7:03:17.606 AM com.apple.launchd.peruser.501[136]: ([0x0-0x1478477].uk.co.opencommunity.vienna2[19099]) Exited: Terminated: 15
3/14/16 7:08:57.683 AM com.apple.launchd.peruser.501[136]: ([0x0-0x147f47e].uk.co.opencommunity.vienna2[19121]) Exited: Terminated: 15
3/14/16 7:09:15.122 AM Vienna[19136]: path: /Applications/Vienna.app/Contents/Frameworks/Growl.framework
3/14/16 7:09:15.125 AM Vienna[19136]: Using Growl.framework 2.0.1 (2.0.1)


Regards,
    Gary Nunes

**Comment by PacoH** [comment]
Having same problem. Icon bounces in Dock, icon not showing in cmd-tab application switcher, 0% CPU usage in Activity Monitor, no entries in system log. OS X 10.8.5 on Mac Pro 2010.
Did anyone test this or get it to work?

**Comment by josh64x2** [comment]
I'll try to replicate an in-app upgrade and see what happens

**Comment by PacoH** [comment]
Yeah well just FYI, that's the first thing I tried and it failed to upgrade. Just downloaded the app, closed the running app and never installed the update.

**Comment by josh64x2** [comment]
Hooray! I've been able to reproduce it using the in-app upgrade soooo now I can try to fix it :grin:

**Comment by josh64x2** [comment]
OK, so it has something to do with the preferences. if you delete the preferences .plist it will launch once but then you have to delete the .plist again. Getting there though!

**Comment by josh64x2** [comment]
@barijaona any ideas?

**Comment by barijaona** [comment]
@JanX2 wrote : 
> Looks like the first log entry [has something to do with NSNotificationCenter](https://news.ycombinator.com/item?id=10823897).

@josh64x2 wrote : 
> OK, so it has something to do with the preferences.

Don't know if this is related, but there is no `removeObserver` in SyncingPreferencesViewController's `dealloc`

**Comment by josh64x2** [comment]
It is related to one of the following keys:
`
    SUEnableAutomaticChecks
    SUFeedURL
    SUHasLaunchedBefore
    SULastCheckTime 
    SUSendProfileInfo
	LastRefreshDate
`
However I don't think it is the `SU*` Sparkle ones. I'll have a further look when I have time. My gut feeling is it is both the keys `LastRefreshDate` AND `SULastCheckTime` which leads me to think it's something to do with the way the date is being handled.

**Comment by jonesey95** [comment]
Just came here to say that this bounce-bounce-bounce is happening to me as well. Mac OS 10.8.5. The app eventually stops bouncing and can be seen in the Activity Monitor, but I never see the Vienna window and can't switch to the program. I can't Quit from Activity Monitor; I have to Force Quit.

**Comment by josh64x2** [comment]
@JanX2 were you using 10.8.5 when you reported this issue? Or does it just seem to be happening on 10.8.5 more than other version of OS X?

**Comment by garynunes** [comment]
Josh thanks for looking into this. Just a reminder (if needed) that the problem exists independent of the in-app (Sparkle) upgrade. After the in-app upgrade failure I also tried directly downloading both the 3.1.0 beta and final and both had the same problem.

Again, thanks.
    Gary Nunes

**Comment by josh64x2** [comment]
@JanX2 Sorry Jan but this issues has been essentially hijacked for the 10.8.5 locking issue :grin:

**Comment by josh64x2** [comment]
@garynunes and others on 10.8.5 could you please test this build?

[Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/179289/Vienna.zip)

**Comment by PacoH** [comment]
Works! Subscriptions intact with play status preserved. Thanks!

**Comment by jonesey95** [comment]
Version 3.1.1 Beta 1 :2063955: is working for me. I've had it open for a few hours now. No crashes, seems fine. Thanks.

**Comment by garynunes** [comment]
3.1.1 Beta 1 :2063955 successfully launched. I will use it for a while and report problems, if any. The only thing I've noticed so far is that all of my Wired feeds report an error when trying to refresh ... for the moment I'll assume that's an independent issue (maybe a problem with the feeds themselves).

Regards,
    Gary Nunes

**Comment by josh64x2** [comment]
OK thanks! I'll make sure it gets released soon.

**Comment by barijaona** [comment]
Fixed in 3.1.1
