### ISSUE TITLE
Implicit conversion loses integer precision

### ISSUE THREAD

**Issue by JanX2** [ViennaRSS/vienna-rss#577]
There is a huge number of warnings like this:

> /…/vienna-rss/src/StringExtensions.m:266:16: Implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int'

This is a remnant of ancient 32-bit Cocoa. Is there any interest in me fixing these? There is a workflow I have often used in the past to get cleaner 64-bit ports. The main problem is, that this requires touching a lot of lines and files. 

While I am at it, I could also convert the code base to use modern Objective-C.

Any thoughts?

**Comment by josh64x2** [comment]
@JanX2 we need to re-write most of Vienna. A lot of the code is out of date and the architecture makes it difficult to refactor and replace libraries such as ASIHTTP. If you think it is worth your time to fix any warnings or convert more of the code to modern Objective-C then we are more than happy to accept your contributions! 

I see from your GitHub page that you have a lot of cocoa/Objective-C experience. Do you have any other suggestions for Vienna?

**Comment by JanX2** [comment]
There is one little thing I have been wanting to do. Clicking the count of unread entries should optionally mark them all read. I need to dig up my notes about this. 

At some point in ancient times there actually already was some contribution of mine in the code base. Alas it appears to have been superseded. ;)

**Comment by josh64x2** [comment]
A lot of the code in the project has been superseded by newer versions of OS X and AppKit which is probably what happened to your contribution I'm afraid! There is a lot of code we could remove.

I was thinking about starting a re-write in Swift but I haven't had time to get far with it (and I love Objective-C more than Swift!).

**Comment by JanX2** [comment]
Same here for the time being. I still write most of my code in ObjC, but Swift 3.0 looks really promising. In my experience, the love comes when working in a language and I already see the glimmers of love for Swift. 

It’s really when interfacing with old ObjC code when Swift is most painful for me.

**Comment by josh64x2** [comment]
I'm no longer getting any `Implicit conversion loses integer precision: 'NSUInteger' (aka 'unsigned long') to 'int'` warnings in my code. Did you enable additional compiler warnings?

**Comment by JanX2** [comment]
I did not disable them. I am using the defaults in both Xcode and the project.

**Comment by josh64x2** [comment]
Oh yes I see now I get the warnings when I build for profiling.

**Comment by JanX2** [comment]
These should all be fixed by #579.
