### ISSUE TITLE
ASIHTTPRequest warnings

### ISSUE THREAD

**Issue by JanX2** [ViennaRSS/vienna-rss#580]
Can we somehow fix the warnings (format strings, etc.) in ASIHTTPRequest. Maybe with a private pod?

**Comment by josh64x2** [comment]
@JanX2 Replacing ASIHTTP with AFNetworking or AlamoFire (bridged to Objective-C) is high on our list of priorities. I'm having trouble with getting the asynchronous networking working reliably though. Do you have experience with that?

**Comment by barijaona** [comment]
Our calls to ASIHTTPRequest are in RefreshManager and GoogleReader. Could we directly use NSURLSession, rather than introduce a third party class ?

**Comment by josh64x2** [comment]
I think so but we would still have to change our logic to asynchronous as all of the synchronous stuff has been deprecated.

**Comment by barijaona** [comment]
This duplicates #344
