### ISSUE TITLE
Crash During first run Refesh.

### ISSUE THREAD

**Issue by dak180** [ViennaRSS/vienna-rss#581]
I have attached three crash reports for this; however I could not find the dSYM files for the build so they are not as useful as the could be.

[Crash Reports.zip](https://github.com/ViennaRSS/vienna-rss/files/172957/Crash.Reports.zip)

**Comment by JanX2** [comment]
de76487 from #579 may fix this. It did for me.

**Comment by barijaona** [comment]
The .dSYM can be found at https://bintray.com/viennarss/vienna-rss/vienna-rss/view#files

**Comment by barijaona** [comment]
@dak180 can you try with 3.1.1 ?

**Comment by dak180** [comment]
Still crashes:
[Vienna_2016-03-19-070007.crash.zip](https://github.com/ViennaRSS/vienna-rss/files/180763/Vienna_2016-03-19-070007.crash.zip)

**Comment by barijaona** [comment]
@dak180 How about version 3.1.2 ?

**Comment by dak180** [comment]
@barijaona still crashes in the same way; let me know if you want a new crash log.

Also, I had enough time to note that it is now considered an error if a feed (which is in all other ways valid) does not have any articles in it; this seems odd.

**Comment by barijaona** [comment]
@dak180 : I guess that you disabled the option to check new articles on start up ?
If not, to avoid the initial crash, ensure that you have an entry like this : 

	<key>CheckForNewMessagesOnStartup</key>
	<false/>

in the preferences file `~/Library/Preferences/uk.co.opencommunity.vienna2.plist`

Once this is done, do you see a difference between refreshing all feeds at once and refreshing only a few of them (by selecting them and using the contextual menu item) ?

Regarding empty feeds : they are generally caused by site editors' decision to set number of articles in feeds to 0 (to prevent access through RSS), so putting a warning seems accurate from a user point of view.

**Comment by dak180** [comment]
@barijaona I isolated the feeds that make Vienna crash; I had had a number of feeds from baen before they redid their website.  When that happened everything on the old site (including feeds) got redirected to http://www.baen.com/baenebooks (which is not a feed) and I had not changed them because they have not yet restored the feeds.  Any of these feeds, if fetched, will immediately cause Vienna to crash.

As to empty feeds you can also get them in feeds based on search criteria that currently match nothing which I would not consider something to bother the user about because they presumably know this already.

**Comment by barijaona** [comment]
Is the redirection temporary or permanent ? If temporary, can you send me an example URL ?

**Comment by dak180** [comment]
I think it is a permanent redirect: http://www.baenebooks.com/rssfeed.aspx?channel=news the url for the old news feed

**Comment by josh64x2** [comment]
Correct, curl says:
`HTTP/1.1 301 Moved Permanently`

**Comment by josh64x2** [comment]
@dak180 can you please try this build? 
[Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/192518/Vienna.zip)

**Comment by josh64x2** [comment]
So I've been able to find out the following:
It's an issue on 10.10 but not 10.11. Some part of our code is calling `[NSXMLElement setNamespace]` which is crashing. We don't call that method directly so I'm trying to step through the code and find out what does call it.

**Comment by josh64x2** [comment]
Stepping through is very annoying but I think the issue is in `ASIHTTP` and it happens somewhere around `[RefreshManager folderRefreshCompleted]'...
