### ISSUE TITLE
Cannot full-screen Youtube

### ISSUE THREAD

**Issue by joedj** [ViennaRSS/vienna-rss#584]
When I click the full-screen button on embedded Youtube videos, I get a little popup with the message "Full screen is unavailable.  Learn more".  The Learn more link opens up https://support.google.com/youtube/answer/6276924 in a new embedded tab.

I get the same message on a few different feeds, so I don't think it is anything the site owners have configured.

This was working fine until a few months ago.

**Comment by DavidMunch** [comment]
I see the same issue.

**Comment by barijaona** [comment]
I am afraid this is not a Vienna bug.
I filed a radar with Apple, no news yet.

http://www.openradar.me/radar?id=4810821087526912
https://github.com/barijaona/TrialFullScreen-radar18450829
