### ISSUE TITLE
Some crashes

### ISSUE THREAD

**Issue by DavidMunch** [ViennaRSS/vienna-rss#585]
Crash logs available here: https://dl.dropboxusercontent.com/u/32952/Vienna.zip

Nothing particular on my side, except that it always seem to happen upon a refresh of feeds.

Running OSX 10.11.3 on a 2011 27" iMac.

(On a side note - Cocoaforge seems to have some SQL error, so new threads can't be opened!)

**Comment by JanX2** [comment]
This probably is is a dupe of #581.

**Comment by barijaona** [comment]
Can you try the freshly released version 3.1.1 ?

**Comment by DavidMunch** [comment]
Will do and report back. The crashes come at random, so it may take some time before I can conclude that they don't happen. It is my impression that crashes are more prone after Vienna has been idle for an extended periode of time though.

**Comment by barijaona** [comment]
@DavidMunch can you try this version ? (7.5 Mb)

[Vienna-commit784944c.app.zip](https://github.com/ViennaRSS/vienna-rss/files/184640/Vienna-commit784944c.app.zip)

**Comment by barijaona** [comment]
@DavidMunch can you report 3.1.2 behavior with your config ?

**Comment by DavidMunch** [comment]
So far I haven't been having any issues with 3.1.2, but as reported above, the problem appear at random. But you may close the ticket, and I will report back if I see more crashes. :)

**Comment by DavidMunch** [comment]
Already got a crash. Machine had been sleeping over night, woke it up and Vienna was fine. Went to Vienna half an hour later, and refreshed all subscriptions, Vienna started and then crashed.
OSX10.11.4 + Vienna version 3.1.2 :86bfc3d:

Crash log:
https://dl.dropboxusercontent.com/u/32952/Vienna_2016-04-03-094045_Kakapo.crash

**Comment by barijaona** [comment]
Which layout are you using ?

**Comment by DavidMunch** [comment]
Report (I believe it is called, as I am on a danish system. Top one of the three selectable in the submenu).

[https://dl.dropboxusercontent.com/u/32952/Vienna.jpg]

**Comment by DavidMunch** [comment]
So far so good, 3.1.3 has been stable, where I would surely have seen a crash by now.

**Comment by DavidMunch** [comment]
I will close this, as I haven't had a single crash in almost 3 weeks now.
