### ISSUE TITLE
3.1.0: crash when selecting a particular article

### ISSUE THREAD

**Issue by phik** [ViennaRSS/vienna-rss#591]
Looks like a null pointer dereference, which I think separates it from #585 / #581

Crash dump attached: 
[Vienna_2016-03-17-210626_steamer.zip](https://github.com/ViennaRSS/vienna-rss/files/177893/Vienna_2016-03-17-210626_steamer.zip)

Seems to be 100% reproducible.

**Comment by barijaona** [comment]
Can you give me a feed URL with which you experience this crash ? I suspect it might be related to the notifications problems [pointed to by @JanX2](https://github.com/ViennaRSS/vienna-rss/issues/574#issuecomment-196308903) and I would like to test a workaround.

**Comment by phik** [comment]
The attached rss will crash when you import and then click on the article.

For extra fun, it also hangs Vienna when you try to delete the feed!

(It sure is irritating that github makes you zip everything up...)

[test.zip](https://github.com/ViennaRSS/vienna-rss/files/179307/test.zip)

**Comment by phik** [comment]
Interesting: it also crashes in 3.0.9, which I thought I'd been using before.  I guess not.

Doesn't crash in 3.0.8

**Comment by barijaona** [comment]
Fixed in 3.1.1
