### ISSUE TITLE
Vienna seems to forget the last selected folder /feed when closing & reopening the app

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#596]
This seems a change in behaviour since Vienna 3.1.1:

1. select (and remember which!) a folder or feed in the feed list
2. close / quit Vienna & reopen the app
3. take note of the selected folder or feed.

On my system, it is a different folder/feed than the one I choose above. Actually, it is the feed I had selected when I upgraded to 3.1.1 from 3.1.0 (Vienna’s Github feed for the curious).

3.1.0 and the various betas before all remembered the selected folder / feed.
OS X 10.11.3

**Comment by josh64x2** [comment]
Yup I can confirm this is affecting me too.

**Comment by neilt** [comment]
When I open a feed in a tab, then delete the tab, the tab goes away until the next time I start Vienna, then its "I'm Baaaaack" to quote the movie.  Can't figure out a way to make open tabs go away when restarting Vienna.  They keep coming back time after time.  Probably related to this issue, if not, let me know and I'll open a new issue.

**Comment by neilt** [comment]
Posted too soon, It seems Vienna was not notifying me of updates and 3.1.2 fixed my problem (probably the commit that fixed this issue) with tabs hanging around.  Thanks.

**Comment by barijaona** [comment]
Fixed in 3.1.2
