### ISSUE TITLE
Vienna should automatically defrag messages database

### ISSUE THREAD

**Issue by MacDisein** [ViennaRSS/vienna-rss#618]
Vienna should call VACUUM for it's internal database to reduce file size.
I have called this manually and the messages.db file size decrease from 25 MB to 13.5 MB

https://sqlite.org/lang_vacuum.html

**Comment by barijaona** [comment]
The necessary code is already there : https://github.com/ViennaRSS/vienna-rss/blob/master/src/Database.m#L479-L489

Just need to understand why this wouldn’t be called.

**Comment by josh64x2** [comment]
@barijaona it seems to only be called when you empty the trash.
We could do what was suggested over at objc.io and store the date of last_vacuum in `NSUserDefaults` and get Vienna to run it weekly.

**Comment by barijaona** [comment]
Apparently, there was at a time an attempt to introduce [a preference on emptying the trash](https://github.com/ViennaRSS/vienna-rss/blob/master/src/AppController.m#L624-L649). But currently,  `Database purgeDeletedArticles` is never called if the preference to move articles to the Trash is set to 'never'.

Related : issue #529

**Comment by josh64x2** [comment]
Interesting. Well I am currently reworking the preference panes to use base internationalisation and auto-layout so once I've done that I can easily add in a new option for emptying the trash. 
We should still think about a weekly vacuum though.

On a side note, why do our constants start with **MA**? We aren't Mike Ash... haha

**Comment by barijaona** [comment]
I'd prefer keeping it simple and stupid : purge on quitting app.

**Comment by josh64x2** [comment]
The problem with that is if you have a large database like I do, you delay the quitting process by a few minutes.

**Comment by Eitot** [comment]
@josh64x2 There are APIs to defer work to a separate background process.
https://developer.apple.com/library/content/documentation/Performance/Conceptual/power_efficiency_guidelines_osx/DiscretionaryTasks.html
