### ISSUE TITLE
RichXMLParser crashes in certain circumstances

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#619]
On Vienna 3.1.3, OS X 10.11, trying to subscribe to the attached file will crash Vienna
Initially reported on Twitter by user jagaland : https://twitter.com/jagaland/status/718067870035533824
Problem not present in 3.0.9
[nextlevel.xml.zip](https://github.com/ViennaRSS/vienna-rss/files/209355/nextlevel.xml.zip)

**Comment by josh64x2** [comment]
This looks like the problem is with `NSXMLDocument initWithData:`. We should have a better failure mechanism as well.

**Comment by barijaona** [comment]
Read the end of [this](http://inessential.com/2014/05/13/hard_and_soft_crashes)

The bad news is that try/catch is not a remedy to this particular problem.

**Comment by josh64x2** [comment]
We can exit early though. 
```
if (error) {
  if (error.code == 73) return NO;
  xmlDocument ...
}
```

**Comment by JanX2** [comment]
@josh64x2 The Apple documentation states that you should never touch the inout `error` in any way unless you have first checked that the method your were calling has returned `NO` or `nil`. I can dig it up in the docs, if you want me to. :)

**Comment by josh64x2** [comment]
@janx2 I read (well, quickly went over it) the apple error handling guide today and I didn't see that mentioned so yes please I would like a link! I know we should be checking the error domain too though.

I also read this: http://nshipster.com/nserror/

**Comment by JanX2** [comment]
[Error Handling Programming Guide](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/CreateCustomizeNSError/CreateCustomizeNSError.html)

> **Important:** Success or failure is indicated by the return value of the method. Although Cocoa methods that indirectly return error objects in the Cocoa error domain are guaranteed to return such objects if the method indicates failure by directly returning `nil` or `NO`, you should always check that the return value is `nil` or `NO` before attempting to do anything with the `NSError` object.
