### ISSUE TITLE
YouTube Channels w/ Unique Id's (Instead of User Names)

### ISSUE THREAD

**Issue by thinmanballad** [ViennaRSS/vienna-rss#621]
Using Vienna to filter youtube subscriptions. This works well until I try a channel that has not yet set user name. 

Example Working:
https://www.youtube.com/user/PewDiePie

Example Non Working:
https://www.youtube.com/channel/UCDXXzznSnQtctxZpEqstXvQ

Adding the latter channel in the latest release (mac, Version 3.1.3 :dade33d:) will actually cause a crash while refreshing. Once the application crashes, if 'refresh on open' is selected from preferences, you'll actually kick off a crash loop. The only way I could get around that, was to quickly open preferences and deselect the option. Which would then allow for the problem feed to be deleted.

**Comment by barijaona** [comment]
I couldn’t reproduce the crash you describe.

Through [this tip](https://support.google.com/youtube/answer/6224202?hl=en), you can induce that the RSS feed is https://www.youtube.com/feeds/videos.xml?channel_id=UCDXXzznSnQtctxZpEqstXvQ
