### ISSUE TITLE
User annoyance provoked by images embedded in webpages source code

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#627]
When one visits a webpage like [this one](http://www.zone-numerique.com/canon-powershot-g5-x-prix-tipa-2016-du-meilleur-appareil-photo-compact-expert.html), the following dialog appears each time the page loads / reloads.

![vienna__177_unread_](https://cloud.githubusercontent.com/assets/442030/14672557/46c53ed4-0701-11e6-81b9-920e69cb3639.jpg)

**Comment by mankoff** [comment]
May be related to #265 ?

**Comment by barijaona** [comment]
Yes, this has fixed #265 for data:text too.
