### ISSUE TITLE
Automatic folder jumping

### ISSUE THREAD

**Issue by marchyman** [ViennaRSS/vienna-rss#636]
I use an Unread Articles folder.   Sometime in the last month or two of updates the operation that occurs when the last article in that folder is read has changed.   Vienna used to do nothing when hitting the space bar or 'n' key at the end of the last article.   It now jumps from the Unread Articles smart folder to the feed that contained the last article.   Annoying.

Currently running a minor modification of 25d9dae50ea2c8d229ac68c551cfd375e0c27df2

**Comment by barijaona** [comment]
Could you please test my ArticleListView-Controller branch ? https://github.com/barijaona/vienna-rss/tree/ArticleListView-Controller

**Comment by marchyman** [comment]
On May 6, 2016, at 10:32 PM, Barijaona Ramaholimihaso <notifications@github.com> wrote:
> 
> Could you please test my ArticleListView-Controller branch ? https://github.com/barijaona/vienna-rss/tree/ArticleListView-Controller

Tested.   Works correctly... or at least the way it did a month or so ago.

Will you close the issue or do you want me to do that?

Marc

**Comment by barijaona** [comment]
I will close it once this branch has been reviewed and merged.

**Comment by marchyman** [comment]
This issue is back in v/3.1.5.

**Comment by josh64x2** [comment]
@marchyman can you please confirm which version of macOS you're using?
Thanks!

**Comment by marchyman** [comment]
On Jun 20, 2016, at 9:32 PM, Josh <notifications@github.com> wrote:
> 
> @marchyman can you please confirm which version of macOS you're using?
> Thanks!

10.11.5.  I compiled vienna using Xcode 7.3.1.

Marc

**Comment by barijaona** [comment]
Fixed in 3.1.6
