### ISSUE TITLE
NSInvalidArgumentException

### ISSUE THREAD

**Issue by jgelens** [ViennaRSS/vienna-rss#637]
I suddenly get the following error when starting the app:

> *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'
> abort() called
> terminating with uncaught exception of type NSException

any idea what the problem could be?

thanks

**Comment by barijaona** [comment]
Please send a crashlog (should be located in `~/Library/Logs/DiagnosticReports`)

**Comment by jgelens** [comment]
[Vienna_2016-05-06-124834.txt](https://github.com/ViennaRSS/vienna-rss/files/251989/Vienna_2016-05-06-124834.txt)

**Comment by barijaona** [comment]
Thanks. The causes are a bit unclear to me, but trashing your preferences file `~/Library/Preferences/uk.co.opencommunity.vienna2.plist` should fix the problem.

**Comment by jgelens** [comment]
Yep that fixed the issue. Thanks!

**Comment by barijaona** [comment]
You're welcome
