### ISSUE TITLE
Vienna's RSS refresh stopped working

### ISSUE THREAD

**Issue by JayBrown** [ViennaRSS/vienna-rss#640]
Approx. 24 hours ago Vienna's RSS refresh stopped working. Tried a reboot, installed the current Vienna version again, tried reindexing the database, tried changing some preferences, nothing works. When I add a feed in Safari, refresh works, so RSS seems to be fine system-wide, but when I try to add the same feed to Vienna, it doesn't work. (Vienna still displays all messages until 24 hours ago.) None of my feeds work anymore. Vienna's memory footprint is suddenly also very small: usually Vienna sometimes takes a couple of seconds to quit, but now it's immediate. Is this a known problem? If so, how can I repair it? ty.

**Comment by JayBrown** [comment]
Maybe this is the problem?
```
sqlite3 ~/Library/Application\ Support/Vienna/messages.db vacuum                                                   [09:27:21]
Error: database disk image is malformed
>>> elapsed time 13s
```

**Comment by JayBrown** [comment]
Deleted the .db, reimported subscriptions, and now it works (seems to work) again. But I have no idea what happened there.

**Comment by josh64x2** [comment]
hrm I wonder what caused it to corrupt the database in the first place.

**Comment by JayBrown** [comment]
I looked into system.log, but couldn't find anything. I vaguely remember trying to wake the Mac from sleep and only getting a spinning beachball after entering the account password, which is why I had to do a hard reboot. That was the first time this ever happened, and it was at some point during the last few days. Maybe that messed up the sqlite db. (?)
