### ISSUE TITLE
 'Share' menu item in a contextual menu does not work 

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#648]
Reported by user “sandstrom” [at cocoaforge](http://cocoaforge.com/viewtopic.php?f=18&t=26815#p139371) : the NSSharingService submenu appears in Webview's contextual menu, but does not work.

Other contextual menus items are OK, though.

**Comment by barijaona** [comment]
As explained [here](https://forums.developer.apple.com/thread/21282), having a `- (NSArray *)webView:(WebView *)sender contextMenuItemsForElement:(NSDictionary *)element defaultMenuItems:(NSArray *)defaultMenuItems` method disturbs the 'Share' submenu.

Apple bug ?

**Comment by Eitot** [comment]
Is this still a problem? I cannot confirm this.
