### ISSUE TITLE
No feed after 3.1.4 RC1 or RC2 upgrade

### ISSUE THREAD

**Issue by Julien-Elie** [ViennaRSS/vienna-rss#654]
Hi,

After upgrading to either 3.1.4 RC1 or RC2, I no longer have feeds available.  That is to say, Vienna opens and do not show any window; I only have the menu.
If I download Vienna.app 3.1.3 and replace 3.1.4 RC1/RC2 with it, and launch Vienna, my feeds reappear (the window permitting to read them appears).

I am surprised that no one else has already faced that behavior (I do not see any issue about that).  I do not know how to help reproduce that issue.

Is there something special to do after upgrade to 3.1.4?

Julien

**Comment by barijaona** [comment]
there shouldn’t be anything special after upgrade.

I suggest you : 
- backup your ~/Library/Application Preferences/Vienna folder
- from 3.1.3, do a database reindexation (from the Vienna menu)

**Comment by Julien-Elie** [comment]
I've just tried a database reindexation from 3.1.3.  The related item in the menu is then grey'ed (and cannot be done twice in a row).
Unfortunately, it does not solve the issue:  after upgrading to 3.1.4 RC2, I no longer see the window of the feeds.  Re-installing Vienna.app 3.1.3 makes the window appear.

**Comment by barijaona** [comment]
Quel mystère ! ;-)

Here, the menu item becomes available again once reindexing is finished (it may take a few minutes, depending of your database’s size).

What version of OS X are you using ?

Have you tried removing your preferences file ? (~/Library/Preferences/uk.co.opencommunity.vienna2.plist)

**Comment by Julien-Elie** [comment]
I'm using OS X 10.11.4 (and in a few minutes 10.11.5).

I've just tried to remove my preferences file, then installed 3.1.4 RC2 and... it worked!
I lost the order of my feeds but it's not a big deal to reorder.
Thanks for the hint!

Weird that my preferences file was working for 3.1.3 but not for 3.1.4 RC1/RC2...  If it can help, I can attach it to this bug report.

**Comment by barijaona** [comment]
Yes, please attach it. I doubt it could give some clues of the cause, but it might be interesting.

**Comment by Julien-Elie** [comment]
Here is the file.  I hope it can help to find the bug that appeared with version 3.1.4.

[uk.co.opencommunity.vienna2.plist.zip](https://github.com/ViennaRSS/vienna-rss/files/278139/uk.co.opencommunity.vienna2.plist.zip)

**Comment by dak180** [comment]
@barijaona actually this is happening to me too; so let me know if there is anything else that might be useful tracking this down.

**Comment by barijaona** [comment]
If I use @Julien-Elie 's preferences file, I get these messages in the console : 

````
2016-05-24 06:52:37.824 Vienna[9191:1034505] -[NSTaggedPointerString canGoBack]: unrecognized selector sent to instance 0x3115
2016-05-24 06:52:37.825 Vienna[9191:1034505] -[NSTaggedPointerString canGoBack]: unrecognized selector sent to instance 0x3115
````

**Comment by barijaona** [comment]
These 'unrecognized selector' messages appear when Vienna adds the toolbar  https://github.com/ViennaRSS/vienna-rss/blob/master/src/AppController.m#L462
