### ISSUE TITLE
Vienna does not scroll to top if list of articles is scrolled down and then switches to different feed

### ISSUE THREAD

**Issue by ruurd** [ViennaRSS/vienna-rss#658]
Vienna does not scroll to top if list of articles is scrolled down and then switches to different feed.

Read a feed with multiple articles until the list of articles scrolls up 
Use next to jump to the next feed

expected: the selection is put at the top article and the list is scrolled down to move selection into view
actual: the selection is put at the top article but selected article is not scrolled into view

**Comment by barijaona** [comment]
Confirmed here : http://forums.cocoaforge.com/viewtopic.php?t=26842&p=139450

**Comment by barijaona** [comment]
Not completely fixed in 3.1.5. See http://cocoaforge.com/viewtopic.php?f=18&t=26842#p139538

**Comment by barijaona** [comment]
Fixed by commit b31d75d6d4315f84ecc4de04a76711f3bfdf536c

**Comment by barijaona** [comment]
@ruurd, can you verify if 3.1.6 fixes this ?

**Comment by ruurd** [comment]
Works now. Thank you.
