### ISSUE TITLE
OS X UI bug after switching resolution & input device

### ISSUE THREAD

**Issue by testnotcode** [ViennaRSS/vienna-rss#659]
I use a MacBook Pro retina and switch between typical laptop use on the built-in screen and an external monitor and bluetooth trackpad with lid closed. When I make this switch, scrolling in the articles pane becomes 'jumpy' and acts as if I am actively trying to scroll horizontally as well as vertically. It seems like the pane changes it's boundaries to allow for a few extra pixels of horizontal scrolling that don't actually exist. Quitting and restarting Vienna fixes this issue until the next time I switch to the 'opposite' configuration.

I found it impossible to get a screen grab of this because the jumpiness happens over time and a screen shot is a single frame. Nonetheless I will include this image where the column title Subject is now rendered blurry as an after effect of this horizontal movement.

I use no special 3rd party input device drivers, USB extensions, or other modifications. This is essentially a stock OS X install.

OS X 10.11.5
Vienna Version 3.0.9 :22b3ce2:

![screen shot 2016-05-27 at 10 57 29 am](https://cloud.githubusercontent.com/assets/19611236/15611934/ab916354-23fa-11e6-8a70-77abc43c8a69.png)

**Comment by josh64x2** [comment]
Hrm I might be able to finally test this out.

**Comment by josh64x2** [comment]
@testnotcode do you still have this issue? I haven't been able to reproduce it :(
