### ISSUE TITLE
Version 3.1.4: headline table not scrolled when switching feeds

### ISSUE THREAD

**Issue by Hopper262** [ViennaRSS/vienna-rss#664]
I use the Vertical layout, and navigate mostly using the N or Space keys. Since upgrading from version 3.1.2 to 3.1.4, when I move from one feed (or folder) to the next using those shortcuts, the middle pane no longer scrolls to bring the selected article into view.

My Order rules place unread articles at the top of the article list. As I read articles within one feed, the middle pane scrolls down to keep the selected row near the middle of the display. When I exhaust one feed and go on to the next, the pane does not scroll back up to the top, so the current selection is not visible afterward. My workaround is to press the Up and Down arrow keys: switching the selection manually forces the table to scroll appropriately.

**Comment by barijaona** [comment]
Have you tried the 3.1.5 Release Candidate 1 ? https://github.com/ViennaRSS/vienna-rss/releases/tag/v%2F3.1.5_rc1

**Comment by Hopper262** [comment]
3.1.5 RC 1 seems to fix the issue completely. Thank you very much!
