### ISSUE TITLE
InoReader not syncing

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#671]
Using Version 3.1.4 :6ea6f87, I've been unable to refresh any of my feeds through InoReader for the last 12+ hours.  Spinning refresh icon appears next to feeds, but they never refresh.

Activity window shows Connecting to Open Reader server to retrieve (url) indefinitely.

**Comment by barijaona** [comment]
Have you checked if the credentials in the Preferences are still present ?

**Comment by tonycpsu** [comment]
They are present, yes.

**Comment by tonycpsu** [comment]
Removing messages.db fixes the problem, but I have to manually reorder all of my feeds.  Is there something in the messages.db that could be corrupted or some kind of locking that I could fix?

**Comment by barijaona** [comment]
I guess all your feeds are synced via an OpenReader server ?

**Comment by tonycpsu** [comment]
Yes, InoReader...

**Comment by barijaona** [comment]
Inoreader seems to provide feeds list in chronological order of creation ; this is why the feed order is broken when you let Inoreader drive the recreation of feeds.
You can try exporting your initial subscriptions list from Vienna, and reimport it in a fresh database. In between, have a look at the OPML file in a text editor to check if it seems OK.

**Comment by tonycpsu** [comment]
Well, I ended up just reordering them manually -- I'll try exporting/importing OPML if this happens again.  I'm more concerned about whatever's causing the sync to stop working until messages.db is removed.

**Comment by barijaona** [comment]
Did you try reindexing the database ?

**Comment by tonycpsu** [comment]
No, I didn't even know that was an option, but I see it there in the application menu now.

I'll try that if this happens again.  Thanks.

**Comment by tonycpsu** [comment]
This happened again.  I tried the "remove database, import OPML, re-sync" procedure but this seems to disconnect the feeds from InoReader -- it only pulls down 15-25 articles per feed, with none of my read/marked status.  I tried toggling openreader on/off to get it syncing through InoReader but it wouldn't work.

To get the feeds syncing through InoReader, I have to remove the database again, then sync without first importing the OPML.  This fixes the feeds, gives me my flagged articles, etc. but then my feeds are out of order.  Trying to import the OPML file after this doesn't fix the ordering, so I'll have to manually re-order them all again.

I forgot to save a copy of the messages.db this time.  Is there an email address I can send the file for analysis next time this happens?

**Comment by barijaona** [comment]
barijaona at gmail dot com

**Comment by barijaona** [comment]
Did it reoccur ?

**Comment by tonycpsu** [comment]
No, things have been quite stable recently, aside from some unread counts being wrong that seems to have been fixed in a recent update.  I'll reopen if I see this again in the future.
