### ISSUE TITLE
Restore full screen state when Vienna launches

### ISSUE THREAD

**Issue by Hopper262** [ViennaRSS/vienna-rss#672]
I run Vienna full screen in its own Space. When I quit and relaunch Vienna (which happens on a restart or a version update), it would be nice if it reopened the main window into a Space, instead of opening on the desktop and requiring me to manually click the zoom button.

**Comment by Eitot** [comment]
This behaviour is automatic for NSWindowController (which we currently don’t use). This requires some refactoring, as the main window is currently referenced 100+ times in AppController and elsewhere.

**Comment by josh64x2** [comment]
Ohh good to know - getting a proper NSWindowController is high on the list of priorities for me.

**Comment by Eitot** [comment]
#930 should have solved this.
