### ISSUE TITLE
v3.1.4 has stopped updating feeds. Possible database issues?

### ISSUE THREAD

**Issue by gawdalmighty** [ViennaRSS/vienna-rss#674]
I can't log in to your support forum because it keeps asking a security question about who made the software?
I have no idea. And I can't find this information anywhere?
What the hell?? How does anybody ever manage to sign up to those forums???
Anyway, Vienna has stopped working. It hasn't updated any of my feeds since the end of April but it just keeps telling me everything is up to date. No errors, except of a few feeds. No indication anything's wrong. Just no new content.
And it won't move any of the  content to the trash no matter what timeframe I set for that in preferences.
What on earth is going on? Why has Vienna stopped working and why just for me?

**Comment by barijaona** [comment]
Which version are you runnning ?

**Comment by gawdalmighty** [comment]
3.1.4

**Comment by barijaona** [comment]
I am afraid your database got damaged. Try the « Vienna -> Reindex database » menu item.

**Comment by gawdalmighty** [comment]
I’ve tried that several times and restarting. Still nothing.

**Comment by JanX2** [comment]
Maybe the database file is just locked or read-only for some reason.

**Comment by gawdalmighty** [comment]
Maybe it is.

So, no info about what to do about this if it’s the case then???

**Comment by barijaona** [comment]
Two options : 
- restart anew : export your subscriptions, quit Vienna, remove the database (at `~/Library/Application Support/Vienna/messages.db`), relaunch Vienna and reimport your subscriptions
- upload your database somewhere and send me a link (barijaona at gmail dot com) in order to allow me to investigate

**Comment by gawdalmighty** [comment]
OK well looks like this is the problem. There is no folder entitled “Vienna" at ~/Library/Application Support/

Is there any way to force the program to rebuild or create this?

**Comment by barijaona** [comment]
??? But you see your subscriptions list when you launch Vienna ?

Please zip and upload your preferences file (it should be in `~/Library/Preferences/uk.co.opencommunity.vienna2.plist`)

**Comment by gawdalmighty** [comment]
Yes I do. There is also no file in that location either.

**Comment by barijaona** [comment]
Are you sure you are not confusing `~/Library`(in your home directory) and `/Library` (at the root of your hard disk) ?
The easiest way is to use Finder's ‘Go to Folder…’ menu item (or the Command+Shift+G keyboard shortcut)

**Comment by gawdalmighty** [comment]
No. I’m not sure of that but I still can;t find the other folders you’re talking about.

But if you mean there should be a folder called “Library” under my username then there isn’t.

Searching for “Library” as you suggest ONLY brings up a folder on my Hard Drive.

**Comment by gawdalmighty** [comment]
OK, the Library folder DOES exist, but it is hidden I the latest versions of Mac OS.
http://osxdaily.com/2014/12/16/show-user-library-folder-os-x-yosemite/

Is this maybe the reason my database has stopped working?

**Comment by marchyman** [comment]
On Jun 11, 2016
> 
> But if you mean there should be a folder called “Library” under my username then there isn’t.

It’s there.  Apple hides it. Open a finder window.  Open the Go menu.   Hold down the option key.   Library will be added as a choice as long as the option key is held.  Select it.

**Comment by josh64x2** [comment]
Also having the Library folder hidden doesn't impact the operation of Vienna, it is only hidden from the user interface and not from code. Did you manage to resolve this @gawdalmighty ?
