### ISSUE TITLE
Unable to mark (some) article as read

### ISSUE THREAD

**Issue by phiw13** [ViennaRSS/vienna-rss#678]
Version 3.1.5 RC 2 :426005d:

This is something really random, but happens at least once a day (usually when Vienna has been running for quite few hours).

I select an article in a smart folder (e.g. ‘today’), start reading. But it doesn’t get marked as read. Going to the feed it self and selecting the same article doesn’t mark as read either. What is more weird, if I then go to another feed or folder, then return to the feed with the still-not-marked-read article, all articles in that feed have disappeared.

Sometimes it happens with just one article / one feed, sometimes it affects more than one feed. And, as I said, it only happens at random moments.

Quitting and relaunching Vienna resolves the issue. No data loss.

Console logged this:

```
6/15/16 10:06:54.909 PM Vienna[2935]: Bug retrieving from cache in folder 129 : after 0 insertions of 2, guid http://www.opera.com/blogs/desktop/?p=2165
```

**Comment by barijaona** [comment]
Can you verify if the issue is still present in version 3.1.5 ?

**Comment by phiw13** [comment]
Sure, now testing. I’ll wait a couple of days to be certain given how random that issue cropped up here.

**Comment by phiw13** [comment]
Unfortunately, it doesn’t seem to be (fully fixed):

Today, I clicked on a folder (“Apple”) containing 3 feeds from the fruit company. The badge on the folder noted 2 unread articles. I clicked on both - then noticed none were marked read. I then opened the folder, clicked on the feed to see the articles (again), but it was not possible to mark them as read - the articles themselves lost their blue dot, the feed still had the unread article count.

affected feed : https://rss.support.apple.com/

I noticed it displayed an explanation mark, Vienna Activity window notes:
(error: no articles in feed)
Connecting to https://rss.support.apple.com/
587 bytes received


Console logs the following, the moment I click on the feed itself:

```
6/21/16 10:32:27.794 AM Vienna[10044]: Bug retrieving from cache in folder 73 : after 0 insertions of 23, guid https://support.apple.com/en-us/HT201472
```

I then (manually) refreshed (cmd + R)
after refreshed was completed, I again accessed the affected feed, but the 2 articles remained unread.

while refreshing, I noticed multiple (9) -- this one seem to happen on every refresh :

```
6/21/16 10:39:50.372 AM Vienna[10044]: *** Assertion failure in -[NSXMLDocument insertChild:atIndex:], /Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1259/XML.subproj/XMLTypes.subproj/NSXMLDocument.m:805
```

followed by (2)

```
6/21/16 10:40:07.945 AM Vienna[10044]: CoreAnimation: warning, deleted thread with uncommitted CATransaction; set CA_DEBUG_TRANSACTIONS=1 in environment to log backtraces.
```

followed by (many…)

```
6/21/16 10:40:15.986 AM Vienna[10044]: Uncommited CATransaction. Set CA_DEBUG_TRANSACTIONS=1 in environment to debug.
```

The last 2 only happened after the issue under discussion occurred.

**Comment by phiw13** [comment]
Status update since my last comment above: Vienna has been running for 3 days without quitting it (twice) and without this issue appearing. Until today that is. Trying to mark an article as read failed (in my “today” smart folder). Console did’t log anything relevant at that moment. 

One note though: my iMac was running under heavy load and a bit sluggish (ahem); Spotlight in particular was slooooow (smart folders still use Spotlight under the hood, right?).

**Comment by barijaona** [comment]
Vienna's smart folders are not using Spotlight.
Please, if the problem reappear, launch Activity Monitor and take some screenshots, especially of the "memory" tab.

**Comment by phiw13** [comment]
> Vienna's smart folders are not using Spotlight.

Ok. my bad memory.

So I haven’t seen this issue since my last comment above. Until this morning. I was arrowing down the list in my “today” smart folder, articles being as read on the way. Later I noticed that one article was still in the list, while I’m sure it should not be there – I actually read the article… the slight time delay before an article is marked read (set in preferences) would surely have had no effect there.

> Please, if the problem reappear, launch Activity Monitor and take some screenshots, especially of the "memory" tab.

Well, this morning it would not have been very useful (I only noticed the issue much later). I can tell you though, this time the iMac was under a light load (few apps running: Safari, with only a blank tab, Mail, Messages, Colloquy). I have a menubar widget that reports memory status and CPU load, both were very low. But then, who knows, this is an old machine after all, and perhaps one of the many processes that the OS runs cause a brief “disturbance in the force”?

Anyway, since your first fix, the issue is much much less frequent than it originally was

**Comment by barijaona** [comment]
Can you provide us with a screenshot of the General preferences ? And do you use an OpenReader reader ?

**Comment by phiw13** [comment]
> And do you use an OpenReader reader 

No; never have.

![vienna-prefs](https://cloud.githubusercontent.com/assets/8944809/16677627/b8f7d08a-4512-11e6-845e-962d3d1240a8.png)

**Comment by phiw13** [comment]
I haven’t been able to reproduce the issue any more running the latest beta build: Version 3.1.6 RC 2 :dad2429:

**Comment by josh64x2** [comment]
OK thanks for the update!
