### ISSUE TITLE
Subscriptions disappeared

### ISSUE THREAD

**Issue by acrudolph** [ViennaRSS/vienna-rss#679]
I am using a Mac computer (OS X 10.11.5) with Vienna 3.1.4. When I restarted by computer and went to Vienna, none of my subscriptions appear.

I synch with FeedHQ so I checked the preferences to make sure that it was set up properly. I tried to reindex the database in Vienna without success.

I went to FeedHQ to make sure my account is current (which it as) and I could see my RSS subscriptions in my dashboard. I use the FeeddlerRSS app on my iPad, and the RSS synching with FeedHQ is working.

I reinstalled Vienna on my computer and still no joy.

Help!

**Comment by acrudolph** [comment]
I should also mention that I am not getting any error message when I start up Vienna or click the refresh button. There's nothing there. Also, I installed nothing on my computer that changed Vienna from working to all of a sudden not having any subscriptions.

**Comment by dsilhavy** [comment]
Same problem for me on MAC OSX , already tried to use the development version 3.1.5, but same problem. Reinstalling is not helping either.

**Comment by rgrg1** [comment]
I have the same exact problem.  Mac OS X 10.11.6 El Capitan with Vienna 3.1.5
I went to read my feeds and they were all gone, including the Vienna subscription.  Also couldn't get into Vienna Forum.  Said I was answering the question wrong about who makes Vienna.  If it won't work is there anyway to get a list of my subscriptions?  I can't remember all of the names of the feeds.  Please help.

**Comment by acrudolph** [comment]
I never did find the solution to this problem, leaving Vienna totally unusable. Very frustrating!

**Comment by josh64x2** [comment]
Sorry that this issue has gone on for so long. Can you please try [Vienna 3.1.6 RC2](https://github.com/ViennaRSS/vienna-rss/releases/download/v%2F3.1.6_rc2/Vienna3.1.6_rc2.tar.gz) and let me know if this solves your problem?

**Comment by acrudolph** [comment]
It still doesn’t work :(

**Comment by josh64x2** [comment]
OK, so FeedHQ has all of your subscriptions still and none of them are showing in Vienna is that right? I will create a FeedHQ account for testing.

**Comment by acrudolph** [comment]
Hi Josh,

That is correct. It was all working wonderfully and then it just topped. I’ve checked my FeedHQ account and it’s still active. I used Feedler HQ for my iPhone and the syncing still works. I’ve checked the preferences in Vienna and it’s all good. I’ve reinstalled Vienna countless times. I’ve reindexed the database in Vienna. I’ve run out of things to do. I can’t even set up a local feed.

Thanks for looking into this.

Adrienne

**Comment by josh64x2** [comment]
That's OK!
Are you able to send me a copy of your Vienna database and preferences? You can find them in `~/Library/Application Support/Vienna/`. It would help a lot 😄

**Comment by acrudolph** [comment]
I can’t find a library folder. When I do a search on the computer of ‘vienna’ the only  thing that comes up is the Vienna application and no folder.

I forgot to mention in my emails that I’m using a Mac computer  OS X El Capitan Version 10.11.6. 

Please advise.

Thanks again for your help in this matter. I would love to return to Vienna!

Kind regards,

Adrienne

**Comment by josh64x2** [comment]
I've made a screen capture video to show you how to create the messages.db.zip file and the vienna preferences file. https://app.box.com/s/x9jbaj6fcv8a59na5agc18oek3nu3r2f

Hopefully it helps :)

**Comment by josh64x2** [comment]
@acrudolph Did the video help you find the messages.db file?

**Comment by rgrg1** [comment]
My husband did something, I'm not sure what and got it to work again. Thank you.

**Comment by josh64x2** [comment]
@dsilhavy are you still having this issue?

**Comment by acrudolph** [comment]
Hi Josh,

I haven’t had a chance to watch it. Will do so this evening.

Best wishes

Adrienne

**Comment by dsilhavy** [comment]
@josh64x2 Actually deleting this folder ~/Library/Application Support/Vienna/ worked for me. Looks like the database was corrupt. Still I think it might be useful to add that to the UI, as reinstall did not work for me. Thanks for your help

**Comment by rgrg1** [comment]
Lost subscriptions again.  Went into Time Machine and found the messages.db and restored.  I would love for it to be stable though because if I don't catch it in time, I lose days of subscription feeds.

**Comment by barijaona** [comment]
I will try to add more transaction controls in future versions of Database.m, in order to prevent those problems to appears.

**Comment by barijaona** [comment]
Closing this because it has been so long…
Probably correctly fixed by 3b3ecc1 and f9be01b (which should be incorporated in version 3.5.1)
