### ISSUE TITLE
Marking last article read changes folder selection

### ISSUE THREAD

**Issue by sjmills** [ViennaRSS/vienna-rss#681]
I keep a smart folder named "_Unread Articles" at the top for all unread articles. That's the folder I keep selected. After spacebarring through all articles and the last one gets marked as read, Vienna 3.1.5 is now changing the selected folder from that one to the parent folder of that last article. I believe it started doing this with the previous release. It was fine a couple weeks ago.

It's pretty annoying. Sure it only happens once a night, but it happens every night and I shouldn't have to reselect my preferred folder every night.

**Comment by marchyman** [comment]
That sounds like a dup of #636 which was just re-opened.

**Comment by barijaona** [comment]
Fixed in 3.1.6
