### ISSUE TITLE
Endless loop on Skip folder, when no articles are unread

### ISSUE THREAD

**Issue by ehlers** [ViennaRSS/vienna-rss#696]
Version 3.1.6 RC 1 :1cdc5ae:

When no articles are unread and I activate the "Skip folder" function Vienna gets into an endless loop. It gets unresponsive and the spinning beach ball is shown.

I managed that in two ways:
- Use the hot key shift-cmd-S, when no articles are unread
- When only one article is unread and I use the "Skip folder" button to go to it. After a short delay that article is marked read, but the "Skip folder" button remains active. When I now push the "Skip folder" button, it gets into the endless loop.

**Comment by josh64x2** [comment]
Closed by PR #697
