### ISSUE TITLE
articles duplicated on refresh

### ISSUE THREAD

**Issue by sebkirche** [ViennaRSS/vienna-rss#704]
Hi,

I have an issue with only one of my subscribed feeds: on every automatic refresh all subjects are duplicated, resulting after some time with hundreds of articles, while there is currently only 10 articles available when adding the feed in Vienna.

The feed's url is http://rosasm.freeforums.org/feed.php it's a phpBB forum where I have an account but it is not filled in the feed's authentication info. 
Feed validator tells it is a valid Atom 1.0 feed.

There might be an issue with feeds times, but I did not get where. The case is that on immediate refresh there is no problem, but with automatic refresh (or manual refresh at a later time) the articles get duplicated.

**Comment by josh64x2** [comment]
Adding note from [forum message](http://forums.cocoaforge.com/viewtopic.php?t=26885&p=139602#p139602) that system is 10.11.6 and current Vienna is Version 3.1.6 RC 2 :dad2429:

**Comment by josh64x2** [comment]
Hi,

I've added this feed to my subscriptions and I'll keep an eye on it to see if I get duplicated messages too.

Thanks!

**Comment by josh64x2** [comment]
OK I've started getting the duplicated messages so hopefully will be able to sort this out.

**Comment by josh64x2** [comment]
OK it looks like the issue is with the feed itself. Yes it is a valid feed, but the `<id>` for each post keeps changing. Here is an example of what it looks like in the database.
```
http://rosasm.freeforums.org/viewtopic.php?t=244&p=513#p513|Bug Report • Lea problem
http://rosasm.freeforums.org/viewtopic.php?t=244&p=513&sid=fd76e1aa9c3b07cee52a68f520d99247#p513|Bug Report • Lea problem
http://rosasm.freeforums.org/viewtopic.php?t=244&p=513&sid=e043ce3f384e3abc1d244a48a9b53c34#p513|Bug Report • Lea problem
http://rosasm.freeforums.org/viewtopic.php?t=244&p=513&sid=6368b92d4769cbeaff980f73951ed17a#p513|Bug Report • Lea problem
http://rosasm.freeforums.org/viewtopic.php?t=244&p=513&sid=fb3b74f610bdcc58c734576fd4608078#p513|Bug Report • Lea problem
http://rosasm.freeforums.org/viewtopic.php?t=244&p=513&sid=33ffcbbd2e7ba7b05e29ac77cfe06cad#p513|Bug Report • Lea problem
http://rosasm.freeforums.org/viewtopic.php?t=244&p=513&sid=0ae743abf433cd0da8d2ad17738eccd0#p513|Bug Report • Lea problem
```

The `<id>` is the bit before the `|` symbol, and the title follows after. You can see they all have the same title and first part of the `<id>` is the same, but the `sid=` part of the `<id>` keeps changing.
