### ISSUE TITLE
Updated danish localization per 3.1.6rc2

### ISSUE THREAD

**Issue by DavidMunch** [ViennaRSS/vienna-rss#709]
As per title. 

Attached updated da.lproj folder.
[da.lproj.zip](https://github.com/ViennaRSS/vienna-rss/files/473257/da.lproj.zip)

**Comment by barijaona** [comment]
Thanks for this.
Could you also adapt Interfaces/Preferences/da.lproj ?

I also noticed some untranslated strings near the end of lproj/da.lproj/Localizable.strings

**Comment by DavidMunch** [comment]
Ah yes, I see I missed several strings. Will do them this weekend.

I am unsure as to where I locate Interfaces/Preferences/da.lproj?

**Comment by josh64x2** [comment]
https://github.com/ViennaRSS/vienna-rss/tree/master/Interfaces/Preferences/da.lproj :)

**Comment by DavidMunch** [comment]
Thanks a ton!

**Comment by DavidMunch** [comment]
Updated Localizeable.strings:
[Localizable.strings.zip](https://github.com/ViennaRSS/vienna-rss/files/477543/Localizable.strings.zip)

How do I edit the interfaces/preferences/da.lproj files, as I am not very familiar with Github? I edited one .strings file, which was created on a separate github branch, which is fine I guess. But the next .strings file i tried to edit opened a file browser instead? And the .xib files can't be downloaded (At least, I did that, but Xcode wouldn't recognize it) and I assume it is wrong to edit them directly on the webpage, as it is very unmanageable. So all in all, I assume I am overlooking something!

**Comment by josh64x2** [comment]
You shouldn't need to edit the xib files, I will run a script which reads in the .strings files and generates new xibs from that. 
We are hoping to improve this process but there is so much that needs doing for poor Vienna :(

**Comment by barijaona** [comment]
@josh64x2 , I am interested in knowing more about the scripts you use.

Anything interesting might be useful in the `configs/scripts` folder

**Comment by barijaona** [comment]
Incorporated in 3.1.6
