### ISSUE TITLE
Vienna interpret the content of some texts as script instead of displaying them

### ISSUE THREAD

**Issue by thongngo** [ViennaRSS/vienna-rss#710]
Hi Team,

I found a XSS vulnerability in Vienna 3.1.5 and lower version.

Vienna parses the html content and executes the javascript code without sanitizing (even the original website has already encode html special chars - by htmlentity function, for example).

![vienna_xss_1](https://cloud.githubusercontent.com/assets/5011906/18623101/64e5535c-7e63-11e6-928f-fcf416716560.png)

<img width="726" alt="vienna_xss_2" src="https://cloud.githubusercontent.com/assets/5011906/18623102/6b6894aa-7e63-11e6-9bd4-265e366be857.png">

<img width="441" alt="vienna_xss_3" src="https://cloud.githubusercontent.com/assets/5011906/18623110/73df6546-7e63-11e6-9146-ccd8d883c112.png">

**Impact**: Vienna users who use social network channels where attacker can post a malicious script (even already encoded via htmlentity function) contained a XSS payload that could redirect the Vienna Users to a malicious website to steal sensitive information or even take control the Social Network’s account,…

**Reproduce**:
1. Create a new subscription: http://blog.portswigger.net/feeds/posts/default
2. Click on the post with title "Adapting AngularJS Payloads ...."  (don't worry, it's harmless)
3. A pop-up with "1" should be prompted (XSS payload executed)

Thanks Team

**Comment by thongngo** [comment]
Just saw the 'Enable javascript in the internal browser' function.
If it was enabled by default, it's quite dangerous.

**Comment by josh64x2** [comment]
Hi @thongngo, thanks for reporting this! Do you have any ideas on how we should fix this?

**Comment by walterdolce** [comment]
> Do you have any ideas on how we should fix this?
Hi @josh64x2, I would recommend to have this option disabled by default upon installation. Perhaps it could also be explained why such functionality has been disabled.

**Comment by barijaona** [comment]
From my point of view, this is not really a "vulnerability".
Apple's Webview security features remain active, so if your macOS version has all current patches, nothing really dangerous could happen.
What is wrong here is that the blog text gets unescaped, therefore gets interpreted by the web browser. This needs a fix.

**Comment by josh64x2** [comment]
That's a good point @barijaona

**Comment by barijaona** [comment]
Fiixed in 3.1.7
