### ISSUE TITLE
Ability to import/export via command line

### ISSUE THREAD

**Issue by walterdolce** [ViennaRSS/vienna-rss#711]
Hi all, this is more a question rather than an issue.
Is it possible to import/export the subscriptions with Vienna on the command line?

More info regarding this question can be found [here](http://forums.cocoaforge.com/viewtopic.php?f=18&p=139647&sid=2a3a6468e96499cfa592db93bd692b7f#p139647).

Thank you very much.

**Comment by josh64x2** [comment]
Hi @walterdolce I would say it is not possible at the moment, however it wouldn't be difficult to implement. Let me have a look at it tonight for you 😄

**Comment by walterdolce** [comment]
Thanks @josh64x2 !
I think that would be great for users like me which use the app in multiple places and want . I look forward to hearing your thoughts.
