### ISSUE TITLE
Ability to share state of read articles across Vienna installations

### ISSUE THREAD

**Issue by walterdolce** [ViennaRSS/vienna-rss#712]
Hi, is there a way to import/export the state of the articles I've read?

Example:
- I use Vienna in laptop X and laptop Y
- I use laptop X and receive a notification for a new article "Men go to Mars". Total articles to read counter is at 1.
- I read the article on laptop X. Total articles to read counter is at 0.
- I close laptop X and go home.

Later on..
- I open laptop Y at home.
- I receive notification for a new article "Men go to Mars"...but I've already read this article on laptop X..

Hope the example above explains it. I use Vienna on various laptops and I currently import/export my subscriptions via a couple of AppleScript scripts (while I wait for #711 to allow me to do so differently). But every time I change my subscriptions I receive the same notifications, so I have to "Mark all as read" all the time.

Thank you very much.

**Comment by josh64x2** [comment]
Hi! 
Hrm no there isn't, but it's a good idea. Let's set this as a feature request and see if other people upvote it.

**Comment by DavidMunch** [comment]
Syncing with an Open Reader Server would take care of your issue.

**Comment by barijaona** [comment]
I agree with @DavidMunch. There are some ad supported OpenReader servers. I'll close the issue for now.
