### ISSUE TITLE
Smart Folder Filter Issue

### ISSUE THREAD

**Issue by thinmanballad** [ViennaRSS/vienna-rss#714]
version 3.1.6 RC 2
After adding a group of 'subject contains' filters to a smart folder, I added one 'folder is not' filter. Then when I clicked on the smart folder, I receive the same results as my Unread Articles smart folder.

Removing the 'folder is not' filter from the end repopulates the smart folder with the correctly filtered results. 

Just a couple general questions.
Are there plans to hone the 'Search All Articles' control? I think the inclusion of folder/smart folder filters with possible egrep functionality could add some value.
Also, while on the topic, hows about some regex inside the filter text area? I could write a feature request if that hasn't been done. This is an **amazing** and powerful tool, big thanks to everyone!

**Comment by thinmanballad** [comment]
One other thing related to smart folder conditions. I have folders with a **lot** of conditions. If the dialog could be at max the height set by the user with a scroll bar, it would be perfect. As it is now, once my list grows, the dialog grows over application (like a tongue sticking out) and my filter use is pretty much limited to the size or resolution of monitor.

**Comment by barijaona** [comment]
I could not reproduce the first problem. Are you sure you correctly set the "AND" condition ?

**Comment by thinmanballad** [comment]
Hey, thanks for the response! I'm using the mac Version 3.1.8 :1bc6bc3:
![This screen shot possibly uploaded and can show...]()
* I created a new smart folder. 
* toggled match selector to 'Any' 
* Added a 'Date Is' Today filter.
* Clicked '+' sign and added 'Folder Is Not' reddit filter.
The arrows point at reddit articles that are still in the feed, even though they're in the reddit folder and should be filtered out.

Would selecting 'any' be the same as indicating 'AND' conditions? Otherwise, I'm not sure whether I'm doing it right. Thanks again!

**Comment by barijaona** [comment]
No : if you want a 'AND' match, you have to select 'All'

**Comment by thinmanballad** [comment]
Oops, looks like user error.
Then I guess I have another feature request. 
Combine 'OR' statements and join them with the 'ALL'.  Or *mini* 'or' lists within the 'AND' arguments. I think this would benefit in the ability to curate more fine tuned smart lists. 
![screen shot 2016-11-27 at 3 58 58 pm](https://cloud.githubusercontent.com/assets/6265407/20652281/0a4aa782-b4bc-11e6-86f1-1d3e73df9d4e.png)
This is a little rough and poorly explained, but I'm in a moving vehicle. Thanks again for looking, and if it looks like a worthwhile endeavor, I can try to write it out in more detail.

**Comment by barijaona** [comment]
Interesting idea. I'll merge it in feature request #423
