### ISSUE TITLE
[discussion] RFC3229

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#721]
This issue is to discuss notes around the implementation of RFC3229.
- http://hastebin.com/jipinipabi.sql
- http://bob.wyman.us/main/2004/09/using_rfc3229_w.html
- https://tools.ietf.org/html/rfc3229

First raised in PR #720 by @aeyoun

**Comment by barijaona** [comment]
Closing this as @da2x 's implementation has been added for a few weeks now, without noticeable problems.

**Comment by josh64x2** [comment]
Hey @barijaona that was only a partial implementation of RFC3229

**Comment by barijaona** [comment]
Yes, we didn't implement the `F-range` parameter. But at the client level, it is an option, not a requirement,  and nobody has asked to add it to Vienna.
