### ISSUE TITLE
Respect `Cache-Control: max-age=<seconds>` when scheduling feed updates

### ISSUE THREAD

**Issue by da2x** [ViennaRSS/vienna-rss#722]
Don’t schedule updates of feeds until after max-age or the user-configure update value; whichever is later. No need to pull in feeds more often if the feed response header says the cached feed will remain fresh until at least max-age seconds into the future from the time it was last fetched.

There is also the `Expires: <date>` header which specifies an exact date when the feed is expected to be outdated and needs to be refreshed. I do believe this has fallen somewhat out off fashion in favor of `Cache-Control` but there is no harm in supporting it too.

The goal is of course to save network bandwidth by not performing unneeded requests, and improve device battery by not chatting unnecessarily on the network.

**Comment by markcellus** [comment]
> I do believe this has fallen somewhat out off fashion in favor of `Cache-Control` but there is no harm in supporting it too.

@da2x `Cache-Control` doesn't even appear to be respected. This ticket should be reopened.
