### ISSUE TITLE
3.1.5 + 3.1.6rc2 very crash prone

### ISSUE THREAD

**Issue by DavidMunch** [ViennaRSS/vienna-rss#724]
Vienna crashes some times upon refreshing all articles. This happens more often than not right after waking the computer from sleep. I sync all instances of Vienna with an account on Bazqux.com.

12 crash logs from 3 different machines running macOS 10.11 or 10.12 attached.
[Vienna 3.1.5 + 3.1.6rc2 crashes.zip](https://github.com/ViennaRSS/vienna-rss/files/560391/Vienna.3.1.5.3.1.6rc2.crashes.zip)

**Comment by barijaona** [comment]
Not sure, but commits I recently submitted might improve things : commits 679b29a and adacaaf

**Comment by DavidMunch** [comment]
Just had another crash, so I don't think your commits helped out. :)

**Comment by josh64x2** [comment]
@DavidMunch Can you please take a screenshot of your layout and theme etc so I can try and reproduce?

**Comment by DavidMunch** [comment]
Is this sufficient?
![vienna](https://cloud.githubusercontent.com/assets/3511519/19998221/fde33c28-a26b-11e6-8388-dc4cb8540d30.png)

I should mention that I often see the subscription and Dock icon counts being wrong. Sometimes they goes into negatives, but the most prevalent error (As in 95% of the time), is that I see my Dock icon showing 1 unread subscription despite no articles being unread. But since this also happens from a fresh Vienna install (Again, Bazqux sync), I ruled out database issues, and assume this is unrelated to my crashes?

**Comment by josh64x2** [comment]
Perfect - thanks!
Yeah that is weird with the dock count - other people seem to be having issues with it too. Did your dock icon issues start with 3.1.5 ?

**Comment by josh64x2** [comment]
Once more thing @DavidMunch - does it automatically refresh after waking from sleep or is this when you do a manual refresh?

**Comment by DavidMunch** [comment]
I can't recall when the dock issue started, since we've been on 3.1.5 for so long. :( But I also on occasion see feeds with the number of articles going into negatives.

I can say for sure that the crashes happen on manual refreshes. I've set it to only refresh Vienna every 2 hours, so wether it also happen when it does it automatically is something I have to confirm. I've changed my update settings to 5 minutes.

**Comment by josh64x2** [comment]
OK, I tried all weekend and I was syncing with bazqux. I didn't get any crashes and the error message in your logic doesn't return any Google results.
I am going to try moving Vienna to layer backed views (which we need to do anyway) and see if that helps as your error message implies that it is related to the view layers.

**Comment by DavidMunch** [comment]
I only get about one crash every 1-2 days, so it doesn't happen on a regular basis for some reason. But as mentioned it happens accross 3 different machines on two different networks, and both wifi and ethernet, so I think we can rule out the connection at least.

But good to hear you at least have some idea of where to go next. :) Fortunately Vienna launches so quickly, so its not a major pain that it crashes so often.

**Comment by josh64x2** [comment]
Well it is good if it is that regular because it means I can give you a test build and you'll know soon enough if I've fixed the problem or not. 😄 
I'll reply here once I have one ready, but it probably won't be until some time this weekend.

**Comment by DavidMunch** [comment]
A minor observation: The last 3 crashes I had was definitely upon manually refreshing my feeds, just after waking the computers from sleep. 2 of my 3 computers can be a tad slow to connect to the Internet despite being on ethernet, so could that perhaps be the issue, ie. Vienna expecting a connection that isn't there?

**Comment by barijaona** [comment]
@DavidMunch, I doubt slow connection could be the cause. The crashlogs you provided make me suspect something is wrong in display update. Could you provide more details about your hardware ?

**Comment by DavidMunch** [comment]
27" Mid-2011 iMac, 8GB RAM, 2GB VRAM Radeon 6970m, Samsung EVO 840 SSD, 3.4Ghz i7. OSX 10.11.
27" late-2013 iMac, 16GB RAM, 1GB NVIDIA GeForce GT 755M, HDD, 3,2Ghz i5. OSX 10.11.
Early-2016 Macbook, 8GB RAM, 256GB PCIe NVM SSD, 1,1Ghz m3. macOS 10.12.

Crashes on all three.

**Comment by josh64x2** [comment]
@DavidMunch I've turned on layer backed views for most of the views (but probably not all because of the complexity of the current code base 😄)
Try this build out and let me know if you get the same crashes.
[Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/614521/Vienna.zip)

**Comment by DavidMunch** [comment]
Will do!

**Comment by barijaona** [comment]
@josh64x2 : would you mind publish your working branch ?

**Comment by DavidMunch** [comment]
Already had issues with the new build, although it was different this time compared to the other crashes. Normally Vienna will just crash, but this time it became complete unresponsive, and I got the attached dump when I had to force Quit Vienna from the Dock.

I should note that this happened while I was connected to a Wifi that did not have working internet access.

[Vienna.txt](https://github.com/ViennaRSS/vienna-rss/files/614710/Vienna.txt)

**Comment by josh64x2** [comment]
@barijaona I have pushed to https://github.com/josh64x2/vienna-rss/tree/layer-backed
I note based on the new crash log from @DavidMunch there appears to be an issue with:
```
  10  -[GoogleReader renewToken] + 64 (Vienna + 317792) [0x10189b960]
  10  -[GoogleReader getToken] + 927 (Vienna + 315999) [0x10189b25f]
  10  -[ASIHTTPRequest startSynchronous] + 259 (Vienna + 997681) [0x101941931]
```
So, we should probably check for network connectivity (if we don't already) and also fetch the token asynchronously so it doesn't lock up the UI. I can look into this later today after work.

**Comment by josh64x2** [comment]
OK looks like the issue starts on https://github.com/ViennaRSS/vienna-rss/blob/master/src/AppController.m#L344 which is called after your system wakes from sleep.

**Comment by josh64x2** [comment]
@DavidMunch please try this build and let me know if it helps at all.
[Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/615926/Vienna.zip)

**Comment by DavidMunch** [comment]
Will do.

**Comment by josh64x2** [comment]
@DavidMunch any crashes yet?

**Comment by DavidMunch** [comment]
So far no. :)

**Comment by DavidMunch** [comment]
Another day, another crash unfortunately.

This time I was on Wifi that was working fine, and I did a manual refresh of Vienna about 12 minutes after waking the laptop from sleep.
[Vienna_2016-12-02-101335_Ahsoka.txt](https://github.com/ViennaRSS/vienna-rss/files/626734/Vienna_2016-12-02-101335_Ahsoka.txt)

**Comment by josh64x2** [comment]
Haha thats OK, at least we are on the right track.

**Comment by josh64x2** [comment]
Actually just looking at that crash log, that is another crash related to layers.
The first build I gave you to try had layer backed views on, and that crashed due to networking code in the openreader sync.
The second build I gave you to try did NOT have layer backed views on, but did have modified networking code.

I'm going to create a third build tomorrow with the modified networking code AND layer backed views, maybe that will have a new reason for crashing 😆

**Comment by DavidMunch** [comment]
Haha, well, you ARE making it hard for yourself in that case.. :D

**Comment by josh64x2** [comment]
OK, build lucky number 3!
[Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/628467/Vienna.zip)

**Comment by DavidMunch** [comment]
So far, no issues at all. I think you struck gold with the third build!

**Comment by josh64x2** [comment]
Great to hear! Hopefully it still hasn't crashed. I have a couple of other changes to make to the openreader sync code this weekend and we should be good to go for 3.1.9!

**Comment by DavidMunch** [comment]
No crashes! :) I say we consider this fixed for now, and if I get any short term crashes, I will just re-open the ticket.

**Comment by DavidMunch** [comment]
Sorry, got another one!
[Vienna.txt](https://github.com/ViennaRSS/vienna-rss/files/643972/Vienna.txt)

**Comment by josh64x2** [comment]
😢

**Comment by josh64x2** [comment]
I think I will need to take the following approach:
* Fix the asynchronous networking code in GoogleReader
* Clean up some of the UI code and enable layer-backed views more thoroughly

At least it has reduced the frequency of crashes for you. When we start to make more substantial changes to Vienna for v3.2.0 hopefully the number of crashes will drop to 0.

**Comment by DavidMunch** [comment]
I can certainly wait for that. The number of crashes has decreased dramatically, and since Vienna launches quickly, it is not really a big issue anymore, just an annoyance. 8)

**Comment by DavidMunch** [comment]
I haven't had a single crash since the 10th of December, so I think it should be closed. Your suggestions are probably better spun off into seperate issues anyway.

**Comment by josh64x2** [comment]
OK good to know - I'll keep the issue open until I submit a proper PR with these fixes though. Hopefully I can do that this weekend!

**Comment by barijaona** [comment]
@Josh64x2 could you publish your most recent branch handling this issue ? I understand that it will not be able to directly merge into current master, but I'd like to have a look as I encountered a few crashes lately.

**Comment by josh64x2** [comment]
Hey @barijaona it is at https://github.com/josh64x2/vienna-rss/commits/issue-724 

I can start working on the networking code now I can get rid of ASIHTTPRequest.

**Comment by DavidMunch** [comment]
Had my first crash in a long while. Posting it here, as I assume it is related.
[ViennaCrash.txt](https://github.com/ViennaRSS/vienna-rss/files/949103/ViennaCrash.txt)

**Comment by josh64x2** [comment]
Yup looks like the layer related stuff again. Lets see if the next release is buggy after I review and merge #864
