### ISSUE TITLE
Notification unread article count wrong when syncing feeds

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#730]
When refreshing my feeds from BazQux, the number of unread articles in the desktop notification does not match the number of unread articles shown in Vienna.

For the following screenshot the desktop notification said 2552 unread articles.
![screen shot 2016-11-04 at 19 27 47](https://cloud.githubusercontent.com/assets/799345/19999158/c9d37002-a2c4-11e6-8e1f-fc7e9ee269ca.png)

**Comment by barijaona** [comment]
Fixed in 3.1.8
