### ISSUE TITLE
Import/export broke subscription url

### ISSUE THREAD

**Issue by landy2005** [ViennaRSS/vienna-rss#732]
I have subscription urls with ampersand `&`, ie: `https://en.wikipedia.org/w/index.php?title=Observium&feed=atom&action=history`

After export and than import on different computer, this urls escaped `&amp;` and not worked: `https://en.wikipedia.org/w/index.php?title=Observium&amp;feed=atom&amp;action=history`

Vienna Version 3.1.7 :88ecb57:

**Comment by josh64x2** [comment]
Thanks for reporting this :)

**Comment by josh64x2** [comment]
@barijaona do you think we need to call `[NSString stringByConvertingHTMLEntities:(link ? link : @"")];` [here](https://github.com/ViennaRSS/vienna-rss/blob/master/src/Export.m#L67-L68)?
Surely we have already sanitised the URL when the URL was subscribed to?

Unfortunately `[NSString stringByAddingPercentEscapesUsingEncoding:]` has been deprecated and the replacement isn't available on < 10.8 so until we drop 10.8 support we have to make some hard decisions.

**Comment by barijaona** [comment]
I agree, these calls should be removed there.

**Comment by josh64x2** [comment]
Fixed with commit 408a86c.
