### ISSUE TITLE
Next Unread

### ISSUE THREAD

**Issue by esLivingston** [ViennaRSS/vienna-rss#735]
Version 3.1.7 :88ecb57:

Using cmd+U or 'b' to move to the Next Unread article in a different folder/feed incorrectly leaves the focus on the folder/feed entry rather than on the article item.

**Comment by esLivingston** [comment]
Version 3.1.8 :1bc6bc3:

Same problem present

**Comment by barijaona** [comment]
This behavior seems consistent to me : 
- if you have a **folder** selected (left pane), cmd+U selects the **folder** with the next unread article
- if you have an **article** selected,  cmd+U selects the next unread **article**

**Comment by esLivingston** [comment]
Perhaps it would be better if the command was restricted to Next Unread Article then. I cannot envisage an occasion when I am interested in the next folder that contains an unread article.

It also is a change of behaviour from earlier releases.

**Comment by barijaona** [comment]
I don't really see this as an issue, because the article pane is still visible, and the next cmd+U or 'N' keystroke moves the focus to the article list pane.

**Comment by robertklep** [comment]
@barijaona when I delete the last article, Vienna automatically shifts focus from the Subjects pane to the Folders pane.

When new articles come in, and I press Cmd+U, the focus stays on the Folders pane, which I keep forgetting, so when I've read the first new article and press Backspace to delete it, Vienna asks me if I want to delete the folder—which obviously wasn't my intention :D

Also, Cmd+U seems to always refuse to go to the last unread folder/article, but perhaps that's just for me.

**Comment by esLivingston** [comment]
@robertklep describes the behaviour well. cmd+U results in unexpected behaviour (i.e. focus is left on a folder rather than on the next unread article).

@barijaona is almost correct. The difference is that the focus ends up on the 2nd unread article (because the the first has already been marked as read).

**Comment by barijaona** [comment]
There are two families of Vienna users : those who routinely delete articles once read, and those who archive everything until their Mac cries misery 😆

Guess which kind I am ?

**Comment by josh64x2** [comment]
Perhaps we can look at adding a preference so we can have it both ways?

**Comment by barijaona** [comment]
A preference might be overkill, I agree that it should be possible to have more consistency. 
I am still busy now, but I will look at it in a few days.

**Comment by barijaona** [comment]
Seems to have been fixed now
