### ISSUE TITLE
Still cannot create cocoaforge account, who can help?

### ISSUE THREAD

**Issue by mwoffenden** [ViennaRSS/vienna-rss#739]
I never get the confirmation email.

Trying to sign up for the Vienna forum.

Any help would be appreciated!

**Comment by josh64x2** [comment]
Hi,
Have you checked your junk mail folder as for some reason the cocoaforge emails go there?

Thanks!

**Comment by mwoffenden** [comment]
I have and it’s not there.

**Comment by josh64x2** [comment]
Ok I'll check the server logs later. 
This issue seems to appear randomly :(

**Comment by josh64x2** [comment]
@mwoffenden I think I've fixed this issue - I have resent your activation email. 

Thanks!

**Comment by mwoffenden** [comment]
@josh64x2 I've still not seen the activation email.

**Comment by josh64x2** [comment]
Hmm what username did you sign up with? I'll try again.

**Comment by mwoffenden** [comment]
I believe it was **mwoffenden**.

**Comment by josh64x2** [comment]
I thought that was it, but I can't find the account any more - it may have got deleted when I upgraded the forum software. Can you please try and re-register?

**Comment by mwoffenden** [comment]
Re-registered and got in this time.  Weird bug though.  If I try to change the language to "American English", I get bounced back to the T&C page.  Hey, maybe the T&C say something about which language you must choose?

**Comment by josh64x2** [comment]
OK thanks for letting me know! I'll take a quick look at it but I want to migrate the forums to different software anyway because phpBB is very buggy.

**Comment by josh64x2** [comment]
I think I fixed the T&C issue. Looks like phpBB language packs can still be selected even if they are missing all of the translation files. As a workaround I just copied the en-gb files to en-us until I work out what direction we are going to go with regards to the forums.
