### ISSUE TITLE
Images in article list

### ISSUE THREAD

**Issue by mwoffenden** [ViennaRSS/vienna-rss#740]
Has anyone considered adding this feature to Vienna RSS?

**Comment by barijaona** [comment]
I haven't.
The article list code needs a serious overhaul, so adding any new functionality is not considered a priority.

**Comment by josh64x2** [comment]
It will be a lot easier to add after we overhaul it though!

**Comment by Eitot** [comment]
With images you mean some image in the feed entry itself? Or the feed icon?

**Comment by mwoffenden** [comment]
<img width="958" alt="screenshot_428" src="https://cloud.githubusercontent.com/assets/6774346/22650402/2158640a-ec4d-11e6-8a74-637b32b07e3d.png">

**Comment by mwoffenden** [comment]
<img width="958" alt="screenshot_428" src="https://cloud.githubusercontent.com/assets/6774346/22650432/40be9666-ec4d-11e6-9961-d9d26f9052c2.png">

**Comment by josh64x2** [comment]
@mwoffenden isn't this how the "Unified" layout works? Or is something missing from unified layout?

**Comment by mwoffenden** [comment]
Unified is nice, but still is missing icons next to the articles.  See this browser UI from InoReader:
<img width="1630" alt="screenshot_431" src="https://cloud.githubusercontent.com/assets/6774346/22673111/1d2dfd78-eca6-11e6-9b10-cacc7f7dbc04.png">

**Comment by Eitot** [comment]
I think it would be desirable if we had a fourth layout style that uses multi-line cells, similar to Mail. The current layout styles want to be vertically compressed and I don’t think that we should add images there.

**Comment by mwoffenden** [comment]
Regarding the images in the article list...

- It would be great if the end user had some control over the image height.  S/M/L? 
- Ideally the image area would collapse if there's no image.
