### ISSUE TITLE
Some articles cannot show in preview pane on macOS Sierra

### ISSUE THREAD

**Issue by gonglei** [ViennaRSS/vienna-rss#743]
I'm using Vienna on macOS Sierra. I found some articles cannot show on preview pane. I have to double click it to show on a separate tab. The RSS feeds are:
http://www.echojs.com/rss
https://news.js.org/feed/
https://ecmascript-daily.github.io/atom.xml

**Comment by josh64x2** [comment]
Thanks, I'll try and look into it this weekend :)
