### ISSUE TITLE
Auto Layout and base internationalization

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#744]
Any plans to use Storyboards and Autolayout? Could clean up quite a few .nib and .strings files.

**Comment by josh64x2** [comment]
Hey @Eitot we do have plans for it but we are limited with time. Would you like to help out? 😄

**Comment by Eitot** [comment]
I have experience with Xcode and interface builder, but to be honest, I am not sure where to begin for this project. The project currently uses a mix of NIB and XIB files for each language and I suppose that it will be necessary to switch to a base translation, in order to utilise auto layout. There are also many hooks in the  code itself where the interface files are instantiated.

I have to investigate this a bit to see how much work it would be.

**Comment by josh64x2** [comment]
Yeah it is a very messy codebase and we need to make it a lot cleaner. If you could help come up with a plan of attack I could help implement it.

Another thing that would be great if it is easier for you is to build the UI from scratch with storyboards and I can then write the controllers to connect the UI to the code.

Autolayout and base internationalisation is something I've been wanting to do for a long time!

**Comment by JanX2** [comment]
You could use my fork for batch-converting all the NIBs:
https://github.com/JanX2/NibToXibConverter

**Comment by Eitot** [comment]
I did not realise that Apple added Storyboard to Cocoa only in Yosemite. :(

I have been spending some time yesterday to refactor the remaining NIB files to XIB, enable the Base translation and implement Auto Layout. I will be sending a pull request soon for the work-in-progress.

I have some problems with Auto Layout in two files: SyncingPreferencesView.xib and AdvancedPreferencesView.xib, which cause Xcode to crash all the time when setting the constraints. I am unable to proceed here. I am also not yet sure how I should refactor the existing XIB files that do not have their own language-specific XIB files yet (e.g. ActivityViewer.xib). If anyone has a tip for importing localizable.strings into XIB, that would be very welcome.

**Comment by josh64x2** [comment]
Hi @Eitot thanks for working on this 😄  I hope my work in #757 didn't break anything for you.
I will also help you with the remaining problems you are having. I'll look at SyncingPrefs and AdvancedPrefs tonight.
I believe you can use `ibtool` for importing `localizable.strings` files into xibs. I can check that later as well.
I couldn't see the fork you are working from on your github profile - can you please provide a link? IF it is on gitlab or bitbucket that is ok.

Thanks!!

**Comment by Eitot** [comment]
Have you used this before with `ibtool`? I have tried `ibtool --import-strings-file`, but it does not seem to accept localizable.strings files. It asks for a different file, I am assuming a strings file that was extracted from a XIB file previously.

**Comment by josh64x2** [comment]
Hmm I wrote a script once to help do it. I'll look for it after work

**Comment by josh64x2** [comment]
Ohhh I see what you mean now, the actual `Localizable.strings` files. I might have to write a script for that if I can't find a better way of doing it.
