### ISSUE TITLE
Icon transparency issue?

### ISSUE THREAD

**Issue by marchyman** [ViennaRSS/vienna-rss#745]
I noticed this after updating to 10.12.2 on my late 2012 iMac.  Perhaps it happened earlier?

Anyway, the icon in the dock has changed to be partly transparent and you can see the outline of the icon bounding box.   Here's a screen capture..

![screen shot 2016-12-14 at 6 49 05 pm](https://cloud.githubusercontent.com/assets/784627/21210247/4563f1be-c22e-11e6-874c-674097d1168b.png)

Vienna 3.1.8 plus one local patch that undefs DEBUG compiled for development.

**Comment by josh64x2** [comment]
A few people have reported this issue but I can't reproduce on any of my systems. 
I'm not sure how to approach it...

**Comment by Eitot** [comment]
The flaw is definitely in the icon file, even in the Xcode project. Have you got the source file of the icon?

**Comment by barijaona** [comment]
@nickdaze , do you have it ?

**Comment by Eitot** [comment]
Checking the [commit history](https://github.com/ViennaRSS/vienna-rss/commits/master/Resources/vienna-3.icns), the icon was broken at the last commit. I suppose tha the compression tool used broke the alpha channel.

Given that the commit happened due to Leopard compatibility at the time, I think that reverting to an earlier commit should be enough.

**Comment by marchyman** [comment]
On Dec 17, 2016, at 5:36 PM, Eitot <notifications@github.com> wrote:
> 
> Checking the commit history, the icon was broken at the last commit. I suppose tha the compression tool used broke the alpha channel.

The last commit was 2013.  The icon was broken quite recently, possibly when I updated to 10.12.2.  I don’t think there was an issue on 10.12.1.

This may be a case of a new OS not handling an old format icon the same way.

**Comment by Eitot** [comment]
I saw the opaque background on El Capitan as well, before I upgraded yesterday. It did not occur to me at the time. I have quickly tried to reproduce the problem with the same tool, but to no avail. Not sure what caused the problem, but in any case, it looks as though the older version does not have this.

**Comment by josh64x2** [comment]
OK we should put the icon in an assets catalogue too.

**Comment by josh64x2** [comment]
On the plus side the people experiencing the issue have it consistently so it should be simple to test a fix!

**Comment by josh64x2** [comment]
Oh this was reported [over on the forums](https://forums.cocoaforge.com/viewtopic.php?f=18&t=26914&p=139763#p139722) and I made a [test build(https://app.box.com/s/b4mquduwrv13tm4vvhga0hujtji957wi) which apparently fixed the issue. 
I completely forgot about it 😁 I will try and find the branch I made the fix in and submit a PR.

**Comment by marchyman** [comment]
Yes, I can confirm it is fixed with your changes.  One note... the icon in the Dock did not change (was still messed up) even after launching the updated version of Vienna.   Removing the icon from the Dock then adding it again from the Applications folder resolved that glitch.

**Comment by josh64x2** [comment]
I think thats a standard Dock thing that it does sometimes. Relaunching the Dock or rebooting the computer should fix it as well.
