### ISSUE TITLE
Adding XML link causes crash at startup

### ISSUE THREAD

**Issue by evanmiltenburg** [ViennaRSS/vienna-rss#746]
I tried to add [this feed](http://www.cleverhans.io/feed.xml), but then Vienna (latest version, OS X) crashed and it now keeps crashing on startup. 

* Bug fix question: Is it possible to fix this issue locally by removing the URL manually from somewhere?
* Feature request: could you make some sort of check to prevent Vienna from reading malformed data?

Here's the Terminal output:

```
/Applications/Vienna.app/Contents/MacOS/Vienna ; exit;
Illegal instruction: 4
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...7 completed.

[Process completed]

```

**Comment by miguelarauj1o** [comment]
@evanmiltenburg, what's your Vienna/OSX version?

**Comment by lapcat** [comment]
This is the same as https://github.com/ViennaRSS/vienna-rss/issues/877

**Comment by barijaona** [comment]
Same solution than #877
