### ISSUE TITLE
Feeds display in a strange way

### ISSUE THREAD

**Issue by giannigdev** [ViennaRSS/vienna-rss#747]
Hello everyone, is someone aware of this issue? it doesn't happen with every subscription i have but for some( you can see it by yourself by adding the 'Little Bites of Cocoa blog'). This is an image of the problem:

![1](https://cloud.githubusercontent.com/assets/4886490/21296184/426e7804-c566-11e6-9c21-7afeba762ec8.png)

It would be nice to receive some feedback from other users; do you think it's a problem of Vienna or of the subscription itself? thank you for your time. I am using this version with Yosemite 10.10.5 (14F1912):

![2](https://cloud.githubusercontent.com/assets/4886490/21296201/a315144c-c566-11e6-85db-23d8b7d81a98.png)

**Comment by JanX2** [comment]
This looks like a typesetting issue due to the use of emoji. I seen that as well in Vienna occasionally.

**Comment by josh64x2** [comment]
Yes it is part of an emoji issue. We need to move our tableviews to be view based instead of cell based. Hopefully we can get this work done in the next month or so.

**Comment by josh64x2** [comment]
Any help is most welcome :)

**Comment by barijaona** [comment]
Closing this as it is basically the same issue as issue #447
