### ISSUE TITLE
Ghost articles from deleted feed

### ISSUE THREAD

**Issue by reeleis** [ViennaRSS/vienna-rss#750]
I recently deleted a feed, possibly while my feeds were refreshing, and now all of the articles from that feed are in my unread articles list (even though they had all been marked as read before). When I try to mark them as read or delete them they show up again as unread if I go between folders or quit and restart Vienna. I have tried reindexing the database and emptying the trash with no success.

Vienna Version 3.1.8 :1bc6bc3:
Running on OS X 10.11.6

**Comment by miguelarauj1o** [comment]
Hey @reeleis, does this issue still alive?

**Comment by reeleis** [comment]
I haven't been able to reproduce it (I restored an earlier version of my database), so I'll go ahead and close the issue. Thanks!
