### ISSUE TITLE
Retina RSS icon in bar menu

### ISSUE THREAD

**Issue by danielhutnan** [ViennaRSS/vienna-rss#752]
Please update retina (2x resolution) RSS icon in bar menu - Mac Os.

Thank you.

**Comment by josh64x2** [comment]
hey @danielhutnan are you using a 5K imac by any chance?

**Comment by danielhutnan** [comment]
Hello @josh64x2, I'm using MacBook Pro Retina and external 4k LCD monitor.

**Comment by josh64x2** [comment]
OK I think we are going to need to start providing @3x icons. Can you please take a screenshot of how it currently looks for you?
Does it look equally bad on the MBP Retina when you don't have the monitor plugged in?

**Comment by josh64x2** [comment]
@danielhutnan can you please try this test version and let me know if the icons look better?

Thanks!

[Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/679497/Vienna.zip)

**Comment by danielhutnan** [comment]
@josh64x2 now it doesn't work - no icon displayed.

There you can see the 3.1.8 version:

<img width="358" alt="1" src="https://cloud.githubusercontent.com/assets/12529041/21577273/73695908-cf55-11e6-8ef7-ea81ad0db64a.png">
<img width="328" alt="2" src="https://cloud.githubusercontent.com/assets/12529041/21577274/739238f0-cf55-11e6-842a-202886288d9c.png">

**Comment by josh64x2** [comment]
OK I think that test build has a bug because I had to turn the status bar icon off and on again in the preferences for it to display. I'll check it out and hopefully have a new one to upload shortly.

**Comment by josh64x2** [comment]
@danielhutnan please try this new version: [Vienna.zip](https://github.com/ViennaRSS/vienna-rss/files/679919/Vienna.zip)

The icons displayed for me straight away. 😄

**Comment by danielhutnan** [comment]
@josh64x2 now it's perfect! 👍

**Comment by danielhutnan** [comment]
Thank you.
