### ISSUE TITLE
JustSimple - finally great style. :)

### ISSUE THREAD

**Issue by danielhutnan** [ViennaRSS/vienna-rss#753]
Hello everybody,

I've created very nice, clear and simple style for your RSS feeds. :)

[JustSimple.viennastyle.zip](https://github.com/ViennaRSS/vienna-rss/files/677177/JustSimple.viennastyle.zip)

If it is possible, please add it to [Extras](http://www.vienna-rss.org/?page_id=76).
I have no idea how it works there.

I hope you will like it as much as I do. 

Thank you.

Best Regards,
Daniel Hutnan

**Comment by josh64x2** [comment]
Hey @danielhutnan I really like this style - thanks!
One question though, it doesn't seem to work properly in Unified layout (it crops the bottom of each article) but I'm not sure if this is a limitation with your style or if it is a bug with Vienna.

Can you please test in Unified layout mode and let me know what you think?

Thanks!

**Comment by danielhutnan** [comment]
Hi @josh64x2, you're right. There was a little mistake on my side. It's been successfully fixed. :) Now it works great but I can see one more bug with Vienna. If there is a lot of content, it takes some time to load correctly. Before is content of article fully loaded, there is big white space between two of them in Unified layout mode.

**Fixed version**
[JustSimple.viennastyle.zip](https://github.com/ViennaRSS/vienna-rss/files/678588/JustSimple.viennastyle.zip)

Thank you.

Best Regards,
Daniel Hutnan

**Comment by josh64x2** [comment]
Thanks for fixing this :) I'll upload it now

**Comment by josh64x2** [comment]
All uploaded :) It's second on the list.

**Comment by marchyman** [comment]
I notice that this style suffers from the incorrect image aspect ratio bug that has been squashed elsewhere in the past.  This patch seems to fixe the issue.

`
--- stylesheet.css~	2016-12-30 03:26:14.000000000 -0800
+++ stylesheet.css	2017-01-03 12:42:00.000000000 -0800
@@ -21,6 +21,9 @@
 	margin:10px 0px 10px 0px;
 	max-width:700px;
 	padding:0px;
+	box-sizing: border-box;
+	-webkit-box-sizing: border-box;
+	height: auto !important;
 }
 
 iframe, object, embed {
`

**Comment by josh64x2** [comment]
@danielhutnan I can confirm what @marchyman says, can you please attach an updated .zip?

Thanks!

**Comment by danielhutnan** [comment]
@marchyman @josh64x2 Hello guys, I'm sorry for the late answer. I can't agree. With the style what @marchyman has wrote, it's creating very big spaces between the articles in Unified layout mode and images are all aligned to the left. I can't see the bug what @marchyman says.

Can you please make some screenshots?

Anyway, it's necessary to add display:block to img element because some texts are floating around the images and fix max-width:700px...

I will fix all together, just tell me more about bug or show some screenshots.

Thank you!

**Comment by marchyman** [comment]
On Jan 9, 2017, at 7:35 AM, danielhutnan <notifications@github.com> wrote:
> 
> @marchyman @josh64x2 Hello guys, I'm sorry for the late answer. I can't agree. With the style what @marchyman has wrote, it's creating very big spaces between the articles in Unified layout mode and images are all aligned to the left. I can't see the bug what @marchyman says.
> 
> Can you please make some screenshots?

Sure.

Without patch:



With the patch



I copied the patch from a change that was made to some other style a while back.   I just checked and found the only line that was needed is this:

height: auto !important;

removing the bix-sizing changes will solve the issues you saw on other layouts.

Marc

**Comment by josh64x2** [comment]
do @marchyman's screenshots show for anyone else?

**Comment by danielhutnan** [comment]
@josh64x2 no, I can't see them but he is right. It's enough to add just height: auto !important;

I will fix it asap.

**Comment by marchyman** [comment]
I'm sorry my images didn't show up.  I sent them in email.  I'll try to remember for the future to use the web based form if I have attachments.  Updated style downloaded and seems to be working just fine.

**Comment by danielhutnan** [comment]
@marchyman no problem. Thank you. :)

**Comment by josh64x2** [comment]
Just updated the copy of the theme on our server. Thanks again @danielhutnan :)
