### ISSUE TITLE
Different Date Format Control for Different Feed 

### ISSUE THREAD

**Issue by FakeYin** [ViennaRSS/vienna-rss#756]
Will it be possible to control how date is read on a feed by feed basis? 

Some feed have the format of <dc:date> yyyy-dd-mm <...> (e.g., 2017-02-01) which will be read as 1st Feb 2017 instead of 2nd Jan 2017. 

Is there a way to control above behaviour?

**Comment by Eitot** [comment]
It is a bit unusual to use non-standard date formats in feeds. It is possible presently, but I think that this may be desirable to implement nonetheless.
