### ISSUE TITLE
Grey square surround for Vienna application icon in the Dock

### ISSUE THREAD

**Issue by gearstash** [ViennaRSS/vienna-rss#760]
MacOS Sierra 10.12.2, Vienna 3.1.8 :1bc6bc3:

The Vienna icon is rendered normally without the grey square surround in the Dock on another Mac--all preferences identical. I don't see any difference in the .icns files...

**Comment by marchyman** [comment]
> On Jan 11, 2017, at 1:19 PM, gearstash <notifications@github.com> wrote:
> 
> MacOS Sierra 10.12.2, Vienna 3.1.8 :1bc6bc3:
> 
> The Vienna icon is rendered normally without the grey square surround in the Dock on another Mac--all preferences identical. I don't see any difference in the .icns files...

That problem was found and fixed a little after 3.1.8.

Marc

**Comment by josh64x2** [comment]
Yup, thanks for reporting this though :) we have fixed it and it will be in v3.1.9 which should be released this weekend if all goes well!!!
