### ISSUE TITLE
Replacement of PSMTabBarControl

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#762]
Once the project switches to Mavericks in the future, it may be worth replacing PSMTabBarControl with this project: https://github.com/MiMo42/MMTabBarView. It has a Yosemite style as well.

It does build with 10.8 without any warnings/issues, but I don’t know whether it actually works on it.

**Comment by josh64x2** [comment]
I have a 10.8 VM I can try it on, thanks :)

**Comment by josh64x2** [comment]
Unfortunately the demo app crashes on 10.8 :(

**Comment by Eitot** [comment]
I have done some tests and unfortunately it is not as capable of dealing with Auto Layout as I had hoped. The provided Yosemite style seems to work, because it uses the same ‘hack’ that I used by enforcing an intrinsic size, but the Mavericks style does not without manually adding it. The project maintainer does not seem very active at the moment, with outstanding pull requests.

I am not sure what to do about this. Clearly, MMTabBarView is a more modern code base and it was still updated in December. Small changes can always be made by us.

There is a promising alternative in [KPCTabsControl](https://github.com/onekiloparsec/KPCTabsControl), though it doesn’t look and behave as nicely as MMTabBarView and is not as feature-rich either. The framework is currently built only for Yosemite, but it seems to build without errors for Mavericks too.

**Comment by josh64x2** [comment]
Should we look at this for 3.2.0 or save it for 3.3.0?

**Comment by barijaona** [comment]
It might be a bit late for 3.2.0, if we maintain the January 28th deadline.
I had a look back at PSMTabBarControl this morning, and spotted a few bugfixes and improvements. I will submit them in a few hours.

**Comment by TAKeanice** [comment]
What is the plan on this? Since I know some stuff about the tabbing system of Vienna now, I could maybe do something about it.

**Comment by josh64x2** [comment]
Oops haha @Eitot would know what the plan is I guess. I think we were waiting to drop 10.9 support?

**Comment by barijaona** [comment]
My immediate intention is to have our own version of MMTabBarView.

**Comment by Eitot** [comment]
Forking MMTabBarView is definitely the best solution. It just isn’t maintained and has open pull requests. The only other alternative is KPCTabControl, which isn’t as good, also not actively maintained and requires Yosemitez

**Comment by TAKeanice** [comment]
I am trying to use MMTabBarView currently. Although they say, that it is not drop-in, initially only very few changes will be required.

**Comment by Eitot** [comment]
Done in #1110.
