### ISSUE TITLE
Gatekeeper in Sierra

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#765]
Apple expanded Gatekeeper in Sierra with ‘app translocation’. The application bundle is launched from a random path on the file system:
![screen shot 2017-01-19 at 02 34 15](https://cloud.githubusercontent.com/assets/15073177/22090092/d7487226-ddef-11e6-9a8d-58273fe92d0a.png)

Although it does not seem to impact Vienna functionally, it may be worth adopting Apple’s recommendation to use [code-signed disk images](https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW19) to avoid this.

**Comment by barijaona** [comment]
Is it really an issue ? I find it easier for an average user to directly get a .app
It could be interesting replacing .tar.gz file extensions with .tgz though.

**Comment by Eitot** [comment]
A disk image has the added advantage that we can add a visual instruction for the user to place the app in the Applications directory.

![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.globalnerdy.com%2Fwordpress%2Fwp-content%2Fuploads%2F2013%2F09%2Fxcode-window.jpg&f=1)

**Comment by josh64x2** [comment]
I think a disk image is more user friendly for the average user because they know that’s the format they usually get their apps in.

**Comment by Eitot** [comment]
[This repo](https://github.com/osxfuse/osxfuse/blob/master/build.d/targets/release.sh) has a great example for an automated way to create a disk image like shown above.
