### ISSUE TITLE
Update Organisation Identifier

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#766]
We need to update the organisation identifier from **uk.co.opencommunity.vienna2** to **org.vienna-rss.vienna**.

**Comment by Eitot** [comment]
Some of these files here will have to be migrated:
![screen shot 2017-01-19 at 03 15 57](https://cloud.githubusercontent.com/assets/15073177/22091141/aa23081e-ddf5-11e6-8249-a6180c3fd0b4.png)

**Comment by josh64x2** [comment]
We can do this as part of migrating to an app sandbox as mentioned in #262

**Comment by Eitot** [comment]
I suppose the bundle identifier should become com.* now.
