### ISSUE TITLE
Vienna crash from incorrectly escaped URLs

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#768]
As reported on the forums: https://forums.cocoaforge.com/viewtopic.php?f=18&t=26924

I've been able to reproduce with this [example xml file](https://github.com/ViennaRSS/vienna-rss/files/717773/viennacrash.rss.zip) when selecting the post titled: "The Giant Beastcast - Episode 86".

The issue appears to be https://github.com/ViennaRSS/vienna-rss/blob/master/src/StringExtensions.m#L717 and last night Vienna ended up using 48.5 GB of memory due to this issue 😱

**Comment by josh64x2** [comment]
Last chance for me to get this in v3.1.9 😁

**Comment by barijaona** [comment]
Fixed in stable branch

**Comment by barijaona** [comment]
Closed at version 3.1.12
