### ISSUE TITLE
Scrolling continues when jumping between articles

### ISSUE THREAD

**Issue by DavidMunch** [ViennaRSS/vienna-rss#769]
1. Scroll down through an article.
2. While the article is still scrolling and the cursor is still hovering over the article view, press a key to go to another article.
3. The new article is scrolled down.

Expected result: No scrolling when changing articles.

**Comment by Eitot** [comment]
It seems that the remaining ‘momentum’ of the scrolling is carried over to the next article. Curiously, this happens in Apple Mail too.
