### ISSUE TITLE
10.8 Fixes for autolayout

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#771]
The issue is for discussing the autolayout fixes required for 10.8

FYI @Eitot @barijaona

**Comment by josh64x2** [comment]
@Eitot I've fixed some of the 10.8 stuff by removing all of the manual splitview layout stuff from `ArticleListView` and using the NSSplitView autosave functionality.
There are some constraint issues though and I'm not sure where to start.

The following displays in the console when launching the app:
```
26/01/17 12:26:35.200 PM	Vienna[270]	Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7f931b02b560 h=-&- v=-&- V:|-(0)-[MessageListView:0x7f931a489940]   (Names: '|':NSClipView:0x7f931a489320 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f931b02b5c0 h=-&- v=-&- V:[MessageListView:0x7f931a489940]-(0)-|   (Names: '|':NSClipView:0x7f931a489320 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f931a4ab820 h=-&- v=-&- V:|-(17)-[NSClipView:0x7f931a489320]   (Names: '|':NSScrollView:0x7f931a488f10 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f931b0a6020 h=-&- v=-&- V:[NSClipView:0x7f931a489320]-(0)-|   (Names: '|':NSScrollView:0x7f931a488f10 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f931b0a8f60 h=--& v=--& V:[NSScrollView:0x7f931a488f10(8)]>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7f931b02b5c0 h=-&- v=-&- V:[MessageListView:0x7f931a489940]-(0)-|   (Names: '|':NSClipView:0x7f931a489320 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
26/01/17 12:26:35.201 PM	Vienna[270]	Unable to simultaneously satisfy constraints:
(
    "<NSAutoresizingMaskLayoutConstraint:0x7f931a4ab820 h=-&- v=-&- V:|-(17)-[NSClipView:0x7f931a489320]   (Names: '|':NSScrollView:0x7f931a488f10 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f931b0a6020 h=-&- v=-&- V:[NSClipView:0x7f931a489320]-(0)-|   (Names: '|':NSScrollView:0x7f931a488f10 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f931b0a8f60 h=--& v=--& V:[NSScrollView:0x7f931a488f10(8)]>"
)

Will attempt to recover by breaking constraint 
<NSAutoresizingMaskLayoutConstraint:0x7f931b0a6020 h=-&- v=-&- V:[NSClipView:0x7f931a489320]-(0)-|   (Names: '|':NSScrollView:0x7f931a488f10 )>

Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.
```

This results in the list of articles being collapsed up towards the filter bar because the splitview doesn't restore the autosaved layout correctly.

**Comment by josh64x2** [comment]
You can look at my branch [mavericks-autolayout](https://github.com/josh64x2/vienna-rss/tree/mavericks-autolayout) if you want to try.

**Comment by josh64x2** [comment]
Actually maybe we should have HorizontalArticleListView and VerticalArticleListView as two different subviews so we dont have to programmatically change the layout of everything.... what do you think?

**Comment by Eitot** [comment]
I am a bit puzzled as to why the NSClipView has an autoresizing-mask constraint of 17 at the top and the NSScollView a height constraint of 8.  Logically, the first should be 0, the other should not exist. It seems that it then chooses the break the wrong constraints, the top constraint of the message list and the bottom constraint of the NSClipView.

Is there anything helpful when you enable this:
```
defaults write uk.co.opencommunity.vienna2 NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints -bool YES
```

I did not spot any Auto Layout issues in Mavericks’ console, so it must be something particular to ML.

**Comment by josh64x2** [comment]
Ooops I got the names for 10.8 and 10.9 mixed up :D I'm just going to rename my branch...

**Comment by Eitot** [comment]
I pushed a commit to my `autolayout` branch that hopefully fixes the tab bar. Can you merge and test this on 10.8?

**Comment by josh64x2** [comment]
Sure, I'll have to do it on Friday though after work

**Comment by josh64x2** [comment]
@Eitot the logic works, but the animation is still weird...

**Comment by josh64x2** [comment]
with regards to my `mtnlion-autolayout` branch, i enabled `defaults write uk.co.opencommunity.vienna2 NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints -bool YES`

And it shows: 
![screen shot 2017-01-27 at 19 16 43](https://cloud.githubusercontent.com/assets/799345/22364395/5d1a2684-e4c5-11e6-80bb-13adf10beb57.png)

And in the console it says:
![screen shot 2017-01-27 at 19 17 24](https://cloud.githubusercontent.com/assets/799345/22364402/6b2f3692-e4c5-11e6-8fca-ef11aba8d13f.png)

Which is weird because I didn't get a repeat of the `NSAutoresizingMaskLayoutConstraint` stuff...

**Comment by Eitot** [comment]
OK, I approached the tab bar differently now. Can you merge again?

**Comment by barijaona** [comment]
Don't forget that the filter bar can appear only on the main tab, not on browser tabs.

**Comment by Eitot** [comment]
I see what you mean. It is not dismissed when switching to an empty tab.

**Comment by barijaona** [comment]
Yeah, some code is needed in AppController's `-handleTabChange:` (or on `-updateStatusBarFilterButtonVisibility`)

**Comment by barijaona** [comment]
Can you have a look at my `autolayout` branch ?

**Comment by josh64x2** [comment]
OK on 10.8 the animation is fixed, also the filter bar now only shows on the articles tab and not the browser tabs.
I like the fact that the filter shows below the tab bar - it reflects that the filter is only for the articles view and not the parent view.

Still having constraint issues, and the articles list is collapsing when turning tabs on and off as show:
![screen shot 2017-01-28 at 10 23 29](https://cloud.githubusercontent.com/assets/799345/22391236/45b7fbf4-e544-11e6-8b8c-ef09f7f67b9e.png)

and then when I expand it manually:
![screen shot 2017-01-28 at 10 29 07](https://cloud.githubusercontent.com/assets/799345/22391318/a5cc7aec-e544-11e6-8acc-efabe38d95c4.png)

**Comment by barijaona** [comment]
Can you confirm if the issue with article list collapsing is specific to 10.8 ?

**Comment by josh64x2** [comment]
Well I've only tested on 10.8 and 10.12. If someone can test on 10.9 and it works I guess we could drop 10.8 support earlier.

**Comment by Eitot** [comment]
I haven’t seen this behaviour on my 10.9 VM at least. I will test the latest commits on it to be sure.

**Comment by barijaona** [comment]
Apart from 10.8 support, do you see other advantages in having two separate split views ?
My opinion is that currently, we should prioritize code modernisation over legacy support. We can drop 10.8 compatibility early if it requires too much effort.

**Comment by josh64x2** [comment]
In my opinion it's a little cleaner - they are technically different views.
They would both contain the same subviews - ArticleListView (or is it MessageListView?) and ArticleView. The subviews would resize appropriately due to autolayout.

What would be a good name for the parent view of the right hand side of the app? SubscriptionDetailView? Technically it shows the detail of a subscription/folder selected on the left hand side...

**Comment by Eitot** [comment]
ContentDetailView? Or just DetailView?

**Comment by barijaona** [comment]
I am OK with the proposed approach and would go with FolderDetailView.
Each FolderDetailView would contain a MessageListView and an ArticleView.

UnifiedDisplayView could later also benefit from this approach.

**Comment by josh64x2** [comment]
I finder Folder confusing because individual subscriptions are not folders, and we use folders for a different purpose in Vienna...

@eitot what is the issue with the side bar?

**Comment by barijaona** [comment]
I agree it might be misleading at first, but it's Vienna's terminology, either in user interface or in code (ex: FolderView), so I prefer consistency.

**Comment by josh64x2** [comment]
I am quite happy to change all references from Folder to Subscription :) - we decided on Subscription and Post in the ViennaNG discussions. Otherwise I think just DetailView.

**Comment by Eitot** [comment]
> what is the issue with the side bar?

It is not sized correctly, same problem as with the other split view.

**Comment by barijaona** [comment]
Vienna's terminology is in fact quite logical once you understand that the model is Apple's Mail : in Mail, you've got the Mailbox and Message menus ; in Vienna, it's Folder and Message 🤓

**Comment by josh64x2** [comment]
Mailbox/Message is also the same as Subscription/Message then.

I'm sorry I just think it is very confusing especially considering we also have objects called Folder and Smart Folder which have nothing to do with the Folder (Subscription) and I think it could also confuse and deter potential contributors. 

We can worry about it later though, and I'll call the parent view `DetailView` as per @Eitot's suggestion 😄 

---

@Eitot I never had issues with the sidebar being sized incorrectly, even on 10.8 :( I thought I had it working well when I removed the delegate from that SplitView.

**Comment by Eitot** [comment]
Technically, Mail does not have the equivalent of a folder. There are just mailboxes. A feed/subscription would be a mailbox, an entry/article would be a message.

**Comment by barijaona** [comment]
In fact, the error was to put the "New Subscription…", "New Smart Folder…" and "New Group Folder…" commands in the "File" menu. Logically, they should be in the Folder menu to mimic Apple Mail's behavior 🤓

**Comment by Eitot** [comment]
Maybe I can have a look at the nomenclature Apple used in Snow Leopard. 😅

**Comment by josh64x2** [comment]
I found this image haha

![mactip82](https://cloud.githubusercontent.com/assets/799345/22395021/2d36a56c-e585-11e6-8d45-f85355551ba4.png)

But we are losing focus on the real issue here ;)

**Comment by Eitot** [comment]
Yep, in Snow Leopard’s Mail there are feeds. Feeds are added; not subscribed to. There is no consistency with regard to the name for an entry, both ‘Message’ and ‘Feed Article’ are used. There is no equivalent for a folder, but ’New Mailbox’ is indeed in a separate menu.

![screen shot 2017-01-28 at 8 22 01 am](https://cloud.githubusercontent.com/assets/15073177/22395123/6b75138c-e534-11e6-8321-bc8fd160a222.png)

**Comment by josh64x2** [comment]
My preference is for consistency with the what the user sees. 

If I am a user and I notice a bug with the way emoji are displayed in the title of an RSS/Atom feed that I want to try and fix, I'm going to look for "feed" references in the code, not folder.
A folder is a collection of feeds for the user.

That's where I am coming from 😄 

Anyway, @Eitot do you have a screenshot of the sidebar issue you're having? Also you might be interested in this very basic Swift version of Vienna I started but never got around to finishing... https://gitlab.com/ViennaRSS/viennang

**Comment by Eitot** [comment]
I find the word ‘Subscription’ a bit weird too. ‘Feed’ seems more to the point in a feed reader.

The first start of the program seems to work fine, but once you restart, the sidebar is collapsed either to the left or right as far as it can (there is a minimum-width constraint there that prevents it from collapsing all the way). I haven’t figured out what is causing it.

**Comment by josh64x2** [comment]
Hmm that sounds like the NSSplitView autosave and restore isn't working properly again :(

**Comment by Eitot** [comment]
Is everything else working?

**Comment by josh64x2** [comment]
For me it is all working on 10.12. Are there any constraint errors in the console?

**Comment by Eitot** [comment]
I meant in ML. :)

**Comment by josh64x2** [comment]
Ahh yup! Everything else works, even the sidebar doesnt collapse. it's only the message list that collapses...

**Comment by Eitot** [comment]
Curious that you can’t reproduce it. Have you perhaps enabled the state-restoration feature in ML? System Preferences → General.

**Comment by josh64x2** [comment]
I don't think so...
![screen shot 2017-01-28 at 21 10 51](https://cloud.githubusercontent.com/assets/799345/22395846/48452f04-e59e-11e6-9a75-b54df5a6bce5.png)

**Comment by josh64x2** [comment]
@Eitot I removed all of the NSSplitViewDelegate stuff from ArticleListView in my `mtnlion-autolayout` branch which has improved things on 10.8

I also investigated the console errors I was getting before and I believe the culprit is this guy:
![screen shot 2017-01-29 at 18 37 59](https://cloud.githubusercontent.com/assets/799345/22402631/3db5a92e-e652-11e6-8e27-ce4315f08611.png)

I removed some of them from some views in MainMenu.xib and it reduced the number of `NSAutoresizingMaskLayoutConstraint` errors in the console. 

A quick google also resulted in [this advice](https://oleb.net/blog/2013/03/things-you-need-to-know-about-cocoa-autolayout/):
>8. Don’t Forget To Disable Autoresizing Masks
For backwards compatibility of your code, the springs and struts model is still the default. For every programmatically created view that you want to use Auto Layout with, call setTranslatesAutoresizingMaskIntoConstraints:NO.

That all looks to me like it might be the root cause.
We need to work out the most logical way to remove the autoresizing masks from our views and update our auto-layout constraints with the appropriate values.

**Comment by josh64x2** [comment]
So for `ArticleDisplayView` in Interface Builder, the attributes inspector shows this:
![screen shot 2017-02-06 at 12 28 13](https://cloud.githubusercontent.com/assets/799345/22631841/cce525f0-ec67-11e6-8e6d-3ab0dc6ac5a8.png)

I think the key for mountain lion is to make the view work with that checkbox disabled (which currently doesn't work in Sierra either).

Hopefully I'll have some time tonight to try and get it working in Sierra.

**Comment by Eitot** [comment]
Disabling that options means that we have to create the constraints ourselves. I suppose we have to do this in code, at the point where the view is added to its superview.

**Comment by josh64x2** [comment]
I'm still trying to fix this 😬 Unfortunately I haven't had as much time as I would have liked lately. I hope to get it done this weekend!

**Comment by josh64x2** [comment]
@Eitot do you think sticking it in an NSBox might help?

**Comment by Eitot** [comment]
NSBox is just a subclass of NSView, I doubt that it changes anything. I actually got rid of all the boxes, because they were difficult to work with when I enabled Auto Layout.

**Comment by Eitot** [comment]
Did you have a chance to have a look at it?

**Comment by josh64x2** [comment]
Unfortunately no, I've been unwell 🤒
One of the problems seems to be related to disclosure view: for some reason the height of the tab bar gets calculated incorrectly and when it is collapsed it thinks the constraint for the height is -2.

**Comment by Eitot** [comment]
I haven’t observed that particular behaviour yet, but the disclosure view is not an ideal implementation anyway. I modelled it after Apple’s example with the stack view and it does not seem to work that well without them. Plus, the tab bar is not compatible with Auto Layout to begin with, I’ve had to manually force an intrinsic size on it.

**Comment by josh64x2** [comment]
Ok that is probably why - because the proplem with height occurs after I change the Article Display View to use auto layouts instead of transforming auto resize masks.

If I don't manage to fix it by this weekend I suggest we drop 10.8 support early.

**Comment by Eitot** [comment]
I am still pondering what to do next. I have started working on the toolbar and a new implementation for the plug-in manager, but I am stuck when it comes to implementing it. I think that separating code from the app controller is a high priority, because everything seems to be leading back to it. But the class is so massive that I just don’t know where to begin.

Do you have any suggestions for smaller pieces of code (that fit together logically) that could be moved out of the app controller? Perhaps some of the smaller pieces first and then bit by bit.

**Comment by josh64x2** [comment]
I have the exact same problem you do - I'm not sure where to start! Some ideas I've had previously are:

- Create a proper AppDelegate and moving the app delegate functions out of AppController
- For the folder list outline view, move the dataSource and delegate into its own class so we can look at moving to view based Tables.
- Remove Growl and the Growl code from AppController (requires dropping 10.8 support to maintain feature parity for notifications)
- Rewrite the whole project from scratch because of how tangled all of the code is

You could also just analyse each function in AppController and write a list of what we would need to do first to remove it from the AppController.

Any other ideas?

**Comment by Eitot** [comment]
Rewriting the whole project seems to be a wee over the top. 😜

I think we won’t get around a full analysis of the app controller. I will have a look at removing code wherever I can, in small steps. Writing a new app delegate seems to be a good goal.

I have already taken care of the toolbar delegate methods, and will have a look at all the toolbar-related actions.

**Comment by Eitot** [comment]
We should also think about restructuring the project directory. Currently it is just a bit too chaotic for my liking. This however will also be painful, considering all the config files and scripts.

**Comment by josh64x2** [comment]
I like the way https://github.com/coteditor/CotEditor has their project folder set up.

There are so many things I want to fix haha, I think getting rid of ASIHTTP is probably the most important though :(

**Comment by Eitot** [comment]
You were already working on a replacement, right?

**Comment by josh64x2** [comment]
Yeah and then I got distracted with this 10.8 autolayout haha. 

Replacing it with minimal afford requires dropping 10.8 support too so we can use NSURLSession etc sooo that's sounding pretty good right about now.

**Comment by Eitot** [comment]
Is it a lot of work still?

**Comment by josh64x2** [comment]
It's a fair bit of work because we need to use asynchronous network programming and the current mess of code assumes a synchronous flow. 

The new subscription window is an example - it should not hang while it waits to add a new subscription. Instead, it should display some sort of progress indicator and then when it has verified the new subscription it can enable the OK button to commit the subscription to the database.

**Comment by Eitot** [comment]
Sounds like a ton of fun. 😄

But it will be a worthwhile improvement. ASIHTTPRequest, Growl, MASPreferences, SDEvents etc. all have Cocoa replacements nowadays. Even the database stack could probably be refactored into Core Data. It is astonishing how much work Cocoa developers had to do years ago.

**Comment by barijaona** [comment]
I agree it's time to drop 10.8. We can explain the rationale behind it in a blog post.

**Comment by josh64x2** [comment]
@barijaona OK great 👍 

@Eitot Looks like we can change to stack view now 😄

**Comment by Eitot** [comment]
Have you merged your ML branch yet? I cannot see it anymore.

**Comment by barijaona** [comment]
Mmmh, merging your various branches is getting difficult to read.

Your respective works diverged starting from commit 08aff47a06a1a4531d00b233e5bdf440d76eafde, and you started mixed things directly related to autolayout with other stuff.
I suggest that we restart from commit b2fe4ded459afd869b55d1bed07386786b852a0d for layout related work, and merge it quickly into master.

**Comment by josh64x2** [comment]
I deleted my mtnlion-autolayout branches because all of the other changes in the main autolayout branch created merge conflicts.

Now we don't need a proper mtnlion-autolayout branch I don't intended to recreate one haha

**Comment by barijaona** [comment]
My point is that these recent branches are breaking our [guidelines](https://github.com/ViennaRSS/vienna-rss/wiki/Good-manners-with-Git) for submitting code. It’s getting very difficult to identify what is finished and what is not.

We need to refocus a bit and have separate branches which are gradually merged into master when their respective purpose is reached.

For instance, I have an issue with tabs being hidden. At launch, this is what I get : 

![capture d ecran viennarss-autolayout](https://cloud.githubusercontent.com/assets/442030/23179982/e1a35550-f880-11e6-865c-bb137d03b428.png)

while the correct behavior is 

![capture d ecran josh64x2-mtnlion-autolayout](https://cloud.githubusercontent.com/assets/442030/23180005/f51b1adc-f880-11e6-9fe3-1c3b724f99ce.png)

It took me a long time to identify that this issue might be caused by commit  6a00f1ad8603fc9e56200604ebeaf0f6f42c0677, but I am not eager to untangle all

**Comment by josh64x2** [comment]
I'm closing this because I can't work out how to fix it for mountain lion and I would rather spend time supporting the majority of users that are not on 10.8

Whoever wants to try and fix it can feel free!

**Comment by Eitot** [comment]
The `autolayout` branch misses some of the fixes that barijaona and I made on your Mountain Lion branch. The last snapshot of these are in my [`autolayout`](https://github.com/Eitot/vienna-rss/tree/autolayout) branch. I think we have to look at merging those.

**Comment by josh64x2** [comment]
@Eitot OK I'll have a look at it - thanks!
