### ISSUE TITLE
Build-time issues in Xcode issue navigator

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#772]
These warnings are getting a bit annoying, can we do something about them? Particularly update Pods/Vienna project to Xcode’s recommended settings and perhaps disable the ‘typecheck calls’ and deprecation warnings in ASIHTTPRequests, at least for the ‘development’ build configuration.

**Comment by josh64x2** [comment]
Sure - go ahead and disable the warnings for ASIHTTPRequest as we will be migrating away from it soon 🤞 

Definitely also update the project configurations to Xcode's recommended settings as well :)
