### ISSUE TITLE
All articles were marked as read

### ISSUE THREAD

**Issue by the10ccm** [ViennaRSS/vienna-rss#777]
Hi Vienna guys, 

Today I've faced an issue. It is the second time when I spotted the same thing. 
I added the http://feed.rutracker.cc/atom/f/1373.atom feed to a group folder. Articles were fetched. I opened an article. CPU and HDD stuck for some time and all articles in all subscriptions has been marked as read. I've tried to reproduce the issue however I can't repeat one.

I've got Vienna 3.1.8 :1bc6bc3:.

**Comment by Eitot** [comment]
I can’t reproduce this either. :/
