### ISSUE TITLE
Notify upon adding an identical feed

### ISSUE THREAD

**Issue by nimdajitam** [ViennaRSS/vienna-rss#778]
Please, think about adding new feature that will notify user when adding new source (inside the dialog) that this particular one is already added to make the UX flow more intuitive and useful. Many, many thanks.

**Comment by josh64x2** [comment]
I agree this would be very useful.

**Comment by barijaona** [comment]
There is already a notification for strictly identical feeds.
What you are probably asking is detection of similar feeds, which would also be useful for #524
