### ISSUE TITLE
Folder images should refresh automagically

### ISSUE THREAD

**Issue by mwoffenden** [ViennaRSS/vienna-rss#780]
I'm only seeing the generic RSS icon.  I'm syncing with InoReader.

<img width="1438" alt="screenshot_432" src="https://cloud.githubusercontent.com/assets/6774346/22673177/959ee52e-eca6-11e6-80f5-333335adf57c.png">

**Comment by mwoffenden** [comment]
Not sure why, but I had to manually "refresh folder images" to get them to show up.  (Why doesn't the program just update the images automagically?)

Also, there is a cloud symbol next to each feed.  Not sure that adds much value, maybe there should be a preference to turn those off?

**Comment by Eitot** [comment]
I agree that it should be refreshed automatically. I will mark this as a bug for now.

The sidebar is due for a makeover to bring it in line with Apple’s preferred style (see #764). I’ll mark it as an improvement request.

**Comment by mwoffenden** [comment]
Great, looking forward to that.  Could we have an option to turn off those pesky cloud images?
