### ISSUE TITLE
AdBlock Plus

### ISSUE THREAD

**Issue by mwoffenden** [ViennaRSS/vienna-rss#781]
Vienna's integrated browser is a great feature.  But please incorporate [AdBlock Plus](https://adblockplus.org/) into the browser.

**Comment by Eitot** [comment]
This is not something developers can easily provide within the bounds of Apple’s WebKit APIs. I suppose it theoretically possible to use the source code of an open-source blocker and inject the contents into the web view using JavaScript. However, I don’t think that this is feasible at this time.

You should have a look at system-wide network-based blockers, such as [GlimmerBlocker](https://glimmerblocker.org).

**Comment by mwoffenden** [comment]
[GlimmerBlocker](https://glimmerblocker.org/) appears to be working well with Vienna.  Nice!

**Comment by josh64x2** [comment]
I think we can close this, though maybe we need to suggest GlimmerBlocker on the FAQ or something.
