### ISSUE TITLE
PSMTabBarControl.palette

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#782]
What does this bundle do exactly? A quick search suggests that it may be a remnant of pre Xcode 4.

**Comment by josh64x2** [comment]
Judging by the contents it looks similar to an asset catalogue.

**Comment by Eitot** [comment]
It’s a plug-in for Interface Builder. It used to be possible to add custom objects to the utility area (the tabs were called ‘palettes’. It disappeared with Xcode 4. I guess we can get rid of it.

**Comment by josh64x2** [comment]
I'm happy for it to go now, or we can wait for when we kill off PSMTabs altogether - your call :)
