### ISSUE TITLE
Vienna-rss website parked due to expiration Feb 24

### ISSUE THREAD

**Issue by pckizer** [ViennaRSS/vienna-rss#792]
Visiting the official site I see:

Welcome to: vienna-rss.org
This Web page is parked for FREE, courtesy of GoDaddy.com.

FYI

**Comment by josh64x2** [comment]
Thanks @pckizer I raised this issue with the domain holder yesterday (@mstroeck) and hopefully they can fix it soon.

**Comment by josh64x2** [comment]
I just registered vienna-rss.com and I'll wait another day to see if vienna-rss.org gets renewed. If it doesn't i'll start moving everything to vienna-rss.com. FYI @barijaona

**Comment by pckizer** [comment]
Did you ever get any response from @mstroeck ?

**Comment by josh64x2** [comment]
Hmmm no I haven't. @barijaona I think we should start migrating to vienna-rss.com if you are OK with it?

**Comment by josh64x2** [comment]
I've set up vienna-rss.com and it should start to work in around 3 hrs. I'll need to update the wordpress config when it goes live.

**Comment by josh64x2** [comment]
Ok it's all working on .com now and I've posted an announcement on the forums. There will be some broken links but I'll tidy them up over the next day or so.
