### ISSUE TITLE
On plug-ins

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#798]
I am currently thinking about/working on a new implementation of the plug-in manager, which I hope to focus on once the Auto Layout transition is done.

### Current implementation
In a nutshell, the PluginManager class loads the data from disk and produces toolbar and menu items. This class is instantiated in the AppController class in `awakeFromNib` (i.e. MainMenu.xib is loaded from disk). During its setup it will add the menu items to the main menu. Its instance methods are called when toolbar delegate methods are called (to retrieve the toolbar items). This approach introduces some problems:
* The model directly relies upon the main menu to add the menu items. It should be the other way round: the view controller retrieves the model data. Plus, by adding the items to the main menu only, the menu items cannot be used elsewhere, e.g. in the Share menus.
* The model creates the view items (toolbar and menu items) itself, which is supposed to be the task of view controllers.
* The model has no reusable data for controllers to use. They cannot access the plug-in data in any way, other than in the form of pre-generated toolbar items. It would be trivial to expose the Info.plist data in a public dictionary, but this is raw data that could be encapsulated.

The PluginManager also stands in the way of separating the toolbar code from AppController and migrate some of the code to Interface Builder (https://github.com/ViennaRSS/vienna-rss/issues/764#issuecomment-277651661). Moreover, the PluginManager is fairly big, with almost no encapsulation. It has lengthy methods with lots of if statements for the different plug-in types.

### Suggested improvements
* Have separate models for each plug-in type and have them share a common interface or parent. The plug-in-specific logic does not need to be in the plug-in manager itself.
* Have a plug-in manager model that contains the logic for loading the plug-ins from disk and instantiating them into separate model objects. Its only purpose is to load the data and make it available to other parts of the application.
* Let the view controllers take care of creating the toolbar and menu items, by retrieving the plug-in data from the manager. This also allows us to support [NSSharingService](https://developer.apple.com/reference/appkit/nssharingservice), so that users can use the ‘Share’ menu. This would also make some of the built-in plug-ins obsolete (Facebook, Twitter, Safari reading list, etc).

### Discussion points
During my review of the code, I have across some aspects that I am not sure about and would like to have your input. I only want to focus on the necessary implementation first, but it would be useful to know these points in advance, to take them into account when designing the models.

#### Plug-ins and styles
Plug-ins and styles share a lot of the same code. Styles are loaded in the ArticleView class. It seems to me that it makes sense logically to treat styles as another type of plug-in and have a more generic plug-in manager  model that takes care of just loading the files and instantiating model objects. The style-specific code can still be handled in a ‘style plug-in’ model or in a view controller.

What is your opinion on this? Do you think we should keep them separate and have two managers, one for each type? If we combine them instead, what should be the internal nomenclature for them? Call them all plug-ins (style plug-in, sharing plug-in etc.), or use a more overarching term, such as extension?

#### Persistence
Plug-ins exist in the form of bundles. Vienna provides some of them in the SharedSupport directory, users can install their own in the app-support directory (or let Vienna do it for them by clicking on a bundle). Upon launch, Vienna checks each directory and loads the data. This process is repeated every time.

Do you think it makes sense to have an alternative storage form? For instance, if we load the plug-in data into a database, then we can skip this loading process for subsequent launches and only use it when the user adds a new plug-in. This can reduce the launch time.

#### Preferences
All plug-ins are entirely dependent upon their bundles. If the user wishes to disable a plug-in, they can only choose to remove the plug-in bundle. This is problematic when it concerns the SharedSupport plug-ins (it breaks the code-signing seal). We could add a section to the preferences window where users can change some aspects of plug-ins, such as enabling and positioning (e.g. in the menu).

This begs the question: if we were to provide an interface there, do we still need the bundles? It would be tempting to let the user create plug-ins right there. For instance, search plug-ins (currently undocumented, but they work all the same) only need a query URL, a title and an identifier. Script plug-ins can reference any file located in the user’s Application Scripts directory. Sharing and referral plug-ins are also very simple.

What do you think?

**Comment by josh64x2** [comment]
Hi @Eitot, I don't have much time to make a detailed comment for now but I'll give some feedback so you can keep thinking :)

I think we could have styles be another type of plugin like you suggested. The ArticleView could fetch style type plugins from the PluginManager.
For naming, I like extension but I think that could get confused with native macOS extensions and so it is probably better to call them Plug-ins. TextMate refers to them as Bundles so that's another option as they are bundles...

For storage I think we leave them on disk for now as the database is fragile and I don't think startup time is an issue. Actually I know with larger databases the quitting time is actually an issue and so keeping the database lean for now would be nice.

Preferences are interesting... again we could look at TextMate 2 or even Adium for ideas.

Will you be implementing this in Swift? 

I'll try and update my answers tomorrow.

**Comment by Eitot** [comment]
I have the same concerns about the word extensions. Bundle seems too broad though. I will have a look at some other software for inspiration. The only app with such a plug-in system that I have on my system is Sketch and it calls them plug-ins too.

I will be drafting it in Swift, because I am more comfortable with that language. The plug-in models also lend themselves for value types. It should not be problematic to translate it into Objective-C. Ultimately, the plug-in manager is not overly complicated.

One thing I have not considered yet is how this plug-in manager will be used. Currently, it is instantiated once in AppController. This works, because the main view controller lives there too. In the future, it will have to be accessible to other view controllers. We briefly touched upon this with the singleton pattern, but you said you weren’t too keen on using it? What else could we use to make this work? I have looked at the service-locator pattern, but I am really not sure how to implement it.

**Comment by josh64x2** [comment]
I don't like the singleton pattern but it makes sense for something like a plugin manager. We don't have to use singleton though as we could instantiate it as a normal object and pass a weak reference to other view controllers that need access to the plugin manager.

I'm happy with you keeping all of the code in Swift as that will be the future of Vienna anyway. You don't have to try and translate to Objective-C.

**Comment by DavidMunch** [comment]
See also #171.
