### ISSUE TITLE
vienna-rss.org down and domain expired?

### ISSUE THREAD

**Issue by DavidMunch** [ViennaRSS/vienna-rss#799]
Site is down and it appears the domain expired on 2/24/2017.

**Comment by josh64x2** [comment]
@DavidMunch yeah @mstroeck let it expire and hasn't responded to our attempts to contact him. (see #792)

I purchased vienna-rss.com and changed all our links in #796 which is the best solution I could come up with...

**Comment by josh64x2** [comment]
I'll close the issue but any discussion can continue :)

**Comment by DavidMunch** [comment]
Ah, good that you aware of it! I didn't see the other issue in the list, because it was closed already. 8)

**Comment by josh64x2** [comment]
I guessed that was the reason :) Hopefully our search links will slowly update...
