### ISSUE TITLE
Change links in helpbook to vienna-rss.com

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#800]
We have some links in our helpbook files that need to be changed from vienna-rss.org to vienna-rss.com

**Comment by Eitot** [comment]
Will send a PR later.

**Comment by josh64x2** [comment]
@Eitot I notice in your pull request all of the other links I didn't think about; namely the default feeds.

Should I write a small migration statement in the DB migration code to replace any existing vienna-rss.org feed URLs with vienna-rss.com ones for users that kept the default feed to keep updated on Vienna?

**Comment by Eitot** [comment]
That is probably a good idea, yes. Provided it doesn’t add too much bloat to the codebase. 😛
