### ISSUE TITLE
Sorting messages

### ISSUE THREAD

**Issue by TonVH** [ViennaRSS/vienna-rss#807]
Since no reaction on the forum. I post this here.

Presently I sort on the subject but within the same subject the individual lines are in reversed orden meaning the latest on top and the oldest bottom.

This makes reading a bit awkard.

Is there a way to sort so that within the same subject messages are sorted oldest first, newest last?

**Comment by barijaona** [comment]
I am not sure I understand what is the issue. Can you add a screenshot or give the URL of an example feed ?

**Comment by TonVH** [comment]
Presently one can sort on a single column. So either subject, date/time, and so one.

What I would like is sorting on 2 columns. First on subject and then (within subject) on date/time. This is especially usefull with forums because then messages will appear on correct sequentence within the same subject.

**Comment by Eitot** [comment]
Does anyone know if this can be done in NSTableView? I don't think I have ever seen this. The request makes perfect sense though.

**Comment by JanX2** [comment]
@Eitot Sorting on multiple columns is already there by default. You just sort in ascending order of precedence. Whenever there is a collision/equality in one column it will be resolved by the previous column/the one taking less precedence.

**Comment by Eitot** [comment]
I meant whether NSTableView provides a user-controllable interface for this. Columns are usually sorted by clicking on the column's header row, but this only applies to a single column in the whole table view. I know that you can implement this in the model, but I have not seen an implementation, at least not in Apple's apps.

**Comment by JanX2** [comment]
That’s what I was referring to, @Eitot: The property `sortDescriptors` of `NSTableView` is an `NSArray`of `NSSortDescriptor`objects. You set this up, from a user perspective, by first clicking the column header with the least precedence and then continuing on up to the column header who’s column has the highest precedence. 

To implement support for this, which is already in place in the framework-supplied `…Controller` implementations, you fall back to the next `NSSortDescriptor` whenever a comparison for the higher level returns an `NSComparisonResult` of `NSOrderedSame`.
