### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#821]
Just to add to #801: I have had a look at what would be required to use Carthage instead of CocoaPods. It seems that only ASIHTTPRequest and CDEvents are problematic, the rest builds just fine.

We are already planning to move away from ASIHTTPRequest and I happen to have a simple GCD-based implementation of a directory monitor that we can use instead of CDEvents (based on Apple documentation and sample code).

The big advantages of Carthage are that it does not require an Xcode project of its own and does not force our own project into a workspace (which Pods also maintains control of and it exposes the logs to build issues in pods). It is also a decentralised solution that does not depend on a central server like Pods does, meaning that we can always pull directly from a git repo.

Thoughts?

---
- [ ] ASIHTTPRequest
- [x] CDEvents #830

**Comment by josh64x2** [comment]
I agree it will be a better solution as it won't interfere with the project file.

I'll work on the network code this week - hopefully it won't be a huge task.
