### ISSUE TITLE
Custom objects in XIB files

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#826]
I have noticed that Xcode and Instruments mark two custom objects in IB as memory leaks. Specifically [these two](https://github.com/ViennaRSS/vienna-rss/blame/master/Interfaces/Base.lproj/MainMenu.xib#L1466-L1467):
```xml
<customObject id="HRR-OU-3yj" customClass="ArticleListView"/>
<customObject id="HLa-Gy-vMd" customClass="PreferencesWindowController"/>
```

The second one was introduced by me by moving the PreferencesWindowController into MainMenu.xib. Instantiating it in code does not seem to cause this, but I want to know why. Is there a difference between creating the controller in MainMenu.xib and initialising a property in code?

@josh64x2, what does the first one do? It doesn’t seem to have any connections to anything.

**Comment by josh64x2** [comment]
Oh that must have slipped in when I was trying to fix 10.8 autolayout. 

I'll have a look at it properly today and see why it is leaking as having it in an object in the xib should be fine...

**Comment by josh64x2** [comment]
Hmm I had a quick look but couldn't see anything obviousy. Did you work out what the issue was with `PreferencesWindowController` ?

**Comment by Eitot** [comment]
No. I am not sure if this is really a problem or not. I assumed that instantiating the window controller in MainMenu.xib would have the same effect as in a storyboard, but it seems that this is treated as a memory leak. Given that the window controller will always be around anyway, it should not really matter.
