### ISSUE TITLE
Cocoa API deprecations (10.10+)

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#828]
Just FYI, these APIs are deprecated as of 10.10.

NSDate methods:
- [ ] `-dateWithString:calendarFormat:`
- [ ] `-dateWithCalendarFormat:timeZone:`
- [ ] `-dateByAddingYears:months:days:hours:minutes:seconds:`
- [ ] `-dayOfMonth`
- [ ] `-monthOfYear`
- [ ] `-yearOfCommonEra`

Classes:
- [ ] NSCalendarDate (replaced by: NSCalendar, NSDateComponents and NSDateFormatter)
- [x] NSRunAlertPanel (replaced by: NSAlert)
- [x] NSCancelButton (replaced by: NSModalResponseCancel)

Replacing them does not seem to be urgent at this point, though it needs to be done eventually.

**Comment by josh64x2** [comment]
I did have a look at the date functions and they seemed to be replaced by more convoluted alternatives. Mind you, I find the new Apple developer doc format VERY confusing haha.

**Comment by Eitot** [comment]
That’s why I posted it here, I could not quickly figure it out either. 😅

**Comment by Eitot** [comment]
I have a PR ready for these.

Do you feel strongly about having an identical replacement for the NSCalendarDate extension? It currently has some code for creating the relative date strings, e.g. “Today” and “Noon”. NSDateFormatter can do the former automatically. However, the comments in the extension explain that NSDateFormatter was specifically not chosen in order to get capitalised words for “Today” and custom words for certain times, such as “Noon” (NSDateFormatter does not do this).

I think that we should use NSDateFormatter regardless, even if some languages may end up with lower-cased words and we lose the “Noon” and “Midnight”. NSDateFormatter has the added benefit that we are not making any assumptions about the date formatting or locale at all and leave everything to the system and the user’s settings. According to Apple’s documentation, some languages have more relative words than “Today”, “Tormorrow” and “Yesterday”, which would be convenient to have as well.

NSCalendarDate has no direct replacement. NSCalendarDate’s `-date:` always returns a date object for the current timezone, whereas NSDate is always in UTC. Apple’s current approach seems to be that _internal_ usage of dates should always be based on NSDate, whereas NSDateFormatter should be used for presentation to the user and NSCalendar for date arithmetic.

This presents the problem that Vienna currently uses NSCalendarDate for calendar arithmetic. I am not entirely sure what the effect will be, because these dates are mainly in Database.m. I will be adding a few tests, but I know for certain already that the dates will not match.

**Comment by josh64x2** [comment]
Ok I've been dealing with dates a lot lately at work so if you submit your PR I'll go through the pros and cons :) I think not having capitalised words is not a big issue...

I really admire your determination to go through Apple's documentation!
