### ISSUE TITLE
Icon Shadow on new iMac

### ISSUE THREAD

**Issue by arjay67** [ViennaRSS/vienna-rss#834]
Currently using Vienna 3.1.8 :1bc6bc3: on a late 2015 iMac (17,1) with macOS Sierra 10.12.3. Previously was using a nearly identical machine and upgraded to one with a 2TB Fusion drive. After the upgrade, the icon now appears with a square shadow around it. Attempted removing and reinstalling with no change. Certainly not a show stopper from a functional standpoint, but it is unappealing. Examples below of how is appears in the dock and Applications folder:

<img width="188" alt="screen shot 2017-03-21 at 2 11 06 am" src="https://cloud.githubusercontent.com/assets/15148380/24140199/272ee306-0ded-11e7-98d6-f79d918bc1c7.png">
<img width="140" alt="screen shot 2017-03-21 at 4 14 47 am" src="https://cloud.githubusercontent.com/assets/15148380/24140208/2c262720-0ded-11e7-823b-9edc860aa0df.png">
<img width="99" alt="screen shot 2017-03-21 at 4 15 11 am" src="https://cloud.githubusercontent.com/assets/15148380/24140212/2e6859d6-0ded-11e7-971b-aa0123fad5c5.png">

**Comment by Eitot** [comment]
Thanks for the report. This has been fixed in #749 and should be resolved in the next update.

**Comment by josh64x2** [comment]
I guess we will leave this open until @barijaona can release 3.1.9 as it has been raised a few times.

**Comment by barijaona** [comment]
If nobody objects, I will release a 3.1.9 release tonight.
There are other 3.1.x pertinent changes on the way, but publicizing the new vienna-rss.com domain name seems a requirement.

**Comment by josh64x2** [comment]
@barijaona please release tonight :)

**Comment by Eitot** [comment]
Please merge #831 though. Has anyone tested Vienna under Mavericks recently?

**Comment by josh64x2** [comment]
I have not... though this release will be 10.8 compatible so I should test under that tonight...

**Comment by Eitot** [comment]
I have that same fix for the legacy branch, just didn’t push it yet.

**Comment by josh64x2** [comment]
OK I'll let @barijaona review and merge for v3.1.9 when he is getting the release ready
