### ISSUE TITLE
Status bar text behaviour

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#846]
From [Cocoaforge forums](https://forums.cocoaforge.com/posting.php?mode=reply&f=18&t=26946#pr139859): Often I hover over a link in an article to see where it goes, only to have the status bar overwritten with the string, "Article load completed." It would be nice if this advisory were to be suppressed if the status bar is in actual use at the time. Thanks.

**Comment by Eitot** [comment]
Perhaps it would be an idea to get rid of the status bar eventually. The fetch status is all over the place: in the toolbar, in the sidebar next to each feed, a notification and the status bar. I think it would be most useful in the sidebar. Alternatively, there could be a dialog at the bottom of the sidebar, like Mail has.
![screen shot 2017-03-28 at 18 41 05](https://cloud.githubusercontent.com/assets/15073177/24416765/25298a80-13e6-11e7-9e1f-3b9e3b9ce640.png)

The URL description could be shown in an overlaying status bar, like in Safari.
![screen shot 2017-03-28 at 18 41 33](https://cloud.githubusercontent.com/assets/15073177/24417014/0fa692b0-13e7-11e7-8ff0-8cbc89d219f1.png)

**Comment by josh64x2** [comment]
Related to PR #936
