### ISSUE TITLE
articles stay unread in both vienna and innoreader

### ISSUE THREAD

**Issue by ggruenau** [ViennaRSS/vienna-rss#847]
Since yesterday, articles stay unread in Vienna and Innoreader, even if they have been read in Vienna (right-click and mark-as-read doesn't show any effect). Only way to get articles marked as unread is to login to innoreader.com and read them there ... 
Vienna Version 3.1.9 :e81515b:

**Comment by ggruenau** [comment]
Vienna Version 3.1.9 :e81515b:

**Comment by barijaona** [comment]
I could not reproduce the problem

**Comment by barijaona** [comment]
Are you sure your Vienna app is correctly logged to Inoreader ?

**Comment by ggruenau** [comment]
Its working fine again today on both my machines. Seems that it was a problem on the Inoreader platform itself. Thanks for trying to reproduce.
