### ISSUE TITLE
PPC Version

### ISSUE THREAD

**Issue by LETRA** [ViennaRSS/vienna-rss#858]
Hi. I have an old iMac G4 and wonder if the old version for Tiger PPC is functional. If you can tell me how to download it and if you can still work simply. A greeting.

**Comment by josh64x2** [comment]
Hi there,
I love knowing PPC macs are still getting used :)
Version 2.3.4 was the last that supported 10.4 Tiger, and you can download it from here: https://sourceforge.net/projects/vienna-rss/files/ReleasedVersions/2.3.4/Vienna2.3.4.2305.zip/download

**Comment by LETRA** [comment]
And they can still be useful as well as beautiful! Many thanks!!

2017-04-05 13:57 GMT+02:00 Josh <notifications@github.com>:
