### ISSUE TITLE
GB zapped web bug

### ISSUE THREAD

**Issue by sveinbjornt** [ViennaRSS/vienna-rss#859]
Strange issue: string "GB zapped web bug" appended to rss item text. This string is not present in the original RSS file when I curl'd it:

<img width="1029" alt="screen shot 2017-04-07 at 23 25 17" src="https://cloud.githubusercontent.com/assets/654045/24820576/14cd25b4-1bea-11e7-8cdf-4165619acf17.png">

<img width="1272" alt="screen shot 2017-04-07 at 23 30 28" src="https://cloud.githubusercontent.com/assets/654045/24820669/7d8b590e-1bea-11e7-8baf-4f9d0a8ac58a.png">

Feed source: http://feeds.feedburner.com/i-ljosi-sogunnar

**Comment by josh64x2** [comment]
Hmm that's weird. I'm not able to reproduce. Would it be possible for you to delete fhe feed, re-add it to Vienna, and see if the problem is still occurring?

**Comment by sveinbjornt** [comment]
Deleted feed, re-added and same thing occurs.

**Comment by sveinbjornt** [comment]
When I look at the source in Vienna via Show XML Source, the feed XML has a comment "" appended to the description tag.

**Comment by josh64x2** [comment]
OK, which version of Mac OS and Vienna are you using?

**Comment by josh64x2** [comment]
This old bug report suggests it's due to the use of glimmer blocker: https://www.cocoaforge.com/viewtopic.php?f=18&t=23854

are you using glimmer blocker?

**Comment by sveinbjornt** [comment]
Yes, I am using GlimmerBlocker. Disabled it and the problem disappeared.
