### ISSUE TITLE
Can't mark any articles as read

### ISSUE THREAD

**Issue by tonycpsu** [ViennaRSS/vienna-rss#861]
As of today, I can no longer mark any articles as read.  I use InoReader as my feed backend.  Things I've tried to resolve the problem include restoring my `~/Library/Application Support/Vienna` directory from time machine backups, reindexing the database, and force-refreshing feeds from the feed's right click-menu.  Nothing changes -- articles are not marked as unread when I visit them, nor when I right-click and select "Mark Read".

Version 3.1.9 :e81515b:

**Comment by tonycpsu** [comment]
And now it's working.  I suspect a problem on InoReader's end.

**Comment by josh64x2** [comment]
@tonycpsu inoreader has these problems time to time. We should look into displaying an informative message if inoreader has failed to update the mark as read.
