### ISSUE TITLE
[outdated link on site] "Missing A Feature" page links to Sourceforge

### ISSUE THREAD

**Issue by tnorthcutt** [ViennaRSS/vienna-rss#867]
The "[Missing A Feature? Get It Done!](http://www.vienna-rss.com/?page_id=40)" has a link pointing to [https://vienna-rss.sourceforge.io/?page_id=16](https://vienna-rss.sourceforge.io/?page_id=16), while the newer version of that page lives at [http://www.vienna-rss.com/?page_id=16](http://www.vienna-rss.com/?page_id=16).

![image](https://cloud.githubusercontent.com/assets/796639/25314771/6e07978a-2807-11e7-85e6-7a986e371a39.png)

**Comment by josh64x2** [comment]
Thank you for reporting this :) It should be fixed now...

**Comment by tnorthcutt** [comment]
@josh64x2 ᕕ( ᐛ )ᕗ
