### ISSUE TITLE
Streamlined Style selection

### ISSUE THREAD

**Issue by Aoiike** [ViennaRSS/vienna-rss#871]
In the current version of Vienna, the option to use the Web Version of Articles is referred to as
"Load Full HTML Articles" in the Folder Menu as one of two selectable options
"Use Web Page for Articles" in the Info Window as a Checkbox
Which is a little confusing, and Styles cannot be set per-Feed or per-Folder.

Goals of this idea:
1. Per-Feed and per-Folder Style setting, you can have one feed in Web View, One in Tyger, and One in XCast persistenly without having to constantly change settings.
2. The option to display the Web Version in the style Menu, effectively being a "no style" option.
3. Reduce amount of clicks and Menus required to change these settings.

Actual Changes:
1. Remove Both "Use Current Style for Articles" and "Use Web Page for Articles" from the Folder Menu
![folder-menu](https://cloud.githubusercontent.com/assets/26124815/25498214/07bb3344-2b7f-11e7-8c22-dae4fa3b2a5d.png)
2. Add "Web Page" (or something better suited) to the top of the View->Style Menu with a Separator to distinguish it from being a normal Style.
![style-menu](https://cloud.githubusercontent.com/assets/26124815/25498374/abefeeb4-2b7f-11e7-9b13-87c92d7860d7.png)

3. Remove The "Load Full HTML Articles" Checkbox from the Info window
4. Add a Dropdown matching the View->Style Menu to the Info Window
![info-window](https://cloud.githubusercontent.com/assets/26124815/25498219/0cd3ca4e-2b7f-11e7-975a-1aa86b856a19.png)

5. Make the Filter Bar a fixed part of the interface containing the same Filter features at the Right end, and adding the "Feed Style" Dropdown at the Left end.
![style-selection](https://cloud.githubusercontent.com/assets/26124815/25495974/2cd84a5c-2b77-11e7-995b-85592751895d.png)
The reason for putting dropdown on this bar rather than the Main toolbar is to clearly indicate that both these Options are Specific to the Feed or Folder below it, and not a Global Option.
The reason for making this bar persistently visible is to be able to always see without having to click anything what style is currently in use, and to eliminate needing to bring up the bar in order to filter.

**Comment by josh64x2** [comment]
I like these proposed UX changes! Thank you 😄

**Comment by Eitot** [comment]
I agree with the menu and info panel changes, but am slightly opposed to moving the style menu to a separate bar and fully opposed to making that bar a static component. The toolbar is by no means a ‘global menu’; it can, and does, change depending on its context. Vienna currently does not implement all these toolbar items correctly, which is something I want to address at some point.

**Comment by barijaona** [comment]
Setting a default style for new feeds/folders would therefo be needed in Preferences.
