### ISSUE TITLE
Feed pagination

### ISSUE THREAD

**Issue by diimdeep** [ViennaRSS/vienna-rss#873]
Is it supported ? 
AFAIK RSS and Atom spec don't describe pagination, still there is implementations..

For example in Wordpress `https://example.com/?feed=rss2&paged=#` [src](https://wordpress.stackexchange.com/questions/108185/pagination-of-rss2-feed)

**Comment by Eitot** [comment]
Is this not a server-side thing only? Vienna only fetches the contents of the feed from the given URL. If the server presents only the contents of ‘page 2’, then that is what Vienna will show.
