### ISSUE TITLE
Can't open anymore the Vienna App after I have added a subscription

### ISSUE THREAD

**Issue by giannigdev** [ViennaRSS/vienna-rss#877]
The Vienna App continues to crash, do you guys have any idea about why it's crashing? i have attached the crash report: 

[Vienna_2017-05-07-133307_Giannis-MacBook-Pro.crash.zip](https://github.com/ViennaRSS/vienna-rss/files/981550/Vienna_2017-05-07-133307_Giannis-MacBook-Pro.crash.zip)

Both buttons lead to crash of the app. If there is some way to save my subscribtions before reinstalling the App.

![fotoa](https://cloud.githubusercontent.com/assets/4886490/25780654/7b5601b8-332b-11e7-918e-37934bd4dac8.png)

**Comment by Eitot** [comment]
The crash report is not very specific, unfortunately. It does not show where Vienna is at fault. Can you remember what you did before the crash occurred?

**Comment by giannigdev** [comment]
I was adding an rss to a group folder. After that i pressed the arrow to expand that folder, but it didn't expand(i am sure that folder had different rss inside except the one i was adding). Then i pressed again the arrow - > the group folder disappeared from the list and the crash occurs.

**Comment by barijaona** [comment]
Did you try removing the preferences file ? 
~/Library/Preferences/uk.co.opencommunity.vienna2.plist

This might also help : http://forums.cocoaforge.com/viewtopic.php?t=26313&p=137346#p137346

**Comment by giannigdev** [comment]
I have realised what is the error. If you try to add this feed ( http://www.cleverhans.io/feed.xml ) in a group folder it crashes. I have checked the feed and it doesn't contain anything, so i guess this is the reason why Vienna App crashes. Is there a check if we have added a valid feed or not?

**Comment by barijaona** [comment]
The culprit is the empty feed name in the database 😈 

![sans_titre](https://cloud.githubusercontent.com/assets/442030/25832169/af81b292-3471-11e7-8ace-c2dcfdfd200a.jpg)

Temporary workaround : replacing the (NULL) value with something sensible.

**Comment by giannigdev** [comment]
So if i understand correctly the feed name is stored in the foldername field of the DB. I think it's essential to check that a field it's not null before doing any operation, so the user is informed that is trying to add an invalid feed.

**Comment by josh64x2** [comment]
Yup I can work on it if someone else isn't already

**Comment by barijaona** [comment]
Please do !

**Comment by giannigdev** [comment]
@josh64x2 thanks for your time ;)

**Comment by barijaona** [comment]
Fixed in current stable branch

**Comment by barijaona** [comment]
Closed at version 3.1.12

**Comment by giannigdev** [comment]
Thanks both @lapcat , @barijaona for this fix!

**Comment by barijaona** [comment]
You’re welcome.
