### ISSUE TITLE
Add support for JSON Feed

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#889]
JSON Feed is a new format - similar to RSS and Atom but in JSON.
It has potential to get traction because JSON is simpler to implement and test than XML, and the data model already contains nearly all fields that most feeds need, without requiring complex methods to generate a summary, main image and so on.

More info: [jsonfeed.org](https://jsonfeed.org/).
If we implement support of JSON Feed, we should try to share code with the Google Reader class.

**Comment by Eitot** [comment]
Perhaps a bit too novel?

**Comment by barijaona** [comment]
Yes, we have the usual egg and chicken dilemma… but it is already supported on [many popular publishing tools](https://jsonfeed.org/code) and at least [another Mac newsreader](https://betamagic.nl/blog.html).

I am slightly worried by the slow decline of RSS support by mainstream medias, so implementing JSON feed early would be : 
- a statement that feeds are an important feature for many people
- a visible sign of Vienna's vitality, even if its user interface might feel a bit outdated

**Comment by josh64x2** [comment]
Well I'd keep it out of `GoogleReader` class because the responsibilities are totally different.

**Comment by Eitot** [comment]
From what I can see, XML parsing is done by the RichXMLParser class. For once, this seems to be quite nicely done, as it is only really used by RefreshManager and coupled across the place. This means that it should be straightforward to add a JSON complement to RichXMLParser.

It may be a good idea to add a parser protocol or superclass to account for potential implementation differences between both parsers.

From what I understand, JSON parsing isn’t that fantastic in Foundation though. I did come across SwiftyJSON a while ago, which might be something to consider.

**Comment by Eitot** [comment]
Swift 4 has native encoding/decoding support for JSON and other formats. They demonstrated this and it looks very interesting and useful. Will be doing some tests while working on #798. Might be worth delaying support for JSON feed until 10.13 release.

**Comment by Constantin07** [comment]
I cannot read CoreOS news https://coreos.com/releases/releases.json too
Very inconvenient to use different RSS readers for XML and JSON formats.
Is there any plan to add `json` support ?

**Comment by Eitot** [comment]
I am currently working on refactoring the RSS parser to work with the new Decoder protocol. Then it should be relatively easy to add a JSON Feed decoder based on a simple protocol implementation.

**Comment by TAKeanice** [comment]
There is no problem with a Swift-only framework, because we can easily write an adapter class which is marked `@objc` gives us access to everything we need from FeedKit. Or we can look how far we get by making everything we need `@objc`. Keeping our own FeedKit version with some few lines changed should not break our necks

**Comment by mcorossigo** [comment]
Please, JSON Feed is becoming increasingly popular, with new shiny rss readers like NetNewsWire supporting it out of the box.
It would be great if Vienna could support it.

**Comment by josh64x2** [comment]
Test feed could be https://usesthis.com/feed.json
Please feel free to add any others whilst I start working on this soon.

**Comment by barijaona** [comment]
Closed by #1649
