### ISSUE TITLE
ExportTests fail

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#898]
They seem to have been failing for a while, according to the Travis logs.

```
testExportWithGroups, ((countExported) greater than (0)) failed: ("0") is not greater than ("0") - Pass
testExportWithoutGroups, ((countExported) greater than (0)) failed: ("0") is not greater than ("0") - Pass
```

**Comment by josh64x2** [comment]
Yeah I think I should fix this now I have more time 😄

**Comment by josh64x2** [comment]
OK I can see why it is failing now :P There is no database on the travis CI server to actually export the feeds from and so exporting returns 0 feeds!
