### ISSUE TITLE
Emptying trash upon termination

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#905]
The user receives this dialog when attempting to quit Vienna with items in trash:
![screen shot 2017-06-09 at 22 29 53](https://user-images.githubusercontent.com/15073177/26993423-3fc699d0-4d63-11e7-8bfb-e239ee3a609b.png)

Interrupting the termination process is something that Apple moved away from since Lion. Instead, the user should be able to quit immediately and resume the activity when the app is reopened. Asking whether the trash should be emptied isn’t worth interrupting this flow. Moreover, the user cannot currently revisit the decision to suppress the warning or change the behaviour.

I want to propose doing this differently. I suggest to remove the dialog, add a checkbox to the preferences and choose a reasonable default behaviour. We should also consider adding the option to delete only older messages from trash with a variable time (e.g. 7 days, 30 days and so forth), like Mail, Notes, Photos or even Finder (in Sierra) do.

**Comment by josh64x2** [comment]
I like this- especially the option of having a variable time.

**Comment by barijaona** [comment]
What could be a smart combination of this with Vienna's current ability to automatically move read and unflagged articles into the Trash ?
