### ISSUE TITLE
Vienna causes a font download request

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#921]
Per [this forum thread](http://forums.cocoaforge.com/viewtopic.php?t=26973):
> Hoping someone can provide an answer (and adjustments) to this issue.
>
> I have Vienna 3.1.10 on a MacBook Pro running 10.12.5. Vienna is now asking to download fonts when going to certain webpages from the links.
>
> Thanks,
>
> bf
>
> ![](http://forums.cocoaforge.com/download/file.php?id=913&sid=bafed8c425fb1c04aa23304ffdff8c9d&mode=view)

I can confirm this issue, I have seen it once before. My guess is that a web-view is causing this, based also on [this report](https://stackoverflow.com/questions/41234444/prevent-prompt-to-download-font-referenced-in-webview-in-macos-application) at StackOverflow. I do not know whether this is particular to WebView as opposed to WKWebView.

**Comment by macsrwe** [comment]
The two I see all the time are this one and one whose name is something like "Gung Seo."  I get these a half dozen times a day each.

A forum response asked for particular URLs that do this.  Here's one:

https://www.standard.co.uk/news/uk/rspca-called-to-rescue-lizard-which-turns-out-to-be-a-dirty-sock-a3635086.html

I would like to be able to tell Vienna just to deny these requests and shut up about them.

**Comment by barijaona** [comment]
Seems like the problem does not appear anymore on macOS 10.13 (High Sierra) ?

**Comment by barijaona** [comment]
Answering to myself : no, it still appears.
