### ISSUE TITLE
Deleting article from smart folder or filtered folder does not work

### ISSUE THREAD

**Issue by barijaona** [ViennaRSS/vienna-rss#924]
See http://forums.cocoaforge.com/viewtopic.php?t=26908&p=139682
and https://forums.cocoaforge.com/viewtopic.php?t=26932&p=139807

**Comment by josh64x2** [comment]
@barijaona do you think this has been fixed with your recent commits?

**Comment by barijaona** [comment]
Yes. I just forgot to close the issue.
