### ISSUE TITLE
Vienna can't be downloaded from Vienna-RSS.com

### ISSUE THREAD

**Issue by DavidMunch** [ViennaRSS/vienna-rss#937]
As [pointed out](https://forums.cocoaforge.com/viewtopic.php?f=18&t=26985) on the Cocoaforge forums by a user, the website at Vienna-RSS.com doesn't actually have an active download link for the newest release for Vienna, which is a great oversight!

The user complains that he has to get the latest releases from sites such as Macupdate.com, which is to put it mildly, not in any way optimal, especially considering the adware which may come bundled with the software.

Solution: Create a download link to binaries of the newest (And older?) releases of Vienna on the website.

OP from Cocoaforge:

> The Vienna website is missing a download link/menu. I see new releases in Macupdate, but I refuse to download from there and go to the Vienna website. Then wander around until I remember that there is a github link (for the source, which incidentally includes the binaries) in the development menu, though it's just text, not a real link. And I keep forgetting to make a bookmark to github (well, did it now).

> Best would be a direct download link to specific versions in github, if that's possible. At least a link to the release section. Renaming the development link to say binary downloads are there wouldn't work well for average non-geeky users.

**Comment by josh64x2** [comment]
Argh good point.
I got sidetracked about the new site and so the temporary one is still up! i'll add a link.

**Comment by josh64x2** [comment]
OK I've added a blog post and a link at the top of the page which points to the latest github release. And hopefully I'll get around to getting a proper website up one day soon 😄
