### ISSUE TITLE
GitHub homepage for Vienna links to the wrong website

### ISSUE THREAD

**Issue by rEes9P** [ViennaRSS/vienna-rss#951]
The [project homepage](https://github.com/ViennaRSS) on GitHub links to www.vienna-rss.org,  which is a very dodgy looking coupons site, instead of www.vienna-rss.com. The first time I came across Vienna I went to the coupons site and needlessly got very concerned about the legitimacy and safety of the app. It'd be good to have the link fixed. Thanks for a great app!

**Comment by josh64x2** [comment]
Thank you, I'll change It shortly :)

**Comment by josh64x2** [comment]
All done!
