### ISSUE TITLE
Xcode configuration files

### ISSUE THREAD

**Issue by Eitot** [ViennaRSS/vienna-rss#954]
I think we should discuss the efficacy of these files. I made the following observations:

1. Base-Framework.xcconfig and Vienna-StaticAnaylzer.xcconfig are not used. They aren't referenced by any other file except project.pbxproj (but only for the file reference).
2. The StaticAnalyzer configuration itself is not tied to any build schemes currently. I assume that anyone can use private schemes and switch to this configuration. However, what is the benefit of this configuration in addition to what Xcode already offers when using the "Analyze" option in the Product menu? I also noticed that many of the default settings that apply to the other two configurations do not apply to this profile.
3. Some configurations are outdated or questionable. An example: the deployment configuration sets `IBC_FLATTEN_NIBS` to false. This results in larger, unoptimised NIB files in the app bundle. Perhaps it makes sense for development, but not for release.
4. Some configuration files duplicate existing Xcode defaults.
5. Some configuration files are superseded by configurations that Xcode recommends from time to time.

I think we should consider re-integrating the configurations into Xcode again. The added benefit of having separate files do not outweigh the additional complexity and maintenance, in my opinion. Xcode has a decent interface, including a filter that shows only those keys that were overridden by us. Stripping the configuration files cleans up the configuration hierarchy quite a bit.

**Comment by josh64x2** [comment]
I'm all for simplicity! They are unnecessary for our purposes and I support removing the configuration files.
