### ISSUE TITLE
Opening URLs in browser is broken

### ISSUE THREAD

**Issue by josh64x2** [ViennaRSS/vienna-rss#972]
At https://github.com/ViennaRSS/vienna-rss/blob/master/src/TabbedWebView.m#L285 `controller` is still `nil` so the URL never opens in a browser.

I've only verified this with my preferences set to open links in external browser, but I assume `controller` is not set in the class and so it probably affects other functionality too.

I think opening URLs is probably more of an `[ArticleView, TabbedWebView]Controller` or `MainWindowController` responsibility and so the relevant code can be moved out of `AppController`. Thoughts @Eitot and @barijaona ?

**Comment by josh64x2** [comment]
This affects the `master` branch by the way.

**Comment by Eitot** [comment]
I want to refactor this into a proper NSTabController eventually. Unfortunately, that is 10.10 API.

Still, I thought I did test this. I must have missed an initialiser somewhere when I moved stuff out of IB.
