### ISSUE TITLE
what to do when a RSS feed points to a ransomware server

### ISSUE THREAD

**Issue by Fedster** [ViennaRSS/vienna-rss#975]
Not really a Vienna issue, but I had two RSS feed connecting to ransomware associated servers and causing the IT department to get pretty excited (details below).  The question is, can ransomware or other malware be passed on to my own computer through Vienna?

My details:  MacOS 10.12.6, Vienna 3.1.11 :2aa3b6bd: 

The feeds:

www.thejoinersapprentice.com pointing to 45.33.9.234

and 

www.holteyplanes.com pointing to 79.170.40.167

**Comment by barijaona** [comment]
It's difficult to give a general answer, but my opinion is it's no riskier visiting a site with Vienna than visiting it with the default version of Safari accompanying your version of macOS.
So if your macOS is decently up-to-date, you shouldn't be too much worried.

**Comment by Fedster** [comment]
How much code does Vienna let a page load and execute?  The same as Chrome (I do not use Safari)?  Ideally it should load the text and little more (maybe images that are staticky linked?).  This is a potentially serious issue because Vienna visits tons of sites, more than I'd do by hand, and thus can increase the risk substantially.  I do not think that not being too much worried is a proactive enough security approach.

**Comment by barijaona** [comment]
The main risk is with outdated webkit plugins (like Flash, Silverquick…). Vienna can run them while Safari is increasingly deprecating them.

Have a look at `~/Library/Internet Plug-Ins` and `~/Library/Internet Plug-Ins` and remove anything which is unneeded.
You can also disable them completely through Vienna's advanced preferences.
