### ISSUE TITLE
Changing the available styles doesn't work

### ISSUE THREAD

**Issue by ghost** [ViennaRSS/vienna-rss#978]
Hi! I am trying the newest version of the Vienna RSS (3.1.11) but changing the available styles doesn't work. It always stays as the default theme and clicking on the available styles doesn't do nothing. Looks like it's broken.

Thanks a lot and keep up the great work!

**Comment by ssssilva** [comment]
Sorry, I've figured out. I though the styles would change the overall look (and not just the way pages are displayed. 
By the way, I've noticed a new (and beautiful) revamped look done by Aoiike. Is there a way to try it or will it be available soon? Thanks!

**Comment by Eitot** [comment]
> By the way, I've noticed a new (and beautiful) revamped look done by Aoiike. Is there a way to try it or will it be available soon? Thanks!

Not just yet. We are planning to provide nightly builds, but no ETA.

**Comment by ssssilva** [comment]
Looking forward!
