### ISSUE TITLE
Blurry text on non-retina Thunderbolt Display

### ISSUE THREAD

**Issue by Zodiac1978** [ViennaRSS/vienna-rss#979]
I have a MacBook Pro with a Thunderbolt display connected to it.

On the Retina display of the MacBook Pro everything is fine. On the Thunderbolt display I get this blurry text after scrolling the content:

![bildschirmfoto 2017-08-10 um 10 30 59](https://user-images.githubusercontent.com/870475/29161704-8465febc-7db7-11e7-8e13-5882c262e3c5.png)

Mac OS X 10.11.6

**Comment by Eitot** [comment]
Is this blurriness permanent or does it go away after a while or when you do something specific? I am particularly interested in knowing what effect resizing the window and/or changing the split-view dimensions has.

**Comment by Zodiac1978** [comment]
Sorry for the late response, but I can't reproduce this error anymore, so I can't answer your questions. If the problem appears again I'll report it again with more details.

**Comment by Zodiac1978** [comment]
This error is not reproducible for me, but it happened again from time to time. I can now confirm that resizing the window or the framing does indeed fix it. I will try to change split-view the next time it will occur.
