### ISSUE TITLE
Feature Request: Run an AppleScript on launch and/or quit

### ISSUE THREAD

**Issue by smurffff** [ViennaRSS/vienna-rss#981]
It would be useful if Vienna could automatically run an AppleScript on launch and/or quit. I envision this as a pair of Preferences that let the user specify the path to an AppleScript to run at either of these times.

I launch Vienna via AppleScript to work around a window sizing problem (<https://github.com/ViennaRSS/vienna-rss/pull/811>) but I imagine there would be lots of uses of this feature if it were available, e.g. mark all read on quit, or empty trash on quit (<https://github.com/ViennaRSS/vienna-rss/issues/905>).

**Comment by Eitot** [comment]
I am leaning in favour of this, but I have no experience with AppleScript. Is there a mechanism for postponing the termination until the script has finished running?
