### ISSUE TITLE
Spacebar jump between post doesn't really select the 1st one when it changes to a new feed

### ISSUE THREAD

**Issue by Garito** [ViennaRSS/vienna-rss#994]
Try this:
Go to the last unread post of a feed and press space
It will jump to the first unread post of the next feed, yes?
now try to open this first one of the new feed with enter
It opens the homepage of the source not the first article as expected
This is a bug, yes?

Thanks

**Comment by lapcat** [comment]
Thanks for the report. This should be fixed in the newly released Vienna 3.1.13.

**Comment by Garito** [comment]
Thanks!
